### ISSUE TITLE
Filter users by group

### ISSUE THREAD

**Issue by mandrew** [silverstripe/silverstripe-cms#1000]
By default you can filter the member table by name, email etc. but it would be great to have filter by 'group' as another option. This might not be possible in the table by default but maybe outside the table would be good?

To do this at the moment you have to select groups and then click the groups in order to see the filtered list. I'm doubt this process is very clear to a first time user.

**Comment by kinglozzer** [comment]
This would indeed be a nice addition but, as it’s an enhancement that no one has taken ownership of for over 3 years, I’m going to close this
