### ISSUE TITLE
Better character replacement for URLSegment

### ISSUE THREAD

**Issue by SewerHrehorowicz** [silverstripe/silverstripe-cms#1002]
Diactric signs, such as ęółąśłżźć are deleted, and they should be replaced by euoslzzc. I don't know how it looks in other languages, but it works like that in Polish.

**Comment by tractorcow** [comment]
Changing to 4.0 since there's no fix in time for 3.2.

**Comment by dhensby** [comment]
I think "use iconv" is a suitable solution here... Is anyone going to take this on or shall we close it?

**Comment by tractorcow** [comment]
Solution in this case is to install iconv, and set `SS_Transliterator.use_iconv` to true via config.

I suggest to change this to true by default from 4.0 onwards.

**Comment by tractorcow** [comment]
Closed with https://github.com/silverstripe/silverstripe-framework/pull/5949
