### ISSUE TITLE
[BUG] Insert Media / "Bad Request"

### ISSUE THREAD

**Issue by guci0** [silverstripe/silverstripe-cms#1015]
Hello,

I found a bug, please watch video:
http://dtl.pl/assets/pic/SS-raw-3.1.4-Bad-Request.mp4

Response from "Bad Request" is:
Ajax requests to this URL require an X-Pjax header

Version: SilverStripe 3.1.4.

Best regards!

Paweł P.

**Comment by unclecheese** [comment]
The attached video no longer works, so unfortunately this issue is not actionable. If this issue still exists, please resubmit the bug with a written description of how to reproduce it.

**Comment by phptek** [comment]
@unclecheese The video seems to be accessible once again...

**Comment by kinglozzer** [comment]
@phptek is the issue occurring in 4.x? If so, happy to re-open
