### ISSUE TITLE
Allow removing Help from the menu

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-cms#1020]
See also this forum post from 5 years ago: 
http://www.silverstripe.org/general-questions/show/6930#post260666

Apparently, the Help link is added near the end of execution, causing the following to fail in _config.php: 

`CMSMenu::remove_menu_item('Help');`

While that does work on ReportAdmin and even CMSSettingsController. I suppose moving the addition of that menu item to the same place as where CMSSettingsController is added, should fix it.

**Comment by jonom** [comment]
@JorisDebonnet do you know if this is still an issue? Would you like to open a PR to implement @chillu's suggestion?

**Comment by tractorcow** [comment]
Yes please... otherwise we might have to close this if no one is willing to implement this.

**Comment by JorisDebonnet** [comment]
I'll try to check this in the weekend.

**Comment by nathanbrauer** [comment]
Friendly annual bump. ;)

**Comment by robbieaverill** [comment]
Option for SS4 at #156 - could be backported to SS3

**Comment by dhensby** [comment]
If we fix this in 4, I think this can be closed ;)

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-admin/pull/156
