### ISSUE TITLE
SS_Report: titles are over-encoded

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-cms#1036]
The main page with the list of reports seems to encode the titles. For example, any apperance of the character ' is replaced with `&#039;`s (in the html source, the & appears as `&amp;`). In Dutch, translation of pages is pagina's, so it appears in almost every line. Alternatively you can also test with a " in the language file, which will show up as `&quot;`. 

After clicking on it, it is shown correctly in the `<h3>` title however, so the issue is clearly only in this overview list. 

You can test it by placing a " anywhere under SideReport in the cms language file, for example in SideReport.EMPTYPAGES.

**Comment by kinglozzer** [comment]
Looks like this was fixed in https://github.com/silverstripe/silverstripe-cms/pull/1165
