### ISSUE TITLE
CMS Form Templates

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-cms#1037]
The CMS relies on framework's templates for the form fields, such as FormField_holder.ss and so on.

This means if you have a module or piece of work that overrides the FormField_holder.ss template, then it will use that instead of the framework's.

I'd suggest that the CMS should have it's own templates for all of these templates, rather than relying on templates outside of the control of the CMS module

**Comment by kinglozzer** [comment]
It appears your wish has been granted in SS4 😉
