### ISSUE TITLE
Deprecate and remove ContentController::ChildrenOf() / ::Page($link)

### ISSUE THREAD

**Issue by axyr** [silverstripe/silverstripe-cms#1042]
I sometimes see developers relying on getting pages in templates by URLSegment or ID  that can be changed by endusers in the CMS.

This often happens when devs want to categorise pages and get the children of a particular page.

I think this should be solved by either creating a custom PageType that can only exist once and get Children by MyCustomPageType::get->First()->Children(), or create a DataObject to assign a Page to 1 or more categories.

I really can't think of a use case where creating a Page or Controller method to get a DataList or ArrayList with Pages by ClassName or by has_one/many_many DataObject is not better then getting Pages by URLSegment or ID in a template..

**Comment by GuySartorelli** [comment]
Closing as these methods are not a maintenance burden and its up to developers to choose how they want to access their pages. It's not worth the effort to deprecate these methods IMO.
