### ISSUE TITLE
Filter reset not updating view correctly.

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-cms#1053]
After searching for specific page content or title, whichever you want, and then selecting reset, resets the filter correctly.

But the view of the sitetree, stays the same, with the arrows indicating the entire tree is expanded. Suggesting the filter is not resetted.

**Comment by phptek** [comment]
@Firesphere are you referring to the fact that once you select the "Clear filter" link, CMS users are taken back to the Pages admin, with the central filter pane open? 

The SiteTree might _appear_ to be the same if the results of your search are found in content under each of your SiteTree's top-level pages. As long as the "Clear filter" link and block are no longer showing, then this _appears_ to be desired behaviour.

If this is _not_ what you mean, my apologies, but a step by step as to what you're doing to replicate the problem would be really useful :-)

Thanks.

**Comment by Firesphere** [comment]
Woah, half a year ago :)
I got the question from a customer. I'll have to get in touch with them again to re-explain what they do and how they considered it unwanted behaviour. I'll get back to this ;)

**Comment by kinglozzer** [comment]
I guess that customer never did get back to you, eh @Firesphere? 😉 Can’t spot anything wrong in 3.5.3 or 4.0.0-alpha7

**Comment by Firesphere** [comment]
Nope, customer never got back indeed :D
