### ISSUE TITLE
IE9 history.js

### ISSUE THREAD

**Issue by sjdeere** [silverstripe/silverstripe-cms#1057]
When i use Internet Explorer 9 
I see Javascript errors related to history.js
Silverstripe 3.1.5

assets/_combinedfiles/lib.js line 2074 column 286
History.js error
[code]
if(History.getHashByUrl(url)){throw new Error('History.js does not support states with fragment-identifiers (hashes/anchors).');}
[code/]
![ie9problem](https://cloud.githubusercontent.com/assets/2814873/3643056/e3e7c402-10cc-11e4-9e83-1fc0c83946d4.png)

I have tried to additionally install the fluent module  https://github.com/tractorcow/silverstripe-fluent

**Comment by wilr** [comment]
IE9 support will be dropped for 4.0 so unlikely to see any fixes for this unless a PR is raised.
