### ISSUE TITLE
RedirectorPage_Controller redirects on any action

### ISSUE THREAD

**Issue by sb-relaxt-at** [silverstripe/silverstripe-cms#1059]
I'm not sure if it is the desired behaviour that a RedirectorPage redirects every request, independent of the specified action, e.g.: `/category/` is a RedirectorPage to `/category/article/` (or any other site), a request to something like `/category/somethingstupid/` will also be redirected (HTTP 301) by this page. From my point of view this is an unexpected behaviour. Neither is the requested URL "Moved Permanently" to the redirection target, nor is this the normal behaviour when calling an invalid page (without a RedirectorPage beeing involved). I believe that a "404 Not Found" should be returned in the mentioned case.

**Comment by tractorcow** [comment]
I suggest we move redirection behaviour to index() method; The page should only redirect then if not matching another action, or a sub-page.

**Comment by tractorcow** [comment]
If this issue is closed please confirm also that https://github.com/silverstripe/silverstripe-cms/issues/1062 is fixed.

**Comment by robbieaverill** [comment]
Fix at #1863, I don't have fulltextsearch available at the minute to validate that it fixes #1062
