### ISSUE TITLE
Redirector page as homepage stops search functionality

### ISSUE THREAD

**Issue by petrklus** [silverstripe/silverstripe-cms#1062]
Hi,

I have a redirector page as a homepage, however, it seems to clash with the full-text search module. Whenever I use the search functionality on a site with redirector homepage, I get redirected instead of seeing search results

**Comment by tractorcow** [comment]
Caused by https://github.com/silverstripe/silverstripe-cms/issues/1059

**Comment by dhensby** [comment]
Please can you confirm his is now fixed?

**Comment by tractorcow** [comment]
Fix is at https://github.com/silverstripe/silverstripe-cms/pull/1863 for reference.
