### ISSUE TITLE
IE9  Hang when attempting to switching to another page in CMS SiteTree after save and Publish.

### ISSUE THREAD

**Issue by sjdeere** [silverstripe/silverstripe-cms#1065]
CMS problem.
Im seeing the browser hang when I navigate to a different page in the site tree using Internet Explorer 9.  (You get that blue button animation with 3 dots)

Steps to Repeat.
After default fresh install and logged into CMS I go to the home page and type a small edit in the tnymce  content box.
![step1-content update](https://cloud.githubusercontent.com/assets/2814873/3755115/d368c548-1821-11e4-9e9e-8333afd79bb4.jpg)

It hit save & publish
![step2 hit save and publish -success](https://cloud.githubusercontent.com/assets/2814873/3755123/f1239b80-1821-11e4-8590-d1bf909a265c.jpg)

ok thats was successful .. Now I click on About us in the site tree on the left. This is where i get the blue button animation and the browser just hangs
![step3- navigate to other page in sitetree - hang](https://cloud.githubusercontent.com/assets/2814873/3755143/2296840c-1822-11e4-97c1-74fc760f0016.jpg)

I have done some tests developer tools  running to try and see where the error is.
![step3_detail_ie9_example](https://cloud.githubusercontent.com/assets/2814873/3755166/3e37e98a-1822-11e4-99ea-9d3f71b3a392.jpg)

![step3_detail_ie9_js_error](https://cloud.githubusercontent.com/assets/2814873/3755170/43083154-1822-11e4-84bb-6a1776ac9baf.jpg)

Things to note:
Install type: I have installed a fresh SilverStripe 3.1.5 via composer to test this. no other modules etc.
The Browser is Internet Explorer 9 on Windows 7.
The compatibility icon in IE9 is unchecked (you can't login other wise anyway! as it says please use internet explorer 8+  ..etc) 

F12 developer tools  says BrowserMode: ie9  Document Mode: IE standards

getting a permission denied error

Error Details are

SCRIPT70: Permission denied 
assets/_combinedfiles/lib.js  line 2770  character 899

complete extract of line 2770
if(href.match(/^javascript:\s*mctmp/))href='';return href;},createBookmark:function(){return this.getInstance().selection.getBookmark();},moveToBookmark:function(bookmark){this.getInstance().selection.moveToBookmark(bookmark);this.getInstance().focus();},blur:function(){this.getInstance().selection.collapse();},addUndo:function(){this.getInstance().undoManager.add();}};});ss.editorWrappers['default']=ss.editorWrappers.tinyMCE;(function($){$.entwine('ss',function($){$('textarea.htmleditor').entwine({Editor:null,onadd:function(){var edClass=this.data('editor')||'default',ed=ss.editorWrappers[edClass]();this.setEditor(ed);if(typeof ssTinyMceConfig!='undefined')this.redraw();this._super();},onremove:function(){var ed=tinyMCE.get(this.attr('id'));if(ed){ed.remove();ed.destroy();$.each(jQuery.cache,function(){var source=this.handle&&this.handle.elem;if(!source)return;var parent=source;while(parent&&parent.nodeType==1)parent=parent.parentNode;if(!parent)$(source).unbind().remove();});}

debug cursor  points at the "p of parent"  guess thats 899th character  

while(parent&&parent.nodeType==1)parent=parent.parentNode;if(!parent)$(source).unbind().remove();});

**Comment by tractorcow** [comment]
SS 4.0 addresses these issue by using pre-combined static files, rather than live-combining files in assets folder. We are unlikely to look at this issue again unless it re-occurs in ss 3.6.
