### ISSUE TITLE
Clearing cache redirects to wrong page if mod_rewrite is disabled

### ISSUE THREAD

**Issue by Widdershin** [silverstripe/silverstripe-cms#1066]
With a local LAMP stack set up, with mod_rewrite disabled, adding `flush=1` to the URL redirects you a URL that would only work with mod_rewrite enabled.

Example:
I am on `http://localhost/index.php/about-us/`.
I change the URL to `http://localhost/index.php/about-us/?flush=1`
The cache is flushed successfully, but I am redirected to `http://localhost/about-us/?flush=1&flushtoken=<flushtoken>` when I should be redirected to `http://localhost/index.php/about-us/?flush=1&flushtoken=<flushtoken>`.

System:
Silverstripe 3.1.5 (both framework and CMS)
Linux Mint 15 x64
PHP 5.5.3-1ubuntu2.6
Apache/2.4.6 (Ubuntu) 

I tried searching for the issue across the CMS and framework, but couldn't find anything. I am also unsure if this is the appropriate repo for this issue.

It's also fairly low importance because I couldn't imagine many people running mod_rewrite off.

**Comment by tractorcow** [comment]
Fix is to make flush redirect respect `BASE_SCRIPT_URL`

**Comment by tractorcow** [comment]
See `ParameterConfirmationToken::currentAbsoluteURL()`

**Comment by dhensby** [comment]
duplicate of https://github.com/silverstripe/silverstripe-framework/issues/5197

fixed by https://github.com/silverstripe/silverstripe-framework/pull/5200
