### ISSUE TITLE
Editing URL of child of RedirectorPage causes links to old URL to redirect to target of Redirector

### ISSUE THREAD

**Issue by pdelany** [silverstripe/silverstripe-cms#1078]
While performing an upgrade from SS 2.4 to SS 3.1, I've noticed that some behaviour has changed regarding pages that have had their URLs updated.

In both SS 2.4 and 3.1, if a page's URL is changed, links to the old URL are nicely redirected to the new URL. However, in 3.1 (at least), if the parent of the page in question is a RedirectorPage, then the link will now redirect to the target of the redirector page. In 2.4, it redirects to the new URL.

E.g,. if page was originally:

/some/page

and changed to /some/otherpage

and /some is a redirector page, to /elsewhere

then in 2.4 /some/page redirects to /some/otherpage, 
but in 3.1 this redirects to /elsewhere.

While there might be arguments on both sides, I'm wondering if this change in behaviour is a bug or an enhancement. Although I'm probably biased, since this behaviour change is going to cause me a minor headache for my upgrade, I honestly do believe the 2.4 behaviour is, in general, the more desireable, as it would seem to be the intention of anyone who updates the URL to /some/otherpage for /some/page to still direct there.

**Comment by tractorcow** [comment]
Probably related to https://github.com/silverstripe/silverstripe-cms/issues/812

**Comment by tractorcow** [comment]
To do: Write a test that ensures a child of a redirector page can be renamed, and will be picked up by old page redirector.

**Comment by hoodweb** [comment]
Ran into same issue

**Comment by maxime-rainville** [comment]
This works has expected on Silverstripe CMS 4.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
