### ISSUE TITLE
`LeftAndMain` doesn't run in Stage reading mode

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-cms#1094]
`LeftAndMain` doesn't run in stage reading mode, which means ModelAdmin doesn't run in stage reading mode; this impacts the use of `ModelAdmin` to administrate `Versioned` `DataObject`s as the latest live version is always returned for editing.

If you happen to be editing a `SiteTree` object through `ModelAdmin` this leads to a divergence in the `CMSMain` view and the `ModelAdmin` view.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5005
