### ISSUE TITLE
Cannot disable file uploads globally

### ISSUE THREAD

**Issue by Matthew-Bonner** [silverstripe/silverstripe-cms#1105]
At the moment there is no global setting to disable file uploads, which is a problem when some people use an external file manager and for security reasons want to disable file uploads. There should be a setting we can use to remove all upload buttons across the administration area and a further setting to prevent uploads on the front-end if desired. At the moment you have to hack around with the code in order to achieve this.

**Comment by kinglozzer** [comment]
In SS4 you can just choose to not install the `asset-admin` module.
