### ISSUE TITLE
Wrong cache headers hinders split view

### ISSUE THREAD

**Issue by mertenhanisch** [silverstripe/silverstripe-cms#1106]
The browser seems to cache pages when you edit them in split screen. When you change a page for the first time and click on save & publish the changes are shown in the preview panel, but after that changes are not showing in the preview panel. I think ?stage=Stage should never be cached.

**Comment by kinglozzer** [comment]
I can’t recreate this in 3.5.3 or 4.0.0-alpha7, can someone else double-check and then close?
