### ISSUE TITLE
BUG SiteTree _resampled images URLs don't get rewritten when folders move.

### ISSUE THREAD

**Issue by micmania1** [silverstripe/silverstripe-cms#1114]
To reproduce:
* Create a new Folder in the 'Files' section.
* Go to any Page and add an image to the Content.
* Resize the image.
* Save & Publish
* Go to the Files section and rename the folder.
* Go back to the page (note that the image path hasn't updated.).

**Comment by sminnee** [comment]
I believe that this has been addressed with the SS4 filesystem rewrite. Can you confirm, @micmania1?

**Comment by tractorcow** [comment]
I can confirm this is fixe in 4.x. Moving files moves all generated files, and there are no more static file paths in HTML areas anymore (since the move to shortcodes).
