### ISSUE TITLE
History and Settings tab are not removable

### ISSUE THREAD

**Issue by g4b0** [silverstripe/silverstripe-cms#1120]
History and Settings tab are hardcoded in [template file](https://github.com/silverstripe/silverstripe-cms/blob/3.1/templates/Includes/CMSMain_Content.ss), so they can not be removed through getCmsFields().

It would be useful to exclude them from the CMS when managing low-privilege users.

**Comment by chillu** [comment]
Happy to review a PR which adds permission codes for this, which can be enforced in the `CMSMain_Content.ss` template for now. Changing these to `getCMSFields()` will be a major pain, both in the current Entwine system and any new UIs built on React and form schema. Maybe we'll get around to supporting "lazy loaded" tabs in React, but I wouldn't hold my breath. Closing this as an enhancement without an owner for now.
