### ISSUE TITLE
$description not working in page.php

### ISSUE THREAD

**Issue by Friksel** [silverstripe/silverstripe-cms#1128]
When changing the $description in page.php (like so: private static $description = 'Base Page';), the description of sitetree.php remains ("Generic content Page") and so doesn't get overwritten by page.php. Neither after dev/build. For all other pages setting the description works like charm, but not for page.php itself. Looks like I'm not the only one having this problem, so it seems like it's a bug.

Using Silverstripe 3.1.6

**Comment by Friksel** [comment]
Sorry for my late reply
 @cam-findlay because I'm not that into the framework and there's probably a good reason why it's not build this way in the first place. I don't have an overview on dependencies and what it can influence for example. Seems like a small change for people that work on the framework itself on a 'daily' basis

**Comment by tractorcow** [comment]
Fixed with the SiteTree::classDescription() method

https://github.com/silverstripe/silverstripe-cms/blob/63f930c4e990ae2502c6b7f0e141dec59982e1b4/code/Model/SiteTree.php#L2804
