### ISSUE TITLE
Problem with back office display after validation error

### ISSUE THREAD

**Issue by dhminh** [silverstripe/silverstripe-cms#1130]
Hi there,

I added 2 custom fields to Settings by the followings:

  private static $db = array(
        'Latitude' => 'Decimal',
        'Longitude' => 'Decimal'
    );
    public function updateCMSFields(FieldList $fields) {
        $fields->addFieldToTab("Root.Main", new NumericField("Latitude", "Latitude"));
        $fields->addFieldToTab("Root.Main", new NumericField("Longitude", "Longitude"));
    }

Everything seems ok until I input string such as "abc" into these two fields (instead of numeric values). Back office shows "validation errors" right after that. This is right. But it displays the setting form unexpectedly.

![2014-11-12_17h02_32](https://cloud.githubusercontent.com/assets/9693332/5008303/082a3528-6a8e-11e4-8eec-ecb5d29e0a5a.png)

Seems that there is a problem with ui-tab. Below is how it looks before validation:

![2014-11-12_16h43_34](https://cloud.githubusercontent.com/assets/9693332/5008225/47d35b1a-6a8d-11e4-8c7e-b8ab9b266efe.png)

Note that I did not make any changes except adding the two fields.
Did I miss anything?

**Comment by sminnee** [comment]
This is much more solid in SS4, I think we've solved it.
