### ISSUE TITLE
sitetree view collapsed when editing the page

### ISSUE THREAD

**Issue by blpraveen** [silverstripe/silverstripe-cms#1135]
When open a page to edit from the frontend,  sitetree view is collapsed all the time  not  expanded to the page  currently being edited.

In the page template
             `<li><a target="_blank" class="edit" href="admin/pages/edit/show/$ID" title="Edit this page"><span>&nbsp;</span>Edit</a></li>`

**Comment by dhensby** [comment]
Is this still a problem?

**Comment by dhensby** [comment]
No it's not, coz it's closed - sheez
