### ISSUE TITLE
Error page management

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-cms#1139]
I think error pages need an overhaul in the CMS. Two main reasons why:
1. **Error pages don't belong in the site tree.** An error page isn't really a 'page' at all, it's a message that is shown when something goes wrong. It doesn't belong in the site's page hierarchy because it's content may be shown at any URL.
2. **Content editors see the 'Page not found' and 'Server error' icons in the CMS and think something is broken.** They don't see these icons as pages to be opened and edited, they see them as a sign that something has gone wrong with the website.

A simple solution would be to manage error messages in the Settings section instead of the Pages section.
- New tab: Settings > Error Messages
- Grid field that lists error pages by code and title

I also think that whenever you build the database or perform a ?flush, the static copies of the error pages should be regenerated. Why?
1. Template changes may affect the way error pages are rendered
2. Menus included in the static copy change often
3. Environmental changes may affect the base tag

I've quite often broken a live site (just for a moment of course!) and seen an error page with a busted layout and menus full of mock content I used during development, whose links point to my local dev machine. The fact is that I don't customise error messages between sites, I'm happy with the default message. My clients don't even want to know what an error page is, so these icons sit in the site tree, to be updated only when I see how broken the static error page has become. Not ideal.

**Comment by chillu** [comment]
Discussion about this on mailinglist now: https://groups.google.com/forum/#!topic/silverstripe-dev/VFXrusjAnKE
