### ISSUE TITLE
CMSMain cached SiteTree hints should be easier to clear

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-cms#1141]
Currently, the cached SiteTree hints can only be cleared by visiting, for example, `http://mysite.com/admin/pages/add?flush=1`: a flush outside the context of `CMSMain` won’t clear them.

The use of `Zend_Cache::CLEANING_MODE_ALL` should also be removed in this change, as it may have undesired effects (https://github.com/silverstripe/silverstripe-framework/issues/3122).

Ideally, as this code is heavily tied to static config, this should also be cleared on a dev/build. We can either delay until functionality similar to `Flushable` exists for dev/build, or possibly add a hack (e.g. a public static getter for the `SS_Cache` instance, which we use to clear the cache in `cms/_config.php`).

**Comment by tractorcow** [comment]
Zend has been replaced with symfony/cache.
