### ISSUE TITLE
Information disclosure with stage=Stage and not logged in

### ISSUE THREAD

**Issue by oddnoc** [silverstripe/silverstripe-cms#1142]
In the anonymous case, appending ?stage=Stage to a URL does not trigger a permission failure if the page does not have staged content. Instead, the reading mode is set to stage, the page is displayed, and it can reveal staged content from other pages (such as a list of recently changed pages).

In addition, ContentControllerTest#testViewDraft does not test this case.

**Comment by oddnoc** [comment]
I have a solution to this at oddnoc@7fa1df7, and it passes my practical (load it in a browser) test. However, I'm having trouble getting the test (oddnoc@4367fbe) to work correctly. No matter what I do, the unit test gets a 200 OK, even when the page is published. I hope someone with more intimate knowledge can have a look. Thanks!

**Comment by patricknelson** [comment]
:+1: maybe @jonom or @tractorcow might be interested in checking this out.

**Comment by tractorcow** [comment]
Also see https://github.com/silverstripe/silverstripe-cms/issues/1270

**Comment by jonom** [comment]
I think Damien has addressed this with: 
* https://github.com/silverstripe/silverstripe-framework/commit/38e154af0aae89a36f4d3906612ea4bbbf726177
* https://github.com/silverstripe/silverstripe-framework/commit/6089a7c5bd25d6591deb154f1a34908fa91ac198
* https://github.com/silverstripe/silverstripe-framework/commit/fa0160a874c536528d8300e034a7aa8bb6e23989

Will be available in SS 3.3. Can you confirm this can be closed @tractorcow?

Thanks for reporting @oddnoc sorry for the radio silence. And thanks for fixing Damien!
