### ISSUE TITLE
BUG Save and delete buttons showing on 'Files' section and throwing errors.

### ISSUE THREAD

**Issue by camfindlay** [silverstripe/silverstripe-cms#1150]
I have noticed that if you go to the Files section of the CMS you initially get presented with a Save and Delete button which throw errors when pressed (a regression error here perhaps?).

![silverstripe files](https://cloud.githubusercontent.com/assets/367847/5687208/1493751e-98af-11e4-8746-4bad64e6b700.png)

If you then drill down into the File structure and back up (with the 'assets/show/#' action present - the buttons disappear (which I assume is the intend UI for the top level of the Files section?).

![silverstripe-files-2](https://cloud.githubusercontent.com/assets/367847/5687228/4ff5ebbe-98af-11e4-9411-7a2a24e5cba1.png)

**Comment by micmania1** [comment]
Does this happen on a base install (ie no modules)?

**Comment by camfindlay** [comment]
I'll test it and check @micmania1 :+1:

**Comment by camfindlay** [comment]
@micmania1 yes it is a bug on a fresh checkout of 3.1.8

**Comment by chillu** [comment]
Fixed by https://github.com/silverstripe/silverstripe-cms/pull/1186

**Comment by camfindlay** [comment]
:+1:
