### ISSUE TITLE
adding new page form in CMS - sticky error message

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-cms#1155]
error message is sticky (appears long after I already created some other pages):

![image](https://cloud.githubusercontent.com/assets/167154/5771438/085e0136-9da2-11e4-88cf-c12a48c85629.png)

**Comment by dhensby** [comment]
What version of SS is this and can you provide steps to replicate and any relevant skeleton code, please?

**Comment by sunnysideup** [comment]
Ok - this is actually a bit tricky ...

(1) create a new page (at any level), no need to publish it

(2) delete it

(3) click on add new

create a new page ...

![image](https://cloud.githubusercontent.com/assets/167154/6087248/14df6d60-aeae-11e4-8662-39f134da3d7e.png)
no error shown .... but nothing happens

Note:
![image](https://cloud.githubusercontent.com/assets/167154/6087322/e013b540-aeae-11e4-8f1d-c2181b5da632.png)


Then do something else... Then come back to add page:
![image](https://cloud.githubusercontent.com/assets/167154/6087327/f72f0e78-aeae-11e4-8013-53d37233d599.png)

**Comment by sunnysideup** [comment]
In the first screen an error should show "bla not allowed on root level" ...

**Comment by dhensby** [comment]
@sunnysideup are there any dependencies here, like a blog module? can you let us know the set up, please?

I still need to know SS version and skeleton code (or composer.json of deps, if it's all core code)

**Comment by sunnysideup** [comment]
```shell
    composer create-project silverstripe/installer ./temp
```

then add the following page type:

```php

<?php
class PageThatCantBeRoot extends Page {

	private static $can_be_root = false;

}
class PageThatCantBeRoot_Controller  extends Page_Controller {


}
```

![image](https://cloud.githubusercontent.com/assets/167154/6095936/76ec7b7e-afda-11e4-9261-70988ede6253.png)

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
