### ISSUE TITLE
add new page form - funny jump in check boxes between selection 

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-cms#1156]
compare

![image](https://cloud.githubusercontent.com/assets/167154/5771447/3177f086-9da2-11e4-87a8-ed2aafeaf11f.png)

to 

![image](https://cloud.githubusercontent.com/assets/167154/5771451/3c661662-9da2-11e4-9160-abbd327fd901.png)

**Comment by dhensby** [comment]
Unfortunately a framework issue that manifests itself in the CMS
