### ISSUE TITLE
new page form: strange brackets in select page type

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-cms#1157]
![image](https://cloud.githubusercontent.com/assets/167154/5771456/6c39a688-9da2-11e4-8113-a2655284d987.png)

**Comment by dhensby** [comment]
Can you provide a bit more information on the set up?

SS version, environment, are there any custom changes?

I can't replicate this using 3.1--dev

**Comment by sunnysideup** [comment]
This is how to replicate it:

1. 
![image](https://cloud.githubusercontent.com/assets/167154/5790373/07be716c-9efa-11e4-979b-469465ea814f.png)

2. click on "Under another page"

3. click on "top level"

4. click on "Under another page"

even if you select a parent page you get the same effect:

![image](https://cloud.githubusercontent.com/assets/167154/5790389/8a91b72a-9efa-11e4-85c3-469366673f18.png)


I know these are just little things, but it would be great to get them cleaned up.

**Comment by dhensby** [comment]
ok, I can replicate this on 3.1.9

**Comment by dhensby** [comment]
This is a bug in framework as it's the TreeDropdownField that is broken
