### ISSUE TITLE
SiteTree UI is not updated on child pages when a parent page is unpublished

### ISSUE THREAD

**Issue by silverstripe-elliot** [silverstripe/silverstripe-cms#1161]
When a CMS author unpublishes a parent page, the child pages are also unpublished. However, the SiteTree UI is not updated to reflect this change on the children. The parent page shows as a Draft, but none of the child pages will show as a Draft without logging out or refreshing the page. 

To reproduce this issue on demo.silverstripe.org:
1. Publish a page "test".
2. Publish "child1" under "test
3. Publish "child2" under "test"
4. Unpublish "test".
5. Click either child page.
    \* Observe "Draft" badge is placed next to parent page in Site tree, but not on children
    \* Observe "Save and publish" is green and "unpublish" option is gone from "More options" on child page, indicating an unpublished page. 

If you refresh the CMS or log in again, the parent and child pages show Draft badges.

![parent-is-draft-child-is-unpublished-1](https://cloud.githubusercontent.com/assets/5863816/5911597/9d801398-a62c-11e4-9e4a-7359cf8a1170.png)
![parent-is-draft-child-is-unpublished-3](https://cloud.githubusercontent.com/assets/5863816/5911652/6bc1460a-a62d-11e4-91ee-62116217cfea.png)

**Comment by tractorcow** [comment]
I've had a look at this issue, and it seems to be due to an explicit decision to only update the tree node that was updated. See `LeftAndMain::updatetreenodes` (only updates that node) and `LeftAndMain::getsubtree` (updates whole subtree).

We could update the script to always update the sub-tree, but it appears that this would have real performance implications. 

I think we should still do this, but with additional testing to make sure that we don't suddenly make the tree view slow and impossible to use.

**Comment by tractorcow** [comment]
Maybe we can fix it in 3.2?

**Comment by tractorcow** [comment]
Agree with sam's call on this; It's a nice to fix but ultimately the impact of the change means it probably isn't feasible to do it before beta2.

**Comment by dhensby** [comment]
or 3.5?

**Comment by tractorcow** [comment]
Someone needs to write a fix for this in any case.

**Comment by dhensby** [comment]
@someone can you get on it?

**Comment by chillu** [comment]
Still the case in 4.0. Ideally I'd fix UX issues like that in the bigger picture of investigating how we deal with tree-based UI components, and wire this all up with GraphQL that would do this state management on the client. That's already a stretch for 5.0 (Q4/2018) though, so it might be valueable to spend a bit of time patching this in Entwine.

**Comment by unclecheese** [comment]
https://github.com/silverstripe/silverstripe-admin/pull/597 updates all the visible child nodes. It's not very mindful of performance considerations, but it does that job. Wondering if maybe we could only run the request when the list is less than a certain number.
