### ISSUE TITLE
Error when creating ErrorPage in split view/preview mode

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-cms#1163]
See screenshot below. Steps to recreate:
- Edit any page and enable 'split view' or 'preview' mode
- Click back to 'Pages' and add a new ErrorPage

Looks like it just needs a `$defaults` value, saving draft/publishing fixes the error as it is then given an error code.

![screen shot 2015-02-11 at 10 05 45](https://cloud.githubusercontent.com/assets/1655548/6145084/f9dd92aa-b1d5-11e4-9e9e-00e458e80d40.png)

# Pull request
* [x] https://github.com/silverstripe/silverstripe-errorpage/pull/28

**Comment by sminnee** [comment]
See also https://github.com/silverstripe/silverstripe-framework/issues/3280

**Comment by maxime-rainville** [comment]
Still an issue in 4 
![image](https://user-images.githubusercontent.com/1168676/49421689-d658eb80-f7f5-11e8-8c70-f734ffbcc08e.png)

**Comment by maxime-rainville** [comment]
Done a PR. Like @kinglozzer said ... it just needs a default.

**Comment by maxime-rainville** [comment]
Fixed in 4.4 by silverstripe/silverstripe-errorpage#28
