### ISSUE TITLE
very minor issue: [Notice] Undefined index: Search

### ISSUE THREAD

**Issue by Jellygnite** [silverstripe/silverstripe-cms#1164]
If in dev mode and run the SearchForm with no value for the search term it returns the following notice. 
When in live mode it returns all pages from SiteTree which I believe is undesirable. I suggest  adding 
        if(!isset($data['Search'])){
            $data['Search'] = '';  
        }

or returning an empty array.

/\* ERROR MSG  AS FOLLOWS*/
[Notice] Undefined index: Search
GET /home/SearchForm

Line 116 in /cms/code/search/SearchForm.php

**Comment by lukereative** [comment]
Closing this as SS3 is now in security only support and will not be fixed for 3.x.
