### ISSUE TITLE
Drag and drop file upload in CMS does not work in Internet Explorer 11

### ISSUE THREAD

**Issue by smartinet1** [silverstripe/silverstripe-cms#1174]
We have a client with IE11 who is unable to use the drag and drop upload support. The "drop area" section does not appear at all.
There is no issue on Firefox, Chrome, or Safari browsers.
Before people bash IE, the client has an SOE and can't run alternate browsers in their environment. As IE11 has full support for HTML5 etc. why does this function not work, and where in the documentation does it state this?
Interestingly, I had no issues dragging and dropping the below attachments to here in the same IE11 browser.
I have reproduced this issue in both the client's SS implementation and on the demo.silverstripe.org site, we have the same issue in our environment using IE11 as the client's environment.
Internet Explorer 11:
![silverstripe - ie11](https://cloud.githubusercontent.com/assets/11451379/6659369/01a0a998-cbd8-11e4-910a-7a8c6c4ff807.png)
Firefox 36.0.1:
![silverstripe - firefox](https://cloud.githubusercontent.com/assets/11451379/6659370/01a1bf04-cbd8-11e4-8111-cae68e82cac8.png)

In addition to this issue, the general use of the CMS is buggy, with table manipulation being severely limited when using the page editor, among other issues with images, etc.

**Comment by lukereative** [comment]
Closing this as the upload field has completely changed in SS4.x and works with D&D IE11. As 3.x is in security only support this issue is not going to be fixed for 3.x
