### ISSUE TITLE
package tarballs with top directory

### ISSUE THREAD

**Issue by richtekp** [silverstripe/silverstripe-cms#1178]
Don't put all files in the tarball because it messes up directories of users who are used to a top directory in the tarball (usually named `[program]-[version]`) containing all files and didn't check the content with `tar tf`.

experienced with http://www.silverstripe.org/assets/releases/SilverStripe-cms-v3.1.12.tar.gz

**Comment by dhensby** [comment]
hmm, good point. GH provides downloads in the way that is being suggested here.

**Comment by chillu** [comment]
This should be raised in the `buildtools` project, see https://github.com/silverstripe/silverstripe-buildtools/blob/master/build.xml#L196. While I agree that it'd be less surprising this way, I think that the archive format is part of our "public API" - devs will have built automation around it which relies on a certain file structure in the archive - so I'm not in favour of changing it.
