### ISSUE TITLE
Broken Links Report contains broken links when used with Translatable module

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-cms#1183]
When the Translatable module is installed, the Broken Links Report generates invalid links to pages it lists. The format it uses is `/admin/pages/edit/show?locale=en_US/1`, rather than `/admin/pages/edit/show/1?locale=en_US`.

Steps to reproduce:

1. Create new instance of Silverstripe (tested with v3.1.12)
2. Add and enable the Translatable module (tested with v2.0.6)
3. Invoke a broken link by creating a link from one CMS page to another and then deleting said page
4. Visit the Broken Links Report and try to click on the page in the list. An `InvalidArgumentException` will be raised.

The affected code is in `code/reports/BrokenLinksReport.php` - specifically lines 82 and 87.

**Comment by chillu** [comment]
Fixed through https://github.com/silverstripe/silverstripe-cms/pull/1188

**Comment by zarocknz** [comment]
@chillu Unfortunately some of the other reports are broken as well, not just the 'broken links' one. 

Both the Pages with No content (EmptyPagesReport.php), and Pages Edited in the last 2 weeks (RecentlyEditedReport.php) suffer from the same issue where the ID is getting added after the locale so the translatable module throws an "unknown locale en_NZ/80" type of error.

This is also broken in the CWP flavour of SilverStripe, which we are using for the project where this was noticed. I see CWP requires the translatable module, so I can't really uninstall it.

I suppose we'll just have to tell our client to not try to use these reports until a fix CWP rolls out, unless you have any ideas for a work around in the short term?

Thanks.

**Comment by tractorcow** [comment]
> I see CWP requires the translatable module, so I can't really uninstall it.

Please do... copy cwp-basic-recipe modules into your root and delete the modules you don't need. Everything in there except framework and cwp-core are optional. :)

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe-labs/silverstripe-reports/pull/37

**Comment by tractorcow** [comment]
(2/2) Rest of fix for this at https://github.com/silverstripe/silverstripe-cms/pull/1542
