### ISSUE TITLE
RedirectorPage still redirects even if URL is invalid

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-cms#1197]
For example, if you setup a redirector page at `/base-section` which is intended to redirect to `/base-section/overview`, but a user visits an invalid page URL such as `/base-section/old-page` it will _always_ redirect that request to `/base-section/overview`, even if that URL is `/base-section/very/long/with/many/slashes`. This was a problem with my site (and fixed pretty quickly once I tracked down what was causing it) because this base section had a lot of pages underneath it that all shifted to be one level deeper, making this quirk more apparent. Please note that this is just one example, but I suspect that there may be other situations where this result would not be quite as helpful

Looking deeper, this may be due to the [Redirector::init()](https://github.com/silverstripe/silverstripe-cms/blob/3.1/code/model/RedirectorPage.php#L164) method not checking to see if an action was provided. In my opinion, if you setup a redirector page at a specific URL and the user enters a URL that doesn't match that page's URL, it should continue past ::init() and process as usual, therefore resulting in an expected 404.

**Comment by maxime-rainville** [comment]
Confirmed fixed on Silverstripe 4.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
