### ISSUE TITLE
Allow $allowed_children to take account of extensions or be made configurable

### ISSUE THREAD

**Issue by gordonbanderson** [silverstripe/silverstripe-cms#1208]
The scenario I have run into is this.  I have a class called PageWithImage, simply a standard Page with an Image called MainImage, and a PageWithImageFolder extending PageWithImage containing PageWithImage.  If I set $allowed_children as follows I see what is I think the expected behavior of any class that extends PageWithImage showing up in the CMS as addable under a PageWithImageFolder.

```
static $allowed_children = array('PageWithImage');
```

The problem here is that for third party modules whose Page objects do not extend PageWithImage I cannot add them to a PageWithImageFolder.  Yes I can add an image using an extension to the third party page, but there is no way to allow this as addable without having to maintain a separate branch of the "page with image" module for each project.

So what are the options?
* Make $allowed_children configurable from YAML, thus it could be overriden on a project by project basis.  I think this would be the cleanest solution but when I tried it I could not get it to work (the building of the config manifest failed)
* Maintain forks of all third party projects I wish to show in a folder as images in the website - would make composer a pain, would have to manually update forks, so not really an option.
* Change $allowed_children to take account of classes that have a certain extension.  In the problem above if I add an image to a third party module Page using say 'AddImageExtension' then if I added 'AddImageExtension' to $allowed_children then the third party module Page(s) would show up as addable in the CMS and be valid.  From grepping through the code, it appears that the methods validate() and allowedChildren() in SiteTree.php would need changed.
* Remove the $allowed_children from PageWithImageFolder.  I'd prefer if there was a better solution :)

If anyone has any alternative suggestions for a solution I'm listening :)

**Comment by micmania1** [comment]
allowed_actions needs to be defined on each controller for security reasons. Its to protect against allowing actions without realising it. I believe this was introduced in 3.1.

I'd consider it a bug that you can't define extra actions in YAML. Does removing the EXCLUDE_EXTRA_SOURCES fix this for you? https://github.com/silverstripe/silverstripe-framework/blob/3.1/control/RequestHandler.php#L313

**Comment by gordonbanderson** [comment]
@micmania1 It appears the issue with YAML is that the definition of allowed_actions can't be the result of a method.  I get a PHP syntax error if I don't declare it as an array('Class1','Class2') etc

**Comment by gordonbanderson** [comment]
@micmania1 The problem is with allowed_children, not allowed_actions

**Comment by kinglozzer** [comment]
@gordonbanderson You should be able to set `$allowed_children` in config.yml, can you paste the YAML block you’re trying to add?

**Comment by micmania1** [comment]
oh, sorry. carry on... :D

**Comment by gordonbanderson** [comment]
@kinglozzer I traced it down to this being invalid syntax

```php
static $allowed_children = Config::inst()->get('PageWithImage', 'allowed_children');
```
with PHP parse error in the Apache log
```
PHP Parse error:  syntax error, unexpected '(', expecting ',' or ';' in /home/gordon/work/git/weboftalent/jakayanrides/www/page-with-image/code/PageWithImageFolder.php on line 9
```

It seems that invoking a static variable via a method is not valid in PHP.  Is there a way around this that I don't know about?

**Comment by gordonbanderson** [comment]
Or do you mean @kinglozzer that an existing mechanism exists to check for allowed_children in YML files and that the static declaration that was failing for me above is not required?

**Comment by gordonbanderson** [comment]
OK I see an example here of configuring can_be_root in a YML file, namely https://github.com/silverstripe-australia/silverstripe-multisites/blob/master/_config/sitetree.yml - so setting allowed_children in a similar manner perhaps?

**Comment by kinglozzer** [comment]
I’m still a bit confused about your exact page structure/inheritance, but if you need to do it in PHP you can do it in `_config.php`:

```php
$pageWithImageChildren = Config::inst()->get('PageWithImage', 'allowed_children');
Config::inst()->update('PageWithImageFolder', 'allowed_children', $pageWithImageChildren);
```

but as far as I’m aware the following should work in YAML:

```yml
PageWithImageFolder:
  allowed_children:
    - MyPageTypeA
    - MyPageTypeB
```

Can you solve what you want with either of the above methods?

**Comment by gordonbanderson** [comment]
Aha, thanks @kinglozzer you pointed me in the right direction.  I deliberately chose a random different allowable child as below and that worked :)

```yml
---
Name: pagewithimage
---
PageWithImageFolder:
  can_be_root: true
  allowed_children:
    - FlickrSetPage

PageWithImage:
  can_be_root: false
```

**Comment by gordonbanderson** [comment]
@kinglozzer Thanks for your help, I didn't know about this aspect of SilverStripe configuration.  And it looks like we all but synchronously posted :)  Issue now resolved.
