### ISSUE TITLE
ProvideComments Label to be removed

### ISSUE THREAD

**Issue by blpraveen** [silverstripe/silverstripe-cms#1220]
ProvideComments column not longer exists in the sitetree table.
Below line needs to be commented or removed

$labels['ProvideComments'] = _t('SiteTree.ALLOWCOMMENTS', "Allow comments on this page?");

**Comment by dhensby** [comment]
@blpraveen where is that line?

**Comment by phptek** [comment]
```
#> find cms -type f -name '*.php' | xargs grep -n ProvideComments
cms/code/model/SiteTree.php:2180:			$labels['ProvideComments'] = _t('SiteTree.ALLOWCOMMENTS', "Allow comments on this page?");
```

**Comment by chillu** [comment]
Line no longer present in 4.x
