### ISSUE TITLE
BUG Fix behat tests for "insert file"

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-cms#1223]
See https://github.com/silverstripe/silverstripe-framework/pull/4249#issuecomment-113388104

The functionality itself is fine, but someone needs to update the behat test so it doesn't constantly fail.

**Comment by tractorcow** [comment]
cc @Zauberfisch  / @scott1702

**Comment by kinglozzer** [comment]
I meant to say I did look at this briefly recently. It’s a bit of an awkward one... the existing behat test is for picking a file: to do that in an `UploadField`, behat needs to switch into an iframe. Behat can do that, but we’ll need to add something to tell it how to do it, and it can only do it if the iframe has a name (which it doesn’t). So it looks like we’ll need:

- A framework PR to add a `name="something"` attribute to the `UploadField` iframe
- A behat-support PR (I think?) to add logic for picking files inside that `UploadField` iframe
- A CMS PR to actually update the broken tests to use that logic

**Comment by tractorcow** [comment]
I think it's been addressed in https://github.com/silverstripe/silverstripe-cms/pull/1234

**Comment by tractorcow** [comment]
Backported this fix to 3.2 with https://github.com/silverstripe/silverstripe-cms/pull/1236

**Comment by kinglozzer** [comment]
Well, that’s _much_ simpler than I thought it would be!
