### ISSUE TITLE
Update Media box: "Update" button often pushed off bottom

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-cms#1224]
Often the **Update** button gets pushed off the bottom of the **Update Media** box. You can get to it by scrolling, but this isn't always obvious.

![](http://spdr.me/1gx8N+)

The issue seems to be caused by the fact that the height of the thumbnail displayed in the top left can vary. 

Perhaps a fix could be to generate the thumbnail using "PaddedImage" so that it's always the same dimensions?

**Comment by tractorcow** [comment]
Is this present in 3.1 or just 3.2?

**Comment by jonom** [comment]
Fit (previously CroppedImage) or Pad (PaddedImage) would probably both work okay here... but I'd say there's a problem with the modal layout if this is happening - most lightbox scripts calculate the dimensions of the content and size the box appropriately. Would be better to fix the problem at the root so we don't have to place a specific height constraint on it.

Those width + height fields could be inlined in a single row too to look a little better and save some vertical space.

**Comment by purplespider** [comment]
Fixed in SilverStripe 4, as footer containing button is now sticky.
