### ISSUE TITLE
UI Bug: Multi-selection "Actions" dropdown contains redundant "Actions" item

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-cms#1225]
The **Actions** dropdown accessed by clicking the **Multi-selection** button on the main Site Tree screen contains a redundant item labeled "Actions":

![](http://spdr.me/188ee+)

I get that this is probably just so the dropdown displays a label "Actions" by default, but it really shouldn't also be an option in the dropdown.

**Comment by tractorcow** [comment]
This was actually resolved in the 3.x branch; Please see the below screenshot.

![image](https://cloud.githubusercontent.com/assets/936064/9029421/5eed2bf8-39e7-11e5-8720-09235a33ace0.png)

For reference, this is what's in 3.1 (so it's not just a 3.2 issue)

![image](https://cloud.githubusercontent.com/assets/936064/9029425/773ec676-39e7-11e5-8605-5cfc0efddae5.png)

I think we decided it was an enhancement not so much a bugfix, so it went into the features branch with the UX rewrite.
