### ISSUE TITLE
TinyMCE editor inserts wraps <ul> / <ol> contents with <span> and inline styles

### ISSUE THREAD

**Issue by prembo** [silverstripe/silverstripe-cms#1240]
I've observed this with silverstripe-cms 3872b02f6592ce49b90167e81ad1ef12bd8e1945 (but it may have been there for a lot longer) and on Webkit browsers (see this possibly related [Wordpress bug report](https://core.trac.wordpress.org/ticket/17154)).

When converting existing content (e.g. `<p>`'s) into `<ul>` to `<ol>`, the text is wrapped in `<span>`'s with inline styles.  If you type the text and create subsequent list items via hitting enter, these `<span>`'s aren't created.

Eg. assuming the following is present...
```
<p>line 1</p>
<p>line 2</p>
<p>line 3</p>
```
And then it is highlighted and the unordered or ordered list button is clicked, the following is the resulting markup:
```
<ul>
<li><span style="font-family: inherit; font-size: 1rem; line-height: 1.6;">line 1</span></li>
<li><span style="font-family: inherit; font-size: 1rem; line-height: 1.6;">line 2</span></li>
<li><span style="font-family: inherit; font-size: 1rem; line-height: 1.6;">line 3</span></li>
</ul>
```

**Comment by prembo** [comment]
I'd previous thought it only does it when converting to `<ul>`'s and `<ol>`'s, however it seems to also apply to any text that is pasted too, even though "Paste as Plain Text" is selected.

**Comment by cwchong** [comment]
Does the issue arise if you use Firefox instead?
Cause I believe that webkit browsers add these inline span styles on editable content areas.

If the issue does not occur when using Firefox, you can try the following workaround, if you are sure you do not need inline span styles:

Add the following to your _config.php:
```
HtmlEditorConfig::get('cms')->setOptions(array(
	'extended_valid_elements' => "span[!class]"
));
```

This allows only spans with class attribute provided, thus inline spans will be removed

**Comment by dhensby** [comment]
Is this a framework issue or a tiny MCE one?

**Comment by tractorcow** [comment]
SS4.0 uses TinyMCE 4.0, which I doesn't seem to reproduce this problem.

```html
<ul>
<li>line 1</li>
<li>line 2</li>
<li>line 3</li>
</ul>
```
