### ISSUE TITLE
TinyMCS Insert Link - download a file should offer an upload box/ drag and drop 

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-cms#1242]
When selecting text in the WYSIWYG editor, when you insert a link to a file it should offer to upload a file (or drag and drop to upload a file).

It would be quite handy when inserting a file.

**Comment by kinglozzer** [comment]
This has been added in 3.2 (https://github.com/silverstripe/silverstripe-framework/pull/4249)
