### ISSUE TITLE
ContentConroller::getViewer() fails to correctly resolve templates for actions

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-cms#1244]
This code fails to execute the correct template in 3.2:

```php

class Page_Controller extends ContentController {

    private static $allowed_actions = array(
       'success',
    );

}
```

This executes `$this->renderWith(array('Page_success', 'Controller'));` instead of `$this->renderWith(array('Page_success', 'Page'));`

**Comment by kinglozzer** [comment]
Oops, accidental button click!
