### ISSUE TITLE
TinyMCE disappears after deploynaut deploy

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-cms#1249]
I'm unsure of where this issue should lie, but the TinyMCE editor disappears after each deploynaut deploy. Sometimes it seems to trigger randomly. 

When this happens a simple ?flush=1 will fix it, though it is frustrating. It doesn't appear to be a Javascript issue as there's nothing in the log. 

![image](https://cloud.githubusercontent.com/assets/67215/8917300/535cb510-3505-11e5-94b3-5b3b59f867aa.png)

**Comment by camfindlay** [comment]
@torleif you should post this issue through to the CWP ops team via the helpdesk rather than on the open source issues on GItHub.

**Comment by torleif** [comment]
done.
