### ISSUE TITLE
CMS Page Filtering

### ISSUE THREAD

**Issue by nglasl** [silverstripe/silverstripe-cms#1251]
So the problem that I'm having..

It seems as though there's some kind of caching happening in regards to the CMS page filtering search form when using custom fields.

I'm currently using my module to populate a **text** field with tags, and then to filter on this (with the ability to handle multiple values).

![tagging](https://raw.githubusercontent.com/nglasl/silverstripe-fusion/master/images/fusion-tagging.png)

![filtering](https://raw.githubusercontent.com/nglasl/silverstripe-fusion/master/images/fusion-filtering.png)

This works okay at first. However, once you start adding more tags to different pages and then filtering, the listing will not appear as you'd expect. I've cross referenced with the database, and although the database fields are correct, the filtering doesn't seem to detect any changes past a certain point. 

When I trigger a hard refresh of the CMS, the filtering will suddenly begin working as expected. This leads me to believe that there must be some kind of caching happening behind the scenes that's causing issues.

This isn't critical, as I believe it's more of an edge case than anything, however it can be frustrating (especially from a user's point of view). This sounds closely related to issue #867, so I also thought that might be worth mentioning :)

**Comment by nglasl** [comment]
Would there happen to be any update on this?

**Comment by tractorcow** [comment]
Sorry, I don't know...

I can't see any cache to speak of. I guess it could be to do with subsequent searches simply not forcing an update of the UX? I guess inspect http traffic and see if the error is client or server side.

**Comment by dhensby** [comment]
Are you using any server-side cache layer like google pagespeed?

**Comment by nglasl** [comment]
I am not, though I am leaning towards it being a UX specific issue. Coming back to this now, it definitely seems like the same problem as https://github.com/silverstripe/silverstripe-cms/issues/867 (that I listed above). I'm going to close this so we can keep things in the one place, but unfortunately I don't have any time to dig further at the moment.
