### ISSUE TITLE
SiteTree duplicate doesn't match the DataObject duplicate, so onAfterDuplication is very tricky

### ISSUE THREAD

**Issue by pitchandtone** [silverstripe/silverstripe-cms#1253]
SiteTree calls $this->invokeWithExtensions('onAfterDuplicate', $clone) whereas DataObject calls $clone->invokeWithExtensions('onAfterDuplicate', $this)

I personally think the latter is better.

**Comment by sb-relaxt-at** [comment]
This issue still exists in 3.2.1. The only usage of the on*Duplicate extension points in the core - [Versioned](https://github.com/silverstripe/silverstripe-framework/blob/3/model/Versioned.php#L1508) - is indicating that the second option is the intended one.

**Comment by tractorcow** [comment]
Yep, but I think it is possibly risky to do this in 3, in case users are relying on the current sitetree behaviour. Do you want to raise a PR to master branch to change this API?

**Comment by tractorcow** [comment]
SiteTree::duplicate also calls parent::duplicate, so these extensions are in fact run TWICE, once for both clone and original, ugh.

**Comment by sb-relaxt-at** [comment]
Yes the duplicated (no pun intended ;-)) call of on*Duplicate is also an issue... Yes I can try to prepare a PR. Concerning the extension methods, it might be the best to create an onBeforeDuplicate and onAfterDuplicate method in DataObject, similar to the on*Write methods? This would allow clean overwriting by SiteTree and prevent duplicate extension calls.

**Comment by tractorcow** [comment]
> it might be the best to create an onBeforeDuplicate and onAfterDuplicate method in DataObject, similar to the onWrite methods?

I'm not sure if that would solve anything though.

**Comment by sb-relaxt-at** [comment]
Well, if we overwrite the duplicate method and call the parent's implementation this would trigger the before/after extensions. Therefore I considered creating onBeforeDuplicate and onAfterDuplicate. This would allow SiteTree to overwrite onAfterDuplicate instead of duplicate.

**Comment by tractorcow** [comment]
SiteTree can already do that; You don't need to add the methods to DataObject for that to work.

All you need is the onBeforeDuplicate in SiteTree, and add the Sort = 0, right?

**Comment by sb-relaxt-at** [comment]
My bad, I have forgotten that invokeWithExtensions also calls the method if it exists on the object itself. So its even easier, thanks :-)

**Comment by tractorcow** [comment]
Cool. :)

**Comment by gregsmirnov** [comment]
Thank you @tractorcow for pointing to this issue. I've got so used that SiteTree is part of Framework... :)

The only but, is `invokeWithExtensions` method does not pass correctly `$doWrite` parameter, that might be useful in extensions. But since it is broken, no extensions may rely on it, it can be removed.
I found this issue, while playing with new extension for "versioned" widgets.

**Comment by tractorcow** [comment]
You're correct; That's another issue.

How about we extend `invokeWithExtensions` to include all parameters in the same format as per `extend`, and also make them pass by-ref? It will need to be done in master branch, of course.

Sound fair?

**Comment by gregsmirnov** [comment]
I agree, the signature of `invokeWithExtensions` and `extend` methods should be the same.
Both changes are backward compatible, so I think they can be added to branches 3.1+ as well.
We actually already use overloaded implementation in `Page::duplicate` for the initial issue.

**Comment by tractorcow** [comment]
We can't add parameters to invokeWithExtension in non-master branches, because it would break existing overrides of that method. It would suddenly cause method signature strict declaration issues.

That's semantic versioning for you. :P

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-cms/pull/1525.
