### ISSUE TITLE
archive function

### ISSUE THREAD

**Issue by guyvanbael** [silverstripe/silverstripe-cms#1258]
I know this is a topic which has been adressed earlier, but i still find the term 'Archive'  a bit misleading because it implies that the page can be restored later on at any time. It is in fact more realistic to say "delete page", because when session is over, the page is actually deleted and can't be restored anymore.

**Comment by kinglozzer** [comment]
@guyvanbael You can still recover the page by opening the filter menu, and selecting “all pages including archived”

**Comment by guyvanbael** [comment]
Thanks Loz,

Didn't know this.... it makes sense now.

2015-08-05 17:44 GMT+02:00 Loz Calver <notifications@github.com>:
