### ISSUE TITLE
BUG : "Show children as list" on archived page causes internal server error message. 

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-cms#1260]
To reproduce in 3.2.0-beta2.:
(1) create a page
(2) archive the page
(3) select archived page
(4) right click-> "show children as list"
(5) error message appears top right

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-cms/pull/1265

**Comment by tractorcow** [comment]
Fixed with #1265
