### ISSUE TITLE
tinymce setting hspace and vspace

### ISSUE THREAD

**Issue by guyvanbael** [silverstripe/silverstripe-cms#1267]
One of my clients drew my attention to the fact that it isn't possible anymore to set (or edit) margins (hspace, vspace) on inserted images in tiny mce like in SS3.0
Found someting in tinymce's options, but adding this to my _config.php doesn't help either :
HtmlEditorConfig::get('cms')->setOption('image_advtab', 'true');

**Comment by dhensby** [comment]
This may help? http://www.tinymce.com/forum/viewtopic.php?id=4755

**Comment by guyvanbael** [comment]
maybe i epressed myself the wrong way. It's not that the hspace and vspace is being stripped. I just can't fill in any values.  In SS3.0 the edit image icon (or right clicking on an image in tinymyc) brought up the dialog window in wich you could enter the hspace or vspace together with width and height. In SS3.1 you can only set width and height.

**Comment by sminnee** [comment]
Correct me if I'm wrong, but aren't hspace and vspace pre-CSS attributes? We've generally built SilverStripe in a way that discourages the use of such markup (you also can't create a font tag, for example), and instead recommend that theme developers use CSS to set up image spacing in a consistent way.

I would expect that this is why the features were removed.

Unless I'm missing something, I don't expect that we'll add the facility back. However, I expect that you can probably add hspace and vspace in the HTML editor view, if you have a particular need for it.

**Comment by guyvanbael** [comment]
If it was me who manages the content, it wouldn't be a problem, because i
am a developer, but most contentauthors aren't familiar with html (or
inline styles for that matter). They just insert an image in tinymce and
want to make text wrap around, but without the option of adding margin (as
it was in SS 3.0), this is pretty useless because al text is right up the
image with no margin at all. Sure i could write a css-rule that creates the
margins, but then it will be applied to EVERY image.

Another option is to add custom classes to the tinymce editor for all
marginoptions.

In the themes i create for my clients, i make sure that images are handled
through gridfield and placed in the correct place by the template, but
sometimes contentauthors want to add extra images in the contentblock and
then the option to set margins on an image was not bad...

I was hoping it was a setting in tinymce, so i could restore it for clients
who need it...

2015-08-24 23:19 GMT+02:00 Sam Minnée <notifications@github.com>:

**Comment by dhensby** [comment]
I imagine this is still configuration in TinyMCE and likely something you can add back in, though I'm not certain how.

From what I can see, many browsers don't even support these attributes any-more, so adding it back will not solve the problems for your content author.

Perhaps adding new properties to the `.leftAlone` and other related image alignment classes would be better?

**Comment by guyvanbael** [comment]
That would be a good solution Daniel! I'll go for this solution.
