### ISSUE TITLE
?stage=Stage should require log-in, even if draft content is unmodified

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-cms#1270]
In 3.2, if you add `?stage=Stage` to a page that doesn't have draft content changes, it will let you switch. Because the permission model is a bit more rigorous, this won't show protected draft content, but it does create a weird experience for the user, with some pages hidden and some displayed in menus.

The change that introduced this is here:

https://github.com/silverstripe/silverstripe-cms/commit/b169823a00fed190bcd55054339baa3bc818cd75#commitcomment-12968653

`?stage=Stage` and `?archiveDate=y-m-d` needs to be restricted, even if content isn't modified on draft.

**Comment by sminnee** [comment]
The change was made because the code broken when viewing the archive site of a page that doesn't now exist on draft.

A more complete fix will probably to to refactor https://github.com/silverstripe/silverstripe-cms/blob/3.2/code/model/SiteTree.php#L912 to be accessible elsewhere. The code in 912-921 is responsible for checking access to unpublished content.

`canViewStage()` could possibly be deprecated in favour of `canViewUnpublished()`, which performs something like the 917-921 check as well as canView().

**Comment by jonom** [comment]
I think Damien has addressed this with https://github.com/silverstripe/silverstripe-framework/commit/38e154af0aae89a36f4d3906612ea4bbbf726177
Can you confirm @tractorcow?

**Comment by sminnee** [comment]
I would say "yes"
