### ISSUE TITLE
Users shouldn’t be able to see page types they can’t create in the “Add Page” view

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-cms#1272]
See https://groups.google.com/forum/#!topic/silverstripe-dev/dNa9riK5e-o

**Comment by dhensby** [comment]
I think this is working as intended and this is ultimately a feature request?

**Comment by kinglozzer** [comment]
It was a side effect of the `canCreate()` changes between 3.1.10 and 3.1.11 (see the Google Group discussion above), so I think it’s probably a regression as I doubt they were intentionally made visible

**Comment by dhensby** [comment]
They are visible by disabled, which seems intentional to me. We've come a long way since 3.1 and to undo it now seems a bit silly on a technicality - the admin CSS can always be changed to hide the disabled items

**Comment by tractorcow** [comment]
I think we can close this...
