### ISSUE TITLE
CMS users can view/select pages they don’t have permission to create

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-cms#1273]
Spotted this on 3.1.14-rc1.

If a user doesn’t have permission to create a page, it appears in the list of available page types (#1272) but is disabled. If you then choose “Under another page” then all of the page types are enabled and can be selected. This doesn’t seem to happen if a parent page is pre-selected by clicking “Add page” when already editing a page.

The user cannot add the page, the validation error occurs as expected.

Steps to reproduce:
- Create a new page type with `canCreate() { return false; }`
- Visit `admin/pages/add/`, note that your page type is there but disabled
- Click “Under another page”, the page type is now available to be selected

Screenshots:

![screen shot 2015-09-03 at 14 29 51](https://cloud.githubusercontent.com/assets/1655548/9659495/c346d85a-5248-11e5-8673-5c9254444f97.png)
![screen shot 2015-09-03 at 14 30 06](https://cloud.githubusercontent.com/assets/1655548/9659499/c65a4fb8-5248-11e5-827d-4e6e7050e569.png)

**Comment by kinglozzer** [comment]
Still an issue in 3.4, fix at https://github.com/silverstripe/silverstripe-cms/pull/1274

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-cms/pull/1274
