### ISSUE TITLE
Contextmenu broken in 3.1.14+

### ISSUE THREAD

**Issue by innomedia** [silverstripe/silverstripe-cms#1277]
Since still working in 3.1.8 the contextmenu isn't showing up in 3.1.14+ under some circumstances.
Error is: (jquery.js:634 Uncaught TypeError: Cannot read property 'length' of undefined)

Could trace it down to CMSMain.Tree.js (Line 71)
Seems like allowedchildren is empty and causes a function call without objects. Using the lines from 3.1.8 seems to fix the problem. Any Ideas?

**Comment by dhensby** [comment]
Sounds like we need an `undefined` check

**Comment by tractorcow** [comment]
Need to check if this affects 3.2 too; Otherwise we might close this.

**Comment by chillu** [comment]
Works fine for me in 3.x now
