### ISSUE TITLE
Cancel button on 'Add Page' screen doesn't work

### ISSUE THREAD

**Issue by neilcreagh** [silverstripe/silverstripe-cms#1278]
On 3.2 if you click the 'Add Page' button in the CMS (admin/pages/add/) but then don't wish to add a page there's no way out - the cancel button doesn't work but also clicking on Pages in the sidebar doesn't work. It's a minor issue but worth pointing out.

**Comment by kinglozzer** [comment]
@neilcreagh I can’t recreate this, what browser is this in? Any JS errors in the console? It should attempt to use the history API to go back, and then fall back to redirecting to `admin/pages`

**Comment by neilcreagh** [comment]
Apologies - this seems to be a Safari only issue (I'm using Version 7.1.8 on Mac OS 10.9.5). Doesn't seem to be an issue in Chrome or Firefox on same system. (so a very minor issue)

Correction to the issue - the view sticks on the 'Add Page' even if you add a page. (The page gets added but the Add page screen remains). There's no javascript errors showing in the console and a 'refresh' of that page (admin/pages/add/) seems to fix it (temporarily - the next time I try to add a page the same happens, and another refresh fixes it).

**Comment by kinglozzer** [comment]
Ah, I can recreate it in Safari 8 on OS X 10.10.5. Looks like an issue with `history.back()`

**Comment by kinglozzer** [comment]
I’ve had a quick look and I can’t figure out what’s going on... it seems to be silently failing [here](https://github.com/silverstripe/silverstripe-framework/blob/3/admin/thirdparty/history-js/scripts/uncompressed/history.js#L1586).

**Comment by tractorcow** [comment]
Wow, not sure why, but I can get it to work every second click. It seems the first one attempts to go back but does nothing.

**Comment by tractorcow** [comment]
3.1 is the same.

**Comment by dhensby** [comment]
How likely is this issue to be addressed?

**Comment by tractorcow** [comment]
If it's fixed in master, we might just close this; 4.0 uses page.js and replaces the old History.js library we are relying on.
