### ISSUE TITLE
SiteTree settings toggle fields not working (3.2)

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-cms#1280]
Some inputs shouldn’t be shown unless a certain option is selected (e.g. “Parent page” shouldn’t show unless “underneath a parent page” is selected). See screenshot:

![screen shot 2015-09-23 at 14 50 19](https://cloud.githubusercontent.com/assets/1655548/10046759/8a3783e2-6202-11e5-8ef3-b5f6e41fc424.png)

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-cms/pull/1281
