### ISSUE TITLE
JavaScript is clicking first button in form when pressing "enter" key.

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-cms#1288]
I've had a very difficult time tracking this down, I still cannot figure out why it's happening. However, if you setup a page (any page) and you press enter in any *single line text* field, even if it's not the `Title` field, it will use JavaScript to find the first instance of a `<button>` tag in the form and click on it, regardless of what it is. No matter how you try it, it works in those conditions, for example:

* Just a `Title` field and `UploadField`. Press enter and it will pop open the asset manager. If you upload a file, it will click "Edit" for you.
* If you have the `URLSegment` field present, for some reason, it mysteriously updates (or shows the loading/updating icon).

**For example:**

Before pressing enter:
![before](https://cloud.githubusercontent.com/assets/4269377/10260640/fcd56a4e-6947-11e5-8dfa-fa78651c5575.png)

After pressing enter:
![after](https://cloud.githubusercontent.com/assets/4269377/10260645/0b7af316-6948-11e5-9c0c-565a23fbdb56.png)

**Comment by dhensby** [comment]
Are you certain that this is JavaScript doing this and not just default browser behaviour? 

Have you found the javascript responsible?

**Comment by dhensby** [comment]
The urlsegment updating in title change is intended so that urls match the title, they can also be edited by hand.

**Comment by patricknelson** [comment]
That part I understand. However, again I've tested this in various scenarios that **did not include** the title field nor the `URLSegment` field. I've tested it to ensure it wasn't tied to class name. I've tested it to ensure it is not tied to the button ID. I've verified that it will indiscriminately register the "onclick" event (even dropped in via dev tools) and only for the first button on the form when enter is pressed while also ensuring that the form is not submitted (because there is JavaScript code that calls `preventDefault` already somewhere, obviously). 

No, I've not verified myself that it's not default browser functionality as I assumed it wasn't but I could give it a shot by making a really generic page and mock up the same elements. However even if it were, it's clear default functionality is being prevented. 

Are you sure that maybe there isn't some straggler code hanging out somewhere doing this unintentionally? What bothers me is how impossible it is to find behind the Montaigne of Entwine code and third party plugins. Have you tried the above scenario yourself and set it up just to have ANY random text field (avoid calling it `Title` just to prove it to yourself) and then an upload field which has an image already registered (doesn't need to be setup in the database)? You'll find that something spooky somewhere, some evil fucking demon, is clicking that damned button. That or I need to get a priest and purge my computer.

**Comment by patricknelson** [comment]
And again ,one,Mehta was my point - I looked *for hours* and failed to uncover, or "disentangle" the entwine mess that likely was hiding the culprit.

**Comment by patricknelson** [comment]
And again keep in mind that the `URLSegment' field also gets updated even when you press enter on any other field. Honestly pressing enter should submit the form on any field except when you're actually directly editing the segment itself. 

I've tested this enough to verify that if you have a totally unrelated field called `CatsAreCool` and pressed enter in it, and still had a `URLSegment` field present and also had an `UploadField`, it would nonsensically show the rotating icon next to `URLSegment` even though obviously your action has absolutely nothing to do with the URL. If for example you had deleted the `URLSegment` fiekd (either via dev tools or just from `getCMSFields()`) it would click on the edit button (or asset browser for some reason, if empty) of the `UploadField`. It doesn't make any sense and shouldn't happen, ever. 

Naturally again I think that should submit the form like it does all forms by default.

**Comment by patricknelson** [comment]
Also I think I confirmed (will need to get to a computer) that these are not `<button type"submit">` but rather just `<button type"button">`

**Comment by patricknelson** [comment]
Ok after some more testing it appears that, by default, the browser assumes all the buttons missing the `submit` type attribute are still submit buttons and will, as part of HTML5 spec, trigger a click on those buttons prior to form submission when pressing enter. It appears to be unintended functionality to me at the CMS level, still, because the buttons that are intended as form submission buttons are clearly defined with that type attribute. 

Things functioned normally and as expected when I setup all non-submit buttons with the `button` type.

**Comment by micmania1** [comment]
I think this might be  a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/3181

**Comment by patricknelson** [comment]
It looks like SS 3.2 is still just a RC, so should I submit a proposed fix against the `3.1` branch still?

**Comment by patricknelson** [comment]
Ok, this was a combined fix applied to `3.1` on CMS and framework, since the general issue affected both repositories. The bug referenced here apparently is more directly addressed in the `silverstripe-framework` repository.

* **CMS:**
  * Issue: https://github.com/silverstripe/silverstripe-cms/issues/1288 (you are here)
  * PR: https://github.com/silverstripe/silverstripe-cms/pull/1290
* **Framework:**
  * Issue: https://github.com/silverstripe/silverstripe-framework/issues/3181
  * PR: https://github.com/silverstripe/silverstripe-framework/pull/4651

**Comment by patricknelson** [comment]
Closing because this specific issue (as outlined in first comment) is actually fixed by https://github.com/silverstripe/silverstripe-framework/pull/4662 and bundled with CMS related fix in #1292.
