### ISSUE TITLE
Redirector Page Tests Fail when custom theme present

### ISSUE THREAD

**Issue by Otterpocket** [silverstripe/silverstripe-cms#1298]
tests/model/RedirectorPageTest.php

Redirector Page Test::test Empty Redirectors RedirectorPageTest::testReflexiveAndTransitiveInternalRedirectors

Tests pass when:
protected static $disable_themes = true;
Is added.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
