### ISSUE TITLE
Should AssetAdmin be part of Framework/Admin and not CMS

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-cms#1299]
`File` objects are part of core and the stripped down admin provided with framework seems like it would be able to handle having an `AssetAdmin` - as well as being a useful addition for people using just the basic admin.

**Comment by tractorcow** [comment]
I think it should be. @flashbackzoo do you concur?

**Comment by flashbackzoo** [comment]
Yeah I can see a case for it being in Framework/Admin. But maybe a stripped back version with extensions points and an `AssetAdmin` extension in CMS? It seems like a very CMS thing. But I can see why you're suggesting it moves too.

**Comment by chillu** [comment]
Given what @unclecheese is cooking up with kickassets, there will be people which don't need `AssetAdmin` at all. Maybe this is an opportunity to single it out as a separate module, with a default dependency in `silverstripe-installer`, similar to the `reports` module.

**Comment by dhensby** [comment]
@chillu whilst we are installing modules in the webdir, I'd try to avoid moving single files out into modules

**Comment by sminnee** [comment]
I'd suggest that we park this change until after we move modules into the `vendor/` dir.

I'd also want to consider whether the File & Folder classes should be pushed into the same module as `AssetAdmin`. I'm not sure that having a subsystem's data model and its admin UI in separate modules is a great idea: the pair of modules will be quite heavily coupled, which is generally considered bad architecture, and would increase the number of cross-module commits.

There's also a slippery slope argument: should we push SecurityAdmin into a module in case people build replacements of that? Ditto CMSMain...

All that said, I think pushing the following into a separate module would make a lot of sense:

 * File/Folder classes
 * AssetAdmin
 * File selection dialog in TinyMCE
 * Insert link to file option in TinyMCE
 * File URL shortcode

The rationale would be that you could swap it out for a different asset management paradigm, e.g. the DMS module that Julian Seidenberg and others developed.

Under this scheme, I'd keep DBFile as part of core, as a piece of low-level plumbing.

**Comment by micmania1** [comment]
+1 separate module.

**Comment by chillu** [comment]
This discussion has been continued as an RFC on https://github.com/silverstripe/silverstripe-framework/issues/5289, so closing it here.
