### ISSUE TITLE
Remove old page lookup by default

### ISSUE THREAD

**Issue by micmania1** [silverstripe/silverstripe-cms#1305]
A 404 in SilverStripe is extremely expensive as it looks through old/moved pages before throwing a 404.

Would anybody oppose removing the functionality by default and replacing it with documentation explaining how to add it back, alongside warnings explaining how this can affect the site? My opinion is that developers should be making these decisions consciously, rather than having this stuff in by default. 

Any important redirects should be explicitly set in any case.

This change would just remove the OldPageRedirector extension from `ModelAsController` and `ContentController` classes and would go into 4.0 as its potentially a breaking change.

**Comment by ss23** [comment]
I think this would result in significantly decreased user experience on most sites.

SilverStripe is used a lot more by smaller sites that would like this feature than by big sites. In addition, there's more chance of a big site to remove this with the resource they have than smaller sites to add it since they're more out of the box.

I'd be okay with making it easily disabled, but not off by default.

**Comment by micmania1** [comment]
I think its a good feature for small sites, but bad for big as you said. I think the problem exists exactly the same for smaller sites, but they're not monitored so nobody notices when they go down. 

That's why i'm for conscious decision over *not* reading the docs.

**Comment by jonom** [comment]
@micmania1 do you have any figures on what kind of a performance hit we're talking about? I had the impression that the old page lookup query is fairly simple so shouldn't be too bad. [Rendering the 404 page is definitely expensive](https://github.com/silverstripe/silverstripe-framework/issues/4149) (the same as any other page) as it's fully dynamic, but are you sure the old page lookup part is costly?

**Comment by jacobbuck** [comment]
Would be nice if it was configurable so we have the choice :smile:

**Comment by jonom** [comment]
This needs testing to see if it's actually a performance issue. I suspect it's not, but probably wouldn't hurt to make it configurable since not everyone may want this feature, performance issue or no.

**Comment by jacobbuck** [comment]
I don't care about this from a performance issue, but a behaviour issue. We just want to switch it off because we're having issues with it unexpectedly redirecting to other pages with the same URLSegment but different Parent, and we manually manage redirects anyway.

**Comment by ss23** [comment]
@jacobbuck You can see https://github.com/silverstripe/silverstripe-cms/blob/f7985b34f23b8f8723f5b3a816e836d92be97c68/code/controllers/ModelAsController.php#L10 it's implemented as an extension. 

Without having tested it, you should be able to remove it in your codebase already

**Comment by jonom** [comment]
`ModelAsController::remove_extension('OldPageRedirector')` in your _config.php might work?

**Comment by jonom** [comment]
Can't remove it with just yml unfortunately AFAIK.

**Comment by jacobbuck** [comment]
Yep, adding this to our _config.php worked:

```
ContentController::remove_extension('OldPageRedirector');
ModelAsController::remove_extension('OldPageRedirector');
```

**Comment by tractorcow** [comment]
I think this just raises the necessity of yml-only option for removing extensions.

I'm in favour of named extensions, personally.


```yaml
MyObject:
  extensions:
    versioned: Versioned
```

Then to disable

```yaml
MyObject:
  extensions:
    versioned: null
```

**Comment by jacobbuck** [comment]
Something like this would be nice to configure, rather than removing an added extension. i.e:

```
SiteTree:
   redirect_old_pages: false
```

Also how about:

```
MyObject:
  remove_extensions:
    - Versioned
```

**Comment by ss23** [comment]
May be worth starting a separate issue for "How to best remove extensions in yaml". Whether it's enabled by default seems to be the core of this particular issue.

**Comment by tractorcow** [comment]
I guess the initial question has been answered, that it's easy enough to remove in your project (albeit via PHP not yml), so I'll close this. :)
