### ISSUE TITLE
"Insert Link" > "Download a File" Bug on Adding 2nd Link in 3.2

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-cms#1307]
Thanks to @kinglozzer, in 3.2 CMS users can upload a file directly from the "Insert Link" > "Download a File" modal box.

However, I've identified a bug that didn't occur in the [separate 3.1 extension module](https://github.com/kinglozzer/htmleditoruploadfield) for this feature:

**To reproduce:**
1. Click *Insert Link* > *Download a File*
2. *Upload* a file via the UploadField
3. Click the *Insert Link* button
4. Select a different piece of text within the content field, and repeat steps 1 & 2 as if you wanted to add a 2nd link to a diffferent file.

**What happens:**
The UploadField is prepopulated with the file from the first link.

**What I expect to happen:**
The UploadField to be empty, ready for uploading a different file for the 2nd link.

**Workaround:**
Clicking **Remove** and then continuing as usual works fine, but it can be very confusing for users. Equally, refreshing the CMS before adding the 2nd link empties the UploadField too.

**Comment by purplespider** [comment]
Still occurs in 3.2.1

**Comment by dhensby** [comment]
Looks like we need a behat test for this and to re-render the form on new clicks

**Comment by purplespider** [comment]
Would be good to get this fixed for 3.3 :)

**Comment by dhensby** [comment]
ping @kinglozzer is this anything you could look at?

**Comment by kinglozzer** [comment]
A nice easy one to fix :) https://github.com/silverstripe/silverstripe-framework/pull/4908
