### ISSUE TITLE
BUG ContentController::getViewer gets incorrect set of templates in custom controllers

### ISSUE THREAD

**Issue by camfindlay** [silverstripe/silverstripe-cms#1310]
ContentController::getViewer when called from an index action of a custom controller extending Page_Controller gets the wrong templates.
 
In 3.1 this list of templates:

```
Array
(
   [0] => GoogleCseController
   [1] => Page
   [2] => ContentController
   [3] => Controller
)
```

becomes “this” list in 3.2 with no changes to the custom controller code in the project:
```
Array
(
   [0] => Page
   [1] => GoogleCseController
   [2] => Page
   [3] => Controller
   [4] => Page
   [5] => GoogleCseController
   [6] => Page
   [7] => Controller
)
```

**Comment by tractorcow** [comment]
Confirmed regression in 3.2.

**Comment by tractorcow** [comment]
As an additional note, this occurs when a ContentController subclass is routed directly (via routes yml) without an actual page dataobject.

**Comment by dhensby** [comment]
Not fixed yet?

**Comment by tractorcow** [comment]
I think we should just stop letting people use ContentController without a page. It's like saying my sailboat-without-sails goes too slow.

**Comment by dhensby** [comment]
Hmm - I thought I'd had this problem before and it'd been patched - but clearly not...

**Comment by dhensby** [comment]
I agree with @tractorcow, though - you shouldn't be extending `page_controller` in this way

**Comment by sminnee** [comment]
Based on the above, closing as wontfix
