### ISSUE TITLE
SiteTreeURLSegmentField not properly using ->getURLSuffix()

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-cms#1312]
I noticed that the CMS will link to a page on the front-end when editing it in the CMS by proxy if taking whatever is currently set in the URL Segment and then providing a prefix/suffix, which must be retained separately. However, the following method seems to hard-code the `data-suffix` attribute and doesn't use the `->getURLSuffix()` method, unlike it's partner attribute `data-prefix` which is using its own respective getter (which I can control):

``` php
    public function getAttributes() {
        return array_merge(
            parent::getAttributes(),
            array(
                'data-prefix' => $this->getURLPrefix(),
                'data-suffix' => '?stage=Stage' // Should be $this->getURLSuffix() instead?
            )
        );
    }
```

Should this be changed? If so, should the `$urlSuffix` protected property go ahead and be initialized to `'?stage=Stage'`? It doesn't seem to have any adverse effects on the front-end, since the suffix doesn't get displayed (even though it appears in the link text in the template due to `->getURL()` method on the object) but is still properly maintained via JavaScript.

**Comment by dhensby** [comment]
Does this still need a fox?

**Comment by dhensby** [comment]
Or a fix

**Comment by patricknelson** [comment]
I assume it does, since I'm still seeing the aforementioned code here: https://github.com/silverstripe/silverstripe-cms/blob/3/code/forms/SiteTreeURLSegmentField.php#L33

My question above still stands, however. That is: Should this be changed per above?

**Comment by dhensby** [comment]
Yes, your fix looks good

**Comment by patricknelson** [comment]
Ok cool, I'll queue this up for a PR soon. What branch?

**Comment by patricknelson** [comment]
I suppose `3.3` since this looks more like a bug

**Comment by patricknelson** [comment]
Also I think this would cause a bug if you didn't want to be in draft mode, it could refresh the right pane if you edit the field and it redraws by showing the stage version instead of maintaining state properly. I'll go ahead and throw out a quick pull request for this.

**Comment by torleif** [comment]
This becomes an issue when using Subsites. When you try to navigate to subsite.com/page?stage=Stage, it tries to authenticate you which won't work if you're using SAML/some other authentication method.

**Comment by patricknelson** [comment]
Hi @torleif that may be more of an issue with the [subsites module](https://github.com/silverstripe/silverstripe-subsites) itself. I say that because the issue is the proper maintenance of the current state (i.e. Is my current preview state draft or published mode?) and not necessarily the fact that now attempting to view draft content causes a login error. I think that's due to lacking shared cookies across domains, needed to share session information. 

While on one hand, a quick fix for you would be to always link to the published (or "Live" stage) I think here we are more worried about just making sure that your current mode is the one being linked to if you click. 

If you're still interested though (since it's only tangentially related), see here where we dive into the rabbit hole of how to link to the correct page depending on if you're editing a draft or not and the URL has changed (just one implication of this). https://github.com/silverstripe/silverstripe-cms/pull/1449

**Comment by patricknelson** [comment]
Also @torleif your avatar looks amusingly like an upside down :expressionless: :-|

**Comment by torleif** [comment]
@patricknelson yes my quick hack was to override SiteTreeURLSegmentField that checked the subsite type, and then renamed the ?stage=Stage prefix.

it's an ugly hack, but it means that CMS authors can use the url link while editing subsites.

**Comment by maxime-rainville** [comment]
Just did an SS4 fix for a duplicate issue https://github.com/silverstripe/silverstripe-cms/issues/1364
