### ISSUE TITLE
Virtual Page Permissions

### ISSUE THREAD

**Issue by nglasl** [silverstripe/silverstripe-cms#1318]
I have recently encountered an issue regarding virtual page permissions (which I consider to be unexpected behaviour), and have confirmed this is still present in **3.2**..

So basically, when you set the **can view** (and most likely the **can edit**) for a virtual page, hitting **save and publish** only writes the permissions for the draft version. I might want to set my virtual page to only be viewable by administrators (maybe from a restricted multisite instance), and although it seems as though this is the case from the CMS, the page will not actually be restricted (the permissions will be determined based on the original page). Perhaps the virtual page is pointing to a page that already has some permissions? The same problem.

I would have expected permissions to be determined at an individual page level, regardless of content, however it does not help that the interface isn't correctly reflecting what has been published. I have found that the following resolved my issues, and I would consider these changes to be fundamental..

```yaml
VirtualPage:
  non_virtual_fields:
    - 'CanViewType'
    - 'CanEditType'
```

**Comment by tractorcow** [comment]
I agree with you that this is an issue; Although the fix would probably result in a change in behaviour.

The earliest I could expect this fixed is probably in 3.3.

In the mean time the work around you suggested would work fine (by setting in a custom yml file), so hopefully it's not urgent. ;)

**Comment by nglasl** [comment]
Thanks for the quick response and clarification :)

**Comment by tractorcow** [comment]
Fixed in https://github.com/silverstripe/silverstripe-cms/pull/1373.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-cms/pull/1377#event-527251563
