### ISSUE TITLE
RedirectorPage internal/external link toggle doesn’t work

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-cms#1328]
It currently just shows both options, the toggles do nothing:

![screen shot 2015-11-16 at 09 48 14](https://cloud.githubusercontent.com/assets/1655548/11178826/2e8df200-8c47-11e5-8028-cb7e7648a0b8.png)

**Comment by dhensby** [comment]
SS version?

**Comment by kinglozzer** [comment]
@dhensby Sorry, 3.2.1

**Comment by dhensby** [comment]
Did it get introduced in 3.2.1?

**Comment by kinglozzer** [comment]
No, it’s present in 3.2.0 too. Probably caused by the IDs of form elements changing between 3.1 and 3.2 (same as #1280)

**Comment by sminnee** [comment]
Did it ever work? ;-)

I assume the function itself actually works; we're just looking for a JS cleanup?
