### ISSUE TITLE
Error processing too aggressive since 3.1

### ISSUE THREAD

**Issue by dkolodziejczyk** [silverstripe/silverstripe-cms#1332]
The Page Not Found error processing is too aggressive.
We've migrated our sites to SilverStripe and as part of that many of the original URLs changed. We've implemented functionality to re-direct those original URLs to the new locations by extending ErrorPage. This system worked on SS 3.0, but SS error processing changed in 3.1.
<code>
class PageNotFoundErrorPage extends ErrorPage {

	static $hide_ancestor = 'ErrorPage';
	static $icon = 'mysite/images/icons/error';

}

class PageNotFoundErrorPage_Controller extends ErrorPage_Controller {

	function init() {
		parent::init();

		// Remove existing redirection so we can redirect again
		$this->getResponse()->removeHeader('Location');

		// some code to determine the new URL

		/**
		 * If default error processing proceeds past this point an undesirable state in the headers
		 * with a new location, but a 404 status code rather than 301 is sent to the browser.
		**/
		$this->redirect($newURL, 301); // inherited all the way from class Controller();
	}
}
</code>

I was able to work around this for the time being by adding this function override to our PageNotFoundErrorPage_Controller class

<code>

	/** 
	 * This overrides Controller::redirect
	 * SS 3.1 changed error handling and forced the status code to 404 if processing was allowed to continue
	 * past this point. This made an undesireable inconsistent state in the headers with a new location, but a 404
	 * rather than a 301. Set the headers and die is the alternative.
	**/
	public function redirect($url, $code = 302){
		$response = new SS_HTTPResponse($code);
		$description = $response->getStatusDescription();
		header($_SERVER['SERVER_PROTOCOL'] . " $code $description");
		header("Location: $url", true, $code);
		die();
	}

</code>

**Comment by dkolodziejczyk** [comment]
Thanks Damian,

The OldPageRedirector class is interesting. I've been wondering how SilverStripe does the old page redirection and now I can figure it out from the code. I'll take a look and see if there's anything in there that I can use. For now I have a solution that's working even if it's not ideal.

Dana

**Comment by dkolodziejczyk** [comment]
By the way, the old system URLs is only one of the uses for this redirection. We also have a UrlRedirect DataObject that Editors can use to set up redirects when they find Articles that are have very similar content by supplying an old URL and a target URL. Additionally we have a field on our Pages for vanity URLs where an editor can enter a vanity URL for a specific page. Just some ideas that others might find useful.

Dana

**Comment by dhensby** [comment]
I don't think intercepting the 404 error is the best way to perform redirects. 

If the redirects are permanent and don't need to be managed its best to do this in the `.htaccess` file as a good old 301 redirection map. 

If they need to be managed, I'd encourage you to look into modules that do this or hooking in to some other part of the request process. 

Being objective, I'm not sure the error processing is too aggressive, there's just a change in behaviour between 3.0 and 3.1 that breaks your current implementation. 

Unless you can suggest why what is happening is bad for users and provide a patch, then I think this issue can be closed.

**Comment by tractorcow** [comment]
> We've implemented functionality to re-direct those original URLs to the new locations by extending ErrorPage. 

Yeah, as @dhensby has said, that's not the intended purpose of this page. You need to implement your fixed redirects via htaccess, or a custom OldPageRedirector extension.

You'll need to put your model logic into `public function onBeforeHTTPError404($request) {}`, as OldPageRedirector does.
