### ISSUE TITLE
Changing Page class prevented if SiteConfig.CanCreateTopLevel permission is missing 

### ISSUE THREAD

**Issue by sb-relaxt-at** [silverstripe/silverstripe-cms#1334]
If a user does not have the permission to create pages at the top level, he cannot change the class of an existing page. This is due to SiteTree#getClassDropdown using canCreate to determine which page types should be shown in the Settings-Tab. As canCreate is called without parameters, it falls back to checking whether or not the user is allowed to create the page on the top level. I suggest to [add a context parameter](https://github.com/silverstripe/silverstripe-cms/blob/3/code/model/SiteTree.php#L2679): 

    !$instance->canCreate(null, array('Parent' => $this)

As this seems to work, and I do not believe that there is any side effect, I will try to provide a pull request asap.

**Comment by tractorcow** [comment]
Should it be canCreate() || canEdit() ?

**Comment by sb-relaxt-at** [comment]
Normally creating a Page seems to be only limited by canCreate. It is possible for a user to create a Page, although it cannot edit this Page after creating. Therefore it would be only consistent to just check canCreate.

**Comment by tractorcow** [comment]
See https://github.com/silverstripe/silverstripe-cms/issues/1333#issuecomment-160462954 to link these two discussions. :)

**Comment by tractorcow** [comment]
Ok, I think these two issues are similar but still separate.

I would suggest setting the context parameter to the parent of the current object, rather than the object itself.

```php
!$instance->canCreate(null, array('Parent' => $this->Parent())
```

**Comment by sb-relaxt-at** [comment]
Yes of course, my mistake.
