### ISSUE TITLE
How to sort children pages in theme

### ISSUE THREAD

**Issue by pramod1988** [silverstripe/silverstripe-cms#1338]
I want to sort page children by their sorting order
I tried adding  
static $default_sort = 'Sort';
in mysite/_config.php 
But it is not working, it is sorting by children id. I want to sort it by their sorting order.

**Comment by jonom** [comment]
Hi @pramod1988, issues on this project are reserved for reporting bugs. I'd suggest working your way through the Lessons and then asking for support through one of the recommended channels at http://www.silverstripe.org/learn/
