### ISSUE TITLE
Blocked preview mode with multisite domain

### ISSUE THREAD

**Issue by ingermarie** [silverstripe/silverstripe-cms#1343]
When editing multisite content in CMS with preview mode open for alternate domain page:

``` javascript
Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://domain1.dev" from accessing a frame with origin "http://domain2.dev". Protocols, domains, and ports must match.
```

The issue is obvious, but it keeps users from editing content without reloading the page.

**Comment by dhensby** [comment]
I think this may be fixed with https://github.com/silverstripe/silverstripe-framework/pull/5163 ?

**Comment by dhensby** [comment]
whoops!

**Comment by tractorcow** [comment]
Same as https://github.com/silverstripe-australia/silverstripe-multisites/issues/44

**Comment by tractorcow** [comment]
@ingermarie have you tried setting https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options or https://en.wikipedia.org/wiki/Cross-origin_resource_sharing?

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
