### ISSUE TITLE
CMSBatchAction::getParameterFields() never seems to get called/used

### ISSUE THREAD

**Issue by micschk** [silverstripe/silverstripe-cms#1350]
`CMSMain::BatchActionParameters()` calls `getParameterFields()` for each batch action. This is supposed to add additional parameter fields to the batch actions in CMS, but it seems `CMSMain::BatchActionParameters()` never gets called and thus no parameter dropdown gets added.

### PRs
- [x] ~~https://github.com/silverstripe/silverstripe-cms/pull/2590~~
- [x] ~~https://github.com/silverstripe/silverstripe-admin/pull/1124~~
- [ ] https://github.com/silverstripe/silverstripe-cms/pull/2629
- [ ] https://github.com/silverstripe/silverstripe-cms/pull/2628
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/1167
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/1168

**Comment by tractorcow** [comment]
I guess we should remove it in 4.x? do you agree?

**Comment by GuySartorelli** [comment]
Batch actions parameters are now used per https://github.com/silverstripe/silverstripe-cms/pull/2746
