### ISSUE TITLE
/admin/pages breadcrumb displays home page information

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-cms#1351]
When no page is selected (i.e. you're at /admin/pages/) a breadcrumb for the home page is displayed indicating it is selected when it is not. It should just say 'Pages'.

![silverstripe_-_pages](https://cloud.githubusercontent.com/assets/1079425/11984601/6e406864-a971-11e5-93fb-f721bf09e118.png)

**Comment by tractorcow** [comment]
I think this is the same in 3.2 :) I agree it's wrong though.

**Comment by jonom** [comment]
What the... how did I close this?

**Comment by jonom** [comment]
You're right @tractorcow don't know why I didn't notice it in 3.2 :)

I added a milestone to this but feel free to remove if I shouldn't have done that.

**Comment by tractorcow** [comment]
I'm still trying to figure out why I keep adding "in progress" to new issues.

**Comment by jonom** [comment]
Here's a better description from https://github.com/silverstripe/silverstripe-cms/issues/1356

----

This seems to have always been the case, but has become more obvious in 3.3.

When on the root Pages tab, the title of the homepage is displayed at the top:
![](http://spdr.me/1hv8n+)

I see no reason for this, as nothing being displayed relates to the homepage.

I'd expect it to just say "Pages", like it does above the site tree when in editing mode:
![](http://spdr.me/7zbN+)

**Comment by tractorcow** [comment]
@scott1702 @flashbackzoo want to look at this?

**Comment by scott1702** [comment]
Traced this back to a php problem with how breadcrumbs are generated in LeftAndMain.php on line 744

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-cms/pull/1369

**Comment by kinglozzer** [comment]
Closed via dbb8b5852fae0366ddbaa071ab845df88d7c0bdd
