### ISSUE TITLE
3.3: New Batch Actions - Confusing Usage Flow

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-cms#1357]
Upon clicking on the new Batch Actions button in 3.3, the actions dropdown appears but defaults to the "Restore" action. This is confusing, as in most cases it results in all pages becoming grayed out and un-checkable:
![](http://spdr.me/4EMq+)

So you first need to select your desired action, then select your pages, then go back up and click the Go button.

If the purpose is to make the users choose their action before selecting the pages to apply it on, then perhaps it's best to bring back an empty state to the dropdown, such as "Select action"?

**Comment by tractorcow** [comment]
I think adding a default "choose action" option is probably the best bet. I don't think it's fair to choose one by default, right?

**Comment by tractorcow** [comment]
I'll add the 3.3.0-rc1 milestone, since this is the version this UX is introduced in.

**Comment by purplespider** [comment]
Yep, a "Choose action:" option, which doesn't disable the checkboxes sounds like the best option to me. Makes it clear to users what they need to do, and allows them to either choose the action first, or select their pages first.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4969
