### ISSUE TITLE
3.3: Page breadcrumbs inconsistently display "Pages" crumb

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-cms#1358]
Click on a page in the sitetree in 3.3 it will display the title at the top (plus breadcrumbs if a child page):
![](http://spdr.me/P64w+)

However, if you perform an action such as click **Save & Publish**, a "Pages" breadcrumb appears from nowhere:
![](http://spdr.me/Uoye+)

**Comment by tractorcow** [comment]
Looks like a minor bug in the UX revamp. pinging @flashbackzoo  / @scott1702

**Comment by jonom** [comment]
Related: https://github.com/silverstripe/silverstripe-cms/issues/1351

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-cms/pull/1369

**Comment by kinglozzer** [comment]
Closed via dbb8b5852fae0366ddbaa071ab845df88d7c0bdd
