### ISSUE TITLE
Pasting a full URL in "anchor" causes an internal server error

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-cms#1359]
A client of ours pasted a full URL into the “anchor” field mistakenly, and then tried to save the page. This causes a server error in `SiteTreeLinkTracking::process()` as it tries to parse out the anchor and use it as part of a regular expression. This then left the user unable to do anything with the page in question due to server errors. The link looked like `href="[sitetree_link,id=2]#http://www.mysite.com/page-2/"` (where `page-2` is the URL segment of page ID 2), and the error message was `preg_match(): Unknown modifier 'w'`.

Not sure whether this should be fixed in JavaScript, but either way we should probably code more defensively in `SiteTreeLinkTracking` just in case.

**Comment by tractorcow** [comment]
Oh dear!

Your fix looks good; Can you add a unit test and PR it please?

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-cms/pull/1360
