### ISSUE TITLE
Settings > Page location field broken

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-cms#1362]
The styling of this field appears to be broken in 3.3, as well as the toggle visibility behaviour.

![screen shot 2016-01-11 at 9 31 07 am](https://cloud.githubusercontent.com/assets/1079425/12241179/7cc813e4-b846-11e5-9768-f774e6189a6f.png)

Works fine in 3.2

**Comment by tractorcow** [comment]
Calling all UX devs! @scott1702

**Comment by scott1702** [comment]
I can't seem to reproduce in Chrome on OSX, what browser are you using?

**Comment by jonom** [comment]
I'm using Chrome on OS X too :D so... that's weird.

**Comment by scott1702** [comment]
Just did a fresh install of 3.3.0-beta1 and still can't reproduce :confused:. You wouldn't happen to have any additional modules installed which could affect that?

**Comment by jonom** [comment]
I tried a fresh install too after seeing it on two separate projects but maybe I've got something weird going on locally. I'll try to investigate further soon.

**Comment by tractorcow** [comment]
Looks ok to me too

![image](https://cloud.githubusercontent.com/assets/936064/12282639/6389a7a2-ba04-11e5-854e-49c65eb432dc.png)

**Comment by jonom** [comment]
I must have something weird going on at my end, sorry for the hassle. I'll check this out some more when I get a chance and re-open if an authentic issue.

**Comment by dhensby** [comment]
@jonom check browser extensions?

**Comment by tractorcow** [comment]
Oh, I bet it's adblock. I've had it sometimes do weird things in the CMS.

**Comment by dhensby** [comment]
@jonom always try in private browsing mode (assuming you don't allow extensions to run in PB)

**Comment by scott1702** [comment]
So I just came across this bug... https://github.com/silverstripe/silverstripe-framework/pull/4982 seems to be the fix

**Comment by jonom** [comment]
Thanks for continuing to look in to this guys! I'm on vacation for another week but will look in to this more when I get back if required. I think I tested this on a few different browsers before filing (including Safari with no extensions) so it might just be one of those intermittent ones... Do you know how you triggered this bug in the end @scott1702? I know you couldn't reproduce it initially.

**Comment by dhensby** [comment]
@scott1702 that fix isn't being accepted at the moment as its not actually the root problem, it just mitigates it. 

If this is a CSS issue then we will need to get on with fixing that problem, but I don't think that's the issue

**Comment by scott1702** [comment]
@jonom I couldn't reproduce on 3.3 but it just happened to appear on master.

@dhensby Yeah I don't think that's the issue either.

**Comment by dhensby** [comment]
Confirming this looks fine for me too on 3.3.x-dev

![](https://dl.dropboxusercontent.com/u/3429338/Clippings/2016-01/2016-01-27_14-15-52-uwd9K140nS.png)

What doesn't look good is the logout on the RHS cc @scott1702

**Comment by scott1702** [comment]
Hmmm not sure why that's still appearing, the old icon was removed at https://github.com/silverstripe/silverstripe-framework/commit/fe2be0c2620ab9d94d09aca32388efaf4b13eca9#diff-fbdf06a201820e03fbf15abd8d3d6bdaL79. Maybe it needed a flush?

**Comment by tractorcow** [comment]
@scott1702 can you please investigate and fix this? We'll need a new RC2 if that's an issue.

**Comment by dhensby** [comment]
Even when I flush I have the problem @scott1702:

![](https://dl.dropboxusercontent.com/u/3429338/Clippings/2016-02/2016-02-01_16-02-34-RhxO5UoDx3.png)

**Comment by dhensby** [comment]
@scott1702 - found it, it hasn't been removed from _retina.scss:89

**Comment by scott1702** [comment]
Oh right, sorry I couldn't get around to this earlier. I'll PR

**Comment by tractorcow** [comment]
Fixed at https://github.com/silverstripe/silverstripe-framework/pull/5006

**Comment by dhensby** [comment]
I love how this issue seems to have moved from one completely unrelated issue to fixing the logout icon on retina screens

**Comment by tractorcow** [comment]
Yeah who did that @dhensby ?
