### ISSUE TITLE
urlSuffix in SiteTreeURLSegmentField is ignored

### ISSUE THREAD

**Issue by nathanbrauer** [silverstripe/silverstripe-cms#1364]
The offending line:

https://github.com/silverstripe/silverstripe-cms/blob/41d4aa38a368be3ee15538b25b89fcc4c04d995c/code/forms/SiteTreeURLSegmentField.php#L33

Replace with:

``` php
                'data-suffix' => $this->getURLSuffix(),
```

In `code/model/SiteTree.php`, replace:

``` php
        $urlsegment->setURLPrefix($baseLink);
```

...with:

``` php
        $urlsegment->setURLPrefix($baseLink)->setURLSuffix("?stage=Stage");
```

# Pull requests
* [x]  https://github.com/silverstripe/silverstripe-cms/pull/2574

**Comment by nathanbrauer** [comment]
related to @chillu's commit:
https://github.com/silverstripe/silverstripe-cms/commit/00097a5d5d34a4e1277b2c0f1821a2302d70a04a

**Comment by tractorcow** [comment]
Do you want to PR a fix for this please?

**Comment by nathanbrauer** [comment]
Normally I would be happy to, but I'm locked down right now.  Nicole knows a bit of what I'm talking about.  I wouldn't be able to until Feb.

**Comment by nathanbrauer** [comment]
Maybe someone on @nyeholt's team can

**Comment by maxime-rainville** [comment]
Did a PR for SS4 https://github.com/silverstripe/silverstripe-cms/pull/2574.
