### ISSUE TITLE
WYSIWYG Uploaded Image Loses Track of Original if Renamed

### ISSUE THREAD

**Issue by jyrkij** [silverstripe/silverstripe-cms#1365]
Uploading an image via WYSIWYG causes the image to be saved in `assets/Uploads` with the name it originally had. The user then changes the name and/or path via `admin/assets`. This causes the 'connection' to be lost. There isn't any real relation to the file, the file name is the only 'connection'.
#999 is somewhat related to this. But this should be considered a separate issue because #999 doesn't handle the renaming / moving files case.

This issue causes broken files in reports in turn. These reports bought me to this at first as our client was puzzled with hundreds of broken file reports.
## Steps to reproduce

I tested this only with 3.1 but I believe the same issue exists in 3.2 unless something has been done to address this.
1. Start with a fresh installation.
2. Upload an image via WYSIWYG, place it in Content and Save (and Publish).
3. Go to Assets admin and rename the file.
4. Run broken files report.
5. There is a page with broken file now.
## Possible fixes

I see two possible fixes for this:
1. Tracking the File `ID` somehow in the inserted `img` tags. File rename/move would then check for all `Text` fields for the current file `ID`.
2. Every file rename/move should check for the previous path in all `Text` fields.

Number 2 would probably be easier to implement as there'd be no need to add information to img tags. IMHO both of these are quite heavy operations so better ideas would be welcome.

Also a way to fix existing broken files would be nice but I believe that cannot be done as there's no information left...

/cc @FinBoWa

**Comment by tractorcow** [comment]
We are going to use shortcodes for images in 4.0, so that should solve this issue right?

**Comment by chillu** [comment]
We're using shortcodes now, yay!
