### ISSUE TITLE
Not closed _config.php breaks admin panel

### ISSUE THREAD

**Issue by dariuszp** [silverstripe/silverstripe-cms#1366]
Hi,
my admin panel broke. Any request I tried to do, changed url but didn't change panel content. So I was forced to refresh pages using F5.
Console didn't throw errors, everything was looking fine. For a moment I was thinking that 3.2 is broken but fresh installation gave me working panel.

So after many tries I figure out that if you create _config.php file with content like this:

```
<?php

``` 

instead like this:

```
<?php

?>
```

it will break your admin. I never close php file using **?>** because you end up with risk that some white characters will be printed in output when you don't want that. It can be very dangerous if you force file download via php script.

Silverstripe 3.2 is affected. I was using Google Chrome at that time. To recreate this problem, create new module inside your silverstripe project and in that module, create **_config.php** with **<?php** but without **?>**

**Comment by dhensby** [comment]
You need to have an empty line in your file, not the explicit close.

I'm not sure exactly why this is but it's a "known issue"

**Comment by kinglozzer** [comment]
See https://github.com/silverstripe/silverstripe-cms/issues/1344#issuecomment-163159786 :)
