### ISSUE TITLE
Email link with Subject or Body cannot be edited

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-cms#1374]
A (relatively) recent update made it possible to add a subject and body to a `mailto:` link. That's nice, but only "writing" was implemented: the dialog can not "read" a `mailto:` link that has a subject and/or body, resulting in errors because "the email address is not valid" (since it has `?subject=` etc in it). This is of course frustrating for people that don't want to edit HTML code. 

The dialog should recognize those parameters, cut them off, and place them in those new Subject and Body form fields.

**Comment by tractorcow** [comment]
We're going to upgrade tinymce in 4.0, so it'll probably need to be addressed there.

**Comment by JorisDebonnet** [comment]
I assume it will work completely differently in 4.0 then. But right now it is inconsistent for 3.x, and will remain so for users that don't upgrade to 4.0. 

So I really believe it needs to be fixed, as far back as whenever the feature was added (perhaps 3.1?). I'll try to figure out when it was introduced.

**Comment by JorisDebonnet** [comment]
Well, I was mistaken about the Body parameter, that has never been included. But **3.2.0** introduced the feature where you can specify a subject for an Email link, so 3.2.x (and anything after it) should certainly fix the issue where you cannot edit a link that is created that way.

**Comment by JorisDebonnet** [comment]
Aaand here we go, this is the commit that introduced it: 
https://github.com/silverstripe/silverstripe-framework/commit/6ad8f7c3dd1d4b18d9982ac33e709dac6436a664

(so it's in framework, not cms; I always get confused about the distinction :) )

**Comment by tractorcow** [comment]
So it looks like it was added in 3.2; Worth fixing there then I guess, and we can merge up?

**Comment by JorisDebonnet** [comment]
[Done](https://github.com/silverstripe/silverstripe-framework/pull/4981).

**Comment by tractorcow** [comment]
I'll close this when we merge the other PR. :)

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/issues/4981

**Comment by kinglozzer** [comment]
Oops, my bad, nice job fixing this up @JorisDebonnet!
