### ISSUE TITLE
Can't save empty text field in Silverstripe admin

### ISSUE THREAD

**Issue by teeli** [silverstripe/silverstripe-cms#1380]
After some text has been filled and saved to a textfield or html editor field in Silverstripe admin, it's no longer possible to remove the text. If you remove all text from a field and save, it will not clear the earlier text value. Happens on custom fields and built-in fields.

Is this a bug, or is there some way to enable saving empty values?

Silverstripe 3.2.1.

**Comment by tractorcow** [comment]
Are you using fluent by any chance? Which fields are you trying to clear?

**Comment by tractorcow** [comment]
In a vanilla 3.2 install I can enter and clear the MetaDescription field, at least.

**Comment by teeli** [comment]
Yes, I'm using Fluent. Clearing any field doesn't work (Title, Content, MetaDescription, Custom fields I've added myself, nothing works). Removing Fluent seems to solve it, so that is indeed causing it. 

So not an issue with Silverstripe itself, now I'll have to figure it out with Fluent.

Thanks.
