### ISSUE TITLE
BUG Batch actions not allowed on new pages

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-cms#1387]
It looks like new pages recently added to the left hand tree view won't get a batch checkbox until the page is hard-refreshed, or you navigate to edit another page.

![image](https://cloud.githubusercontent.com/assets/936064/12798005/f22eed5e-cb2b-11e5-87fe-a0db26eb77cd.png)

It could be that partial loading of the tree is missing a necessary style, or that the tree JS api isn't detecting new nodes as allowing batch actions.

**Comment by scott1702** [comment]
Related https://github.com/silverstripe/silverstripe-framework/issues/3524

**Comment by tractorcow** [comment]
ok, this is a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/3524 then. I'll close.
