### ISSUE TITLE
Has_one relationships on Page seem to be broken since 3.1

### ISSUE THREAD

**Issue by anselmdk** [silverstripe/silverstripe-cms#1398]
Having a `has_one` relationship to an image in `Page`, when creating a page on `3.3`, filling in data, and subsequently saving it, I'm getting an error the first time the page is being saved. 

I've created the following behat scenario and tested this in both `3.3`, `3.2` and `3.1.`. It's broken in both `3.3` and `3.2`:

```
Feature: Create a page
  As an author
  I want to create a page in the CMS
  So that I can grow my website

  @active
  Scenario: I can create a page from the pages section
    Given I am logged in with "ADMIN" permissions
    And I go to "/admin/pages"
    And I should see a "Add new" button in CMS Content Toolbar
    When I press the "Add new" button
    And I select the "Page" radio button
    And I press the "Create" button
    Then I should see an edit page form

    When I fill in "Title" with "About Us!"
    And I fill in the "Content" HTML field with "my new content"
    And I press the "Save draft" button
    #And I put a breakpoint
    Then I should see "Saved" in the "button#Form_EditForm_action_save" element
```

My page contains the following:

```php
class Page extends SiteTree
{
    private static $db = [];

    private static $has_one = [
        'TitleImage' => 'Image',
        'PrimaryImage' => 'Image'
    ];
}
```

I'm getting the following error:

```
INSERT INTO "Page_versions"
 ("TitleImageID", "PrimaryImageID", "RecordID", "Version")
 VALUES
 (?, ?, ?, ?)

Duplicate entry '1-2' for key 'RecordID_Version'
IN POST /admin/pages/edit/EditForm
Line 55 in framework/model/connect/DBConnector.php

Source
======
  46:  		if (!empty($sql)) {
  47:  			$formatter = new SQLFormatter();
  48:  			$formattedSQL = $formatter->formatPlain($sql);
  49:  			$msg = "Couldn't run query:\n\n{$formattedSQL}\n\n{$msg}";
  50:  		}
  51:  
  52:  		if($errorLevel === E_USER_ERROR) {
  53:  			// Treating errors as exceptions better allows for responding to errors
  54:  			// in code, such as credential checking during installation
* 55:  			throw new SS_DatabaseException($msg, 0, null, $sql, $parameters);
  56:  		} else {
  57:  			user_error($msg, $errorLevel);
  58:  		}
  59:  	}
  60:  	
  61:  	/**

Trace
=====
DBConnector->databaseError(Duplicate entry '1-2' for key 'RecordID_Version',256,INSERT INTO "Page_versions"
 ("TitleImageID", "PrimaryImageID", "RecordID", "Version")
 VALUES
 (?, ?, ?, ?),Array)
MySQLiConnector.php:238

MySQLiConnector->preparedQuery(INSERT INTO "Page_versions"
 ("TitleImageID", "PrimaryImageID", "RecordID", "Version")
 VALUES
 (?, ?, ?, ?),Array,256)
Database.php:134

SS_Database->{closure}(INSERT INTO "Page_versions"
 ("TitleImageID", "PrimaryImageID", "RecordID", "Version")
 VALUES
 (?, ?, ?, ?))
Database.php:178

SS_Database->benchmarkQuery(INSERT INTO "Page_versions"
 ("TitleImageID", "PrimaryImageID", "RecordID", "Version")
 VALUES
 (?, ?, ?, ?),Closure)
Database.php:136

SS_Database->preparedQuery(INSERT INTO "Page_versions"
 ("TitleImageID", "PrimaryImageID", "RecordID", "Version")
 VALUES
 (?, ?, ?, ?),Array,256)
DB.php:311

DB::prepared_query(INSERT INTO "Page_versions"
 ("TitleImageID", "PrimaryImageID", "RecordID", "Version")
 VALUES
 (?, ?, ?, ?),Array)
SQLExpression.php:121

SQLExpression->execute()
Database.php:301

SS_Database->manipulate(Array)
DB.php:358

DB::manipulate(Array)
DataObject.php:1350

DataObject->writeManipulation(SiteTree,2016-02-18 11:01:07,)
DataObject.php:1389

DataObject->write()
CMSMain.php:914

CMSMain->save(Array,CMSForm,SS_HTTPRequest)
Form.php:462

Form->httpSubmission(SS_HTTPRequest)
RequestHandler.php:288

RequestHandler->handleAction(SS_HTTPRequest,httpSubmission)
RequestHandler.php:200

RequestHandler->handleRequest(SS_HTTPRequest,DataModel)
RequestHandler.php:222

RequestHandler->handleRequest(SS_HTTPRequest,DataModel)
Controller.php:158

Controller->handleRequest(SS_HTTPRequest,DataModel)
LeftAndMain.php:451

LeftAndMain->handleRequest(SS_HTTPRequest,DataModel)
AdminRootController.php:92

AdminRootController->handleRequest(SS_HTTPRequest,DataModel)
Director.php:385

Director::handleRequest(SS_HTTPRequest,Session,DataModel)
Director.php:149

Director::direct(/admin/pages/edit/EditForm,DataModel)
main.php:184
```

I'd love to help, but have no idea how to fix this. I suppose it has to do with the ORM rewrite.

Reverting to `3.1.` for now...

**Comment by tractorcow** [comment]
Looks like a problem with versioning. Do you want to test with 3.2.2-rc1 and see if that version still has the noted issue?

**Comment by anselmdk** [comment]
It probably is. To be more specific, I've tested with the following:

* `3.3.x-dev`: the issue appears
* `3.2.x-dev`: the issue appears
* `3.1.x-dev`: no issue

I expect that includes `3.2.2-rc1`?

**Comment by tractorcow** [comment]
Let's prioritise this bugfix.

Possibly related to https://github.com/silverstripe/silverstripe-framework/pull/5041?

**Comment by kinglozzer** [comment]
@tractorcow Someone on IRC was reporting the `Versioned::writeWithoutVersion()` wasn’t working in 3.2 - apparently it always writes a row to the versions table, perhaps that’s also related to these two issues? Maybe `$_nextWriteWithoutVersion` is being ignored somewhere along the line (I can’t see any unit tests covering `writeWithoutVersion()`, so it’s possible)

**Comment by tractorcow** [comment]
Is there a chance of a reproducable test I could use? I'll add the test to https://github.com/silverstripe/silverstripe-framework/pull/5074 to see if this resolves that issue also.

**Comment by dhensby** [comment]
Was this fixed by #5074?

**Comment by anselmdk** [comment]
I tried a few days ago, I'm pretty sure that no.

**Comment by anselmdk** [comment]
See above for the Behat test.

**Comment by tractorcow** [comment]
Unfortunately #5074 was merged into 3.2 only; There will still be an issue in 3.1 unless we maybe back-port it.

**Comment by anselmdk** [comment]
In my case code where Page has a `has_one` relationship to an image _only_ works on `3.1`.
I'm hoping to be able to move back to using `3.2` or `3.3` once this has been fixed.
Would it help if I try to write a full Behat test that creates that page, and then fails? Against which branch should I write the pull request if so?

**Comment by dhensby** [comment]
If we think it's fixed on 3.2, put a test against that and lets see

**Comment by tractorcow** [comment]
I've tested this with current 3.2 (sha d2fa01fb17be7aa2b5d8bf6c3c6cce43656274b4) and it seems fine.

```php
<?php
class Page extends SiteTree {

	private static $has_one = array(
		'Image' => 'Image'
	);

	public function getCMSFields()
	{
		$fields = parent::getCMSFields();
		$fields->addFieldToTab('Root.Image', new UploadField('Image'));
		return $fields;
	}
}
```

I wonder if there's something else in your project @anselmdk that could be causing this.

**Comment by anselmdk** [comment]
@tractorcow I'll check up on that within a few days and will let you know if it works for me! If not I'll try on a clean installation.

**Comment by anselmdk** [comment]
I just tried this on
```
"silverstripe/cms": "3.3.x-dev",
"silverstripe/framework": "3.3.x-dev",
```
and it seems to have disappeared.
I checked, and can see that the fix was merged the 22nd February to framework, and subsequently to the 3.3 branch. I'm not sure how I could have missed this, but great!

Closing.
