### ISSUE TITLE
Breadcrumbs drops onto two lines

### ISSUE THREAD

**Issue by MichaelJJames** [silverstripe/silverstripe-cms#1402]
![breadcrumb-issue](https://cloud.githubusercontent.com/assets/6860174/13317205/06218660-dbac-11e5-8208-bc1efeb3883f.png)

**Comment by scott1702** [comment]
That's the intended behavior for breadcrumbs :wink:

**Comment by kinglozzer** [comment]
@MichaelJJames Yeah that’s the new style. The alignment of the buttons looks off because betterbuttons hasn’t been updated to match the new layout yet (see https://github.com/unclecheese/silverstripe-gridfield-betterbuttons/issues/123)
