### ISSUE TITLE
Internet Explorer 10 buttons on edit page weird

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-cms#1403]
While (sadly) viewing the page edit screen in IE, the action buttons on the bottom of the page display this:

![msie issue](https://cloud.githubusercontent.com/assets/67215/13383442/be89155c-deee-11e5-8db4-4071ccb5ebdf.PNG)

There's three things wrong with it:

1. It's different to how it looks in chrome/FFx/Safari (not important)
2. There's two drop down icons on the more options button (not important but probably can be easily fixed)
3. If you're using the subsite module and click 'preview', the page leads to a 404 (important)

**Comment by jonom** [comment]
Hey @torleif what version of the CMS is this? It doesn't look familiar to me... maybe 3.0? FYI you can get the version by hovering over the SilverStrip logo at top-left in the CMS.

**Comment by tractorcow** [comment]
Maybe it just looks weird because of IE? :P

@scott1702 do you know what could cause this?

**Comment by torleif** [comment]
@jonom it's 3.2, though I'm pretty sure I've seen it in 3.1 as well

**Comment by jonom** [comment]
@torleif this is what I'm seeing in IE10 with a bare-bones 3.2.3 install:

![screen shot 2016-02-29 at 9 05 25 am](https://cloud.githubusercontent.com/assets/1079425/13402121/b93f51e0-dec3-11e5-9d15-3d162928a63f.png)

It looks the same as FF/Chrome etc.

Maybe you have a module conflict or some legacy IE conditional stylesheets lying around somehow? I would try dumping the CMS and Framework folders and re-installing and see if that helps.

**Comment by tractorcow** [comment]
@torleif if you see this again, can you track down the CSS that causes one or either of these arrows?

**Comment by torleif** [comment]
@tractorcow I've managed to track down the issue to a network domain policy on our corporate network. We're forcing MSIE to send the following user agent string:

```Key	Value
User-Agent	Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3)``` 

This is tricking SilverStripe into thinking it's running MSIE 7.0 (despite the fact I'm overriding this with a  X-UA-Compatible "IE=Edge,chrome=1" string). On line 395 in LeftAndMain,php it includes the following CSS file /framework/admin/css/ie7.css that makes the browser borked. 

If the domain policy is not set, MSIE sends the following User Agent string:

```Key	Value
User-Agent	Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko```

And the extra css file does not get included. 

A solution would be to drop the MSIE7.0 CSS file, though it would only help out glacial speed organisations like ours.

**Comment by torleif** [comment]
From what I can tell, SilverStripe still supports MSIE 7.0, so I'll close this issue
