### ISSUE TITLE
BUG: CMS Preview iFrame loads CMS if editing draft page

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-cms#1406]
SS: 3.3.1 (upgraded from 3.2.1)

The CMS Preview iFrame loads another CMS interface if the page you're trying to edit is Draft. If the page is Published then the preview of the page is loaded correctly.

**Comment by jonom** [comment]
@christopherdarling I've tested this on both an upgraded site (from 3.1) and on a fresh install of 3.3.1 and couldn't replicate this issue. Could you try a fresh install? I wonder if this is related to some custom code in your project.

**Comment by christopherdarling** [comment]
@jonom odd.. perhaps it was some old session data or localstorage, although I did try the site in incognito mode before reporting it.. anyway, seems to be working now on both the upgraded site and also a clean install.
