### ISSUE TITLE
Full Text Search not working

### ISSUE THREAD

**Issue by Misagh90** [silverstripe/silverstripe-cms#1408]
Hi,
I try the full text search on SS 3.3.1 & 3.2.3 when i enable it, this message display on dev/build

> [User Error] Uncaught SS_DatabaseException: Couldn't run query: ALTER TABLE "File" ADD fulltext "SearchFields" ("Title","Filename","Content") The used table type doesn't support FULLTEXT indexes
> GET /test/dev/build?flush=all&flushtoken=f49b7eaa8d4b6890231b501e252b7b4e
> Line 55 in /home/teleprom/public_html/test/framework/model/connect/DBConnector.php_

& I try it with SS 3.1.2 and it's work.

**Comment by Misagh90** [comment]
@tractorcow @cam-findlay

**Comment by camfindlay** [comment]
Hi there, for these sort of technical implementation questions please post on our [forums](https://www.silverstripe.org/community/forums/). You need to be using MyISAM table types in order for this kind of searching to work. See https://docs.silverstripe.org/en/3.3/developer_guides/search/fulltextsearch/#adding-fulltext-support-to-mysqldatabase

**Comment by camfindlay** [comment]
@tractorcow you can close this @Misagh90 if you want to discuss further please start a forum post.

**Comment by tractorcow** [comment]
Thanks @cam-findlay , I was actually about to post the same link.

If you put this in your `_config.php` it would make it work magically.

```php
FulltextSearchable::enable():
```
