### ISSUE TITLE
SiteTreeLinkTracking vulnerability

### ISSUE THREAD

**Issue by dylangrech92** [silverstripe/silverstripe-cms#1409]
Silverstripe 3.2.1

If in an HTMLField you have a link like this: `<a href="##">whatever</a>` it will escape this preg_match rule:

'Broken' => !preg_match("#(name|id)=\"{$matches[1]}\"#", $htmlValue->getContent())

Inside SiteTreeLinkTracking.php Line 263

**Comment by dhensby** [comment]
thanks for reporting, I've submitted a PR, care to take a look?

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-cms/issues/1431
