### ISSUE TITLE
CMS favicons and link to home page suggestions

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-cms#1412]
Hi all. Quick suggestion for CMS. Easy to do...I'd do it myself but a bit busy at the moment.

(1) get the favicon appearing in the browser tabs when working in the CMS, according to current theme. It would look a touch more professional.
(2) make the site title, as set in "Settings", a link to the home page so one can quickly get to the site without having to log out of the cms and without having to edit the address in the address bar. The advantage is that if one has logged in to the CMS with "Remember me" then going from CMS to the site is a single click and keeps you logged in. If one also puts a link to from the site to the CMS via an "Admin" link, then it is a single click to go from one to the other. Of course, this is not needed in split editing mode, but on smaller screens, split mode isn't available and so this would come in handy. See below:

 ![screenshot from 2016-03-05 16 28 16](https://cloud.githubusercontent.com/assets/8912185/13551269/f3f08ed6-e2f0-11e5-9305-371644739aed.png)

**Comment by SpiritLevel** [comment]
And one more thought: replace the SS logo with the company favicon, and put the SS logo somewhere not associated with the company name. Maybe put the SS logo on the logout button, or somewhere in the breadcrumb pane ? Or put the SS logo on the help button ? Just ideas to consider :)

**Comment by SpiritLevel** [comment]
And one more thought: if there is no favicon in the current theme, have the SS favicon appear in the browser tabs as a fallback. One could put an option to select a custom CMS favicon in Settings ?

**Comment by jonom** [comment]
Hey @SpiritLevel thanks for these ideas! We try to keep github issues focused on bugs only though... this isn't really documented well, currently buried at the bottom of the [bug report page](https://docs.silverstripe.org/en/3.3/contributing/issues_and_bugs/) but the right place to discuss an idea for a new feature is either UserVoice or the mailing list.

@cam-findlay were you thinking about updating the CONTRIBUTORS.md and some other key pieces of content to make this a bit clearer? Background: https://groups.google.com/d/topic/silverstripe-dev/DeLEi8yl0ew/discussion Maybe we also need a separate 'Feature Requests' or 'Discuss ideas' page in the docs in the Contributing section?

I'll close this for now but feel free to pick up discussion elsewhere or submit a PR for these changes at which point we *can* discuss it on github :) sorry I know it's a bit convoluted.

By the way - favicons already work for me - the CMS shows same favicon as the site. Is your favicon file located in the web root and called `favicon.ico`? This should be all that's required for the browser to  fetch and display that icon, we shouldn't need to supply any special code to support that.

**Comment by SpiritLevel** [comment]
Thank @jonom ...I know, I was being a bit cheeky putting the suggestions here...I thought the favicon issue  "might" qualify as a bug :P

OK. Clearing browser cache and restarting browser got the favicons appearing on the CMS page tabs. However, I am NOT using a favion.ico in the webroot. Instead, I have all favicons in a theme subfolder and have a meta tag in the head of my main Page.ss template redirecting the browser there for all favicons. So, the interesting point here is that this redirection appears to work for CMS pages as well as all pages that extend Page.php. But, perhaps it doesn't work "right away": in the above screen shot, my hope page tab has a favicon but the CMS page tabs don't...maybe there is a small bug in there.

**Comment by kinglozzer** [comment]
@SpiritLevel Just on your other points - if we ever override the logo in the top-left, we do so by including our own CSS using [`LeftAndMain.extra_requirements_css`](https://github.com/silverstripe/silverstripe-framework/blob/3/admin/code/LeftAndMain.php#L136). You can also set the link for the logo (not the text, however) using the [`LeftAndMain.application_link`](https://github.com/silverstripe/silverstripe-framework/blob/3/admin/code/LeftAndMain.php#L1642) config value

**Comment by SpiritLevel** [comment]
Super, thanks @kinglozzer for pointing out where to adjust these things ! Have made those changes in my sites :)
