### ISSUE TITLE
BUG in 3.3.1 : CMS tab indicator a bit confused

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-cms#1419]
![screenshot from 2016-03-09 04 29 38](https://cloud.githubusercontent.com/assets/8912185/13633955/bf34675a-e5af-11e5-8dd9-889bf39f2d92.png)

Can't reproduce but I caught it on candid camera!

**Comment by dhensby** [comment]
Touch screen?

TBH, if you can't replicate it I'm not sure we can do much about it?

**Comment by anselmdk** [comment]
Could that have to do with this one?
I just updated composer while on `3.1.x-dev`, and this happened to me when clicking on random pages. Now I rolled back to `3.1.18`, and it disappeared.

<img width="626" alt="screenshot 2016-03-09 19 05 52" src="https://cloud.githubusercontent.com/assets/1316533/13645311/adbed598-e62a-11e5-857c-9af99828eb1b.png">

**Comment by dhensby** [comment]
I don't think so. Can you open an issue for that please @anselmdk

**Comment by SpiritLevel** [comment]
@dhensby No, it wasn't on a touch screen. When I refreshed the page, it remained as above. I'll keep my eye open for how to reproduce.

**Comment by anselmdk** [comment]
@dhensby I created https://github.com/silverstripe/silverstripe-cms/issues/1421 for that one.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-cms/pull/1425 for @anselmdk 's issue.

**Comment by phptek** [comment]
This has annoyed me for years! I have just tracked it down and can reproduce it (if anyone cares, seeing as @tractorcow might have fixed it)

Security --> Groups --> Select a Group --> Click the "Groups" breadcrumb link --> hey presto!

**Comment by dhensby** [comment]
Can confirm replicated in 3.5.x-dev

**Comment by dhensby** [comment]
Both tabs have the `ui-active-state` class after following @phptek's steps

**Comment by maxime-rainville** [comment]
Looks like it's been fix in SS4.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
