### ISSUE TITLE
Recently Edited Report contains broken links when used with Translatable module

### ISSUE THREAD

**Issue by LeviWB** [silverstripe/silverstripe-cms#1420]
When the Translatable module is installed, the Recently Edited Report generates invalid links to pages it lists. The format it uses is /admin/pages/edit/show?locale=en_US/1, rather than /admin/pages/edit/show/1?locale=en_US

This sounds like a very similar issue to #1183

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-cms/pull/1422
