### ISSUE TITLE
CMS Tabs are off on `3.1.x-dev`

### ISSUE THREAD

**Issue by anselmdk** [silverstripe/silverstripe-cms#1421]
I updated composer while on `3.1.x-dev`, and this happened to me when clicking on random pages. Now I rolled back to `3.1.18`, and it disappeared.

<img width="626" alt="screenshot 2016-03-09 19 05 52" src="https://cloud.githubusercontent.com/assets/1316533/13645311/adbed598-e62a-11e5-857c-9af99828eb1b.png">

**Comment by tractorcow** [comment]
It looks like a set of tab content divs are being created... those should not even be in the HTML.

**Comment by tractorcow** [comment]
It looks as though https://github.com/silverstripe/silverstripe-cms/pull/1416 is the problem.

**Comment by tractorcow** [comment]
Tested and fixed with https://github.com/silverstripe/silverstripe-cms/pull/1425

**Comment by kinglozzer** [comment]
Whaaaaat?! I don’t know how I managed to miss this, sorry guys :disappointed:
