### ISSUE TITLE
3.3 ModelAdmin FilterForm overlaps GridField

### ISSUE THREAD

**Issue by RVXD** [silverstripe/silverstripe-cms#1427]
Since 3.3 the modeladmin filter form on the left side overlaps the modeladmin gridfield. Strange to see this in a stable release. See screenshot.
![screen shot 2016-03-15 at 08 44 43](https://cloud.githubusercontent.com/assets/1586761/13770968/d73603ba-ea8a-11e5-9efa-fd4f611bc996.png)
Even if filterform is collapsed the overlaps stays.
![screen shot 2016-03-15 at 08 47 25](https://cloud.githubusercontent.com/assets/1586761/13770970/dc9f9fc8-ea8a-11e5-843b-aea24f9937c6.png)

**Comment by kinglozzer** [comment]
@RVXD It looks to me like you’ve got some browser caching going on there. The filter panel should now be completely hidden until you click on the magnifying glass at the top-right, when it should then scroll down from the top - see screenshots below:

![screen shot 2016-03-15 at 09 10 59](https://cloud.githubusercontent.com/assets/1655548/13772795/e70d40d4-ea8d-11e5-9d7d-cabe1f2b8f01.png)
![screen shot 2016-03-15 at 09 11 05](https://cloud.githubusercontent.com/assets/1655548/13772796/ea2fd308-ea8d-11e5-8a70-c9b22abddc4a.png)

**Comment by RVXD** [comment]
Thanks for the response. I did a reinstall to check, since it was not caching. 
The problem was caused by a module that was included:
"littlegiant/silverstripe-catalogmanager": "*"
It causes the filters to show up in the wrong place.

**Comment by kinglozzer** [comment]
Ah, thanks for confirming @RVXD

**Comment by dhensby** [comment]
It's worth reporting to that module

**Comment by stevie-mayhew** [comment]
@RVXD - I've fixed that in the latest version of catalog manager - `3.0.0` - https://github.com/Little-Giant/silverstripe-catalogmanager/pull/48

**Comment by RVXD** [comment]
Great thanks!
