### ISSUE TITLE
BUG Clicking page settings doesn't show settings page

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-cms#1438]
Possibly related to https://github.com/silverstripe/silverstripe-framework/pull/5243

Clicking "settings" on a page will load the page edit view again, and won't display the settings tab.

![image](https://cloud.githubusercontent.com/assets/936064/14238309/991a3584-fa83-11e5-9c02-f07adbb487c7.png)

Jira: https://silverstripe.atlassian.net/browse/OSS-1724

**Comment by flashbackzoo** [comment]
Pretty sure it's related to this using a wildcard at the end of the route https://github.com/silverstripe/silverstripe-framework/blob/master/admin/javascript/src/LeftAndMain.js#L259

**Comment by flashbackzoo** [comment]
Fixed with https://github.com/silverstripe/silverstripe-cms/pull/1418
