### ISSUE TITLE
BUG Add page numbered bullets display weird (4.x)

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-cms#1439]
![image](https://cloud.githubusercontent.com/assets/936064/14238338/2b46b284-fa84-11e5-9b1e-d717bf16d056.png)

Also can be found on the insert link dialog in TinyMCE

![image](https://cloud.githubusercontent.com/assets/936064/14238347/3de61bbe-fa84-11e5-9248-6eeb702d6906.png)

Jira: https://silverstripe.atlassian.net/browse/OSS-1725

**Comment by chillu** [comment]
I think we should simplify those styles rather than fix them. @clarkepaul?

**Comment by clarkepaul** [comment]
Yup I agree, those designs are very old looking. Cut back even it is just titles eg. "Step 1" & "Step 2". It's a nice one for me to pick up.

**Comment by hafriedlander** [comment]
Fixed by https://github.com/silverstripe/silverstripe-framework/pull/5292

**Comment by jeffreyguo** [comment]
The bullet 1 looks good. However, bullet 2 "Choose page type" is not, the number "2" and text "Choose page type" are in separate lines.

**Comment by clarkepaul** [comment]
I've just tested master locally in both chrome and FF and this is what I see
![pasted_image_6_05_16__11_14_am](https://cloud.githubusercontent.com/assets/555033/15060123/f51806de-137b-11e6-9502-faed178e102b.png)

**Comment by jeffreyguo** [comment]
@clarkepaul , glad to see it is fixed in master. I was testing in demo site http://ss4demo-uat.sites.silverstripe.com/ and still get this issue.

**Comment by jeffreyguo** [comment]
![screen shot 2016-05-06 at 12 07 58 pm](https://cloud.githubusercontent.com/assets/6565447/15060896/3ea504d0-1383-11e6-97c2-a0c31e00f3ca.png)

**Comment by clarkepaul** [comment]
I've opened a separate issue regarding the wrong font being rendered, maybe there is a chance that this also fixes the miss alignment. https://github.com/silverstripe/silverstripe-framework/issues/5463

**Comment by clarkepaul** [comment]
And I've opened another for the markup being different for each step. https://github.com/silverstripe/silverstripe-cms/issues/1480
