### ISSUE TITLE
BUG can't create pages through right click menu

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-cms#1440]
Can’t create a child page when right click on a parent page in the site tree and select Page, got “bad request” error. Can’t duplicate either.

![image](https://cloud.githubusercontent.com/assets/936064/14238405/1edf1864-fa85-11e5-8f61-fbcacad86aed.png)

![image](https://cloud.githubusercontent.com/assets/936064/14238399/059b36da-fa85-11e5-8ede-689171e5da18.png)

Jira: https://silverstripe.atlassian.net/browse/OSS-1726

**Comment by clarkepaul** [comment]
Tested on master and don't have this issue. Works fine in Chrome and also tested on IE10, no even glitchy.

**Comment by hafriedlander** [comment]
Yup, can't replicate. Closing as either fixed or can't replicate.
