### ISSUE TITLE
BUG Clicking 'add new' page in cms doesn't remember current parentid

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-cms#1441]
Same as https://github.com/silverstripe/silverstripe-cms/issues/855 and https://github.com/silverstripe/silverstripe-cms/pull/1371, but currently affecting master branch.

“Add new” page is not set current page as parent, it is always “Top level”.

![image](https://cloud.githubusercontent.com/assets/936064/14239055/ff40d81a-fa8b-11e5-9894-41893e8ea630.png)

Jira: https://silverstripe.atlassian.net/browse/OSS-1727

**Comment by clarkepaul** [comment]
I think is fixed if I understand the issue right.

**Comment by tractorcow** [comment]
Yes it's fixed now. :D
