### ISSUE TITLE
BUG Incorrect alignment of batch actions dropdown

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-cms#1442]
See screenshot:

![image](https://cloud.githubusercontent.com/assets/936064/14239219/6e0e56d6-fa8d-11e5-8654-6cdc51261505.png)

Currently affects master branch.

Jira: https://silverstripe.atlassian.net/browse/OSS-1730

**Comment by hafriedlander** [comment]
Fixed in current master.
