### ISSUE TITLE
MINOR Clicking save & publish moves buttons up the screen

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-cms#1443]
![image](https://cloud.githubusercontent.com/assets/936064/14239400/7d700244-fa8f-11e5-814c-6f231a05f5a4.png)

The “Save”, “Save and publish” section moves up if the page is not long enough. But it should be stayed at the bottom all the time.

Affects master branch.

Jira: https://silverstripe.atlassian.net/browse/OSS-1733

**Comment by chillu** [comment]
Note that this only happens after saving a page

**Comment by clarkepaul** [comment]
JS errors. Seems to be only while editing the redirector page but I think this also relates directly to https://github.com/silverstripe/silverstripe-cms/issues/1468

**Comment by chillu** [comment]
Can't reproduce on Chrome or IE10 - I think that must've been a generic JS error which has been fixed since (possibly related to PJAX callbacks), rather than anything specific to the layout mechanism which we haven't really touched in SS4.
