### ISSUE TITLE
BUG Expanding sub-tree in pages list view doesn't work

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-cms#1444]
![image](https://cloud.githubusercontent.com/assets/936064/14239464/33534d78-fa90-11e5-9c49-ed68afb6e3d9.png)

Jira: https://silverstripe.atlassian.net/browse/OSS-1734

**Comment by clarkepaul** [comment]
I test this yesterday and couldn't see any issues, can you confirm this is still a problem. Related fix https://github.com/silverstripe/silverstripe-framework/pull/5406
