### ISSUE TITLE
ErrorPage not properly writing static files 

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-cms#1447]
Currently `ErrorPage->writeStaticPage()` ([here](https://github.com/silverstripe/silverstripe-cms/blob/3/code/model/ErrorPage.php#L253)) is not properly checking the return value of `file_put_contents()`. It is performing loose type checking instead of ensuring the result is actually `false` ([see documentation](http://php.net/manual/en/function.file-put-contents.php#refsect1-function.file-put-contents-returnvalues)).  When an error page, for some reason or another, doesn't contain a body and is zero bytes, `file_put_contents()` will dutifully write zero bytes and return the integer `0`, as it should.

So:
```php
// ...
$filePath = self::get_filepath_for_errorcode($this->ErrorCode, $this->Locale);
if (!file_put_contents($filePath, $errorContent)) {
    // ...
}
```

Should instead be:

```php
// ...
$filePath = self::get_filepath_for_errorcode($this->ErrorCode, $this->Locale);
if (file_put_contents($filePath, $errorContent) === false) {
    // ...
}
```

I think the fact that an error page has returned a `$response->getBody() == ''` result is a different issue and, as such, the error checking that this method *may* need to be in a different discussion. However the core point here is that it is causing a crash with an irrelevant error message in my particular edge case when, instead, it should simply be continuing as normal or at least producing an accurate error message (if we decide a zero length body is indeed an error in its own right).

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-cms/pull/1448
