### ISSUE TITLE
Exporting to CSV from the BrokenLinksReport is missing columns

### ISSUE THREAD

**Issue by jakedaleweb** [silverstripe/silverstripe-cms#1451]
**CMS shows**
- Page name
- Date last published
- Problem type
- URL

**CSV shows**
- Sub heading (which is showing the same detail as Page name but the title is different
- Description (this looks like the page Summary information)
- Image (all rows containing the word Image)

**Comment by tractorcow** [comment]
Sounds like a reasonable bugfix... rename some columns, add some missing ones, and fix the "Image" column. :D

**Comment by dhensby** [comment]
Bump

**Comment by dhensby** [comment]
This appears to be fixed in 3.x-dev
