### ISSUE TITLE
BUG SiteTree duplicate duplicates LinkTracking records

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-cms#1453]
I believe there's a bug when duplicating a page in the CMS the LinkTracking many_many records are also duplicated.

For example; 
1. Page A (URL /home/) contains links to Page B (URL: /about-us/).
2. Page B lists Page A as a dependent page - correct
3. Duplicate Page B in the CMS. Page C is created (URL: /about-us-2/)
4. Page C lists Page A as a dependent page - incorrect

**Comment by tractorcow** [comment]
Looks legit... we need to track down what's going on in SiteTree::duplicate() and fix.

Possibly related to https://github.com/silverstripe/silverstripe-cms/issues/1253

**Comment by nglasl** [comment]
I recently encountered this, and ended up needing to remove any **BackLinkTracking** **onAfterDuplicate**. This definitely requires some further digging.

**Comment by tractorcow** [comment]
I'm not sure that DataObject should be invoking duplicateManyManyRelations when duplicating; Maybe it should be an option to DataObject::duplicate?

**Comment by tractorcow** [comment]
Let's revert https://github.com/silverstripe/silverstripe-framework/commit/ed666b71b79faade645502e170b295deabccf5ef

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/6169.

Now duplication of many_many is opt in, which means SiteTree::duplicate / ::duplicateWithChildren won't automatically include them.
