### ISSUE TITLE
Layout breaks after creating redirector page

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#1468]
I think this relates directly to https://github.com/silverstripe/silverstripe-cms/issues/1443 but added as a separate issue just in case.

![pasted_image_2_05_16__4_50_pm](https://cloud.githubusercontent.com/assets/555033/14947498/9b21bc38-1088-11e6-98f4-e74b16a8e95b.png)

**Comment by chillu** [comment]
Can't reproduce on Chrome or IE10 - I think that must've been a generic JS error which has been fixed since (possibly related to PJAX callbacks), rather than anything specific to the layout mechanism which we haven't really touched in SS4.
