### ISSUE TITLE
SS4 demo: Styling issue and items missing on right-click menu in site tree

### ISSUE THREAD

**Issue by jeffreyguo** [silverstripe/silverstripe-cms#1470]
Styling issue and menus missing when right click on a page in site tree (tested in Chrome, IE10)
![screen shot 2016-05-06 at 10 21 18 am](https://cloud.githubusercontent.com/assets/6565447/15059856/ce8a600e-1379-11e6-91b9-35f22a7781b1.png)

**Comment by chillu** [comment]
Paul has fixed this now
