### ISSUE TITLE
SS4 demo: Styling issue on checkboxes in page settings page

### ISSUE THREAD

**Issue by jeffreyguo** [silverstripe/silverstripe-cms#1471]
![screen shot 2016-05-06 at 10 55 07 am](https://cloud.githubusercontent.com/assets/6565447/15059880/0395bcbc-137a-11e6-9f3d-2cd4cda206c7.png)

**Comment by jeffreyguo** [comment]
Tested in Chrome and IE10.

**Comment by chillu** [comment]
Paul has fixed this
