### ISSUE TITLE
SS4 demo: Attached image not shown in content editor(TinyMCE)

### ISSUE THREAD

**Issue by jeffreyguo** [silverstripe/silverstripe-cms#1474]
1) when insert an image into content editor, I can see the image
2) but save and publish the page, the image is hangs on loading
3) the inserted image is shown in frontend, but just not shown in content editor.

![screen shot 2016-05-06 at 11 35 08 am](https://cloud.githubusercontent.com/assets/6565447/15060492/2159a056-137f-11e6-9783-8c219aafc24d.png)

**Comment by tractorcow** [comment]
Will re-test in time for alpha 2.

**Comment by bergice** [comment]
Tested on UAT demo, prod demo and local. Unable to replicate. Please provide some more information if this is still occurring, otherwise I'll mark this as resolved.
