### ISSUE TITLE
No message in alert window

### ISSUE THREAD

**Issue by jeffreyguo** [silverstripe/silverstripe-cms#1476]
When select "unpublish" or "Delete draft" or "Archive" from "more options" on a page, the alert window pops up, but there is no message.
Tested in Chrome and IE10.
![screen shot 2016-05-06 at 11 48 35 am](https://cloud.githubusercontent.com/assets/6565447/15060652/f5f7cdb4-1380-11e6-8c38-c1a6bde3297c.png)

**Comment by chillu** [comment]
This also affects framework functionality like removing members

**Comment by hafriedlander** [comment]
Fixed by https://github.com/silverstripe/silverstripe-cms/pull/1488

Don't know about that other bug @chillu - didn't see anything specific to this fix which might cause it.
