### ISSUE TITLE
Indicate if Save a Campaign was successful

### ISSUE THREAD

**Issue by vinh63** [silverstripe/silverstripe-cms#1477]
There is no indication whether a campaign has been saved once the 'save' button has been clicked.

**Comment by tractorcow** [comment]
Yeah, we need a standard "notification" system for react. @clarkepaul want to think about this?

**Comment by clarkepaul** [comment]
Yup we do, but also the state of the button could change if we can detect it as well.

**Comment by sminnee** [comment]
Duplicate of https://github.com/silverstripe/silverstripe-framework/issues/5516
