### ISSUE TITLE
SS4 demo: Styling issue on checkboxes in page history tab

### ISSUE THREAD

**Issue by jeffreyguo** [silverstripe/silverstripe-cms#1478]
In page history tab, the checkbox overlaps the text.
![screen shot 2016-05-06 at 12 16 50 pm](https://cloud.githubusercontent.com/assets/6565447/15061030/ae87df6a-1384-11e6-862b-1fcbf8ca3467.png)

**Comment by clarkepaul** [comment]
Picking this one up now.

**Comment by clarkepaul** [comment]
I'm requesting this be re-opened in Framework. https://github.com/silverstripe/silverstripe-framework/issues/5355

**Comment by clarkepaul** [comment]
Related PR here https://github.com/silverstripe/silverstripe-framework/pull/5476

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5476
