### ISSUE TITLE
Not able to change page type

### ISSUE THREAD

**Issue by jeffreyguo** [silverstripe/silverstripe-cms#1479]
Wanted to change page type from a page, but got error message "Not found" on demo site, failed to change page type.
![screen shot 2016-05-06 at 12 28 38 pm](https://cloud.githubusercontent.com/assets/6565447/15061218/b5ff0758-1386-11e6-8764-a5291b0798ec.png)

**Comment by hafriedlander** [comment]
This is actually simpler to replicate: just change to "settings" tab, then click save. (No need to change page type).

**Comment by hafriedlander** [comment]
Fixed by https://github.com/silverstripe/silverstripe-cms/pull/1489
