### ISSUE TITLE
SS4 demo: Wrong text colour in user search box

### ISSUE THREAD

**Issue by jeffreyguo** [silverstripe/silverstripe-cms#1482]
In Security module > search, try to type in first name field, you can’t see anything, but if you select all in the field then you will see the text as the text is in the same colour as the text box.

![screen shot 2016-05-06 at 2 52 54 pm](https://cloud.githubusercontent.com/assets/6565447/15063050/db9ab372-139a-11e6-8aca-1f1577961800.png)

**Comment by clarkepaul** [comment]
Fixed by #5507
