### ISSUE TITLE
SS4 demo: The button “Choose File” is missing in Security module

### ISSUE THREAD

**Issue by jeffreyguo** [silverstripe/silverstripe-cms#1483]
In Security module, when try to import users or groups from CSV, it's not able to see the upload button "Choose File".
In addition, seems all texts are in different fonts with CMS v3.3, especially the link “Show advanced usage”.
![screen shot 2016-05-06 at 3 01 18 pm](https://cloud.githubusercontent.com/assets/6565447/15063211/37760aa6-139c-11e6-8c62-101406890c1b.png)

**Comment by clarkepaul** [comment]
It is now present in master, closing
