### ISSUE TITLE
Conditional fields are shown in site settings > Access

### ISSUE THREAD

**Issue by jeffreyguo** [silverstripe/silverstripe-cms#1485]
In Settings > Access, the conditional field “Viewer Groups” only appears after the radio option “Only these people” is selected. But now it shows on page load. Same issue for “Editor Groups” field and “Top level creators” field.

![screen shot 2016-05-06 at 3 15 26 pm](https://cloud.githubusercontent.com/assets/6565447/15063409/35336e44-139e-11e6-8f4a-69f4300ff4cc.png)

**Comment by dhensby** [comment]
What version of the CMS is this? Are there any JS errors in the console?

**Comment by jeffreyguo** [comment]
Tested in SS4 demo site on hackday. It's not able to duplicate now.
