### ISSUE TITLE
Document $enforce_strict_hierarchy

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-cms#1486]
WAS: Document $enforce_strict_hierarchy is being tested for but not used anywhere (apart from a mention in SiteTree)

$enforce_strict_hierarchy is basically used in such a way that if you delete a page, the children are also deleted.  

I think we need a bit more information and documentation on this variable.

**Comment by tractorcow** [comment]
Which page on the docs would this best be suited on? Do you want to write a pull request with what you think is needed?

**Comment by dhensby** [comment]
Hmmm, this is a good point. If it's a feature we don't use, should it be a module instead? Dog flooding and all that? Though if the test coverage is sufficient.....

**Comment by SpiritLevel** [comment]
![dog-island-500](https://cloud.githubusercontent.com/assets/8912185/15445226/82435fe8-1f4f-11e6-9a7d-ac5d3a3dc83b.jpg)

Exactly what I need to switch from Emacs to PHPStorm...and the water has to be cold...

**Comment by sunnysideup** [comment]
Hi Damian and Daniel

I have sort of decided that I will try to make really clear (better than before!) bug reports or Silverstripe core stuff but leave it up to other people to fix it.  I have 148 modules to maintain myself ;-) and so I prefer to fix up those. 

@dhensby - no idea what dog flooding is all about (https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#newwindow=1&q=%22dog+flooding%22+urban+dictionary) but I am loving the picture above.... I regularly flood my dog.

**Comment by SpiritLevel** [comment]
It's a way to cure oneself of bad habits, often applied to doggies:

http://www.training-your-dog-and-you.com/Flooding_Therapy.html

**Comment by sunnysideup** [comment]
sounds like I could do with some ;-)

**Comment by dhensby** [comment]
Damn in autocorrect!

**Comment by SpiritLevel** [comment]
Is that "damn it auto-correct" or "damn auto-incorrect" or even something much worse ? Perhaps the length of your fingers and your keymap settings need to be brought into alignment ? :P

**Comment by dhensby** [comment]
*sigh*

**Comment by mikenz** [comment]
We use the feature, please don't remove it.

`enforce_strict_hierarchy=false` makes sense with `nested_urls=false`, but yes it would be nice to have all these documented somewhere (other than in the code where I normally find them)

**Comment by tractorcow** [comment]
We should probably also test that it works when un-publishing (un-publishing a page should un-publish, but not delete, children).

**Comment by tractorcow** [comment]
To be honest, I think the best place to document it is on SiteTree.php itself,  on the below:


```php
/**
 * <Some description here>
 *
 * @config
 * @var boolean
 */
private static $enforce_strict_hierarchy = true;
```
