### ISSUE TITLE
Alignment and spacing of main CMS panels

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-cms#1491]
![image](https://cloud.githubusercontent.com/assets/111025/15134911/8098f920-16c4-11e6-89dd-df6f2fcee57d.png)

- "Add new" is not vertically aligned with icon
- "Batch actions" seems to be using the wrong font

Observed in `master` on Firefox latest.

**Comment by clarkepaul** [comment]
The font seems to be okay now on master. Fixing alignment

**Comment by clarkepaul** [comment]
Included another bug (https://github.com/silverstripe/silverstripe-framework/pull/5946) which was conflicting with dist files 

Before:
![pasted_image_5_09_16__6_59_pm](https://cloud.githubusercontent.com/assets/555033/18258564/3cf65abc-742c-11e6-8365-14fa737e7bc4.png)
![pasted_image_5_09_16__6_59_pm](https://cloud.githubusercontent.com/assets/555033/18258570/4df5304a-742c-11e6-9e09-c23e8ffbc6fb.png)

![pasted_image_5_09_16__7_00_pm](https://cloud.githubusercontent.com/assets/555033/18258562/3653cabe-742c-11e6-9784-5b8481aba161.png)

After:
![pasted_image_5_09_16__6_58_pm](https://cloud.githubusercontent.com/assets/555033/18258572/593afeda-742c-11e6-9dd7-72b6c7671f59.png)

![pasted_image_5_09_16__6_58_pm](https://cloud.githubusercontent.com/assets/555033/18258577/60a13a9a-742c-11e6-9a55-e323c2fd337c.png)
![pasted_image_5_09_16__6_57_pm](https://cloud.githubusercontent.com/assets/555033/18258579/66c7c934-742c-11e6-82e4-7c46146045ec.png)

![pasted_image_5_09_16__6_57_pm](https://cloud.githubusercontent.com/assets/555033/18258581/6e72cd00-742c-11e6-8ae9-206b836cac89.png)

PR https://github.com/silverstripe/silverstripe-framework/pull/5955

**Comment by chillu** [comment]
Talked to Paul, he'll see if a rule like `.ss-gridfield:first-child { margin-top: -10px; }` is feasible to make this more generic. He convinced me that the negative margin is a necessary evil here in order to keep with the bootstrap convention of only adding margins to the *bottom* of form field holders (`.form-group` in TWBS). We need to add back some inner padding on `.cms-panel-padded` which got lost in the style refactoring. But ideally we can make this all work without having section specific selectors like `.ReportAdmin` - these are relatively generic problems.

**Comment by clarkepaul** [comment]
Ready for review.
Will require same branch name for Framework, CMS, AssetAdmin, Reports, and SiteConfig.
https://github.com/silverstripe/silverstripe-framework/pull/5955
https://github.com/silverstripe/silverstripe-cms/pull/1614
https://github.com/silverstripe/silverstripe-asset-admin/pull/254
https://github.com/silverstripe/silverstripe-reports/pull/49
https://github.com/silverstripe/silverstripe-siteconfig/pull/37


I did a good amount of testing prior to the webpack work being merged and since then have done another round and every seems to be good.

**Comment by flamerohr** [comment]
Looking good, a few bits I had found that were inconsistent with the rest, Filter button is a little overlapping:
![screen shot 2016-09-20 at 1 29 47 pm](https://cloud.githubusercontent.com/assets/1064889/18654782/f0bbe100-7f37-11e6-918d-d7fc3f06551e.png)
this one is missing some padding:
![screen shot 2016-09-20 at 1 30 15 pm](https://cloud.githubusercontent.com/assets/1064889/18654787/f9130004-7f37-11e6-8134-740bd41907c7.png)
and the upload field doesn't have any padding below it:
![screen shot 2016-09-20 at 1 40 51 pm](https://cloud.githubusercontent.com/assets/1064889/18654795/0763b19e-7f38-11e6-827f-5ae86f5ddb35.png)

**Comment by clarkepaul** [comment]
The filter button and import button is going to have to be a separate issues, I discounted them (along with many other issues) but will need to see if they are captured somewhere else.
My campaigns area was broken, @chillu couldn't figure out why so I missed that notice but I will look into that issue now.

**Comment by flamerohr** [comment]
Your campaigns area may be fixed by this https://github.com/silverstripe/silverstripe-framework/issues/6031
I ran into a few issues with Campaigns and "Sessions", it was a pain to find

**Comment by tractorcow** [comment]
@flamerohr I'm going to merge @clarkepaul 's PR and rebase that one on top of it.

**Comment by clarkepaul** [comment]
Fixed one the file upload bug mentioned above:
Now:
![image](https://cloud.githubusercontent.com/assets/555033/18657727/041cf3b0-7f51-11e6-897d-343e5265f17a.png)
![image](https://cloud.githubusercontent.com/assets/555033/18657729/0a66a162-7f51-11e6-877b-c01afc6e0d4f.png)

**Comment by clarkepaul** [comment]
PR for other issue mentioned above about "Filter" button having no space is https://github.com/silverstripe/silverstripe-reports/pull/50

**Comment by clarkepaul** [comment]
Added fix for spacing above campaign alert, area was using legacy classes so updated them to the newer panel classes.
Before:
![image](https://cloud.githubusercontent.com/assets/555033/18659403/78220c34-7f5e-11e6-8199-0b2dba5137c1.png)

After
![image](https://cloud.githubusercontent.com/assets/555033/18659364/39601ff4-7f5e-11e6-8cd6-ac15469aaaf3.png)

**Comment by flamerohr** [comment]
Looking good :D happy to merge when you're ready

**Comment by clarkepaul** [comment]
Good by me :)

**Comment by tractorcow** [comment]
All merged.
