### ISSUE TITLE
Request from user feedback: Make CMS website title a link to website in new tab

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#1496]
The website title currently doesn't have a link, it would be useful if the title opened up the website in a new tab.
![pasted_image_16_05_16__12_19_pm](https://cloud.githubusercontent.com/assets/555033/15277739/801cddea-1b60-11e6-94a8-d44d8dd03172.png)

**Comment by Firesphere** [comment]
Well, that didn't go as planned. The a tag in the CMS has the image set as background, instead of having it assigned to a specific class (like a.logo). This needs to be updated before trying to add a link to the text.
