### ISSUE TITLE
SiteTree “archive” action doesn’t work in Live reading mode

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-cms#1497]
I’ve got an interface on the “front-end” where users can add/edit/delete blog posts. `SiteTree::doArchive()` will leave draft pages in the CMS unless the reading mode is switched to stage before performing the action:

```php
// This will result in the page still being present in the CMS as a draft page
$post->doArchive();

// Page will be archived as expected
$oldStage = Versioned::current_stage();
Versioned::reading_stage('Stage');
$post->doArchive();
Versioned::reading_stage($oldStage);
```

**Comment by dhensby** [comment]
The idea is that `doArchive` should be agnostic to the current reading stage? I think I tend to agree.

**Comment by tractorcow** [comment]
Yes that's right; We should probably enforce archive's delete from stage and live explicitly, not just "current mode".

**Comment by dhensby** [comment]
@kinglozzer care to patch?

**Comment by kinglozzer** [comment]
I’ll try to find time to fix this soon

**Comment by kinglozzer** [comment]
I can’t recreate this in a unit test... which is pretty frustrating. Perhaps it’s something to do with the blog module. Will close for now
