### ISSUE TITLE
Loading gif has artifacts

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-cms#1504]
When clicking on a pagetype for example, the little logo filling up etc., has some artifacts/white stripes.

**Comment by chillu** [comment]
Which browser? You mean clicking on a page type radio option in admin/page/add?

**Comment by dhensby** [comment]
@Firesphere want to improve it? orrrrrr shall we close :P

**Comment by Firesphere** [comment]
Just close it, I don't see it in newer releases anymore. Possibly just a simple case of the checkout going slightly corrupt on the gif.
