### ISSUE TITLE
Page urls are not bookmarkable

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-cms#1510]
When editing a page that has a gridfield, the ID of the page being edited is stored in the session, and it makes it really hard to bookmark it.

`/admin/pages/edit/EditForm/field/Fields/item/3/edit`

If I go to another page and then visit this, it usually breaks.

Before 4.0 it would be great to fix these urls so that they matched the "edit" top level url.

Something like:

`/admin/pages/edit/show/11/EditForm/field/Fields/item/3/edit`

Where the edit page link is

`/admin/pages/edit/show/11`

And then we can dump the "store current page in session" dumbness that the cms relies on.

This story is a dependency of https://github.com/silverstripe/silverstripe-framework/issues/6141

PRs:
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/6781 (changelog notes)
 - [ ] https://github.com/silverstripe/silverstripe-cms/pull/1783 (new code)
 - [x] https://github.com/silverstripe/silverstripe-admin/pull/19 (removed code)
 - [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/418 (routing in react section)
 
 
Note: tim has been working on a 3.x fix at #1784

**Comment by chillu** [comment]
Form submissions will be the main issue here - the proposed URL change now has two `$Action` params: `show` and `EditForm`. We can probably work around this through a custom `handleAction()` implementation which pops off `show/11` and sets the current page as `urlParams['ID']` (or another logic path in `LeftAndMain->currentPageID()`.

**Comment by tractorcow** [comment]
It should be fine to have nested actions, as the request url should be shifted as it's passed down the chain of controllers. Each controller at any level should have its own url_handlers with the ability to overwrite any parameters for that request.

**Comment by tractorcow** [comment]
I've fixed in various modules and added links to each in the initial comment.
