### ISSUE TITLE
Site tree scroll to selected page doesn't work (previously was overshooting/undershooting with large trees)

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#1511]
With large trees, if you select an item and the page reloads to go that page for editing the site tree also reloads but the selected item is not in current view anymore and overshoots it.

The desired behaviour is that the currently selected CMS page is visible in the pages list when initially loaded.

### PR
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2591

**Comment by hoKRa1** [comment]
Is this still an issue?

**Comment by clarkepaul** [comment]
This is no longer the issue but a new one, in v4 the sitetree does not scroll down to the selected page anymore at all from my test. Will update title of issue.

**Comment by maxime-rainville** [comment]
Fixed by https://github.com/silverstripe/silverstripe-cms/pull/2591
