### ISSUE TITLE
[master] Settings tab marked selected when it isn't.

### ISSUE THREAD

**Issue by mikenz** [silverstripe/silverstripe-cms#1516]
When on the Content tab, make changes to a field, do not save these changes.

Click the Settings tab, you will receive a 'WARNING: Your changes have not been saved". Click "Cancel" to stay on the current page. 

"Settings" is now incorrectly marked as the active tab, the page still correctly displays the "Content" tab.

**Comment by tractorcow** [comment]
I've seen this bug affect other sections. E.g. security admin.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/6122
