### ISSUE TITLE
Modeladmin: Filters don't show up

### ISSUE THREAD

**Issue by sonet** [silverstripe/silverstripe-cms#1523]
Modeladmin: Filters don't show up since 3.3.x They are working in 3.2.4.

**Comment by kinglozzer** [comment]
@sonet The CSS and JavaScript behind this has changed, so the first thing I’d try is clearing your browser cache. If that doesn’t help, can you check that you don’t have any modules that interfere with that template? E.g. the catalogue-manager module (see https://github.com/silverstripe/silverstripe-cms/issues/1427)

**Comment by sonet** [comment]
@kinglozzer I am using a clean base setup with no modules (other than the standard reports, siteconfig, and postgresql).

**Comment by kinglozzer** [comment]
@sonet Do you get any errors? Can you check if the HTML markup for the search form (highlighted below) is there in your web inspector? Thanks!

<img width="1856" alt="screen shot 2016-06-10 at 16 39 33" src="https://cloud.githubusercontent.com/assets/1655548/15969940/15d24a46-2f2a-11e6-8bae-e8320eaa82b3.png">

**Comment by sonet** [comment]
@kinglozzer The div is there but it has a display: none; No errors.

**Comment by dhensby** [comment]
You need to click the search icon to get them to show?

**Comment by sonet** [comment]
That's helpful. Thanks.
