### ISSUE TITLE
Readonly mode for CMS

### ISSUE THREAD

**Issue by marcello-silverstripe** [silverstripe/silverstripe-cms#1528]
## Acceptance criteria

 * When SilverStripe is in readonly mode (see https://github.com/silverstripe/silverstripe-framework/issues/5693), the CMS shows a warning message.
 * All views in the CMS are readonly - it's as if you've logged in as someone with no edit rights.
 * Some minor UI weirdness is tolerable.

Nice to have:

 * If the server is set to readonly mode while you have the site open, you should see a warning that the site has gone to readonly mode and you should copy any unsaved changes to another document. If possible, this only needs to work if "Security ping" is enabled.
 * If the server is set back from readonly mode while you have the site open, you should see a notification that they should reload the CMS and it's available again. If possible, this only needs to work if "Security ping" is enabled.

**Comment by tractorcow** [comment]
Tracked at https://github.com/silverstripe/silverstripe-framework/issues/5693, so closing this dupe.
