### ISSUE TITLE
On a SiteTree item with canEdit() & canView() both false, right-click to Edit triggers an error

### ISSUE THREAD

**Issue by colintucker** [silverstripe/silverstripe-cms#1529]
Playing with permissions today I noticed that if I have a SiteTree object with both canEdit() and canView() returning false, I can still right-click on the greyed-out item in the tree, and choose "Edit" from the context menu.  This will then trigger an error in CMSMain_Content.ss, as it tries to obtain the EditForm, and receives an SS_HTTPResponse object.  Full stack trace provided below:

<pre>
ERROR [Recoverable Error]: Object of class SS_HTTPResponse could not be converted to string
IN GET /admin/pages/edit/show/9
Line 133 in C:\Windows\Temp\path\user\.cache.cms.templates.Includes.CMSMain_Content.ss

Source
======
  124:  </div>
  125: 
  126:  ';
  127: 
  128: $val .= $scope->locally()->XML_val('Tools', null, true);
  129: $val .= '
  130: 
  131:  ';
  132: 
* 133: $val .= $scope->locally()->XML_val('EditForm', null, true);
  134: $val .= '
  135: 
  136: </div>
  137: ';
  138: 

Trace
=====
include(C:\Windows\Temp\path\user\.cache.cms.templates.Includes.CMSMain_Content.ss)
SSViewer.php:1064

SSViewer->includeGeneratedTemplate(C:\Windows\TEMP\path\user/.cache.cms.templates.Includes.CMSMain_Content.ss,CMSPageEditController,,Array,)
SSViewer.php:1126

SSViewer->process(CMSPageEditController,)
ViewableData.php:360

ViewableData->renderWith(Array)
LeftAndMain.php:596

LeftAndMain->{closure}()

call_user_func(Closure)
PjaxResponseNegotiator.php:89

PjaxResponseNegotiator->respond(SS_HTTPRequest)
LeftAndMain.php:579

LeftAndMain->show(SS_HTTPRequest)
RequestHandler.php:288

RequestHandler->handleAction(SS_HTTPRequest,show)
Controller.php:202

Controller->handleAction(SS_HTTPRequest,show)
RequestHandler.php:200

RequestHandler->handleRequest(SS_HTTPRequest,DataModel)
Controller.php:158

Controller->handleRequest(SS_HTTPRequest,DataModel)
LeftAndMain.php:451

LeftAndMain->handleRequest(SS_HTTPRequest,DataModel)
AdminRootController.php:92

AdminRootController->handleRequest(SS_HTTPRequest,DataModel)
Director.php:385

Director::handleRequest(SS_HTTPRequest,Session,DataModel)
Director.php:149

Director::direct(/admin/pages/edit/show/9,DataModel)
main.php:188
</pre>

Should we be disabling/hiding the Edit option on the context menu?  Or handling the EditForm returned value differently?

**Comment by tractorcow** [comment]
Maybe we could change CMSMain::getEditForm so that canView failure returns null for the result rather than an SS_HTTPResponse.

```php
if($record && !$record->canView()) {
	Security::permissionFailure($this);
	return null;
}
```

That SHOULD still show the error and redirect in the response.

We should also hide edit button in the context menu if canEdit is false.

**Comment by dhensby** [comment]
I've had a look into this and it's uncovered a few issues in the CMS as far as I can see.

Here's what I've got so far

[ ] Only add the edit context menu item if the item can be edited - https://github.com/silverstripe/silverstripe-cms/blob/5f2d8cae0d3da9f4bef13d7240aed9e07cae1099/javascript/CMSMain.Tree.js#L42-L51
[ ] Fix SiteTree to add correct class to node if canEdit is false - https://github.com/silverstripe/silverstripe-cms/blob/5f2d8cae0d3da9f4bef13d7240aed9e07cae1099/code/model/SiteTree.php#L2903-L2933
  [ ] Fix CSS issues that come of this (they take a disabled state instead even though they can be viewed if you use the edit-disabled)

**Comment by colintucker** [comment]
Hmm, small can of worms I've opened? 😄 Thanks very much guys for looking into this!

**Comment by dhensby** [comment]
hmm, and my tests were with `canEdit` false only

**Comment by tractorcow** [comment]
I'm sure I recall merging some change that affected this... wish I could remember where it was. :P

**Comment by dhensby** [comment]
There's been a recent change that means the context menu changes the first option from "edit" to "view" when `canEdit` is false, but that doesn't really fix this bug (or the issues I've found in my testing)

**Comment by tractorcow** [comment]
Ah here it is https://github.com/silverstripe/silverstripe-cms/pull/1537

**Comment by dhensby** [comment]
So that fixes my first of 3 items

**Comment by maxime-rainville** [comment]
Can't replicate this in SS4.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
