### ISSUE TITLE
ModelAdmin Filter does not display

### ISSUE THREAD

**Issue by asecondwill** [silverstripe/silverstripe-cms#1535]
I upgraded to SS 3.4 this week.  Unfortunately the Filter panel does not display in the middle column for ModelAdmin 

I added the following code for our site to fix that:

````
.ModelAdmin .cms-content-filters{
    display: block;
    left: 0;
    margin: 0;
    width: 300px;
}
.ModelAdmin .cms-content-fields .cms-edit-form{
    left: auto !important;
    right: 0;
    width: 85% !important;
}
.ModelAdmin .cms-content-filters .field{
    width: 70%;
    display: block;
}
@media (max-width: 1300px) {
   .ModelAdmin .cms-content-filters .field{
        width: 50%;
    } 
    
    .ModelAdmin .cms-content-fields .cms-edit-form{
        width: 80% !important;
    }
}
````

**Comment by asecondwill** [comment]
quite a bit bug isn't it for a stable release?

**Comment by asecondwill** [comment]
it's not showing up in our model admins, but i've just installed a fresh instance of SS and created a model admin and it's there just like the pages.  So i guess our code clashed with the update.  Ill look into why today.

**Comment by stevie-mayhew** [comment]
Cool, I'll close this and if you discover anything else let us know and we can reopen if it is an issue 😄
