### ISSUE TITLE
[ORM] SiteTree Sort values copied directly to _Live

### ISSUE THREAD

**Issue by frankmullenger** [silverstripe/silverstripe-cms#1544]
Whenever a page is published the sort order for the sibling pages is published also:
https://github.com/silverstripe/silverstripe-cms/blob/master/code/model/SiteTree.php#L2246

Which leads to issues such as reordering the site tree in draft then publishing one of the sibling pages of the portion of the tree that was reordered.

Discussing with @tractorcow the Sort values could perhaps be a change set that is versioned and published independently. Or perhaps using a float for the Sort value so that pages could be reordered without necessarily a change of the Sort values in other sibling pages.

**Comment by tractorcow** [comment]
Related to https://github.com/silverstripe/silverstripe-framework/issues/5800

**Comment by chillu** [comment]
Going to close this in favour of https://github.com/silverstripe/silverstripe-versioned/issues/180
