### ISSUE TITLE
UI Issue in Account Application

### ISSUE THREAD

**Issue by thomasbiddle** [silverstripe/silverstripe-cms#1545]
**Issue:** When adding an account to verify Identity, it's "Revoke X" is sometimes incorrect. 

**Example:** Will show "Revoke Google" on the LinkedIn button.

**Reproduce:** Connect your Google account. Revoke your Google account. Connected your LinkedIn account. LinkedIn button will now say "Revoke Google".

Link to image: [Imgur](http://i.imgur.com/6A7lkFc.png)

**Comment by micmania1** [comment]
@thomasbiddle this isn't built-in functionality. The issue is probably related to an installed module or custom code.
