### ISSUE TITLE
"Add new page here" shows HiddenClass records

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-cms#1553]
**SS/CMS:** 3.4.0
**Blog:** 2.4.0

When I "Add New", I get a list of Page Types that is Page, Blog and BlogPost.

I've extended the VirtualPage, ErrorPage and RedirectorPage classes with DisabledVirtualPage etc which `implements HiddenClass`. They do **not** show up in the list when I click "Add New".

However, if I right click on an existing page in the site tree and hover over "Add new page here", those page types **are** shown.

I suggest that wherever these page types are loaded from should be the same logic as the main add new page.

**Comment by dhensby** [comment]
Good spot - thanks
