### ISSUE TITLE
Insert link into page form requires a layout tidy up

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#1561]
Based on the newly integrated bootstrap forms the layout of the "insert link" into TinyMCE requires a bit of a tidy up. 

Also "Step 1" where you can select the type of link is completely missing from the UI.
3.x:
![image](https://cloud.githubusercontent.com/assets/555033/17090886/0d8ba2c4-5289-11e6-8eb1-285319f0ad76.png)

4.0:
![image](https://cloud.githubusercontent.com/assets/555033/17090893/1b3de044-5289-11e6-8cda-045b1c3ffb9f.png)

**Comment by clarkepaul** [comment]
PR https://github.com/silverstripe/silverstripe-framework/pull/5945

**Comment by tractorcow** [comment]
Merged.
