### ISSUE TITLE
Namespace CMS

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-cms#1572]
See epic link: https://github.com/silverstripe/silverstripe-framework/issues/4562

Dependency PRs (can be merged up front safely).
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/5881
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/5873
 - [x] silverstripe/silverstripe-cms: https://github.com/silverstripe/silverstripe-cms/pull/1571
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/5874
 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/214
 - [x] https://github.com/silverstripe-labs/silverstripe-behat-extension/pull/122
 
 
Once these are merged the main PR are at:
 - [x] https://github.com/silverstripe/silverstripe-postgresql/pull/53
 - [x] https://github.com/silverstripe-labs/silverstripe-sqlite3/pull/24
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/5875
 - [x] silverstripe/silverstripe-cms: https://github.com/silverstripe/silverstripe-cms/pull/1574
 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/213
 - [x] https://github.com/silverstripe/silverstripe-installer/pull/130
 - [x] https://github.com/silverstripe/silverstripe-siteconfig/pull/34
 - [x] https://github.com/silverstripe-labs/silverstripe-reports/pull/42

**Comment by tractorcow** [comment]
Framework behat tests:

![image](https://cloud.githubusercontent.com/assets/936064/17471087/a383e752-5d95-11e6-9351-fd5fc7e81f70.png)

**Comment by tractorcow** [comment]
Er, don't merge yet... there's a bug in `# cms/tests/behat/features/manage-page-permissions.feature:14` that needs fixing.

**Comment by tractorcow** [comment]
Also `# cms/tests/behat/features/search-for-a-page.feature:20`

**Comment by tractorcow** [comment]
Also `# cms/tests/behat/features/publish-a-page.feature:56`

**Comment by tractorcow** [comment]
Ack, caused by https://github.com/silverstripe/silverstripe-asset-admin/pull/214

**Comment by tractorcow** [comment]
![image](https://cloud.githubusercontent.com/assets/936064/17502553/0442fc52-5e3d-11e6-9c3a-27c43cf6a5ce.png)

Yay green cms tests. :)

**Comment by tractorcow** [comment]
Ok, I've locally tested all tests (phpunit and behat) for all modules, and all are green.

**Comment by dhensby** [comment]
All PRs merged
