### ISSUE TITLE
Insert external link into page breaks https links

### ISSUE THREAD

**Issue by DShumkov** [silverstripe/silverstripe-cms#1577]
If you're trying to insert link like 'https://example.com/something' that cuts to 'something'

**Comment by tractorcow** [comment]
@DShumkov which cms version are you testing this on?

**Comment by DShumkov** [comment]
@tractorcow info from composer:

> "name": "silverstripe/cms",
            "version": "3.4.0",

>         "reference": "1ea9444be9901abcac58c56c22d0d5c1ebb5e5b2"

**Comment by tractorcow** [comment]
Thanks. :)

**Comment by tractorcow** [comment]
Oh, is this a link to a page on the same domain your site is hosted?

**Comment by DShumkov** [comment]
Yes and no. There's multidomain set so it's an external link to another domain but both domains on the same instance of Silverstripe.

**Comment by dhensby** [comment]
I think this is a `TinyMCE` issue that I've spent a great deal of time investigating - I couldn't find a way to turn it off and basically TinyMCE is just being too clever for it's own good.

Is it a problem in 4.0?

**Comment by tractorcow** [comment]
@DShumkov do you mind checking it out on ss 4.0 (dev-master) and letting us know if it's still broken?

**Comment by hoKRa1** [comment]
Is this issue still existent on dev-master?

**Comment by chillu** [comment]
Just tried this in recipe 4.4.1, no longer the case.
