### ISSUE TITLE
Save / Publish buttons regression, are no longer grouped and don't float left

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#1581]
After the form restructuring the main page actions are now displaying in the wrong order, and no longer grouped together.

**Comment by clarkepaul** [comment]
![image](https://cloud.githubusercontent.com/assets/555033/18190323/1ce8257a-7116-11e6-949b-32ca3ce9d966.png)

**Comment by chillu** [comment]
Please also fix alignment as part of this

![image](https://cloud.githubusercontent.com/assets/111025/18190324/1e8f7400-7116-11e6-994e-01f56584e7c3.png)

**Comment by clarkepaul** [comment]
Had a go at this but couldn't figure it out.

**Comment by tractorcow** [comment]
I'm looking into it. :D

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/6036

**Comment by clarkepaul** [comment]
Looks good and test in IE, awaiting merge
