### ISSUE TITLE
DOCS changelog for 3.4.1 missing

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-cms#1582]
The URL to the release notes on the download page points to http://doc.silverstripe.org/en/3.4/changelogs/3.4.1 which is returning a 404

**Comment by christopherdarling** [comment]
Found the 3.4.1 docs on github, noticed that it was missing one of the commits I was keeping an eye out for i.e. https://github.com/silverstripe/silverstripe-framework/commits/3.4/admin/code/LeftAndMain.php

af3412a4c2f3088f5647df0e366b9e1b6c41faa4
```
Merge pull request #5340 from dnadesign/fixToGridFieldLoadingWrongCur… …
…rentPage

fix to grid field loading wrong current page id when using multiple tabs
dhensby committed on GitHub 13 days ago 
```

**Comment by tractorcow** [comment]
The issue with that commit will be avoided in the future; Addressed with https://github.com/silverstripe/cow/pull/18
