### ISSUE TITLE
Moved issue

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-cms#1584]
Note: Please make sure any security-related issues you disclose are sent to security@silverstripe.com rather than posted on the public issue tracker. :) (@tractorcow)

**Comment by robbieaverill** [comment]
Thanks @tractorcow, sorry for logging it here :) R

**Comment by tractorcow** [comment]
Na that's ok mate. Probably not a security concern, but still needs to be addressed properly. Ping me on the security list and we'll move discussion there.
