### ISSUE TITLE
Page Duplication

### ISSUE THREAD

**Issue by nglasl** [silverstripe/silverstripe-cms#1588]
I noticed an interesting bug on a 3.2 instance today, and thought I would raise it for public visibility. I've included some steps below on how it can be replicated.

![1](https://cloud.githubusercontent.com/assets/3703500/17919076/d4dbd786-6a0d-11e6-8178-94f8471bfa3c.png)

This is my page. When I attempt to move it somewhere it shouldn't be, I get the following validation error, which is what I expect :)

![2](https://cloud.githubusercontent.com/assets/3703500/17919082/ddc8ba1c-6a0d-11e6-82ce-ccf0153cff51.png)

However, if you look closely, you'll notice that each move attempt creates a copy in the DOM. This isn't really a problem, because they'll be hidden from view. **That is, until you attempt to move the page to the parent it is already under.**

![3](https://cloud.githubusercontent.com/assets/3703500/17919090/f3f58edc-6a0d-11e6-884c-0300f9fac0d4.png)

The good news is that these pages don't actually get created, and will disappear when reloading the CMS. Therefore, the bug likely exists somewhere in JS. It's possible there are other ways to trigger the same bug, however it should at least prevent me from dragging the page to the parent it is already under.

**Comment by nglasl** [comment]
Confirming this remains an issue in SS4. Can you please update the labels?

**Comment by dhensby** [comment]
@chillu do we want to address this for 4.1.0?

**Comment by nglasl** [comment]
Agree, this bug is really minor (and is pretty much an obscure edge case). If the greater picture is to move the site tree over to React, then I'm more than happy for this issue to be closed.

**Comment by nglasl** [comment]
Based on the above, I'm going to close this for now. Thanks for your input everyone!
