### ISSUE TITLE
"insert media" styling regressions in 4.0

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-cms#1591]
Since we're not planning to do the asset-admin powered "insert media" panel (https://github.com/silverstripe/silverstripe-asset-admin/issues/173) until the beta phase, it would be good to clean this up at least a bit - right @clarkepaul?

![image](https://cloud.githubusercontent.com/assets/111025/18162182/52e45a6e-7089-11e6-80af-51c0f6bccf0b.png)

![image](https://cloud.githubusercontent.com/assets/111025/18162216/770c59dc-7089-11e6-98b9-e1a4315efeaf.png)

**Comment by flamerohr** [comment]
I've left comments in the Pull request, one question and one bug found

**Comment by clarkepaul** [comment]
PR ready for review
