### ISSUE TITLE
URL segment edit action has additional space for icon but not wanted

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#1592]
The buttons really need to be updated to Bootstrap styles. 
![image](https://cloud.githubusercontent.com/assets/555033/18190057/b76319aa-7113-11e6-9099-e2e3cc52159d.png)

**Comment by HboyVinod** [comment]
I believe that this issue has been fixed on both Firefox 50.1.0 and Chromium 55.0.2883.87.

**Comment by clarkepaul** [comment]
No longer an issue in SS4
