### ISSUE TITLE
"More options" is in wrong order, with misaligned text and icon

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-cms#1594]
![image](https://cloud.githubusercontent.com/assets/111025/18190289/b5a7ece2-7115-11e6-9793-27c616a491c1.png)

**Comment by clarkepaul** [comment]
I think this is duplicate.

**Comment by clarkepaul** [comment]
Duplicate of https://github.com/silverstripe/silverstripe-cms/issues/1581
