### ISSUE TITLE
MINOR - Cosmetic - 3.3, 3.4 - misaligned spinner on "Sync files" in Files

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-cms#1595]

**Comment by dhensby** [comment]
@SpiritLevel can we get a screen shot, before/after type thing so this is a bit clearer?

**Comment by SpiritLevel** [comment]
Here we go :) The spinner is just a few pixels out of alignment to the left relative to the static circle with arrows. So, when the spinner is spinning, the static circle is still visible, particularly the arrows.
![screenshot from 2016-09-03 08 09 19](https://cloud.githubusercontent.com/assets/8912185/18217009/7ebb80f6-71ae-11e6-81df-34eb754a9ca3.png)
![screenshot from 2016-09-03 08 10 08](https://cloud.githubusercontent.com/assets/8912185/18217010/7ebb7908-71ae-11e6-9954-0692cba28257.png)

**Comment by chillu** [comment]
This feature has been removed from 4.x
