### ISSUE TITLE
After login when session expires, user isn't directed to destination.

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-cms#1609]
If a user's session expires and they attempt to navigate within the CMS (which uses PJAX to load new content), the URL in the address bar will change and then an interstitial login modal is displayed requiring the user to login again. If they login, they do not proceed, but the URL is still changed.

I propose retaining the existing functionality (i.e. URL change, then interstitial) since that is useful in case they decide to reload. However, I think this should be augmented to persist the user's action (possibly resubmit the same PJAX request somehow?) depending on what is happening after they've logged in successfully.

Any thoughts on this?

**Comment by maxime-rainville** [comment]
This is still an issue in SS4.

**Comment by patricknelson** [comment]
Hello from the future! This issue is like >5yrs old but I'm wondering: Does this now belong in https://github.com/silverstripe/silverstripe-admin? 

Also, I'm considering instead submitting a new bug there to just set this up so that if there's a login error, it just doesn't update the URL. Upon successful login (a **_separate_** issue/task) it should then either redirect or simply update the current page's security token (that'd be a long discussion in itself). But better than losing your work...

**Comment by patricknelson** [comment]
I'll close this issue and reopen a related one on the `silverstripe-admin` project instead.  The reason why is because after reviewing the underlying legacy code in `LeftAndMain.js`, it appears that a more important problem (which is related and would block this approach) is the fact that the CMS always updates the URL via `history.pushState()` even if the server-side request fails: https://github.com/silverstripe/silverstripe-admin/issues/1279

So, a quicker and more pragmatic approach to solving _this_ problem would probably be to:

1. First, ensure the URL properly reflects the current page state
2. And then, **separately**, consider the possibility of persisting the users' last action

That second point is something I think not ultimately make sense, so I'll abandon that idea for now and instead just pursue fixing the mixed/buggy UI state that occurs when the server responds with an HTTP error of some sort (see the issue above).
