### ISSUE TITLE
Search form template name includes name space

### ISSUE THREAD

**Issue by pandauxstudio** [silverstripe/silverstripe-cms#1620]
When loading search,, I get the following error:
`[User Warning] None of the following templates could be found: Array ( [0] => SilverStripe\CMS\Search\SearchForm [1] => SilverStripe\Forms\Form ) in themes "Array ( [0] => myThemeName [1] => $default ) "`

Resolved this by creating an override template:
`~/project/themes/projectTheme/templates/SilverStripe/Forms/Form.ss`

Also had to override form attributes in new template from:

`<form $FormAttributes>`

To:

`<form id="SearchForm" action="/home/SearchForm" method="get" enctype="application/x-www-form-urlencoded" class="ng-pristine ng-valid">`

As ID and action included name space.
Also, no indication in docs (https://docs.silverstripe.org/en/4.0/tutorials/site_search/) of a different way of enabling basic full text search.

**Comment by pandauxstudio** [comment]
Issue maybe fixed here:
https://github.com/silverstripe/silverstripe-cms/blob/master/code/Search/SearchForm.php#L89-L92

**Comment by sminnee** [comment]
Namespaces are part of SS4, so this isn't a bug, but the docs need updating.

**Comment by sminnee** [comment]
Sorry, I misunderstood the original bug report.

I can't replicate this in the current master branch. We're releasing 4.0.0-alpha2 very soon, can you see if this works there?

**Comment by pandauxstudio** [comment]
@sminnee yes you're right latest build (4.0.0-alpha2) fixed my issue thanks.
I ended up getting rid of my template override (~/templates/SilverStripe/CMS/Search/SearchForm.ss) which is great.
