### ISSUE TITLE
Div around URL segment needs to take up full width to accommodate actions

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#1624]
If .form__field-holder extended the full width of the edit page panel then the actions wouldn't wrap at certain sizes. Buttons also have margin top which isn't needed.

![image](https://cloud.githubusercontent.com/assets/555033/18735950/20736c3e-80d6-11e6-8f4a-768f2fd2d417.png)

**Comment by wilr** [comment]
Fixed in ui branch.
