### ISSUE TITLE
URL segment loading indicator position in the wrong place

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#1625]
Wasn't quick enough to get a screenshot of it but edit the page name and click outside of the input to see indicator.
![pasted_image_22_09_16__3_20_pm](https://cloud.githubusercontent.com/assets/555033/18736167/9b302a3c-80d8-11e6-8137-9883995e3403.png)

**Comment by hoKRa1** [comment]
Hi Paul,

Just wondering if you had any visual indicators that could perhaps show where the loading indicator is supposed to be positioned. 

Thanks

**Comment by clarkepaul** [comment]
It would be okay to use the existing gif for this issue I would think. I will update all the icons to font-icons at some stage but we don't have a spinning font-icon loading indicator yet.

Old loading gif is here cms/client/dist/images/loading.gif
And it used to appear just before the URL/input I think.
![pasted_image_18_01_17__1_00_pm](https://cloud.githubusercontent.com/assets/555033/22045292/3339dd76-dd7e-11e6-8354-e40ce3c03711.png)

**Comment by chillu** [comment]
Pointer for how to fix this: This is in `admin/pages`, and Entwine logic (not React). Check `SiteTreeURLSegmentField.js`

**Comment by clarkepaul** [comment]
Still an issue and now smaller screen sizes need to also be considered.
