### ISSUE TITLE
Archived and deleted pages still have the option to add to campaign

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#1626]
User is presented with empty Add to campaign modal
<img width="1440" alt="skitch 3" src="https://cloud.githubusercontent.com/assets/555033/18736807/ea0ea1d2-80de-11e6-9bd4-6036c3d02764.png">

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-cms/pull/1667
