### ISSUE TITLE
Insert media from folder other than Uploads shows as empty

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#1627]
Even if there are images within the folders other than Uploads folder it modal returns an empty folder.
![image](https://cloud.githubusercontent.com/assets/555033/18737151/3945a7de-80e2-11e6-8f7b-105036be216a.png)

**Comment by tractorcow** [comment]
Tested and found to be not an issue.

I fixed another issue while I was there though; https://github.com/silverstripe/silverstripe-framework/pull/6234
