### ISSUE TITLE
Search on TreeDropdownField with Array as a $sourceObject doesn't work.

### ISSUE THREAD

**Issue by diegopego86** [silverstripe/silverstripe-cms#1628]
If added this to my Page:

$fields->addFieldToTab('Root.Articles', $myField = new TreeDropdownField('Article1ID', 'Article 1', ArticlePage::get()->map('ID', 'Title')->toArray(),'ID','Title', true));

The TreeDropdwnField loads correctly but the search box doesn't filter the results. Do we need to do something else? Is there any documentation for this?

Thanks

**Comment by dhensby** [comment]
You'll need to create your own filter function and bind it to the `TreeDropdownField` using `setSearchFunction`

The `TreeDropDown` doesn't accept `array` as an object as standard for searching against
