### ISSUE TITLE
RedirectorPage: using $AbsoluteLink breaks external link

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-cms#1630]
When i try to use $AbsoluteLink on a RedirectorPage's external link i get a funny mixture of the external link with my current domain injected.

e.g. 

externalLink: https://twitter.com/myTwitterHandle

my domain: http://mydomain/

result:

https://mydomain/myTwitterHandle

**Comment by robbieaverill** [comment]
@wernerkrauss - I think you should be using `$Link` for RedirectorPage instance - it factors in the mechanisms for links that it supports naturally. [See here](https://github.com/silverstripe/silverstripe-cms/blob/3.4/code/model/RedirectorPage.php#L40-L49).

**Comment by dhensby** [comment]
> @wernerkrauss - I think you should be using `$Link` for `RedirectorPage` instance - it factors in the mechanisms for links that it supports naturally. [See here](https://github.com/silverstripe/silverstripe-cms/blob/3.4/code/model/RedirectorPage.php#L40-L49).

But if you want the absolute link (or you have a generic template that doesn't need or want to know about the page type then using `$AbsoluteLink` shouldn't break...

This definitely sounds like an oversight and bug to me

**Comment by dhensby** [comment]
@wernerkrauss are you sure this bug is as you describe. from what I can see an external link would start with `http` and so `Director::makeAbsolute()` would not mangle it.

It probably would if the external url was `twitter.com/handle` instead of `http(s)://twitter.com/handle`...

**Comment by dhensby** [comment]
OK, I've tested locally and can't replicate this. `$AbsoluteLink` in the context of a `RedirectorPage` works as expected.
