### ISSUE TITLE
SiteTree start from SiteConfig should open the SiteConfig Settings

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-cms#1642]
For a consistent experience, the root of the SiteTree, which is the SiteConfig, selecting it should open the settings.
Maybe as part of the SiteTree, but simply open the Settings tab would improve user experience a lot.

**Comment by Firesphere** [comment]
Within permission limit, of course

**Comment by dhensby** [comment]
If you click the site root and the tab changes I think that's pretty confusing and unexpected behaviour for a user... Is that what you're suggesting?

**Comment by robbieaverill** [comment]
Which version was this? I'm not sure where a SiteConfig sits in the site tree in SS4, other than the site name which isn't clickable
