### ISSUE TITLE
Show unpublished versions checkbox doesn't work in history

### ISSUE THREAD

**Issue by ewweaver** [silverstripe/silverstripe-cms#1648]
Occurs in master.

The checkbox to show unpublished versions no longer works in the history tab.

You can still view the unpublished versions by going direct to the URL of that version number.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-cms/pull/1930

**Comment by tractorcow** [comment]
Fixed, thanks. :)
