### ISSUE TITLE
UploadField Preview thumbnail URL references original image

### ISSUE THREAD

**Issue by camexapps** [silverstripe/silverstripe-cms#1652]
Hi guys,

Just wondering, in regards to the UploadField for an image. Why the preview image file itself is referencing the original image. This has probably been mentioned before? And this is possibly the expected behaviour? I thought it would of referenced something like a generated CMS Thumbnail URL as apposed to the original file?

Seems to significantly slow the admin side down, especially if there are page types with many images attached to them.

We don't have to create a CMS Thumbnail method for this do we?

Any thoughts? 

Sorry in advance if this has been discussed!

**Comment by dhensby** [comment]
I can't reproduce this on 3.4.x-dev - what version of CMS are you using?

**Comment by camexapps** [comment]
OK, I think this is my bad, looks like I have a 3rd party module (one of the Image Responsive modules) with extends the original image class, which I believe is doing this.

You can close this 'issue'.

Sorry!
