### ISSUE TITLE
The tab for list view no longer works

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#1654]
Clicking on the list view icon in the toolbar of Pages doesn't take you to the the list view of the sitetree.

![pasted_image_20_10_16__2_54_pm](https://cloud.githubusercontent.com/assets/555033/19543586/20c5c244-96d5-11e6-837c-73817f240316.png)

**Comment by jaylou** [comment]
I couldn't replicate this with Silverstripe v4 alpha 3, in Chromium 55.0.2883.87 on Ubuntu 16.04 (64-bit). From both the tree view and the tree view with the edit window, it took me to a list view of all the pages.

**Comment by clarkepaul** [comment]
No longer an issue
