### ISSUE TITLE
Menu behaves different on Page history than it does for Page settings and Page edit at certain width

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#1657]
At a browser resolution of around 1350px when you navigate between the Page settings, edit, and history tabs you will see that the menu expands on the history tab. The menu width should behave the same for all tabs.
![pasted_image_21_10_16__10_20_am](https://cloud.githubusercontent.com/assets/555033/19578415/0ad3bf2e-9778-11e6-8c04-febf806bc1fb.png)

![pasted_image_21_10_16__10_20_am](https://cloud.githubusercontent.com/assets/555033/19578400/03359814-9778-11e6-9da7-69547dcb5491.png)

**Comment by hoKRa1** [comment]
Hi Paul,

When navigating between the Content, Settings and History tabs, would you like the menu to consistently expand or not expand and just display the icons (not words)?

**Comment by clarkepaul** [comment]
Yup exactly. The pattern I am wanting to establish is that when the user is three panels deep within the CMS then the navigation collapses allowing more space for the panel they are working within (if the navigation hasn't been put in fixed mode). This pattern isn't consistent throughout the whole CMS yet but I am hoping we can at least have it consistent within the Pages area because that area has the potential of yet another panel (Preview panel) with a total of 4 panels. Hopefully this would help with the CMS be more usable on smaller devices.

**Comment by clarkepaul** [comment]
It makes sense to prioritise https://github.com/silverstripe/silverstripe-cms/issues/1493 ahead of this issue.

**Comment by clarkepaul** [comment]
The history section for pages and other content types is currently being rebuilt, this issue should hopefully be resolved through that work. Keeping the issue just as a double check it gets resolved though.
Related https://app.zenhub.com/workspace/o/silverstripe/silverstripe-framework/issues/7815

**Comment by robbieaverill** [comment]
It looks good to me now @clarkepaul on SS 4.3.x-dev, feel free to reopen if you disagree
