### ISSUE TITLE
save buttons not visible in firefox on osx

### ISSUE THREAD

**Issue by guyvanbael** [silverstripe/silverstripe-cms#1659]
Just installed the latest version dev-master. save buttons are not visible in firefox
Can't save pages in firefox on osx. It does work in Chrome though.
![chrome](https://cloud.githubusercontent.com/assets/3098809/19591921/b6b4394e-9779-11e6-94e7-95eccaece2dc.png)
![firefox](https://cloud.githubusercontent.com/assets/3098809/19591922/b6b58cc2-9779-11e6-9fa7-0b591d9221a9.png)

**Comment by kinglozzer** [comment]
Fix is here https://github.com/silverstripe/silverstripe-cms/pull/1647

**Comment by ewweaver** [comment]
This was fixed in #1669
