### ISSUE TITLE
maincontent tab is gone, can't display added fields in cms

### ISSUE THREAD

**Issue by guyvanbael** [silverstripe/silverstripe-cms#1660]
I installed the dev-master. The maincontent tab is gone (screenshot).
I added fields like this. After dev build, the fields are added, but as soon as i add the getCMSFields function, i get a website error (screenshot 2)

	private static $db = array(
		'FirstName' => 'Text'
	);

	private static $has_one = array(
		'Avatar' => 'Image'
	);
	public function getCMSFields() {
		$fields = parent::getCMSFields();

		$fields->addFieldToTab("Root.Main",new TextField("FirstName","voornaam"));
		$fields->addFieldToTab("Root.Main", new UploadField("Avatar","foto"));

		return $fields;
	}

![maincontent](https://cloud.githubusercontent.com/assets/3098809/19648357/24f31b84-9a02-11e6-90ca-1ca74461d70a.png)

![after adding fields](https://cloud.githubusercontent.com/assets/3098809/19648384/3e15fcb2-9a02-11e6-8702-386bc25e7ca5.png)

**Comment by kinglozzer** [comment]
The tabs are hidden if there is only one - they should show up again when you add a second tab. As for your server error, make sure you enable dev mode so that you can see the actual error message. 

Have you included the appropriate `use` statement for those classes at the start of your PHP file? Remember that classes are namespaced in 4.0:

```php
<?php

use SilverStripe\Forms\TextField;

class MyPage extends Page
{
    public function getCMSFields() {
        $fields = parent::getCMSFields();

        $fields->addFieldToTab('Root.Test', new TextField('Test', 'Test'));

        return $fields;
    }
}
```

**Comment by guyvanbael** [comment]
i added this to my _config.php (like i always do) but somehow it's not working anymore
error_reporting(E_ALL ^ E_NOTICE);
Director::set_environment_type("dev");

**Comment by guyvanbael** [comment]
textfield is ok. do i have to add this for the uploadfield too? It doesn't seem to add my uploadfield
use SilverStripe\Forms\UploadField;

**Comment by guyvanbael** [comment]
i ran the upgrade tool... this is it:
	private static $has_one = array(
		'Avatar' => 'SilverStripe\Assets\Image'
	);
