### ISSUE TITLE
Page history left panel (versions) missing on smaller screens

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#1663]
There is no way to select history versions on smaller screens. Also the tabs start to hide on the far right. Some work has been done as part of improving the responsiveness of the pages area here which would be good to have merged first prior to fixing this issue https://github.com/silverstripe/silverstripe-framework/issues/6164

Desktop:
![pasted_image_25_10_16__2_02_pm](https://cloud.githubusercontent.com/assets/555033/19669444/d0366438-9abb-11e6-9165-7ece4d68f216.png)

Smaller screens:
![pasted_image_25_10_16__2_01_pm](https://cloud.githubusercontent.com/assets/555033/19669415/a2831f4a-9abb-11e6-8702-21deb67b521d.png)

**Comment by tractorcow** [comment]
Seems fixed. :)

**Comment by tractorcow** [comment]
![image](https://cloud.githubusercontent.com/assets/936064/19747832/8839e350-9c3a-11e6-8ec2-b997c3fb3d8d.png)

**Comment by clarkepaul** [comment]
Ah maybe I found this when I was working on the responsive-improvements branch (which will getting merged in soon).

**Comment by sminnee** [comment]
@clarkepaul do you want to fix this in the `responsive-improvements` branch, then?

**Comment by clarkepaul** [comment]
Yup can do if its a quick thing, can reopen if it holds that branch back from getting merged. Can leave closed/fixed. Will make comment on the right issue.
