### ISSUE TITLE
MASTER : CMS->Security->Export to CSV has html showing in label for CSV file

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-cms#1666]
![screenshot from 2016-10-26 16 20 09](https://cloud.githubusercontent.com/assets/8912185/19712229/8f061de0-9b98-11e6-80d3-bb9e817dd8c7.png)

Edit: The above was under the Users tab. It also appears under the Groups tab too.

**Comment by dhensby** [comment]
I think this is fixed now, but I can't find the PR that fixed it...

**Comment by robbieaverill** [comment]
It's fixed in SilverStripe 4.3.x-dev:

![image](https://user-images.githubusercontent.com/5170590/48624828-25112380-e9b6-11e8-993c-90ac243b7e3b.png)

Wherever the PR is, it predates the splitting of framework and admin as far as I can tell =)
