### ISSUE TITLE
setting options for gridfield not working (ss4)

### ISSUE THREAD

**Issue by guyvanbael** [silverstripe/silverstripe-cms#1668]
I added a gridfield to a page.
i added the correct namespaces:

use SilverStripe\Forms\GridField\GridField;
use SilverStripe\Forms\GridField\GridFieldConfig_RecordEditor;

creating the gridfield is no problem, but when i try to use a function from one of the components like in the docs (in this case GridFieldPaginator, but tried GridFieldDataColumns too) i get this website error. The website server has not been able to respond to your request

here's the code:
public function getCMSFields() {
		$fields = parent::getCMSFields();

			$fields->addFieldToTab('Root.guy', new HTMLEditorField("MyTekst","tekstje"));
			$fields->addFieldToTab('Root.guy', $grid = new GridField('Producten', 'Producten', $this->Producten()));
			$config = GridFieldConfig_RecordEditor::create();
			$grid->setConfig($config);
			$items = $config->getComponentByType('GridFieldPaginator');
			$items->setItemsPerPage(2);

		return $fields;
	}

**Comment by kinglozzer** [comment]
You’ll need to use the namespaced class name for the `->getComponentByType()` call too. For example:

```php
$items = $config->getComponentByType('SilverStripe\Forms\GridField\GridFieldPaginator');
```

or alternatively:

```php
use SilverStripe\Forms\GridField\GridFieldPaginator;

// ...

$items = $config->getComponentByType(GridFieldPaginator::class);
```

**Comment by guyvanbael** [comment]
Thanks @kinglozzer! I'm heavily experimenting with ss4 and i must say... i'm running into issues like this quite often. The 4.0 docs doesn't provide this kinda information(yet?)  I hope they will soon

**Comment by kinglozzer** [comment]
It’s difficult to provide upgrade docs for everything, as every class in the framework now has a different name due to namespacing. The upgrade tool [mentioned here](https://docs.silverstripe.org/en/4.0/changelogs/4.0.0/#a-name-upgrading-a-upgrading) should cover most cases automatically, but yes we still need to improve the docs
