### ISSUE TITLE
SS4 MenuTitle always NULL

### ISSUE THREAD

**Issue by guyvanbael** [silverstripe/silverstripe-cms#1670]
Silverstripe SS4 dev master. MenuTitle is not saved to the database.
![menutitle](https://cloud.githubusercontent.com/assets/3098809/19757622/26cec8b2-9c24-11e6-9f71-0e38b6f1c428.png)

**Comment by dhensby** [comment]
Just for anyone stumbling across this issue - if `MenuTitle` == `Title`, then we don't store `MenuTitle` in the DB - that's been the case since SS 2, I believe.
