### ISSUE TITLE
customizing tinymce in SS4

### ISSUE THREAD

**Issue by guyvanbael** [silverstripe/silverstripe-cms#1671]
Tinymce has been considerably stripped down in ss4. I'm trying to put the styles-dropdown back in. I managed to get the dropdown back in, but it doesn't seem to find any classes i defined in my editor.css file. Here's the code:

<?php
use SilverStripe\Forms\HTMLEditor\HTMLEditorConfig;
use SilverStripe\Forms\HTMLEditor\TinyMCEConfig;
global $project;
$project = 'mysite';

global $databaseConfig;
$databaseConfig = array(
	'type' => 'MySQLPDODatabase',
	'server' => 'localhost',
	'username' => 'root',
	'password' => 'root',
	'database' => 'SS_testss4',
	'path' => ''
);
// Set custom TinyMCE configuration
HtmlEditorConfig::get('cms')->addButtonsToLine(2,"styleselect");
//HtmlEditorConfig::get('cms')->enablePlugins("importcss");
HtmlEditorConfig::get('cms')->setOption('content_css', 'mysite/css/editor.css');

**Comment by kinglozzer** [comment]
TinyMCE has been upgraded to version 4 from version 3, so it may be that these options are named something else or the plugins work differently now. We’ve documented that the TinyMCE version has changed (https://docs.silverstripe.org/en/4.0/changelogs/4.0.0/#upgrading-tinymce-to-4-0) , and we link to the TinyMCE migration docs (http://archive.tinymce.com/wiki.php/Tutorial:Migration_guide_from_3.x), but if there’s any way we can improve the docs more then please open a PR (click edit at the bottom of the docs page) :)
