### ISSUE TITLE
TreeMultiselectField shows page title rather than menu title

### ISSUE THREAD

**Issue by hoodweb** [silverstripe/silverstripe-cms#1673]
When using the TreeMultiselectField in the backend, the field shows page titles when SiteTree as the sourceObject. The menutitle may be expected.

**Comment by dhensby** [comment]
Because this is a generic field type and not tightly coupled to the SiteTree object, you'll need to define the label field yourself

NB: this issue should have been filed against framework as that's the repo that contains `TreeMultiselectField`
