### ISSUE TITLE
CMS Toggle floating up on Safari

### ISSUE THREAD

**Issue by nzjoel** [silverstripe/silverstripe-cms#1676]
Issue noticed on 4.0.0 - Alpha 3, using Safari.

The cms-panel-toggle is floating up below the last icon rather than stuck to the bottom of the page.

See screenshot:
![screen shot 2016-11-04 at 3 15 29 pm](https://cloud.githubusercontent.com/assets/1848200/20010853/8c789cfa-a2a1-11e6-9318-094fb18b1924.png)

**Comment by clarkepaul** [comment]
^ PR available
