### ISSUE TITLE
Allow for StudlyCaps controller names

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-cms#1678]
[PSR-1](http://www.php-fig.org/psr/psr-1/) requires controller names be in ```StudlyCaps```. Because SilverStripe has an underscore in the controller name, code bases can't be valid PSR. Interestingly, there are some [modules which have the ability to name controllers in PSR](https://github.com/silverstripe/silverstripe-widgets/blob/0986537be7325373918d63d7c4e34e4d4ef76813/code/model/Widget.php#L266)

Note this change would also require a minor [modification to the framework](https://github.com/silverstripe/silverstripe-framework/blob/c056362b54f0d51880fb4f5dae240a8c9ed1b858/src/View/SSViewer.php#L247).

**Comment by robbieaverill** [comment]
It's worth noting that SS 4 will be adapting PSR style guidelines, but I don't believe there are plans to implement it for SS <= 3.x

**Comment by torleif** [comment]
@robbieaverill hopefully the PSR guidelines will extend to the application code base too. I've created the ability to name ```Controllers``` in PSR using the alpha-2 release to do some testing (but sadly it looks like function has been updated since, so I'll have to create a new function)

**Comment by dhensby** [comment]
I'd say this has been fixed by #1605 because `SiteTree` has a method that is used to generate the controller name (`SiteTree@getControllerName`) so you can override this method to return controllers without `_`.
