### ISSUE TITLE
3.4.1 MINOR Animated gifs stop being animated after resizing. 

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-cms#1681]
I haven't looked into this yet. Just recording it here as a reminder.

To reproduce:
(1) Insert an animated gif into tinyMCE **without making any changes to size**. Then, save and publish.
      The animated gif remains animated, even if its location is altered.
(2)  Insert an animated gif into tinyMCE **and make some changes to size**. Then, save and publish.
      The animated gif is no longer animated.

My guess is the resampling is just using one frame of the animated gif for resizing.

**Comment by kinglozzer** [comment]
I think this is a limitation of GD - not sure about ImageMagick. In theory it’s possible (IIRC, you have to split it frame-by-frame, resize each frame and then stitch it back together), perhaps there’s another library we could use instead of rolling our own which does support this?

**Comment by dhensby** [comment]
I'm going to close this as a feature request rather than a bug - I don't think we make any promises to support animated gifs when resizing.

I'm happy to take a PR to add it, though :)

**Comment by SpiritLevel** [comment]
Yes, but this feature would provide a large visual impact, impressing both the CMS user and the developer (a marketing thing). I know that when I first pulled an animated gif into the CMS, and it worked in both tinyMCE and the preview pane, a smile came across my face :smiley:...if I were also able, as a developer, to use all the other `Image` methods on animated gifs, it would please me greatly...I'll have a quick look for a library...even if there isn't a library to do this, rolling our own seems simple enough, as Loz says:

```php
if( multi-frame image) {
    separate frames
    apply Image::method() to each frame
    re-combine frames
} else {
    apply Image::method() to image
}
```

**Comment by SpiritLevel** [comment]
`Imagick::coalesceImages` to the rescue: http://php.net/manual/en/imagick.coalesceimages.php

I'll have a look at `Image` to see how this might be implemented.

**Comment by SpiritLevel** [comment]
Follow up: `Imagick::coalesceImages` just makes it easier to separate and re-combine frames, so we'd still need a wrapper. There are also similar solutions using GD. 

I did find these libs which might do what we want:

https://github.com/glukash/glu-image
https://github.com/Intervention/image

And it appears Imagick has a lot of other animation manipulation tools:

http://www.imagemagick.org/Usage/anim_mods

I'll need to do some more reading...can you say "distraction" !!
