### ISSUE TITLE
Users without full admin rights unable to duplicate root level pages 

### ISSUE THREAD

**Issue by MattyBalaam** [silverstripe/silverstripe-cms#1685]
I noticed this on 3.4, but also tried a fresh install of 3.2 and it has the same behaviour.

It seems that CMS users who have not been granted full admin rights are unable to duplicate a root-level page. Creating one works fine, but when duplicating there is a check in SiteTree.php `$parent->canAddChildren($member);` which ultimately get to a line in the *getIsDeletedFromStage* function `if(!$this->ID) return true;` Because the root pages parent ID is 0, this then causes canAddChildren to return false.

Speaking on IRC with @kinglozzer he suggested changing the if statement to ` if($parent && $parent->exists()) {` which has fixed the issue for me.

**Comment by kinglozzer** [comment]
A little more info on why this happens:

In [`CMSMain::duplicate()`](https://github.com/silverstripe/silverstripe-cms/blob/cca147513a6887f442ced178af4fec1e1addc2ca/code/controllers/CMSMain.php#L1365-L1368), we check if the user can add a page to this section by checking whether they can add a child to the parent of the page we’re trying to duplicate. If the page being duplicated is a top-level page, `$page->Parent()` returns an empty page, hence the ID of 0.

Changing the check in [`SiteTree::canCreate()`](https://github.com/silverstripe/silverstripe-cms/blob/cca147513a6887f442ced178af4fec1e1addc2ca/code/model/SiteTree.php#L1021-L1028) to check if the parent page actually exists should solve this with no BC-risks - how can you add a page underneath a page that doesn’t exist? 😉

**Comment by dhensby** [comment]
@kinglozzer where's the PR, bru?

**Comment by kinglozzer** [comment]
@dhensby Right here bruh https://github.com/silverstripe/silverstripe-cms/pull/1687

**Comment by kinglozzer** [comment]
Workaround is just to copy and paste `SiteTree::canCreate()` into your `Page` class, and add the `&& $parent->exists()` from #1687
