### ISSUE TITLE
page with broken image ends PHP session

### ISSUE THREAD

**Issue by LC-Eliot** [silverstripe/silverstripe-cms#1690]
Hi,

I'm currently getting an issue on a SilverStripe CMS 3.4.1 where when editing a page which contains a broken image when uploading a new image or updating the changes, the PHP session times out and logs out showing a login popup box to log back in.

**Comment by dhensby** [comment]
Which version?

**Comment by tractorcow** [comment]
He said 3.4.1 :) You are starting to sound like me. :P

**Comment by dhensby** [comment]
oh no, too late here :( sorry

**Comment by robbieaverill** [comment]
Sorry this hasn't received much attention! We're in security and critical bug fix mode now for SilverStripe 3.x - if you still experience this with SilverStripe 4.x please feel free to reopen the issue
