### ISSUE TITLE
Odd URL resolution behaviour

### ISSUE THREAD

**Issue by namliw** [silverstripe/silverstripe-cms#1695]
So, I currently noticed this issue,

for any silverstripe URL, add a extension to the end of it, and the page still resolves. I would though that a 404 page would be the correct result.

original:
http://demo.silverstripe.org/about

expected 404:
http://demo.silverstripe.org/about.boo
http://demo.silverstripe.org/about.boo/

**Comment by dhensby** [comment]
This "problem" has been raised previously - unfortunately I can't find the instances of it - but I believe this is a "won't fix" issue.

**Comment by tractorcow** [comment]
Our current behaviour is to ignore extensions, I'm afraid. Maybe one day we'll decide to change it.
