### ISSUE TITLE
In IE10/11 if a page is published the preview doesn't update

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#1697]
When the draft and published version of a page are the same (ie page is published), the preview of the published version shows as missing page.

This issue doesn't exist on Chrome.
![pasted_image_20_12_16__4_17_pm](https://cloud.githubusercontent.com/assets/555033/21337227/5a66b4b0-c6d0-11e6-92af-0a037a1aa58f.png)

**Comment by HboyVinod** [comment]
Is this still an issue?

**Comment by Firesphere** [comment]
I can't reproduce this in IE11

**Comment by phalkunz** [comment]
I can't reproduce this issue in IE 11 either.

**Comment by clarkepaul** [comment]
Closing as this is resolved already
