### ISSUE TITLE
LinkTracking / dependent pages updated on publishing 

### ISSUE THREAD

**Issue by giovdk21** [silverstripe/silverstripe-cms#1701]
Hello,
I'm using Silverstripe 3.4.1 and I noticed that when saving a page that has some dependent pages, the published version (SiteTree_Live) of those pages are updated too (but not the "draft" - SiteTree)

You can see this by looking at the LastEdited date.

I think it's doing it at https://github.com/silverstripe/silverstripe-cms/blob/3.4/code/model/SiteTree.php#L2405

But it would be great if it could do that only when needed.

Thanks

**Comment by dhensby** [comment]
Basically you want to avoid touching the `LastEdited` value of pages where there are no changes?

It looks like that's the case: https://github.com/silverstripe/silverstripe-framework/blob/3.4/model/DataObject.php#L1379-L1397 nothing should be written if there are no changes

**Comment by giovdk21** [comment]
Hi,
I'm not sure because if now LastEdited is updated every time the page is written then changing this behaviour could be misleading.

But at the same time when publishing a page it would be ideal to call the write method only if needed (now every dependent page is updated regardless every time you publish the page)

Couldn't you assume that if the current page was already published before, then you don't need to update the dependent ones?

Thanks

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
