### ISSUE TITLE
Unable to see "Insert File" button on small screen

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-cms#1706]
Using dev-master (`f669c6a0b`) on my Ubuntu ThinkPad (1920x1080) and Firefox v50, I cannot see the "Insert File" button in the file-upload dialogue, when attempting to insert an image into the WYSIWYG editor's "Insert Media" dialogue. See screenshot below.

Additionally, I expected to be able to hit "Enter" and have that perform the same task, but nothing happened :-/

![ss4-image-upload](https://cloud.githubusercontent.com/assets/478440/21667150/6cbef7e8-d35b-11e6-806e-1b426453f62e.png)

**Comment by chillu** [comment]
Good point, wanted to raise this issue as well - we need more Flexbox layout :)

**Comment by zacps** [comment]
I'm working on this now.

**Comment by phptek** [comment]
@zacps How did you go with this? It'd be good to have any other comments you had, added here.

**Comment by zacps** [comment]
I don't think I have any extra comments other than what's in the pull request [silverstripe/silverstripe-asset-admin#375](https://github.com/silverstripe/silverstripe-asset-admin/pull/375).

**Comment by flamerohr** [comment]
Pull request https://github.com/silverstripe/silverstripe-asset-admin/pull/386
