### ISSUE TITLE
"Image" field is missing "Alt" attribute, can only see "Title" attribute

### ISSUE THREAD

**Issue by peterlu-hinter** [silverstripe/silverstripe-cms#1708]
When you crate a "Image" field or use built in "Files" function, you can only see "Title" attribute. It is missing "Alt" attribute.
Funny thing is that in the WYSIWYG image function, you can see the "Alt" attribute.
Silverstripe version 3.5.0

**Comment by kinglozzer** [comment]
The “Title” database field doesn’t necessarily match up to the `title` HTML attribute. For images added via the WYSIWYG editor, the option to edit the `alt` attribute is present. For images that are output manually (i.e. via `{$Image}` in templates), the default behaviour is to output the “Title” database field as the `alt` attribute. If developers wish to give users a separate field to edit the `alt` attribute, that’s something they can do via extensions.
