### ISSUE TITLE
"Who can view" group dropdown visible by default

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-cms#1714]
It gets a bit confusing when you've selected "inherit from parent page", yet you can still set some groups there. The dropdown needs to be hidden by default.

![image](https://cloud.githubusercontent.com/assets/111025/22004094/c2890b62-dcbd-11e6-943d-d2f00b8e8d5b.png)

## Pull requests
- [x] https://github.com/silverstripe/silverstripe-cms/pull/1820
- [x] https://github.com/silverstripe/silverstripe-admin/pull/63

**Comment by zacps** [comment]
Wouldn't it be better to disable the field instead?

**Comment by unclecheese** [comment]
@chillu I'm not able to replicate this bug on the master branch. The field in question seems to hide and reveal itself based on the state of the radio buttons.

**Comment by unclecheese** [comment]
Have replicated in siteconfig.

**Comment by tractorcow** [comment]
same in asset-admin with new permission controls being added. https://github.com/silverstripe/silverstripe-asset-admin/pull/465

**Comment by flamerohr** [comment]
asset-admin is built on React, so that would require a feature/fix in React
It'd be good to move asset-admin to another story rather than block this one (entwine solution/fix)

**Comment by unclecheese** [comment]
+1 for moving to a new story. While the value is the same, the context is much different, and requires a completely separate dev effort.

**Comment by tractorcow** [comment]
Yes that was my feeling too. Sorry I didn't mean to imply we should do it now.

**Comment by chillu** [comment]
I’ve created a follow up issue: https://github.com/silverstripe/silverstripe-asset-admin/issues/475
