### ISSUE TITLE
Logout expiry dialog isn't styled, and doesn't redirect

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-cms#1715]
![image](https://cloud.githubusercontent.com/assets/111025/22004151/3fd5caba-dcbe-11e6-8408-141c0fef930b.png)

Related: https://github.com/silverstripe/silverstripe-cms/issues/1609

**Comment by sminnee** [comment]
Duplicate of https://github.com/silverstripe/silverstripe-framework/issues/6387
