### ISSUE TITLE
silverstripe_version file irrelevant?

### ISSUE THREAD

**Issue by hoKRa1** [silverstripe/silverstripe-cms#1718]
I understand that the ```silverstripe_version``` file has its 'legacy' within the CMS, but it is empty nowadays. What should we do with it?

**Comment by kinglozzer** [comment]
I *think* it’s still populated with the current version number as part of the release process, but only for the ZIP downloads on silverstripe.org. Given that the ZIP downloads now include `composer.json` and `composer.lock`, I think we could remove it...

**Comment by dhensby** [comment]
probably irrelephant - can @tractorcow tell us?

**Comment by tractorcow** [comment]
It's still useful and necessary.
