### ISSUE TITLE
URL segment "results" causes error

### ISSUE THREAD

**Issue by MarioHofer** [silverstripe/silverstripe-cms#1737]
Hej there awesome SilverStripe folks!

When having "results" in the URL of a page, only a blank screen is shown with the message "Action 'results' isn't allowed on this handler.".

In our case the used URL is "/championship/results".

Should be a bug, or?

Best, Mario

**Comment by MarioHofer** [comment]
It only appears when "results" is a child page.

**Comment by dhensby** [comment]
I'm afraid "results" is likely a reserved word for URLs. I think this is a duplicate issue of #1696
