### ISSUE TITLE
Page redirection can lead to XSS issue

### ISSUE THREAD

**Issue by We5ter** [silverstripe/silverstripe-cms#1743]
(copied content to security@silverstripe.com)

**Comment by tractorcow** [comment]
Hello, can you please ensure you report any security issues you discover (discretely) to security@silverstripe.com? Following good disclosure practices helps us resolve issues before they can become a problem for the greater public. See https://docs.silverstripe.org/en/4/contributing/release_process/#reporting-an-issue

Thank you. :D

**Comment by tractorcow** [comment]
Thank you @We5ter for the report; I've copied your full issue to our internal tracker. You'll get credit for reporting this issue once a release with this fix is available.

**Comment by We5ter** [comment]
Hello,how is this issue going?

**Comment by dhensby** [comment]
@We5ter please communicate with the security team via the email above.

**Comment by tractorcow** [comment]
@dhensby let's catch up on this on Monday :)
