### ISSUE TITLE
"Viewer/Editor Groups" in Page Settings no longer toggles

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-cms#1745]
The group selectors should be hidden unless you select "only these people". This is a regression from 3.x

![image](https://cloud.githubusercontent.com/assets/111025/23377750/0169fce4-fd96-11e6-9fae-5950fb7c85ed.png)

**Comment by flamerohr** [comment]
Created pull request https://github.com/silverstripe/silverstripe-cms/pull/1747 and https://github.com/silverstripe/silverstripe-framework/pull/6664 to address this
