### ISSUE TITLE
Composer Branch Alias for 3.5 is incorrect

### ISSUE THREAD

**Issue by UndefinedOffset** [silverstripe/silverstripe-cms#1751]
Looks like 02b9de93c3969979dab2b5111ba761676b0733d5 caused the branch alias to get incorrectly updated for the 3.5 branch and by the looks of it the travis config as well.

**Comment by tractorcow** [comment]
The `3.x-dev` alias should be ignored on all branches other than `3`. Looking at https://github.com/silverstripe/silverstripe-cms/blob/3/composer.json it seems correctly set at 3.6.x-dev.

**Comment by UndefinedOffset** [comment]
ah ok so the fact that it appears in 3.5's composer.json isn't an issue? https://github.com/silverstripe/silverstripe-cms/blob/3.5/composer.json#L27. The .travis.yml is also using 3 https://github.com/silverstripe/silverstripe-cms/blob/3.5/.travis.yml#L15.

**Comment by tractorcow** [comment]
Ok, I think the CORE_RELEASE=3 is an issue. it SHOULD be `CORE_RELEASE=<thisbranch>`

**Comment by tractorcow** [comment]
I'm not sure how a "merge 3.5 into 3" commit made its way into the 3.5 branch lol. @dhensby ping.

**Comment by sminnee** [comment]
Fixed in 14540729caa30dd2e782e4fd52afe518dc156ed8
