### ISSUE TITLE
can't install alpha5 on mamp

### ISSUE THREAD

**Issue by guyvanbael** [silverstripe/silverstripe-cms#1752]
can't get it installed. Mac os 10.11.6 mamp 307 php 5.5.17
At first... installer didn't load had to manually call install.php
Then  fails on check requirements (richts on htacces, config.php, config.yml, assets)

got that solved, but get this error while installing (screenshot)
![schermafbeelding 2017-03-02 om 08 57 47](https://cloud.githubusercontent.com/assets/3098809/23498231/ed4e53b2-ff26-11e6-815f-3480b985d0bd.png)

**Comment by dhensby** [comment]
This issue has been reported and is due to the use of before/after clauses in config yaml. Try removing them from your site.

**Comment by guyvanbael** [comment]
the after clause in the config.yml is put back in every time causing same error

**Comment by dhensby** [comment]
OK - so this is a problem with the framework and I've opened a PR to resolve it
