### ISSUE TITLE
CMSMain::EditForm()'s "archive" action is not validation exempt

### ISSUE THREAD

**Issue by jakxnz** [silverstripe/silverstripe-cms#1755]
The 'delete' action is exempt from validation, so it would make sense to also include the 'archive' action.

*CMSMain.php line 680*
```
// Set validation exemptions for specific actions
$form->setValidationExemptActions(array('restore', 'revert', 'deletefromlive', 'delete', 'unpublish', 'rollback', 'doRollback'));
```

**Comment by dhensby** [comment]
agreed - PR?

**Comment by chillu** [comment]
Sounds reasonable, happy to review a PR @jakxnz  - closing this as a minor enhancement in the meantime.
