### ISSUE TITLE
CMS page types should use beforeUpdateCMSFields()

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-cms#1756]
Currently it’s not possible to use `updateCMSFields()` to edit the fields added by `ErrorPage`, `RedirectorPage` or `VirtualPage`. Adjusting their `getCMSFields()` methods to use `beforeUpdateCMSFields()` would make this much easier for developers targeting these page types with extensions to modify the fields.

**Comment by tractorcow** [comment]
👍 for this.

**Comment by dhensby** [comment]
v3 or v4?

**Comment by tractorcow** [comment]
It probably needs to be in 4, since it will change the way that existing extensions affect cms fields.

**Comment by robbieaverill** [comment]
Done in #1827?

**Comment by kinglozzer** [comment]
Yep 👍
