### ISSUE TITLE
[ASSETS] Folders with '0.-' in their name causing issues

### ISSUE THREAD

**Issue by swordfox** [silverstripe/silverstripe-cms#1759]
If a folder has '0.-' in the name it renames to something like '58c1deac9cc6d.-Folder-Name'.

**Comment by dhensby** [comment]
CMS version, please

**Comment by swordfox** [comment]
Initially discovered in 3.1.12 but also on 3.5.3

**Comment by dhensby** [comment]
OK - so when and how does it get renamed? is this when trying to create a folder? are you trying to do it through the CMS or programatically?

Can you provide steps to replicate, please?

**Comment by swordfox** [comment]
It's through the CMS files tab.
When you try and create a folder.

Is it happening for you or could it be server related?

**Comment by dhensby** [comment]
Can replicate

**Comment by maxime-rainville** [comment]
I couldn't replicate this behaviour in SS4.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
