### ISSUE TITLE
ss 3.5: icon button group bug

### ISSUE THREAD

**Issue by rasstislav** [silverstripe/silverstripe-cms#1768]
In non english interface in assets are icons wrong. Showing only font-icon-pencil...

https://github.com/silverstripe/silverstripe-cms/blob/3.5.3/templates/Includes/AssetAdmin_Content.ss#L19

![assets](https://cloud.githubusercontent.com/assets/9253113/24827422/8b5c5128-1c49-11e7-98e7-0b5c77d0b66a.png)

**Comment by chillu** [comment]
Confirmed this is an issue in 3.x and the Slovak language, with any browser (tested in Chrome). Since it's no longer an issue in the upcoming 4.x (we're not using icons for this part), we're unlikely to fix it. Closing this issue, but happy to review a PR! :)
