### ISSUE TITLE
TinyMCE to extend full width of panel

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#1773]
There is no reason to limit width of TinyMCE at smaller sizes but we could limit it a larger sizes to make the content area more readable by limiting TinyMCE's width.

In edit mode make the TinyMCE .form__field-holder match other fields:
flex: 0 0 75%;
max-width: calc(16.66667% + 895px);

If in split mode make TinyMCE have a 100% width as we have less space to deal with:
flex: 0 0 100%;
<img width="820" alt="pasted_image_31_03_17__2_41_pm" src="https://cloud.githubusercontent.com/assets/555033/24532905/81b644d2-1620-11e7-9865-074fa5eb20e4.png">

**Comment by flamerohr** [comment]
Pointer: Find the classes that are applied when split-mode and edit-mode are applied, they follow BEM format, so it's quite obvious once you find them.
The classes define what panels to show or hide by css rules (javascript only influences the classes, no longer the hiding)
Add media queries if necessary :D but I don't think it is

**Comment by clarkepaul** [comment]
PR https://github.com/silverstripe/silverstripe-admin/pull/81
