### ISSUE TITLE
UX Research: Update preview toggle 

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#1778]
The preview/split-view/edit-view toggle needs improvements based on user feedback and observations of users wanting to preview their edits.

The feedback we have got is that the preview action is too hidden for users, some interface guidance could help this but we should also be able to provide an easier pattern for the current UI.

Some suggestions for user testing:
https://invis.io/2EB60WWD3#/227002118_Pages_-_Preview_Controls

**Comment by chillu** [comment]
Moving this to the bottom of the beta1 backlog, relies on direction from Paul

**Comment by tractorcow** [comment]
Just to confirm, this only affects the preview control button, and none of the other silverstripe navigator buttons. I'm adding an estimated size in lieu of confirmation with @clarkepaul .

**Comment by clarkepaul** [comment]
Yes this would only be the preview toggle and wouldn't alter any other control, but would require a little of testing with users to find out the best approach as this isn't known without testing.

**Comment by chillu** [comment]
Remove estimate because it's Paul's time only, which doesn't count against team velocity any more
