### ISSUE TITLE
VirtualPage_Controller not targeting correct page controller

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe/silverstripe-cms#1782]
In VirtualPage_Controller, the method hasMethod is trying to check for a method on a controller class name derived from the page name, which doesn't need to exist.

For example, if ArticlePage doesn't have a controller defined and is using Page_Controller, this is not found and VirtualPage_Controller throws error 500 when trying to instantiate a non-existing class (line 546).

**Comment by michalkleiner** [comment]
Same problem is affecting the getViewer method. I'll create a PR with a fix for the 3.5 branch.

**Comment by dhensby** [comment]
@michalkleiner did the PR ever materialise?

**Comment by michalkleiner** [comment]
Hmmm, I think we just created the controllers back then as a quick workaround, so I don't think it did, sorry.

**Comment by kinglozzer** [comment]
This has been fixed in https://github.com/silverstripe/silverstripe-cms/pull/1899
