### ISSUE TITLE
Hidden list

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-cms#1785]
I speculate that it's caused by bootstrap's collapsible feature...

![screen shot 2017-04-07 at 4 27 34 pm](https://cloud.githubusercontent.com/assets/1064889/24785584/5c6e735e-1baf-11e7-9f82-be1122d9eed5.png)

**Comment by chillu** [comment]
Pointers to fix: This is in the "Settings" tab of a page, at the bottom on "who can edit this page". It's a `ListboxField` created in `SiteTree.php`. Styles are in `admin/client/src/styles/legacy/_form.scss`

**Comment by phalkunz** [comment]
Assigned to Ishan J.

**Comment by flamerohr** [comment]
PR here https://github.com/silverstripe/silverstripe-cms/pull/1799/files
