### ISSUE TITLE
New Embed Media Dialog is Blank in Safari

### ISSUE THREAD

**Issue by thezenmonkey** [silverstripe/silverstripe-cms#1786]
The new embed media dialog show as blank (form element height is 0). This relates to item 11 in the flexbug repo https://github.com/philipwalton/flexbugs (flex:1 shorthand defaults to 0 height in safari) 

![silverstripe_-_edit_page](https://cloud.githubusercontent.com/assets/1685217/24832663/64ef7cd4-1c82-11e7-98b4-e3511bee8c3f.png)

**Comment by chillu** [comment]
Pointers how to fix this: The modal can be triggered in any HTML area on a page editing screen. It's controlled by `InsertEmbedModal.js`, with styles in `InsertEmbedModal.scss`

**Comment by flamerohr** [comment]
I believe this was fixed by https://github.com/silverstripe/silverstripe-asset-admin/pull/449

I no longer see the content height as 0 in safari
