### ISSUE TITLE
[ADMIN] Searching for members inside a group throws an exception

### ISSUE THREAD

**Issue by jpbecotte** [silverstripe/silverstripe-cms#1789]
How to reproduce:
CMS > Security > Choose any group > enter something in the text box at the top next to the grid field > Hit enter. An Ajax call is initiated and you'll receive this Exception:

```
ERROR [User Error]: Uncaught InvalidArgumentException: Can't handle action "find"
IN POST /admin/security/EditForm/field/Groups/item/3/ItemEditForm/field/Members
Line 918 in /home/amuq/public_html/framework/forms/gridfield/GridField.php

Source
======
  909: 			if($component instanceof GridField_ActionProvider) {
  910: 				$actions = array_map('strtolower', (array) $component->getActions($this));
  911: 
  912: 				if(in_array($actionName, $actions)) {
  913: 					return $component->handleAction($this, $actionName, $arguments, $data);
  914: 				}
  915: 			}
  916: 		}
  917: 
* 918: 		throw new InvalidArgumentException(sprintf(
  919: 			'Can\'t handle action "%s"',
  920: 			$actionName
  921: 		));
  922: 	}
  923: 
  924: 	/**

Trace
=====
GridField->handleAlterAction(find,find,Array)
GridField.php:879

GridField->gridFieldAlterAction(Array,Form,SS_HTTPRequest)
GridField.php:120

GridField->index(SS_HTTPRequest)
RequestHandler.php:288

RequestHandler->handleAction(SS_HTTPRequest,index)
RequestHandler.php:200

RequestHandler->handleRequest(SS_HTTPRequest,DataModel)
GridField.php:1019

GridField->handleRequest(SS_HTTPRequest,DataModel)
RequestHandler.php:222

RequestHandler->handleRequest(SS_HTTPRequest,DataModel)
RequestHandler.php:222

RequestHandler->handleRequest(SS_HTTPRequest,DataModel)
GridFieldDetailForm.php:102

GridFieldDetailForm->handleItem(GridField,SS_HTTPRequest)
GridField.php:981

GridField->handleRequest(SS_HTTPRequest,DataModel)
RequestHandler.php:222

RequestHandler->handleRequest(SS_HTTPRequest,DataModel)
RequestHandler.php:222

RequestHandler->handleRequest(SS_HTTPRequest,DataModel)
Controller.php:158

Controller->handleRequest(SS_HTTPRequest,DataModel)
LeftAndMain.php:464

LeftAndMain->handleRequest(SS_HTTPRequest,DataModel)
AdminRootController.php:92

AdminRootController->handleRequest(SS_HTTPRequest,DataModel)
Director.php:385

Director::handleRequest(SS_HTTPRequest,Session,DataModel)
Director.php:149

Director::direct(/admin/security/EditForm/field/Groups/item/3/ItemEditForm/field/Members,DataModel)
main.php:191

```

Here's an image: 
![capture d ecran 2017-04-11 a 14 43 51](https://cloud.githubusercontent.com/assets/4622285/24925288/bec51508-1ec5-11e7-8468-44e0de5741b4.png)

**Comment by tractorcow** [comment]
Which version of cms / framework are you using?

**Comment by jpbecotte** [comment]
3.5.3. But it appears with 3.3.1 also.

**Comment by tractorcow** [comment]
Hm, I see what you mean. That's odd, that the GridFieldAddExistingAutocompleter class seems to be attempting to (and failing) to act secondarily as a search form, as well as a relation linking popup. I wonder if this is intentional? I'm not sure that the "enter" action should be expected to do anything, since normally search results appear as you type (or none appear if nothing matches).

Would it be appropriate to remove the "on enter" search behaviour, and leave searching as-you-type in place?

**Comment by spark-green** [comment]
Has anyone found solution for this issue? 
If yes please post here

**Comment by jinjie** [comment]
It happens to me too. In pages that have GridField. Works perfectly when there is no gridfield in the model. On v3.6.2

**Comment by maxime-rainville** [comment]
I couldn't replicate this in SS4.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

If someone can find a way to replicate this issue in Silverstripe CMS 4, leave some comments and I can reopen the issue.
