### ISSUE TITLE
Drag and Drop reordering is tricky

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-cms#1808]
It would be nice if the pages got spaced out a bit more, and a box shows to drop it between the pages, while dragging around, so it's easier to position a page between pages with children, for example.

**Comment by kinglozzer** [comment]
Duplicate of https://github.com/silverstripe/silverstripe-cms/issues/744?

**Comment by sminnee** [comment]
Closing for now.

@Firesphere if this isn't a duplicate of #744 could please reopen and elaborate on what, beyond that ticket, you think we should do.

**Comment by Firesphere** [comment]
Nope, same issue. Didn't find it initially. Closed.
