### ISSUE TITLE
Adding ability to clear link set using the TreeDropdownField

### ISSUE THREAD

**Issue by Codesesh** [silverstripe/silverstripe-cms#1816]
It would be great if there was a little "x" icon to clear the link that has been set when using a TreeDropdownField.

E.g if I select and save a link, I cannot clear it if I wanted to via the CMS.

Unless there is a method that I am missing?

![cross](https://cloud.githubusercontent.com/assets/12224994/25924714/75a70b08-3638-11e7-8abe-51419f74ddf2.png)

**Comment by kinglozzer** [comment]
If my memory serves me well, clicking the selected page a second time will de-select it. Does that work?

**Comment by dhensby** [comment]
@kinglozzer is right, but it's not really intuitive. @clarkepaul any thoughts on this for 4.0?

**Comment by Codesesh** [comment]
@kinglozzer - Ah yes you are right, thank you! As @dhensby mentioned, its not intuitive but at least that option is still there.

**Comment by clarkepaul** [comment]
I agree that is not intuitive at all, it would be common practice to have the x toward the end of the field (even if it was far right of the selected item).

For SS4 there is an x on the new TreeDropdownField although I haven't tried out what's been implemented properly.

**Comment by tractorcow** [comment]
React implementation of this feature is in-progress at https://github.com/silverstripe/silverstripe-framework/pull/6915

However we need to also implement this within the entwine section of the CMS.

**Comment by chillu** [comment]
There is now!

![image](https://user-images.githubusercontent.com/111025/30188288-db23e1ac-9481-11e7-8857-a857ffca112e.png)
