### ISSUE TITLE
SilverStripe CMS composer not updated

### ISSUE THREAD

**Issue by Doniz** [silverstripe/silverstripe-cms#1817]
Hello,

i see CMS package is not updated via composer, so it's not logically at all. Here is typing about:
https://docs.silverstripe.org/en/3/getting_started/server_requirements/#does-silverstripe-3-work-with-php-7 that CMS should work within php7

```
SilverStripe 3.6 or greater will work with PHP 7.0 and 7.1. SilverStripe 3.5 or lower will only work with PHP 5.3 - 5.6.
```

![screen shot 2017-05-11 at 13 08 40](https://cloud.githubusercontent.com/assets/4441455/25944209/252f2c4c-364b-11e7-9139-bb084a346315.png)

but at dependencies i see old versions of `framework`, `siteconfig`, `reports` are ~3.4 versions.

**Comment by tractorcow** [comment]
Hi @Doniz , normally we control framework and cms versions strictly via installer composer.json dependencies. See for example:
 - 3.x dev branch https://github.com/silverstripe/silverstripe-installer/blob/3/composer.json
 - 4.0 dev branch https://github.com/silverstripe/silverstripe-installer/blob/master/composer.json
 - 4.0 alpha release https://github.com/silverstripe/silverstripe-installer/blob/4.0.0-alpha7/composer.json
 
As a matter of practice we don't rewrite all dependencies down the chain for each minor release version. Those `~3.4` constraint versions are loose constraints which are typically superseded by the root composer file.

All 3.x lines of releases are essentially fixed at self.version for all tags; 4.0.0 constraints are fixed to the dev branches of each dependency, and are automatically re-written on release to fixed tags.

I realise that it feels misleading to not include those tags and constraints the whole way down the stack to each module, but given our release and core tagging process it's not really necessary.

I hope that explanation made a little bit of sense! Apologies if it feels a bit unintuitive.

**Comment by Doniz** [comment]
no problem, just when using installer everything is fine. But when you have a project and just want to update to latest 3.x version, have a bit confusing. Because as example composer want to install reports,framework ~3.4 version which is required. 

Ok, thanks.

**Comment by tractorcow** [comment]
We are looking to replace the current dependency "group" system with a recipe system, some time in the future. This means if you want to upgrade to "3 of SilverStripe" you can simply point to the recipe base, and it will fix all necessary versions for the requested dependency. https://github.com/silverstripe/silverstripe-framework/issues/6860

**Comment by Doniz** [comment]
oh that nice and looks promising.
