### ISSUE TITLE
TinyMCE WYSIWYG loses height after saving page

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-cms#1831]
In SilverStripe 4 master, when the _Save draft_ or _Save & Publish_ button is clicked, the TinyMCE WYSIWYG seems to collapse and lose its height:

![](http://spdr.me/6Qr5R+)

**Comment by dhensby** [comment]
Have you resized the field prior to this or did it load that large initially?

**Comment by chillu** [comment]
Good catch James, that's really annoying! Added it as a bug to the beta2 milestone for now.
