### ISSUE TITLE
BUG installer.php doesn't warn about php7 on ss 3.5 and below

### ISSUE THREAD

**Issue by zhyvytskyi** [silverstripe/silverstripe-cms#1835]
Installer writes me "Building database schema...
![2017-05-28 22 48 05](https://cloud.githubusercontent.com/assets/25120629/26531733/2817dc96-43f8-11e7-9c38-3ce68ab59183.png)
"

and breaking down(

I'll be appreciate to someone who know what to do

**Comment by tractorcow** [comment]
@zhyvytskyi which version did you install?

**Comment by dhensby** [comment]
and which version of PHP are you running?

**Comment by dhensby** [comment]
The full backtrace would help too

**Comment by zhyvytskyi** [comment]
the latest one, right from the site

Php 7.0

Trace
DBSchemaManager->requireField(File,ClassName,Array) 
DB.php:552
DB::require_field(File,ClassName,Array) 
Enum.php:90
Enum->requireField() 
DBSchemaManager.php:349
DBSchemaManager->requireTable(File,Array,Array,1,Array,) 
DB.php:530
DB::require_table(File,Array,Array,1,Array,) 
DataObject.php:3429
DataObject->requireTable() 
DatabaseAdmin.php:244
DatabaseAdmin->{closure}() 
DBSchemaManager.php:126
DBSchemaManager->schemaUpdate(Closure) 
DatabaseAdmin.php:246
DatabaseAdmin->doBuild(1) 
DatabaseAdmin.php:96
DatabaseAdmin->build() 
DatabaseAdmin.php:80
DatabaseAdmin->index(SS_HTTPRequest) 
RequestHandler.php:288
RequestHandler->handleAction(SS_HTTPRequest,index) 
Controller.php:202
Controller->handleAction(SS_HTTPRequest,index) 
RequestHandler.php:200
RequestHandler->handleRequest(SS_HTTPRequest,DataModel) 
Controller.php:158
Controller->handleRequest(SS_HTTPRequest,DataModel) 
DevBuildController.php:25
DevBuildController->build(SS_HTTPRequest) 
RequestHandler.php:288
RequestHandler->handleAction(SS_HTTPRequest,build) 
Controller.php:202
Controller->handleAction(SS_HTTPRequest,build) 
RequestHandler.php:200
RequestHandler->handleRequest(SS_HTTPRequest,DataModel) 
Controller.php:158
Controller->handleRequest(SS_HTTPRequest,DataModel) 
RequestHandler.php:222
RequestHandler->handleRequest(SS_HTTPRequest,DataModel) 
Controller.php:158
Controller->handleRequest(SS_HTTPRequest,DataModel) 
Director.php:385
Director::handleRequest(SS_HTTPRequest,Session,DataModel) 
Director.php:149
Director::direct(/dev/build,DataModel) 
main.php:191



it was only one error
![2017-05-29 20 55 02](https://cloud.githubusercontent.com/assets/25120629/26558420/369a6018-44b1-11e7-9ad6-b8feb9533f1d.png)

**Comment by tractorcow** [comment]
> the latest one, right from the site

The latest stable, 3.5.3, doesn't run on PHP7 yet. You need 3.6.0 which isn't stable yet. You can update to this by installing 3.6.0-beta2, and see if that addresses your issues.

We should add a PHP version check to better validate install version for ss 3.5 and below.

**Comment by tractorcow** [comment]
Renamed to match the issue. :)

**Comment by robbieaverill** [comment]
It'd be awesome if there were a central point to get the SilverStripe version from. Adding something like this would be a minor change instead of patch... shall we hack something into the install script for now?

**Comment by dhensby** [comment]
The ideal way to do this would be using composer to figure it out - but composer isn't mandated in 3.x so it'd be tricky...

We could update our build tooling to insert the build versions somewhere, though...

**Comment by chillu** [comment]
3.6 has PHP 7 support. Closing this
