### ISSUE TITLE
BUG Navigating to a page from reports section loads broken CMSMain view

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-cms#1841]
In order to replicate this issue:

 - Go to reports section
 - Select "Pages with no content"
 - Click on one of the pages
 
The CMS will redirect to the /admin/pages section with the selected page in edit mode.

Most of the page will appear to load correctly, however the left hand menu will retain the "reports" menu selected state, and the cms preview mode will be broken.

![image](https://cloud.githubusercontent.com/assets/936064/26718285/995b10dc-47d4-11e7-829e-3aabd200f7c5.png)

It appears that this is the SilverStripe navigation component loading in the incorrect block.

![image](https://cloud.githubusercontent.com/assets/936064/26718330/c0a19f26-47d4-11e7-96b9-49547ce29774.png)

**Comment by ssmarco** [comment]
Please see my pull request here if this works.
https://github.com/silverstripe/silverstripe-reports/pull/75

**Comment by dhensby** [comment]
ping @tractorcow

**Comment by tractorcow** [comment]
It didn't fix the issue somehow.

**Comment by tractorcow** [comment]
My bad, I was testing the wrong local checkout. It's fixed. :)
