### ISSUE TITLE
SS4: Right click, add page fails

### ISSUE THREAD

**Issue by mikenz** [silverstripe/silverstripe-cms#1846]
AddForm receives POSTs from /admin/pages/add and GETs from right clicking a page in site tree and adding a child.

With https://github.com/silverstripe/silverstripe-framework/pull/6998 the GET is now `405 Method Not Allowed`

**Comment by dhensby** [comment]
Thanks @mikenz for finding and reporting this. I think the best solution is to turn off `strictFormMethodCheck` for this form...

**Comment by tractorcow** [comment]
@AntonyThorpe will you PR that fix ?

**Comment by AntonyThorpe** [comment]
@tractorcow PR submitted as requested.  All checks have passed.  Thank you.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-cms/pull/1852

Thanks @AntonyThorpe you are great :D
