### ISSUE TITLE
SiteTree page titles disappear from tree view when that page is saved/published

### ISSUE THREAD

**Issue by BrewCurious** [silverstripe/silverstripe-cms#1848]
**This issue only occurs for sites running in dev mode with template commenting turned on.**

When in the CMS, clicking on the Save or Publish (or Save & Publish) buttons when editing a page in the SiteTree causes the title of that page to disappear from the SiteTree tree view. Refreshing the entire page in the browser brings the title back.

Steps to recreate:
1. Turn on dev mode for the site
2. Turn on source_file_comments
3. Log into the admin
4. Click on a page from the SiteTree
5. Click on Save, Publish or Save & Publish button

It appears as though the SiteTree's tree view is being broken when the updatetreenodes?id=XXX JSON call returns with template comments in its content.

This behavior has been recreated in CMS/Framework versions 3.4.5 through 3.6.0.

**Comment by robbieaverill** [comment]
The ideal option here would be to disable source file comments in `MarkedSet::renderChildren()`, but that would involve a config manifest nest which is a performance hit.

Instead I'll make a PR to strip out HTML comments in the (legacy) Javascript end.

**Comment by robbieaverill** [comment]
Fixed with https://github.com/silverstripe/silverstripe-admin/pull/613
