### ISSUE TITLE
Dropdown menu hidden in Settings section

### ISSUE THREAD

**Issue by kumosal** [silverstripe/silverstripe-cms#1855]
This affects SS v4 alpha7. When a user clicks to selecta group, the list of options is hidden. 
<img width="1212" alt="screen shot 2017-06-18 at 9 49 15 pm" src="https://user-images.githubusercontent.com/709524/27265987-3f8fd0a0-548c-11e7-9466-ecf0eb8c8ae1.png">

**Comment by chillu** [comment]
Confirmed this is still a problem in master (on latest Chrome)

**Comment by tractorcow** [comment]
Cause is the toggle option triggering properly on option change, but not on initial load.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-admin/pull/122
