### ISSUE TITLE
User's permissions are not displayed 

### ISSUE THREAD

**Issue by kumosal** [silverstripe/silverstripe-cms#1856]
Affects SSv4 alpha7. 
A user is assigned to the group of editors. Being a member of that group still doesn't adjust the permissions they have. 
<img width="484" alt="screen shot 2017-06-19 at 1 20 20 am" src="https://user-images.githubusercontent.com/709524/27266180-2dda1486-548e-11e7-89d8-fe4a1bcb8691.png">

## Pull requests
- [x] https://github.com/silverstripe/silverstripe-admin/pull/224
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/7342

**Comment by chillu** [comment]
What's the actual permission codes here for the group? "the group of editors" is very ambiguous. Do you mean the "Content Authors" group created by the default installation?

**Comment by kumosal** [comment]
yes, I mean the "Content Authors" group created by the default installation.

**Comment by unclecheese** [comment]
Have confirmed this bug. The list as shown above never changes, regardless of the group's permissions.

**Comment by unclecheese** [comment]
Have upgraded to impact/high as this significantly handicaps the user experience by obscuring critical information.

**Comment by chillu** [comment]
Thanks Aaron, I've added it to the milestone
