### ISSUE TITLE
Page permissions minor text change

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#1873]
Just a simple text change from "people" to "groups" to make the field clearer.
<img width="161" alt="pasted_image_28_06_17__4_13_pm" src="https://user-images.githubusercontent.com/555033/27620300-d260ca96-5c1c-11e7-94ea-084299532ab9.png">

**Comment by robbieaverill** [comment]
Can of behat worms opened, issues logged and referenced from the two pull requests above.

**Comment by clarkepaul** [comment]
Ha soz, but thanks :)
