### ISSUE TITLE
Inconsistent icon next to Pages panel title

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#1875]
The icon preceeding the Pages site tree panel title isn't consistent at different panel sizes.
No icon on sitetree full view:
<img width="534" alt="pasted_image_29_06_17__5_04_pm" src="https://user-images.githubusercontent.com/555033/27672196-39c0d67e-5ced-11e7-9bb5-365f3f594551.png">

Has icon on smaller sitetree view:
<img width="226" alt="pasted_image_29_06_17__5_00_pm" src="https://user-images.githubusercontent.com/555033/27672148-eec87d48-5cec-11e7-99b5-4ea874406a1b.png">

I suggest we remove the although it might be good to use an updated icon at the top of the panel when its collapsed if no design is provided to direct this issue.
Collapsed:
<img width="114" alt="pasted_image_29_06_17__5_11_pm" src="https://user-images.githubusercontent.com/555033/27672300-f3dbcec4-5ced-11e7-93c7-74171390d261.png">

**Comment by newleeland** [comment]
![screen shot 2017-07-03 at 13 09 37](https://user-images.githubusercontent.com/8085295/27776098-d95d42ce-5ffb-11e7-987a-30db8ca9cc3b.png)

If we remove the icon next the pages, it will be less confusing with 2 other around it that is similar.

![screen shot 2017-07-03 at 14 00 48](https://user-images.githubusercontent.com/8085295/27776139-158092ce-5ffc-11e7-9483-d24cf08875a4.png)

On collapse, we'll see the icon used for the tree view toggle instead, as what you'll see is the "tree view"

**Comment by chillu** [comment]
Icon has already been removed. That also means the collapsed panel icon has disappear though, sigh - so I've created https://github.com/silverstripe/silverstripe-cms/issues/1928
