### ISSUE TITLE
Some french translation disappear from 3.5.X to 3.6.X

### ISSUE THREAD

**Issue by intwebg** [silverstripe/silverstripe-cms#1876]
Hi I have installed the new version 3.6. But, the CMS and Framework is missing some french translation that are in 3.5.X For this problem, we have roll back to version 3.5.X

**Comment by dhensby** [comment]
Is this the case for 3.6.1? We referred the language corruptions for the 3.6.0 release.

**Comment by intwebg** [comment]
it's for 3.6.0.... is it corrected for 3.6.1?

**Comment by dhensby** [comment]
I believe so, please can you confirm?

**Comment by intwebg** [comment]
I have tested this morning. 3.6.1 solve the translation problem in french. Thanks!
