### ISSUE TITLE
Pages with shortcodes showing change warning unnecessarily

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-cms#1877]
When you open a page with shortcodes, and leave it, it will warn "do you want to lose unsaved changes?" even if you haven't changed anything.

**Comment by flamerohr** [comment]
Ok, so the first theory that shortcodes were causing it was wrong :)
Tracked it down to whitespace differences.

New lines are added to block elements in TinyMCE.

My screenshot of the differences:
![screen shot 2017-06-30 at 1 41 37 pm](https://user-images.githubusercontent.com/1064889/27717515-e96220cc-5d99-11e7-92e2-3ddbadf129f3.png)
![screen shot 2017-06-30 at 1 41 40 pm](https://user-images.githubusercontent.com/1064889/27717514-e95ec27e-5d99-11e7-995c-09edd67f03e4.png)
