### ISSUE TITLE
Move current Behat manage-page-permissions.feature to siteconfig, rewrite for Page permissions

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-cms#1895]
**SS4:** The current `manage-page-permissions.feature` feature is testing the siteconfig module. It should be moved to the siteconfig module instead (following 3.x support - https://github.com/silverstripe/silverstripe-siteconfig/issues/68).

Once done the CMS feature should be rewritten to test the permissions settings on an individual page instead of the global site settings.

**Comment by flamerohr** [comment]
Thanks @robbieaverill, I agree :) this will be a good reminder to do this

**Comment by robbieaverill** [comment]
oh - @flamerohr - this was done in https://github.com/silverstripe/silverstripe-cms/pull/1880 and https://github.com/silverstripe/silverstripe-siteconfig/pull/69/files#diff-53c2958e11d4fe9fd6a898a808251dda - forgot to close the issue - thanks 😄

**Comment by flamerohr** [comment]
perfect!
