### ISSUE TITLE
ModelAdmin icon using wrong class (beta1)

### ISSUE THREAD

**Issue by ec8or** [silverstripe/silverstripe-cms#1896]
Deafult icon span for ModelAdmin is currently generated as:
`<span class="icon icon-16 icon-sbs-courseadmin">&nbsp;</span>`

but needs the menu__icon class to render properly like other menu items:
`<span class="menu__icon font-icon-torsos-all"></span>`

![image](https://user-images.githubusercontent.com/1678184/28249024-6a8275e0-6a46-11e7-8ff5-1bbf0aa8b781.png)

**Comment by dhensby** [comment]
fixed with https://github.com/silverstripe/silverstripe-admin/pull/141/
