### ISSUE TITLE
3.6 page filters column missing

### ISSUE THREAD

**Issue by flare04** [silverstripe/silverstripe-cms#1903]
Hi, Just upgraded to version 3.6, centos 6, php 5.3.3.  Everything looks great but when clicking on the pages within the admin section, I don't see the filters column.   How do I get to see that column or can i use a URL directly to display the filters?  I'm trying to recover a page (or unarchive a page)

Using Chrome on Linux

**Comment by kinglozzer** [comment]
It’s at the top-right of the page, a magnifying glass icon. I can’t remember which version it was moved in (possibly 3.2), but if you’re upgrading from a really old version that could explain why it’s hard to find.

If it’s not showing up still, I’d suggest manually deleting your SilverStripe temp directory (usually either `<webroot>/silverstripe-cache/` or `/var/tmp/silverstripe-cache<sitename>`)

<img width="629" alt="screen shot 2017-07-19 at 14 38 33" src="https://user-images.githubusercontent.com/1655548/28369587-fa4cee6c-6c8f-11e7-8652-d716a4c44aab.png">
