### ISSUE TITLE
Position of search icon is off in Pages, should be top right

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#1905]
Minor issue of the search icon not in the right position. Keep in mind how it looks with smaller viewports and insert media modal.
<img width="137" alt="pasted_image_20_07_17__3_57_pm" src="https://user-images.githubusercontent.com/555033/28399942-4c0ee276-6d64-11e7-9155-e0a1aa40df2b.png">

**Comment by chillu** [comment]
@flamerohr Please reference the pull request here, and confirm it's fixed

**Comment by flamerohr** [comment]
position fixed here https://github.com/silverstripe/silverstripe-asset-admin/pull/589
