### ISSUE TITLE
Link to page uses wrong label for pages in TreedropdownField

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#1906]
The treedropdownfield for inserting a link should use the navigation label for pages rather than the page title so that the wording relates to the tree and navigation rather than the page title. For the following example, the homepage is the first item (welcome to the public demo...)
<img width="440" alt="pasted_image_20_07_17__5_09_pm" src="https://user-images.githubusercontent.com/555033/28401477-586119ea-6d6e-11e7-9381-fdd77382f002.png">

**Comment by dhensby** [comment]
Yes, this is something I always change when I build sites

**Comment by clarkepaul** [comment]
Closing as is resolved
