### ISSUE TITLE
Upgrading to v4 - Cannot namespace Page and PageController

### ISSUE THREAD

**Issue by WillGibson** [silverstripe/silverstripe-cms#1911]
I'm just starting to experiment with upgrading to version 4 so we can see how close it all seems to being practical to do on our clients' sites.

I namespaced our Page and PageController classes during the upgrade, and this blew it up.

I've un-namespaced them for now, but was wondering if there is a plan to make them namespaceable, or whether the global namespace is still the preferred situation here?

**Comment by dhensby** [comment]
please see: https://github.com/silverstripe/silverstripe-framework/issues/5844

**Comment by tractorcow** [comment]
Perhaps at ss 5.0 we won't have Page at all, and have a better composability solution for SiteTree along with content blocks and extensions.
