### ISSUE TITLE
Can't directly select an image that has been inserted into the CMS editor - Chrome Only.

### ISSUE THREAD

**Issue by Codesesh** [silverstripe/silverstripe-cms#1912]
Lately we have/alot of clients have noticed that you can't directly click on an image that has been inserted in the CMS editor to select it now.

One way I have found that works is, click + hold + drag slightly to the side, then the image becomes selected.

Doing some testing this only seems to be an issue in Chrome. It works fine in Firefox & Safari.

I have just updated the the latest version: Version 60.0.3112.78 (Official Build) (64-bit) (Mac) - And still can't directly select.

Using Silverstripe 3.6.1.

**Comment by kinglozzer** [comment]
Yep, Chrome only issue, it was broken by Chrome 58. This has been resolved and will be fixed in the next release, see https://github.com/silverstripe/silverstripe-framework/issues/6900
