### ISSUE TITLE
BUG SiteTree::canCreate() assumes parent context is SiteTree instance

### ISSUE THREAD

**Issue by muskie9** [silverstripe/silverstripe-cms#1913]
In upgrading one of our tools we've found that applying a `many_many` relation  to `SiteTree` from a DataObject class causes `allowedChildren` to be checked on the DataObject class. [Tracing this back](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Forms/GridField/GridFieldAddNewButton.php#L39-L50), I found that passing `$record` as `$context['Parent']` in this case causes `SiteTree::canCreate()` to assume the parent context is an instance of `SiteTree` and checks for `allowedChildren`.

I don't have the namespacing in here, but this is the gist of it:

```php
<?php

class MyObject extends DataObject{

    private static $many_many = [
        'Pages' => SiteTree::class,
    ];

    public function getCMSFields(){
        $fields = Parent::getCMSFields();
        $fields->removeByName('Pages');
        if ($this->owner->ID) {
            $config = GridFieldConfig_RelationEditor::create();
            $pages = $this->Pages();
            $linksField = GridField::create(
                'Pages',
                'Pages',
                $pages,
                $config
            );

            $fields->addFieldsToTab('Root.Pages', array(
                $linksField,
            ));
        }
        return $fields;
    }
}
```

**Comment by kinglozzer** [comment]
Context behind this issue: https://github.com/silverstripe/silverstripe-framework/issues/4913. It looks like @tractorcow’s original suggestion was to pass the relation name as the array key rather than `Parent`, so perhaps this should be fixed in framework instead?
