### ISSUE TITLE
Show page search results in table view only (instead of tree)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-cms#1926]
## Overview

There's currently three "modes" for showing page search results

![image](https://user-images.githubusercontent.com/111025/29435215-3cafb042-83fa-11e7-92aa-16c9b4c0247b.png)

Tree results in sidebar next to "edit page" (currently broken, see https://github.com/silverstripe/silverstripe-cms/issues/1925)

![image](https://user-images.githubusercontent.com/111025/29435233-473b0c8c-83fa-11e7-8ca7-d6780cc8b11e.png)

Tree results in full width

![image](https://user-images.githubusercontent.com/111025/29435239-4e225da2-83fa-11e7-8d74-cb7248a6d576.png)

Table results in full width.

In my opinion, the tabular results are by far the most useful representation for search results. It shows the same context as the tree through breadcrumbs, and allows more efficient pagination and sorting than a tree visualisation. It's kind of neat that you can retain search results in the tree sidebar while editing a page, but I wouldn't say it's an essential feature. 

I propose that we remove the tree-based search mode and only show tabular results. This will simplify the UI implementation, and means we don't have to fix bugs like https://github.com/silverstripe/silverstripe-cms/issues/1925. Note that we've already moved away from tree-based search results in the new React TreeDropdownField for similar reasons. This needs to be implemented in non-React sections through https://github.com/silverstripe/silverstripe-admin/issues/142.

/cc @clarkepaul @newleeland 

## Acceptance Criteria

 * When searching from "edit page" context, go to filtered list view
 * When in filtered list view and clicking on "tree", go to unfiltered tree view (don't pass along search parameters)

## Related

 * [Update CMS search functionality to match the newer UI of Files area ](https://github.com/silverstripe/silverstripe-cms/issues/1777)
 * [Use React-based TreeDropdownField in non-React sections](https://github.com/silverstripe/silverstripe-admin/issues/142)

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-admin/pull/205
- [x] https://github.com/silverstripe/silverstripe-cms/pull/1933/

**Comment by chillu** [comment]
Paul has already created designs for this in https://github.com/silverstripe/silverstripe-cms/issues/632. Neither the designs nor the ACs specified what should happen when you click on a search result in that list view. I'm now proposing that it shouldn't show a filtered tree. Your designs also had no way to toggle back from the list view to the tree view. Overall, I want to get rid of any display of a filtered tree, in order to simplify the implementation of this in core going forward.

I've added the following ACs:

 * When searching from "edit page" context, go to filtered list view
 * When in filtered list view and clicking on "tree", go to unfiltered tree view (don't pass along search parameters)

**Comment by clarkepaul** [comment]
@ingo 
> When in filtered list view and clicking on "tree", go to unfiltered tree view (don't pass along search parameters)
I think we should just remove the tree icon altogether as the clear button should really take you back to the tree.

**Comment by newleeland** [comment]
Prototype: https://projects.invisionapp.com/share/ZACM32DPC#/screens/244049029_Pages_Search_Results_1_Tree
