### ISSUE TITLE
SS4: Link to a page requires "Access to all CMS sections"

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-cms#1938]
It seems a user has to have "Access to all CMS sections" in order to use the "Link to a page" function. Even if all other "CMS Access" options are ticked, the modal remains empty unless that user has been given (explicitly) "Access to all CMS sections".

Using SS4-beta-2

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/215

**Comment by chillu** [comment]
Confirmed - raising to `impact/critical`. Linking to pages with autor permissions is kinda crucial :D
