### ISSUE TITLE
SS4: Cached sitetree is being displayed after editing a page

### ISSUE THREAD

**Issue by mikenz** [silverstripe/silverstripe-cms#1939]
On a stock SS4 install:

Log in as admin and click on a couple of pages in the tree until it refreshes the tree (tree will flash).
Click on a published page (eg "Contact Us")
Edit the Page name (eg "Contact Us edited") and "Save" this.
The tree will show the new page name and badge (eg "Contact Us edited  MODIFIED")
Click on another page in the tree (eg "Page not found")
The tree will revert back to before the edit (eg "Contact Us")
Click on the edited page again the tree will be correct,
Click on another page the tree will return to the unedited cached version.

Caching/refreshing issue after editing?

**Comment by chillu** [comment]
Hey Mike, thanks for reporting! I've had a hard time reproducing this a couple of days ago, hence didn't respond immediately. Note that this issue might currently be masked by a regression which triggers the `treeview` load on every page edit view: https://github.com/silverstripe/silverstripe-cms/issues/1949

FYI, you might be interested in installing the Zenhub.com Chrome Extension, which shows you a bit more activity around how we prioritise work :) I've moved this issue into our "Next" column 4 days ago, which means we'll get around to it very soon.

![image](https://user-images.githubusercontent.com/111025/30009464-af9634a2-917c-11e7-8a6b-eaefa0461c71.png)

**Comment by flamerohr** [comment]
to replicate, you can do these steps:
1) open a page "Contact"
2) open a different page "About"
3) make a change and save on "About" so that the label "modified" appears
4) browse to "Contact" and you'll see the "modified" disappears for the "About" page

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-cms/pull/1950

**Comment by sminnee** [comment]
@mikenz are you able to confirm that this is fixed for you in 4.x-dev now, in your project as well as a clean install?
