### ISSUE TITLE
CMS Settings->Access editor group dropdown list not visible 

### ISSUE THREAD

**Issue by vinstah** [silverstripe/silverstripe-cms#1940]
I just tested SS4 on the demo site https://ss4-demo.silverstripe.org/admin/settings/

Noticed that if you click on the editor group you can't see the list of groups. 
On Form_EditForm_EditorGroups_Holder there is style="overflow: hidden;"  and if I remove the style it displays correctly

Chrome Version 60.0.3112.90 (Official Build) (64-bit)
OS Linux Mint 18.1

![security_access](https://user-images.githubusercontent.com/4538082/29845733-15e9c4ee-8d68-11e7-8efe-546d3839da2e.png)

**Comment by tractorcow** [comment]
Thanks, this issue has been fixed in the latest beta. The demo you tested is still alpha7, and is a bit out of date I'm afraid. :)
