### ISSUE TITLE
SS4: Add new / Batch Actions / List view misaligned when SiteTree list has scroll

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-cms#1946]
When the SiteTree column overflows (scrolls) the scrollbar pushes the top page actions out of alignment. Reproducible in both Firefox and Chrome (Linux).

![screen shot 2017-09-01 at 12 14 17-fullpage](https://user-images.githubusercontent.com/1463435/29950454-0607a2ae-8f10-11e7-86f4-6bdcdd015402.png)

**Comment by axllent** [comment]
Closing this as it seems no longer an issue

**Comment by lerni** [comment]
Depending on length (translation), it still doesn't align but with current styles probable not worth fixing :relieved:


https://github.com/silverstripe/silverstripe-cms/assets/472115/680b1b03-8cd1-468b-86d3-ba71da422832
