### ISSUE TITLE
SS4: Cannot create tel: link in TinyMCE

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-cms#1947]
`Link to external URL` does not allow linking to a `tel:<number>` type of link, or rather it prefixes the link automatically with `http://` (possibly because it doesn't contain a `://`?).

**Comment by justinluk** [comment]
Running into the same issue. My solution requires me to edit the link directly in the HTML view.

**Comment by scott1702** [comment]
Workaround for now is to install a thirdparty module https://github.com/firebrandhq/silverstripe-phonelink

**Comment by GuySartorelli** [comment]
I'm going to close this issue given that this isn't actually a bug with the existing functionality (it's not an external URL at all, so it makes sense that external URL wouldn't treat it as you might want it to), and there's a module providing this functionality.

It would be great to have that plugin available in core, and I'd wholeheartedly support a pull request implementing that, but for the time being this is not something the CMS Squad is going to be working on.
