### ISSUE TITLE
Admin- SiteTree - Ability to move mutiple pages in the site tree.

### ISSUE THREAD

**Issue by mithungc** [silverstripe/silverstripe-cms#1951]
Currently can only drag and drop one page at a time in SS4, in-order to change it's location in the sitetree. Require the ability to select multiple pages and move them together to a different location in the sitetree.

Note - In SS2, a checkbox was available to select multiple pages in-order to move them.

**Comment by dhensby** [comment]
Hi, thanks for taking the time to post to our issue tracker.

The issue tracker is intended to be used for reporting bugs and not for feature requests or discussions.

If you'd like to request a feature please see our [user voice page](https://silverstripe.uservoice.com) where you can submit your ideas.

If you feel you're capable of solving this problem and submitting a pull request with this feature added, please do so and a member of the team will review it.

If you'd like to discuss a feature idea before submitting a PR, please submit it to our [mailing list](https://groups.google.com/forum/#!forum/silverstripe-dev)

Thanks for taking the time to make this suggestion.
