### ISSUE TITLE
SiteTree Search - "Tree View" icon doesn't work for search results page

### ISSUE THREAD

**Issue by mithungc** [silverstripe/silverstripe-cms#1958]
On utilizing the 'SiteTree Search' in Admin, the results are displayed in the 'List View'.

Attempting to switch to the 'Tree View' does not work, i.e. clicking the 'Tree View' button, either does not work or redirects back to the 'Admin-Pages'.

Also, accessing a page/search-result in 'List view' opens the page with the 'Tree view' visible, but the 'Search Results' are lost.

Note - Image attached for reference
Version - SS4
![treeview](https://user-images.githubusercontent.com/28516403/30254674-2910e70a-96f0-11e7-9dfd-33c3951b9990.JPG)

**Comment by flamerohr** [comment]
Hi @mithungc,
this is an intentional change https://github.com/silverstripe/silverstripe-cms/issues/1926 to enforce search to use the list view - as it opens the path for us to simplify the API.

Would you be able to provide what use case you have that requires using the tree view while searching?

**Comment by dhensby** [comment]
We should remove the tree view icon from search results of it's not intended to work.

I think users like to see results in tree view because it's how they consume the site tree 99% of the time and it's more intuitive to view it in its logical heirachy than as a list

**Comment by mithungc** [comment]
Hi @flamerohr ,
My general use case involves having the 'Search-Results' open in 'TreeView', so that I can view and work through multiple pages. I am unable to do this in 'List View', as clicking on one of the search-results directly opens the page and the 'Search-results list' is gone.

**Comment by clarkepaul** [comment]
I've raised an issue https://github.com/silverstripe/silverstripe-cms/issues/1978 to remove the icon/toggle as this is an intentional change for now and the icon should have been removed but seems to have been missed :/ 
The tree could be reinstated at some stage but this is still up for discussion, for now it hasn't been identified as priority enough.

**Comment by flamerohr** [comment]
The icon has been removed
https://github.com/silverstripe/silverstripe-cms/pull/1992
