### ISSUE TITLE
Discussion on removing/replacing React due to patents clause

### ISSUE THREAD

**Issue by nspyke** [silverstripe/silverstripe-cms#1971]
If you're not already aware, Facebook has included in the licensing of React to also include Patents. 
https://github.com/facebook/react/blob/master/PATENTS
https://code.facebook.com/posts/112130496157735/explaining-react-s-license/

From what I understand of that, (I'm no lawyer), it means that anyone using React and thereby SilverStripe must grant all software rights to Facebook if they want to continue using React. I think SilverStripe Ltd should consult with their lawyers to find out exactly what the implications of the licence means.

In New Zealand, this may be irrelevant as software can not be patented, but for the wider international community, the use of React in the new version of SilverStripe could end up being a negative feature instead of the intended positive.

WordPress has decided to remove it: https://ma.tt/2017/09/on-react-and-wordpress/

Why should we as the community have to accept that clause to continue using our favourite CMS? Why should our clients have to accept it?

**Comment by dhensby** [comment]
Thanks @nspyke - SilverStripe Ltd are aware of the situation and are looking into it. At the moment I can't give many specifics.

@sminnee may be able to soon.

**Comment by dhensby** [comment]
> From what I understand of that, (I'm no lawyer), it means that anyone using React and thereby SilverStripe must grant all software rights to Facebook if they want to continue using React.

I'm not really sure where this interpretation has come from, though - nothing I can read from the licence implies anything about surrendering software rights to FB

**Comment by flamerohr** [comment]
> From what I understand of that, (I'm no lawyer), it means that anyone using React and thereby SilverStripe must grant all software rights to Facebook if they want to continue using React.
...that's a misunderstanding, although the fears around it is pretty similar to that effect.

It's closer to say that your right to continue to use React in your software is revoked if you choose to sue Facebook for any reason.
The fears lies in the "any reason" part, if Facebook chooses to do is legitimate cause for you to sue them, then you better make sure your software is moved off React before you take action.

**Comment by dhensby** [comment]
> It's closer to say that your right to continue to use React in your software is revoked if you choose to sue Facebook for any reason.

If you choose to sue them over a patent in React... basically you'd fall back to having to pay to licence their patents instead of being given them for free if you tried to sue them over the patent.

It even excludes suing over patents on other FB software.

**Comment by flamerohr** [comment]
I don't really have that understanding from reading the patent clause, but maybe I missed a few keywords in all that lawyer text.

in any case, it's an interesting fear, and has been discussed at length in other forums... none of which had come to any conclusion until a few months ago.

**Comment by sminnee** [comment]
I'm going to investigate this and I'll respond on this ticket once I have.

**Comment by nspyke** [comment]
Thanks @sminnee . I really appreciate this being taken seriously.

**Comment by nspyke** [comment]
Looks like Facebook has taken the feedback on and are relicensing React to MIT.
https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/

Let's hope they don't decide to go back  on this decision  and change it again!

**Comment by GuySartorelli** [comment]
Closing as this sounds like a non-issue now
