### ISSUE TITLE
[bug] When creating and publishing a new page, the "are you sure you want to navigate away" notification pops up

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-cms#1975]
Steps to reproduce:
- Go in to the CMS
- Create a new page
- Hit `Save & Publish`

Observation:
The page asks if you are sure you want to navigate away

Expected:
The page is saved without a notification

The same behaviour pops up when not changing anything on a page and navigating away

**Comment by bendubuisson** [comment]
☝️ on SS4...

**Comment by chillu** [comment]
I think that's since been fixed, can't reproduce on 4.x with Chrome 57

**Comment by guyvanbael** [comment]
this issue is still happening with 4.1.2.  Clicking the save button for the first time saves the page (getting saved message), but the butons stays green. When navigating away the popup appears. Reloading the page fixes it. (i'm on chrome 67 on osx)

**Comment by robbieaverill** [comment]
@guyvanbael which other modules are you using? We've seen this issue in combination with other modules before but I haven't tracked it down to a specific place yet 😄 related: https://github.com/silverstripe/silverstripe-subsites/issues/355

FYI I created a Behat test that proves this bug in subsites context with a bunch of other modules (like fluent), but it passes in isolation with subsites only.

We also have tonnes of Behat tests in CMS already that are testing this behaviour works.

**Comment by guyvanbael** [comment]
@robbieaverill This is my composer.json (it's pretty average)
{
    "name": "silverstripe/installer",
    "type": "silverstripe-recipe",
    "description": "The SilverStripe Framework Installer",
    "require": {
        "php": ">=5.6.0",
        "silverstripe/recipe-plugin": "^1",
        "silverstripe/recipe-cms": "1.1.2@stable",
        "silverstripe-themes/simple": "~3.2.0",
        "axllent/silverstripe-email-obfuscator": "^2.0",
        "wilr/silverstripe-googlesitemaps": "^2.1",
        "colymba/gridfield-bulk-editing-tools": "dev-master",
        "silverstripe/userforms": "^5.2",
        "undefinedoffset/silverstripe-nocaptcha": "^2.0"
    },
    "require-dev": {
        "phpunit/phpunit": "^5.7"
    },
    "extra": {
        "branch-alias": {
            "4.x-dev": "4.2.x-dev",
            "dev-master": "5.x-dev"
        },
        "project-files-installed": [
            "mysite/.htaccess",
            "mysite/_config.php",
            "mysite/_config/mysite.yml",
            "mysite/code/Page.php",
            "mysite/code/PageController.php"
        ],
        "public-files-installed": [
            ".htaccess",
            "index.php",
            "install-frameworkmissing.html",
            "install.php",
            "web.config"
        ],
        "expose": [
            "themes/rurant"
        ]
    },
    "config": {
        "process-timeout": 600
    },
    "prefer-stable": true,
    "minimum-stability": "dev"
}

**Comment by guyvanbael** [comment]
any news on this?

**Comment by maxime-rainville** [comment]
That should be fixed in the next release.
