### ISSUE TITLE
RFC CMS module without versioning

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-cms#1984]
It should be possible to implement a CMS + SiteTree powered website without the versioned module.

# Acceptance Criteria:

 - All modules required by CMS module don't require versioning (including assets module)
 - All changes made to the sitetree are immediately live
 - Terminology such as "archive" is changed to "delete" as appropriate to represent the lack of a version archive.
 - All features that require versioning (e.g. page history, publish, etc) are disabled. This could either by conditionally disabled, or split into a `silverstripe/cms-versioned` extensions module.

**Comment by tractorcow** [comment]
The earliest I could see this is 4.1, but it could be as late as 5.0.

@chillu do you want to comment on this? Note the above A/C are super tentative.

**Comment by sminnee** [comment]
I don’t quite see who’s problem this solves.

**Comment by sminnee** [comment]
Perhaps update the RFC to have more of the “why” as well as the “what”. Who’s going a problem with the current approach that would be solved by removing versioning?

**Comment by chillu** [comment]
Removing milestone until the purpose is clarified. I agree that the level of versioning we push in 4.x will cause friction with many developers, but let's not throw out the baby with the bathwater :) I suspect this would be more than a team's week of work, and cause ongoing friction by considering this variation in every UI and interaction we build - so want to gather more feedback from the community before committing to this in any shape.

**Comment by tractorcow** [comment]
One of my own concerns is coupling; Versioned should be an enhancement to CMS, not a dependency. The less coupling there is, the less fragility between modules.

We've done well up until now to move versioned-specific behaviour into the versioned module, so it's getting close to being able to soften the coupling.

**Comment by chillu** [comment]
We've already decoupled core to a dozen modules in 4.x (which was 1-2 months of team time over the last 1.5 years). So I'm quite wary of going down this road again - it seems like quite a large investment. What organisations and author groups are we targeting that you'd expect to have a "save = published" mentality? I know that Wordpress runs half of the internet with a simple "published" checkbox, and that we're going quite far down the rabbit hole of versioning hell at the moment - but trimming it all the way back to "no versioning at all" doesn't seem to serve much of a practical purpose. That's less than Wordpress provides out of the box.

**Comment by sminnee** [comment]
> What organisations and author groups are we targeting that you'd expect to have a "save = published" mentality?

I think that having a Bill O'Reilly mode ("fk it we'll do it live") as a core feature of the CMS would be much more valuable: let a user switch to live editing, with clear UI indications, for the duration of a session. I think this would address the user need of people who are confused by draft in a less impactful way (do get this feature delete all your draft content & version history and make a significant schema change)

Related to that "always apply edits to a specific campaign" would be a nice companion feature.

I'd seriously question whether decoupling Versioned from CMS will improve the code maintainability: it will recreate a lot of parallel execution paths, one of which is likely to rarely get tested.

PS: "Edit Live" means "Edit both Draft & live simultaneously" in all relevant discussions. This was a point of confusion in a previous comment of mine ;-)

**Comment by tractorcow** [comment]
Ok, given the relative difficulty and low necessity, I'll close this for now.

**Comment by tractorcow** [comment]
Related issue https://github.com/silverstripe/silverstripe-cms/issues/721

Relevant comment:

> While the draft option in SS is awesome, you will find that 85%+ of people working with the CMS will save and publish rather than just save in most instances. Hence, they will be unfamiliar with the concept of a draft page.
