### ISSUE TITLE
Rolling back a deleted page to a specific version causes an error

### ISSUE THREAD

**Issue by sb-relaxt-at** [silverstripe/silverstripe-cms#1995]
Steps to reproduce in SilverStripe 3:
* Create a page
* Change something in order to generate a new version
* Delete the page
* Select an older version in the history tab
* Click on "Back to this version"

There will be an uncaught error "Call to a member function doRollbackTo() on boolean", as in [CMSMain#doRollback](https://github.com/silverstripe/silverstripe-cms/blob/50a9a5de6be012e15d016cc2ed83122e359e0bdc/code/controllers/CMSMain.php#L1250) it is assumed that the record can be fetched via `DataObject::get_by_id`. It might be possible that this issue also affects SilverStripe 4, as the relevant code seems to be unchanged.

## Pull requests
- [x] https://github.com/silverstripe/silverstripe-cms/pull/1999
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2000

**Comment by tractorcow** [comment]
Can confirm, this is a real bug in both versions.

**Comment by tractorcow** [comment]
Fixed for ss4 with https://github.com/silverstripe/silverstripe-cms/pull/1999
