### ISSUE TITLE
Security Members GridField search filters don't work

### ISSUE THREAD

**Issue by nimeso** [silverstripe/silverstripe-cms#2002]
The search/filter bar in the Security/Members tab is not working. I can't type anywhere?
![capture](https://user-images.githubusercontent.com/1796069/31973427-54e9bb54-b982-11e7-981f-568786fe8a75.PNG)

**Comment by tractorcow** [comment]
Which framework / cms version are you running?

**Comment by tractorcow** [comment]
Testing with current 3.6 version works for me locally.

![image](https://user-images.githubusercontent.com/936064/31975626-12a58a54-b98f-11e7-89cc-a840e02ae9b5.png)

Do you have a javascript console error?

**Comment by nimeso** [comment]
Thanks @tractorcow 

I'm on 3.6 and no console errors :( This is in Chrome BTW
The only thing I can think of is that I have extended Member here is the extension:
`<?php
class Student extends DataExtension{
	
	public static $db = array(
		"UID" => "Varchar(128)",
		"IsStudent" => "Boolean",
		"Phone" => "Varchar(128)",
		"Misson" => "Varchar(256)",
		"Reference" => "Varchar(512)",
		"ReferenceName" => "Varchar(128)",
		"ReferencePosition" => "Varchar(128)",
		"LinkedInURL" => "Varchar(256)",
		"TwitterURL" => "Varchar(256)",
		"FacebookURL" => "Varchar(256)",
		"PortfolioURL" => "Varchar(256)",
		"BlogURL" => "Varchar(256)",
		"PersonalityType" => "Varchar(256)",
		"StudentID" => "Varchar(528)",
		"ForgottenPasswordHash" => "Varchar(8)",
		"FirstTime" => "Boolean",
		"ConfirmCode" => "Varchar(256)",
		"Confirmed" => "Int",
		"IsStudent" => "Boolean",
		"IsTutor" => "Boolean",
		"IsOrganization" => "Boolean",
		"OrganizationSize" => "Varchar(256)",
		"Organization" => "Varchar(256)",
		"AllowOrganizations" => "Boolean"
	);
	
	public static $has_one= array(
		"Photo" => "Image",
		"CV" => "File",
		"AraCourse" => "AraCourse"
	);
	
	public static $has_many = array(
		"StudentQuests" => "StudentQuest"
	);
	
	public static $summary_fields = array( 
		'FullName' => "Full Name",
		'EmailAddress' => "Email",
		"AraCourseTitle" => "Ara Course"
    );
    
    private static $casting = array(
        'FullName' => 'Text', 
        'EmailAddress' => 'Text',
        'AraCourseTitle' => 'Text'
    );
	
	public function getCMSFields(){
		$fields = parent::getCMSFields();
		return $fields;
	}

    public function updateSummaryFields(&$fields) {
        $fields = self::$summary_fields;
    }
    
    public function getAraCourseTitle(){
    	if($course = AraCourse::get()->where(array("ID" => $this->owner->AraCourseID))->exists() ){
    		return AraCourse::get()->where(array("ID" => $this->owner->AraCourseID))->first()->Title;
    	}
    	return "No course choosen";
    }

	public function getFullName() {
        return $this->owner->FirstName . ' ' . $this->owner->Surname; 
    }

    public function getEmailAddress() {
        return $this->owner->Email; 
    }
    
    public function onBeforeWrite(){
    	if(!$this->owner->UID){
    		$uid = $this->owner->generate_uuid();
    		$this->owner->UID = $uid;
    	}
	}
    
	function generate_uuid() {
		return sprintf( '%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
			mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ),
			mt_rand( 0, 0xffff ),
			mt_rand( 0, 0x0fff ) | 0x4000,
			mt_rand( 0, 0x3fff ) | 0x8000,
			mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff )
		);
	}
	
	public function onAfterSerialize( &$formattedDataObjectMap ){
		
  		if($this->owner->Photo()->exists()){
  			$formattedDataObjectMap["PhotoLink"] = $this->owner->Photo()->CroppedImage(256,256)->getAbsoluteURL();
  		}else{
  			$siteConfig = SiteConfig::current_site_config(); 
  			$formattedDataObjectMap["PhotoLink"] = $siteConfig->DefaultAvatar()->CroppedImage(320,320)->getAbsoluteURL();
  		}
  		
		if($this->owner->Photo()->exists()){
  			$formattedDataObjectMap["PhotoLinkFileName"] = $this->owner->Photo()->Name;
  		}
  		
		if($this->owner->CV()->exists()){
  			$formattedDataObjectMap["CVFileName"] = $this->owner->CV()->Name;
  			$formattedDataObjectMap["CVFileURL"] = $this->owner->CV()->getAbsoluteURL();
  		}
  		
		if($this->owner->AraCourse()->exists()){
  			$formattedDataObjectMap["AraCourseName"] = $this->owner->AraCourse()->Title;
  		}
  	}
	
}
`

**Comment by nimeso** [comment]
I'm not getting any inputs in the DOM as well.
![capture2](https://user-images.githubusercontent.com/1796069/31977551-eebd5422-b999-11e7-9ad8-26896a948bfb.PNG)

**Comment by nimeso** [comment]
Also not working in 'Groups' BUT it is working in 'Roles' ... strange.
![capture3](https://user-images.githubusercontent.com/1796069/31977634-435e7ed4-b99a-11e7-9f5f-29197ee350bd.PNG)

**Comment by dhensby** [comment]
I think you need to define your `searchable_fields` or `defaultSearchContext` for your student. You're not using DB columns as your summary fields

**Comment by tractorcow** [comment]
All of your public statics should be private static.

Remove updateSummaryFields()

As @dhensby stated, none of the summary fields are DB fields. E.g. if you use `Email` you'll get a search box, but not for `EmailAddress`

I don't understand the need to alias Email as EmailAddress.
