### ISSUE TITLE
New to Silverstripe - How To Install The CMS ??

### ISSUE THREAD

**Issue by Mu9tafa-Online** [silverstripe/silverstripe-cms#2005]
Hello every one - i wanna install "SS4 CMS" but i think i did something wrong. I downloaded "SS4-RC-1" and i extracted the files into my localhost.. i checked the guide and i don't understand what to do here:

![ss4](https://user-images.githubusercontent.com/5323832/32115569-0261a0de-bb50-11e7-8320-8de87bcdcf31.PNG)
.
and this is my localhost files:
.
![ss4_loca](https://user-images.githubusercontent.com/5323832/32115632-37b4ba00-bb50-11e7-844e-f30001edb559.PNG)

**Comment by robbieaverill** [comment]
@Mu9tafa-Online where did you download it from? silverstripe.org? It's possible that it's shipping with an incorrect htaccess file.

**Comment by Mu9tafa-Online** [comment]
Yes I downloaded it from silverstripe.org

**Comment by Mu9tafa-Online** [comment]
i visit localhost/ss4/index.php - and it's work fine .. i tried it last week too .. Everything is fine now :) Thaanx
