### ISSUE TITLE
SS3.6.2 : $summary_fields are appearing twice in GridField header

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-cms#2006]
I created an extension to `Member` and it contains the following code:
```php
    private static $db = array(
        'MembershipExpiry' => 'Varchar',
        'MembershipType' => 'Varchar'
    );

    private static $summary_fields = array(
        'MembershipExpiry' => 'Membership Expiry',
        'MembershipType' => 'Membership Type',
        'MembershipStatus' => 'Membership Status'
    );
```
`MembershipStatus` is a public method computing the membership status dynamically. When viewed in the CMS, the `$summary_fields` are doubled up, with the data only displayed for one instance of the summary fields:

![screenshot from 2017-10-28 23-09-44](https://user-images.githubusercontent.com/8912185/32133531-4b53506c-bc36-11e7-83b5-60180601eb40.png)
 
## Pull requests 
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7893

**Comment by lerni** [comment]
@SpiritLevel - a workaround: https://stackoverflow.com/questions/24418459/how-to-i-modify-or-remove-existing-summary-fields-when-extending-an-object-in-si
