### ISSUE TITLE
SS4 "Cancel draft changes" no longer has a confirmation message

### ISSUE THREAD

**Issue by mikenz** [silverstripe/silverstripe-cms#2009]
This commit: https://github.com/silverstripe/silverstripe-cms/commit/689c198fbecefe7fb73e035184314bb0fa21af06#diff-dc69c38bbf03559bf33058339b8ced29

Removed the confirmation message from the "Cancel draft changes" action. This appears to be unexpected?

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-cms/pull/2014

**Comment by flamerohr** [comment]
Good catch, looks like both `.cms-edit-form .btn-toolbar #Form_EditForm_action_doRollback` and `.cms-edit-form .btn-toolbar #Form_EditForm_action_rollback` selectors are needed and used...

The joys of having two very different functions using the same name...
