### ISSUE TITLE
Remember "list" view preference in "pages" section

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-cms#2012]
# Overview

The pages list view is a very useful way to navigate websites, particularly when they have a large amount of pages (both with a shallow or deep IA). These lists can be filtered and sorted in ways that the tree can't. 

# Acceptance Criteria

 * As a content author, when choosing the list view in the "pages" section, my preference gets remembers the next time I'm navigating to the section
 * When navigating back from an edit page view, the preference is remembered
 * When viewing the tree, the view preference is unset again
 * When loading the CMS, I can interact with pages as quickly as before (meaning the list view gets lazy loaded before tree view)
 * The preference is remembered per device

# Notes

 * Excludes remembering sort/filter criteria
 * This shouldn't be implemented through cookies because it's adding data to every request, incl. assets. We should do this via local storage.
 * This is one piece of the puzzle for decreasing our reliance on a full-featured tree (after replacing TreeDropdownField with a list-based approach). The tree is really hard to maintain, and the jstree library is outdated and too complex for us to keep up with.

# Related

 * [Page edit mode - list/tree toggle](https://github.com/silverstripe/silverstripe-cms/issues/1664)

## Pull requests

- [ ] https://github.com/silverstripe/silverstripe-cms/pull/2049
- [x] https://github.com/silverstripe/silverstripe-admin/pull/375

**Comment by tractorcow** [comment]
Approved and tested; Can be merged on green. Will check back later. :)
