### ISSUE TITLE
Loss of GridField click-to-view functionality after switching tabs

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-cms#2015]
Basically, u lose grid field click functionality after switching to-and-fro tabs

You can click the edit button, but clicking the row does nothing after switching tabs

![26opi4cnus](https://user-images.githubusercontent.com/13566916/32357186-4aca9642-c09f-11e7-876d-5f3677d52b83.gif)

**Comment by zanderwar** [comment]
This may be related to: This may be related symbiote/silverstripe-gridfieldextensions/issues/222 The "Image Categories" section utilizes `GridFieldOrderableRows`

**Comment by tractorcow** [comment]
Closing since this is the fault of gridfield extensions module.

**Comment by unclecheese** [comment]
I'm only able to reproduce this issue with `GridFieldOrderableRows` added. @zanderwar can you confirm that the issue disappears when your remove that module?

**Comment by unclecheese** [comment]
Moving to blocked until we hear confirmation from the OP

**Comment by zanderwar** [comment]
Confirmed, `GridFieldOrderableRows` is the culprit
