### ISSUE TITLE
'Add from files' on a many_many field only allows the selection of a single file

### ISSUE THREAD

**Issue by DorsetDigital** [silverstripe/silverstripe-cms#2019]
SS4 Stable

I have a page with a `many_many` relationship to `Image`
In the CMS, it is possible to drag & drop multiple files to the `UploadField` as expected.

If you choose 'Add from files', the file selection popup appears, but it is only possible to select a single file at a time.   I would expect to see the checkbox functionality here so I can add multiple files in one operation.

**Comment by kinglozzer** [comment]
This issue was moved to silverstripe/silverstripe-asset-admin#693
