### ISSUE TITLE
SS4: GridField formatting and summary_fields bug in SecurityAdmin

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-cms#2020]
As in SS3.6.2 and reported [here](https://github.com/silverstripe/silverstripe-cms/issues/2006), the summary fields are getting doubled up in SecurityAdmin for SS4 as well. 

In addition, the formatting for the GridField is cutting off content on the left:

![screenshot from 2017-11-10 17-42-32](https://user-images.githubusercontent.com/8912185/32643278-343b46ce-c63f-11e7-8a5a-1d4cccf35c26.png)

Edit: this formatting problem only arises when on a laptop with 1366x768 resolution; it is fine on a screen with resolution 1920x1080.

**Comment by dhensby** [comment]
is this issue resolved?
