### ISSUE TITLE
Add page problem in other language

### ISSUE THREAD

**Issue by MohammaddReza** [silverstripe/silverstripe-cms#2022]
the system showing the Internal Server Error when i wants to create new page in other language (im using persian)

**Comment by MohammaddReza** [comment]
Emergency] Uncaught InvalidArgumentException: Invalid date: '0000-00-00 00:00:00'. Use y-MM-dd to prevent this error.

**Comment by flamerohr** [comment]
Created a pull request to at least address the "server error", the root cause of the issue has yet to be fleshed out.

https://github.com/silverstripe/silverstripe-framework/pull/7599
