### ISSUE TITLE
List view of pages alignment and layout improvements

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#2025]
* Column headers without sort have different padding and text colour.
* Column headers with sort don't have a cursor pointer to show its clickable.
* Up arrow is placed weirdly (move to table header?
<img width="550" alt="pasted_image_14_11_17__7_33_pm" src="https://user-images.githubusercontent.com/555033/32766522-3d7fc254-c974-11e7-8b72-d27f444694ea.png">
) 

Related, sorted column headers should have blue underline not green. https://github.com/silverstripe/silverstripe-admin/issues/266
![image](https://user-images.githubusercontent.com/555033/32766746-20cf6514-c975-11e7-9cd5-63afce94974d.png)

**Comment by Cheddam** [comment]
All of the described issues seem to have been resolved (the adjustment of the up arrow is up for PR in #2546)

![image.png](https://images.zenhubusercontent.com/58ce3d9c51aa2c305778db1b/29f8e036-aa6a-4c24-ae0d-afdc0e49437b)

Closing this out.
