### ISSUE TITLE
The Translation not working

### ISSUE THREAD

**Issue by Misagh90** [silverstripe/silverstripe-cms#2038]
Hi,
Some Translation doesn't change
For example the tranlation does not change in right click on pages
![2017-11-23_15-13-18](https://user-images.githubusercontent.com/6697222/33171900-3f7e8d24-d063-11e7-86d8-88df0886b75a.jpg)
![2017-11-23_15-28-11](https://user-images.githubusercontent.com/6697222/33171965-84d1f172-d063-11e7-98a8-acaf6034bff0.jpg)
in some cases the "_t" is exist but there is no String to translate
![2017-11-23_15-28-47](https://user-images.githubusercontent.com/6697222/33172029-c8b1991a-d063-11e7-8197-2f9ceacfd7eb.jpg)

**Comment by dhensby** [comment]
The translations may well be missing, if you go to https://www.transifex.com/silverstripe/silverstripe-cms/translate/ you should be able to help provide them :)

**Comment by Misagh90** [comment]
No, I complete every thing (yml, js & json)
i'll send it to transifex

**Comment by chillu** [comment]
We periodically sync with transifex on every release, so there's going to be a delay in those translations showing up. Can you check the specific translation keys used by the UI, and if those are present in the `<module>/lang` or `<module>/client/lang` folders for your language? This might be in the `admin` or `kms` module-

**Comment by tractorcow** [comment]
Sometimes i18n JS strings can go missing, and since there is no text collector equivalent for those then it could be a real error.

**Comment by ramono** [comment]
I'm having the same problem with Spanish, and I actually wanted to go ahead and help with the missing translations but I can't find the page (above link gives me 404) so I'm not sure how to go about translating them :/

**Comment by tractorcow** [comment]
@ramono do you have a transifex account? I'll add you as a spanish translator if you like.

**Comment by ramono** [comment]
Yes please, I'd like to help with Spanish translations. Thanks.

My account/profile is https://www.transifex.com/user/profile/ramono/

**Comment by tractorcow** [comment]
I've added you as a reviewer as all-modules spanish. :D

**Comment by robbieaverill** [comment]
Hi everyone, synchronising translations from Transifex into the core repositories is part of each release process. I'll assume that these issues have been resolved if the translations have been completed upstream and close this issue accordingly. Feel free to reopen if anyone if having an issue with an existing translation language pack that isn't working in the CMS!
