### ISSUE TITLE
silverstripe 4 VirtualPage doesn't find correct template

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-cms#2039]
_From @cansozeri on November 27, 2017 21:27_

I have created a page from Article page type and I have Article.ss Layout. 

I have created a virtual page that points to Article page. But VirtualPage doesn't find correct template and use Page.ss when loading this virtual link. Content loaded but with page.ss not with article.ss.

_Copied from original issue: silverstripe/silverstripe-framework#7652_

**Comment by kinglozzer** [comment]
I can recreate this, but annoyingly I can’t capture it in a unit test:

```php
$page = new VirtualPageTest_ClassB();
$page->Title = 'Test Page B';
$page->write();
$vp = new VirtualPage();
$vp->CopyContentFromID = $page->ID;
$vp->write();
$response = $this->get($vp->Link());
$this->assertEquals(200, $response->getStatusCode());
$this->assertContains('Test Page B', $response->getBody());
```

Annoyingly, `$vp->Link()` returns a link to the target page, and not the virtual page. I think that’s probably a bug, given that `URLSegment` is explicitly marked in `$non_virtual_fields`.

**Comment by dhensby** [comment]
Hmm, `Link` != `URLSegment` - you'd expect the link in a template (ie: using `$Link`) to link to the destination page and not the `VirtualPage`, right? or do `VirtualPage`s sit in their place in the heirachy but just copy content from another page into the new one?

**Comment by kinglozzer** [comment]
I’d expect that you’d directly access the `VirtualPage` at its URL, and just see the content from the target page. Otherwise it’s just a `RedirectorPage` by a different name 😉

**Comment by cansozeri** [comment]
@kinglozzer yeah I want to see just the target page exactly ... So it has to be render with target layout page.

**Comment by kinglozzer** [comment]
PR incoming, it introduces a new API but unfortunately we can’t avoid that 😞

**Comment by flamerohr** [comment]
I've put this against the 4.1 milestone, but if it fits in with the 4.0 branch then we could shift it there instead

**Comment by cansozeri** [comment]
Please add to repo so we can update it, I am gonna use this virtual Page on a project.
