### ISSUE TITLE
BUG pages/add allowed page-types list not updating

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-cms#2042]
In SS4, page types that are restricted via $allowed_children can't be added through admin/pages/add - there are no JS errors in console showing up

I have the following setup

`PageLanding` has
```php
private static $allowed_children = [ProjectPage::class];
```

`ProjectPage` has
```php
private static $can_be_root = false;
```

When on admin/pages/add in the CMS the `ProjectPage` page-type remains disabled
![image](https://user-images.githubusercontent.com/178039/33373414-bbf5b680-d4f9-11e7-912c-feaa29506c7f.png)

I am able to add the `ProjectPage` page-type via right clicking on the `ProjectsLanding` page which correctly only lists the only available option as `ProjectPage`

**Comment by flamerohr** [comment]
Thanks @christopherdarling for the report.
Please checkout the latest `1` branch in `silverstripe/cms` this has been addressed but not released yet :)

**Comment by christopherdarling** [comment]
Thanks @flamerohr - I've updated recipie-cms to 1.0.x-dev and can confirm this is now working

**Comment by gorriecoe** [comment]
Has this been released to a stable version yet?

**Comment by flamerohr** [comment]
yes it has, I don't remember which version though sorry
