### ISSUE TITLE
RFC: Add "RootURLController::is_home_page(SiteTree $page)" function.

### ISSUE THREAD

**Issue by silbinarywolf** [silverstripe/silverstripe-cms#2051]
**Why?**
Currently to support Multisites, I need to write code like this to ensure a page is actually a home page:
```
protected function isHomePage(\SiteTree $page)
{
    $parent = $page->Parent();
    return $page->URLSegment === 'home' && ((class_exists('Site') && $parent instanceof \Site) || !$parent->exists());
}
```

source:
https://github.com/silbinarywolf/silverstripe-oldman/blob/master/src/Cloudflare.php#L276

**Proposed solution:**
- Create a function with the signature: `RootURLController::is_home_page(SiteTree $page)`
- Uses existing `RootURLController::get_homepage_link` function and compares to the $page-Link(), which will return a boolean $result value.
- This $result value will be fed through an extension point `$this->extend('updateIsHomePage', &$result);` wherein modules like Multisites can modify whether it's actually on the home page or not.
- Write unit test to cover this function, it'll just use the extension point and set `$result = false`, meaning that no page will fit the criteria of home page.

**Comment by tractorcow** [comment]
It seems like extensions modify the home page link, and that isHomePage() is done by comparing this urlsegment to the one being tested.

With that in mind, should we put the extension into `get_homepage_link()` instead? It could be implemented like this:


```php
if (!isset(self::$cached_homepage_link)) {
	$homepage = Config::inst()->get(self::class, 'default_homepage_link');
	static::singleton()->extend('updateHomepageLink', $homepage);
	self::$cached_homepage_link = $homepage;
}
return self::$cached_homepage_link;
```

**Comment by silbinarywolf** [comment]
@tractorcow The conditions for whether something is a home page or not is currently as I understand it, is:
- ParentID == 0
- URLSegment == RootURLController::get_homepage_link()

This doesn't work out for Multisites because a HomePage will have:
- ParentID != 0 (ie. could be anything, but definitely not 0 as "Site" DataObject's are at the top of the SiteTree)
- URLSegment == RootURLController::get_homepage_link()

This is why I'm suggesting a function that checks if a SiteTree instance is a home page.

EDIT: In SS4, I found a function that does what I want already. It just needs an extension point seemingly:
https://github.com/silverstripe/silverstripe-cms/blob/master/code/Controllers/RootURLController.php#L82

**Comment by silbinarywolf** [comment]
@tractorcow If I put the effort in and do a PR on both 3.X and 4.X branches, can I extend should_be_on_root() to have an extension point?

Will most likely do `Injector::inst()->get(__CLASS__)->extend('updateShouldBeOnRoot', ...)` as the function is static.

**Comment by tractorcow** [comment]
@silbinarywolf yeah let's do that. :)

The Translatable hack doesn't work so I'd probably say it can be removed.

**Comment by silbinarywolf** [comment]
@tractorcow I'll leave the removal of the Translatable logic to you guys unless you can explain to me how it's broken. I don't want to cause an unnecessary breakage.

Assumptions on what needs to be done this task:
- Add extension point before `return`, would look like: `Injector::inst()->get(__CLASS__)->extend('updateShouldBeOnRoot', ...)`
- Write unit tests that test the extension point.
- Backporting to SS3 with the unit tests (if time permits)

**Comment by tractorcow** [comment]
You can back-port to 3.x but it may be harder to get support for this new feature included (we aren't actively developing 3.x anymore).

**Comment by silbinarywolf** [comment]
Ah, so no minor releases are planned from this point on?

**Comment by dhensby** [comment]
There will probably be one more as there are a few new features we should probably ship.

**Comment by silbinarywolf** [comment]
Alright. Might be a few months until I can get time to do this work so we'll see if I can make it in or not when I do the SS4 PR.

**Comment by chillu** [comment]
I've created a related card [Prevent deletion of the homepage](https://github.com/silverstripe/silverstripe-cms/issues/2154)
