### ISSUE TITLE
Wrong history view presented when using back button

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-cms#2052]
#### Steps to replicate:

1. Go to a page
2. Make changes and publish
3. Go to history tab
4. select compare mode
5. select 2 versions to compare
6. click "back" arrow next to page title
7. use browser back function

#### Expected behaviour:

To see comparison screen of two selected versions

#### Actual behaviour:

See single historical version

**Comment by tractorcow** [comment]
4.0 only I assume? or 3.x as well?

**Comment by dhensby** [comment]
I've only tested in v4 :)

**Comment by worzy** [comment]
We have experienced this issue as well.  It seems to happen in 4.0.  When navigating between screens in the CMS, the back button does not navigate to the previous screen.  But actually jumps back 2 or 3 screens.

**Comment by robbieaverill** [comment]
This is fixed in SilverStripe 4.3 with the new history viewer, which stores the compare mode state in Redux between PJAX requests
