### ISSUE TITLE
Weird layout in page "Settings" tab in the CMS. 

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-cms#2054]
I didn't noticed this in SS `4.0.0`, it seems like this was introduced with `4.0.1`.

![screen shot 2017-12-11 at 15 10 52](https://user-images.githubusercontent.com/1006185/33879548-111378fc-df2f-11e7-80d9-3a548dd0ada2.png)

So far, the problem occurs in:
 - Firefox (latest)
 - Chrome (latest)
 - Safari

Tablet and Mobile layouts are unaffected (< 992px)

[Relevant Slack chat](https://silverstripe-users.slackarchive.io/ss4/page-98/ts-1513001342000008)

**Comment by DorsetDigital** [comment]
This is Chrome on Linux.  The site in question was updated from 4.0.0 to 4.0.1 (in case that's relevant)

![screenshot from 2017-12-12 10-28-14](https://user-images.githubusercontent.com/15108750/33879718-36a6c9f0-df27-11e7-98b6-3f00d29eede9.png)

**Comment by kinglozzer** [comment]
Appears to be resolved in 4.0.x-dev (and `"silverstripe/admin": "1.1.x-dev"`), so it looks like this was resolved by https://github.com/silverstripe/silverstripe-admin/pull/378

**Comment by tractorcow** [comment]
Yes fixed with https://github.com/silverstripe/silverstripe-admin/pull/378
