### ISSUE TITLE
Can not remove Campains from cms menu

### ISSUE THREAD

**Issue by cansozeri** [silverstripe/silverstripe-cms#2058]
Hi,

I have added ths code to my _config.php, but Campains menu still appears in the menu.

`CMSMenu::remove_menu_item('Campaigns');`

How can I remove this ???

**Comment by robbieaverill** [comment]
Hey @cansozeri 

You can remove the Campaigns menu item in either of the following two ways:

```php
\SilverStripe\Admin\CMSMenu::remove_menu_class(\SilverStripe\CampaignAdmin\CampaignAdmin::class);
\SilverStripe\Admin\CMSMenu::remove_menu_item('SilverStripe-CampaignAdmin-CampaignAdmin');
```

I suggest the first option since it feels more natural (to me) rather than using a sanitised class name as the code.

Cheers!

**Comment by cansozeri** [comment]
@robbieaverill Thanx :=)
