### ISSUE TITLE
Add reserved keywords

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-cms#2059]
Such as `assets`, `vendor` and `resources`, these paths are now pretty much hardcoded to be blocked or redirected/handled elsewhere.
Top-level pages with these keywords should give a validation error or warning to keep users informed of what happened to their page.

# PRs:

 - [ ] https://github.com/silverstripe/silverstripe-cms/pull/2077

**Comment by adrexia** [comment]
I feel that `resources` is too common a page name for it to be used as the name in core. How difficult would this be to change it to something less commonly used by cms authors? Something like `silverstripe-resources` or `client-resources` would be less likely to conflict with existing sites during upgrades, and less likely to cause future frustration for cms authors.

**Comment by NightJar** [comment]
👍 for @adrexia's suggestion of `client-resources` would be both more descriptive and less conflictory (because that's totally a word).

**Comment by tractorcow** [comment]
Sorry, I think it may be a bit too late. We've already added `resources` as the default vendor-symlink folder in 4.0.

**Comment by tractorcow** [comment]
Reserved page names can be automatically inferred from base folders in the public dir.

**Comment by flamerohr** [comment]
that's assuming public folder is implemented for the project though ;)

**Comment by tractorcow** [comment]
It should still work even if BASE_PATH === PUBLIC_PATH; it'll just now include more folders. E.g. `vendor`, `mysite` etc

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-cms/pull/2077
