### ISSUE TITLE
CMSMain::getEditForm() incorrect or unclear code

### ISSUE THREAD

**Issue by worikgh** [silverstripe/silverstripe-cms#2063]
```PHP
       // Check parent form can be generated
        $form = parent::getEditForm($record, $fields);
        if (!$form || !$record) {
            return $form;
        }
```

It is very unclear why if the form is null null is returned or if $record is null $form is returned.
I have not had a problem with this I am reading the code and this struck me as very odd logic

**Comment by tractorcow** [comment]
What it means is "if we have both a form, and a record with which to decorate it, augment it".

Yes it's unclear but that's because LeftAndMain is one of the oldest un-refactored classes in core.
