### ISSUE TITLE
SiteTree::getCMSActions does not work

### ISSUE THREAD

**Issue by elliot-sawyer** [silverstripe/silverstripe-cms#2064]
I'm trying to add a new CMS action to my DataObject when editing through a ModelAdmin, following the documentation [here](https://docs.silverstripe.org/en/4/developer_guides/customising_the_admin_interface/how_tos/cms_alternating_button/#backend-support). If I copy-paste that exact code block into my DataObject, I would expect to see a new action when I open the record in the CMS. To reproduce:

1. Create a new class that extends DataObject
2. Define a new field in $db
3. Create a new method `getCMSActions` as per documentation
4. Run `/dev/build` with `flush=`
5. Observe: no new actions appear

Indeed, if you insert a `die()` command in the `getCMSActions()` method, it appears to never get called at all.

I discussed this with @flamerohr briefly in December and I believe he identified an issue with `GridFieldDetailForm_ItemRequest` that was causing it.

**Comment by dhensby** [comment]
which version of SS?

**Comment by elliot-sawyer** [comment]
First noticed an issue on 4.0.0. Have just updated to 4.0.1 and the issue remains.

`getCMSActions` doesn't get called in GridFieldDetailForm_ItemRequest. I made the following addition to get the new FormAction buttons to appear, but the actions themselves don't seem to work from an extension.

I've started a pull request on https://github.com/silverstripe/silverstripe-framework/pull/7734 as a partial fix.

**Comment by tractorcow** [comment]
These instructions only relate to SiteTree, not non-sitetree dataobjects sorry.

If you want to customise buttons for modeladmin, you will need to implement this via a custom GridFieldDetailForm_ItemRequest subclass.

For instance, Versioned implements this behaviour which you can use as an example.

https://github.com/silverstripe/silverstripe-versioned/blob/1.0/src/VersionedGridFieldItemRequest.php

In the future we want to deprecate both getCMSFields() and getCMSActions() and shift to a FormBuilder model.
