### ISSUE TITLE
SS4 when Image is not published preview is broken in "Insert file from"

### ISSUE THREAD

**Issue by ivoba** [silverstripe/silverstripe-cms#2067]
This is versioned File related.

Its SS4 on PHP 7.1 on a LEMP setup.

When uploading Images in Files section, images that are not published yet arent shown as preview in "Add from files" dialog and also not in GridField summary but a broken image shows.
In Files section images are shown even when not published.

Example: 
```$this->Images()->first()->Image()->StripThumbnail();```
Images is a has_many on a DO which has a has_one on Image.
When clicking "Add Image" button and clicking "Add from files", then choosing a not published image (image marked as DRAFT with orange circle) the preview image in the fileSelectForm pane is broken.

I guess the preview probably looks in the Images folder in assets but as its not published yet its still in .protected.

Imho in admin area images should be available as preview even if they are not published yet.

**Comment by tractorcow** [comment]
@ivoba can you view those files in the /admin/assets section? If you can, after viewing those files, does it then make those files available then in the "add from files" dialog?

If you can, then it's probably a bug with the add from files not enabling the read permissions.

If you can't, there may be an issue with the asset rewriting.

**Comment by tractorcow** [comment]
It's possible the issue is a misconfiguration of your nginx protected assets. Can you share your config please?

This should redirect all 404s for `/assets/` urls back to index.php.

**Comment by ivoba** [comment]
@tractorcow i see thumbnails in /admin/assets section, but when clicking on on the image i have a broken image as preview image in the file edit form on the right side.

here is the nginx config https://gist.github.com/ivoba/296b5ac32da239c7d52964d53efd3013

**Comment by ivoba** [comment]
as i see the thumbnail in admin/assets is a base64 data image as backgound image via css.
shouldnt the preview image use this mechanism as well then?

I also tried other nginx config but still the same:

    location ^~ /assets/ {
        sendfile on;
        try_files $uri =404;
        access_log off;
    }

**Comment by tractorcow** [comment]
> @tractorcow i see thumbnails in /admin/assets section, but when clicking on on the image i have a broken image as preview image in the file edit form on the right side.

Thumbnails are actually served via base64 encoded inline images in most cases, so it would hide the fact that there's a routing issue.

I can see your config doesn't match the expected config; 404 files need to go through index.php to be routed from protected assets.

```
location ^~ /assets/ {
	location ~ /\. {
		deny all;
	}
	sendfile on;
	try_files $uri index.php?$query_string;
}
```

Can you please try this config?

**Comment by tractorcow** [comment]
See https://docs.silverstripe.org/en/4/getting_started/installation/how_to/configure_nginx/

**Comment by ivoba** [comment]
This is what i had in the beginning, i took it from the docs.
See: https://gist.github.com/ivoba/296b5ac32da239c7d52964d53efd3013

But that doesnt help.
I wonder why this doesnt happen with apache?

**Comment by tractorcow** [comment]
Apache has a separate `.htaccess` that is generated and placed directly into `assets/.htaccess` on flush.

https://github.com/silverstripe/silverstripe-assets/blob/1.0/templates/SilverStripe/Assets/Flysystem/PublicAssetAdapter_HTAccess.ss

With nginx the config is in a single file.

**Comment by ivoba** [comment]
ok i got it working.
the error was:
>Unable to open primary script: /var/www/currentindex.php (No such file or directory)"

So i added a / before index.php in the assets section in silverstripe.conf:

     try_files $uri /index.php?$query_string;

Not sure if this has to be fixed in the docs?
Can anyone confirm?

**Comment by tractorcow** [comment]
Oh thanks for that. I'll have a look into it!

**Comment by tractorcow** [comment]
Docs fix at https://github.com/silverstripe/silverstripe-framework/pull/7747 thanks for the help. :)
