### ISSUE TITLE
Layout of Viewer Groups and Editor Groups is broken in FireFox 57

### ISSUE THREAD

**Issue by nspyke** [silverstripe/silverstripe-cms#2071]
In the settings tab of any page, the label and form field is not lined up.

![Screenshot](https://cdn.pbrd.co/images/H2n7hC9.png)

**Comment by chillu** [comment]
@flamerohr Can you confirm that's fixed already?

**Comment by flamerohr** [comment]
https://github.com/silverstripe/silverstripe-admin/pull/378
