### ISSUE TITLE
Main page actions should have labels "Save" & "Publish"

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#2072]
The main page action labels should be shortened to just "Save" and "Publish" as per the actions in the files area which are the using the newer pattern.
eg.
<img width="111" alt="pasted_image_15_01_18__4_24_pm" src="https://user-images.githubusercontent.com/555033/34925845-cfec39f2-fa10-11e7-903a-d07406438256.png">

This will mean the actions will work better responsively and allow more space to other actions included in modules like Advanced Workflow.

I was sure this issue already exists but can't find it so created a new one just incase.

## Pull requests
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2093

**Comment by chillu** [comment]
No new translation key, let's figure out what this means for release process (4.0 shouldn't run text collector and reset keys?)
