### ISSUE TITLE
ss 3.6.4: Framework/CMS versions in CMS displayed as 'unknown'

### ISSUE THREAD

**Issue by Friksel** [silverstripe/silverstripe-cms#2075]
Seems like a little issue, but inside the CMS when hovering over the CMS logo it now displays CMS- and Framework-versions as 'unknown' instead of showing their version numbers. This was working in 3.6.2.

**Comment by robbieaverill** [comment]
Hey @Friksel, thanks for reporting. I can't reproduce this locally. Note that this feature depends on having a composer.lock file in your project, so if you're running SilverStripe without Composer then it probably won't work. Is this how you're running 3.6.4?

**Comment by Friksel** [comment]
@robbieaverill I never used composer on Silverstripe (until version 4). With all versions before 3.6.4 this was working fine (previous version I used was 3.6.2). I'm using the zip file from https://www.silverstripe.org/download/release-archive/ and with every update I just replace the folders 'cms', 'framework', 'reports', 'siteconfig' and 'vendor' in my project with the ones from the zip.

**Comment by robbieaverill** [comment]
Yeah fair enough. It was as changed a few months ago to rely on the composer lock file, so you could still deploy sites without it for this feature, but you’d need to deploy a composer lock file too (up to date). Best to get into the composer routine for SS4 and beyond now though :-) cheers
