### ISSUE TITLE
[bug] Message of unsupported browser shows at random

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-cms#2076]
On a supported browsers, e.g. Firefox, the message screen saying the browser isn't supported shows up at random moments.

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/430

**Comment by chillu** [comment]
20% of our demo.ss.org visitors are currently getting that first impression (Firefox users, assuming most of them visiting for the first time with an empty cache).
