### ISSUE TITLE
Publishing an Error Page causes the users login to die

### ISSUE THREAD

**Issue by UndefinedOffset** [silverstripe/silverstripe-cms#2078]
It looks like for some reason when you publish an error page in SilverStripe 4 for the first time the user is forced to re-login as if their session is expired, I've been able to reproduce this with 4.0.2.

## Pull Requests
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7886

**Comment by phptek** [comment]
This has the annoying side-effect of incorrectly publishing a static representation of itself to the F/S:

```
$> cat assets/error-500.html

Not logged in
```
