### ISSUE TITLE
Actions in popover are broken (should span width of popover)

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#2082]
The links in the "more options" popup should span the width of the dropdown.
Seen on the demo site.

![image](https://user-images.githubusercontent.com/555033/35596547-354dcdfe-067f-11e8-82fe-4ea796d7f173.png)

**Comment by clarkepaul** [comment]
Can't reproduce anymore so closing

**Comment by clarkepaul** [comment]
Reproduced when clicking the "Archive" action the width of the action collapses.

**Comment by lukereative** [comment]
Closing as cannot reproduce anymore on demo:
![demo site](https://user-images.githubusercontent.com/1415622/44066762-34240b24-9fc6-11e8-9b80-b108f5ed2546.png)
