### ISSUE TITLE
SS4 - New top level page still gets placed under existing page

### ISSUE THREAD

**Issue by korthjp17** [silverstripe/silverstripe-cms#2086]
When I'm on an existing page and try to create a new page top level page, it still falls under the existing one as a child page. I selected Top Level from the options, but it didn't seem to make a difference.

**Comment by tractorcow** [comment]
It seems to work fine with me.

Which exact tag of cms / admin / framework are you using?

**Comment by korthjp17** [comment]
updated to recipe 1.0.2 and it seems to be working as expected.

**Comment by tractorcow** [comment]
Nice glad it worked. :)

**Comment by korthjp17** [comment]
just in case it comes up somewhere else, it was on recipe 1.0.1, pulling in cms/framework 4.0.1 and admin 1.0.1

**Comment by tractorcow** [comment]
Yep there's a known issue with TreeDropdownField in that version, that could explain the broken parent selector in add-page.
