### ISSUE TITLE
SS4: Right Click Doesn't Work In "List-Mode" As Expected !

### ISSUE THREAD

**Issue by Mu9tafa-Online** [silverstripe/silverstripe-cms#2095]
I'm Using SS4 (4.0.3) .. and when Right-Clicking on pages in "List-Mode" the default context menu is shown, but it works in "Tree-Mode" - See The Screens Below.
.
![ss_tree](https://user-images.githubusercontent.com/5323832/36059532-adf2494a-0e42-11e8-8495-981b768f4dc1.PNG)

![ss_list](https://user-images.githubusercontent.com/5323832/36059536-c34dc6f2-0e42-11e8-82b0-2d478a75fca7.png)

**Comment by flamerohr** [comment]
List view has never had a context menu show when right clicking

the context menu has been exclusive to the tree view

**Comment by Mu9tafa-Online** [comment]
@flamerohr - Ahaa, So Can I Add It To List-View ?

**Comment by flamerohr** [comment]
That would be interesting to see, if you're able to get one going and create a pull request for it to be added then we'd be more than happy to review and see if we can get it in :)
