### ISSUE TITLE
Annoying JS dialogue when editing....anything

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-cms#2096]
mod-php7.1 / Firefox 58 / framework+cms 4.0.2

I'm surprised the following hasn't been reported elsewhere (possibly on a different repo...there are lots these days!)

Since starting to use SS4 a lot more mid-late 2017 I noticed, but had never bothered reporting until now that every time I want to make an edit to a model (DataObect, SiteTree or whatever) within the cms, a JS dialogue will popup asking:

    Are you sure you want to navigate away from this page? 
    WARNING: Your changes have not been saved."

...except this is rubbish, they have been saved. I can select both "Save Draft" or "Publish" buttons, then select an item from a gridfield row (for example) to edit, and I am presented with this dialogue again. This didn't used to happen in SS3, so I can only assume some change in client side JS within the CMS is part of this. 

See screenshot below of my editing a User Form, but this behaviour is exhibited elsewhere too.

![screenshot](https://user-images.githubusercontent.com/478440/36077764-aa43c2fa-0fd3-11e8-87f2-cd2a51739490.png)

**Comment by phptek** [comment]
UPDATE: This seems to only happen in "dev" mode. I have access to a SilverStripe Platform UAT environment where the same pagetype in the same project build, this doesn't happen.

**Comment by flamerohr** [comment]
hi @phptek, does this happen to you in a vanilla install?
the dialog shows when you trigger a browse away from the page, is there anything that could be triggering this for you?

**Comment by phptek** [comment]
I will check my vanilla install and get back to you.

**Comment by chillu** [comment]
@phptek Any update on this? I can't reproduce it in a vanilla CMS (Pages or ModelAdmin). I know change tracking has been a bit rocky through 4.0 alpha and early beta phases, but I thought we had it ironed out now. Maybe it's limited to userforms only?

**Comment by tractorcow** [comment]
@phptek I suggest you put your code into a gist and I'll test it out locally.

It could be related to:
 - inline editable gridfield 
 - shortcoded items
 - specific gridfield components
 
 If possible, try to find the minimal solution that reproduces this bug, with as few of the above as possible.

**Comment by chillu** [comment]
Closing this, lack of feedback.

**Comment by tractorcow** [comment]
@phptek if you get me the feedback I can open / continue to investigate this. :)

**Comment by phptek** [comment]
Thanks! I still see it, but AFAIK it's 4.0.x. But let me confirm.

**Comment by martinduparc** [comment]
I am able to reproduce on the member listing page (`admin/security/`). If you filter the list of users using the search feature, navigating away from the page will trigger the `Are you sure you want to navigate away from this page?` confirm prompt.

![screen shot 2018-10-26 at 1 36 48 pm](https://user-images.githubusercontent.com/839534/47583136-7df41b80-d924-11e8-8e09-afd4f0fc4e80.png)

**Comment by chillu** [comment]
We've changed the search approach in the upcoming 4.3 release. @lukereative could you check if it's still an issue there? Technically you can opt-out of this new search UI, and you might hit the issue described here, but that lowers its priority.
