### ISSUE TITLE
Mouseover SiteTree to reveal PageType Behaviour is gone

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-cms#2097]
In SS3 (Possibly v2 also) one could mouseover a SiteTree item and a tooltip would display the PageType. This no longer happens in SS4 - is this by design?

# Notes

 * Track under ORB-175

**Comment by chillu** [comment]
I don't think it's by design - that was a useful pro feature!

**Comment by tractorcow** [comment]
Can fix in CMSMain_TreeNode.ss (4.0)

```
<a href="{$node.CMSEditLink.ATT}" title="{$node.Title.ATT}"><ins class="jstree-icon">&nbsp;</ins>
```

Change $node.Title.ATT to `$Title.ATT` and add the `Title` back into getTreeNodeCustomisations.

3.6 code is.

```php
'Title' => sprintf(
	'(%s: %s) %s',
	trim(_t('LeftAndMain.PAGETYPE','Page type'), " :"),
	$obj->i18n_singular_name(),
	$obj->Title
),
```

**Comment by chillu** [comment]
@phptek Wanna try this out and send a PR?
