### ISSUE TITLE
preview doesn't show value from mysite lang files

### ISSUE THREAD

**Issue by guyvanbael** [silverstripe/silverstripe-cms#2107]
The page shows the exact values form the lang yml files. The preview in the cms however doesn't

<img width="1897" alt="schermafbeelding 2018-02-22 om 14 13 33" src="https://user-images.githubusercontent.com/3098809/36540604-567792ae-17db-11e8-8d79-1679ae93906f.png">
<img width="1910" alt="schermafbeelding 2018-02-22 om 14 13 47" src="https://user-images.githubusercontent.com/3098809/36540605-568f185c-17db-11e8-87d7-f6e142821549.png">

**Comment by tractorcow** [comment]
@guyvanbael how are you setting i18n locale? Are you setting it via PHP or yml? Please provide your config.

**Comment by tractorcow** [comment]
I suggest you shift this over to https://github.com/tractorcow/silverstripe-fluent/issues :D

@robbieaverill in case you are interested in this too.

**Comment by chillu** [comment]
Closing here, @guyvanbael please reopen in the correct repo.
