### ISSUE TITLE
You shouldn't be able to save a page without page name and navigation label

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#2110]
It feels like a page should always have a name and navigation label, possibly it should be a required field—or at least get a warning. This would prevent empty items in the tree, and unintentional empty fields.

If they don't want the page to be displayed in the template devs should be able to accommodate that scenario.

Note an empty item in the tree:
![image](https://user-images.githubusercontent.com/555033/36652909-adffdbb0-1b16-11e8-9bce-807527786238.png)

# Related PR
* [ ] https://github.com/silverstripe/silverstripe-cms/pull/2366

**Comment by tractorcow** [comment]
Probably just needs a better RequiredFields validator with Title in it.

Navigation label should default to title, so only one field is required (and maybe URLSegment) :P

**Comment by dhensby** [comment]
I really feel that (when saving as draft, at least) there should be no validation enforced because what is the point in having a feature to save as draft (saving a way point in your work) if it can be "invalid"?

I'd rather the label said "Untitled page" in italics or something that to symbolise it's not got a title, rather than rejecting a request to save progress of the page state

**Comment by robbieaverill** [comment]
@clarkepaul how do you feel about that?

**Comment by jenniferaslan** [comment]
In previous versions of SS, there was no opportunity to save the page without page name or navigation label and we never experienced problems. In this version, we have inadvertently managed to save pages without those fields filled in and have had errors when trying to get things from the database. I vote for restoring the previous user experience where it filled the page name and navigation label with a placeholder like “New Page” or “New User Defined Form.”

**Comment by clarkepaul** [comment]
Some good input here, I like the idea of giving the page a temp name. I think its slightly better if we used "Untitled [Page type]" rather then "New [Page type]" as its only **new** for the first save (the page could be there for years), we can also use "Untitled" if the page has previously been published but the title/navigation label has been removed.

**Comment by ScopeyNZ** [comment]
Are we agreed on "Untitled [Page type]"? There's a PR raised for this now so we should come to a consensus @silverstripe/core-team

**Comment by phptek** [comment]
Regardless of what @clarkepaul might want in the long term, the PR "makes things better than they were" (TM) surely? .... *hopes*

**Comment by tractorcow** [comment]
I've run into issue where a page named `New Zealand` was getting caught by the `is a new page?` logic in js. It was a pain to debug.

So `Untitled`

**Comment by robbieaverill** [comment]
Would that mean I can't have a page called `Untitled no. 5` for the same reason :trollface:

**Comment by clarkepaul** [comment]
I'd be okay with a number at the end (2nd and above). To keep things simple then we should just go with "Untitled" rather than "Untitled blog page", people know its a page.
