### ISSUE TITLE
Group permissions for CMS Access: Access to 'Pages' section gives full permissions. v4

### ISSUE THREAD

**Issue by markhagemann** [silverstripe/silverstripe-cms#2111]
Hi, I'm not sure if I've missed something in the changelogs but I'm comparing ss3 and ss4 group permissions, specifically CMS Access: Access to 'Pages' section and everything else left unchecked. In ss3 this sets all pages to read only (which is what I want) and doing the same thing in ss4 the user in that group has full access to edit, delete, etc. to all pages (which I definitely don't want).

I've tested this with version 4.0.2 and 4.0.3

Please let me know if you require screenshots.

**Comment by dhensby** [comment]
@markhagemann when reporting issues that concern security, please email security [ at ] silverstripe [ dot ] org

Thanks

**Comment by dhensby** [comment]
@markhagemann Thanks for reporting this. Please can you check your `SiteConfig` settings, particularly the `Access` tab in your 3.x install and tell me what the setting for "Who can edit pages on this site?" is?

I have tested this issue in 3.5.x-dev, 3.x-dev and 4.0.x-dev and they all exhibit the same behaviour which is that the `SiteConfig` setting of "Who can edit pages on this site?" being set to "Anyone who can log-in to the CMS" allows a user with access to the Pages section to edit the pages. You have to restrict this to particular groups to stop users being able to edit pages with the set up you describe and I have replicated that across versions consistently.

**Comment by markhagemann** [comment]
Hi @dhensby not changing the SiteConfig access settings was indeed what I missed. Thanks a lot for investigating. I've noticed that the Read Only pages are now just in italics rather than greyed out like ss3, I assume this is expected behaviour? 

Thanks a lot once again.
