### ISSUE TITLE
Disable Anchor Rewriting not working

### ISSUE THREAD

**Issue by Bubomir** [silverstripe/silverstripe-cms#2113]
Hi, 

I try to disable anchor behavior cause I want to parse URL like 

    www.someweb.com 

into anchor href property but silverstripe added before this URL the project URL and then it looks like 

    www.projectURL.dev/www.someweb.com

I found this topic https://docs.silverstripe.org/en/4/developer_guides/templates/how_tos/disable_anchor_links/ in documentation so try to use it but It  does not work in my case. My config looks like this:

    ---
    Name: mytheme
    ---
    SilverStripe\View\SSViewer:
      rewrite_hash_links: false
      themes:
        - 'themeName'
        - '$default'
    SilverStripe\i18n\i18n:
      default_locale: 'sk_SK'

I am using SilverStripe v4.0.3 Thanks for help

**Comment by kinglozzer** [comment]
@Bubomir Which of the following are you trying to create?
```html
<a href="some-page/#www.someweb.com">Link</a>
or
<a href="http://www.someweb.com">Link</a>
```

The `rewrite_hash_links` only affects links that are to an anchor on a page (i.e. links that begin with`#`). If you’re just trying to link to another website, you’ll need to prefix your link with `http://` or `https://`.

Sorry if I’ve misunderstood!

**Comment by Bubomir** [comment]
Thank you so much I didn't know that.
