### ISSUE TITLE
Download and upload asset icons match

### ISSUE THREAD

**Issue by nzjoel** [silverstripe/silverstripe-cms#2124]
Confusingly the download asset icon that shows on the right hand side of the window when you click an asset is the same icon as the upload asset icon that shows on the top bar in the Files section of the CMS. 

I'd expect the download icon to be changed to something that better represents downloading.

![silverstripe_-_files_and_installation_ _cloud_cart_connector_for_quickbooks](https://user-images.githubusercontent.com/1848200/37405462-935bab90-278c-11e8-8a4d-a52457a9def5.png)

**Comment by clarkepaul** [comment]
FYI the one in the editor panel is not a download icon, its actually a replace the file action which is pretty cryptic (upload and replace). I'm also not liking the icon nor the placement even though I initially designed it there, my preference is to move the action to the "more options" dropdown with better icon and supporting text (we're avoiding icons on hover as then they'll be missed on touch devices).

**Comment by nzjoel** [comment]
So it is! You could also then get rid of the magnifying glass too, as it already appears on hover of the image and seems to have the same action (open the file in a new tab).

Putting the replace file action in the more menu makes sense to me. It's not a common action to take in my experience, so probably isn't justifiable to have it so prominent.

**Comment by robbieaverill** [comment]
>my preference is to move the action to the "more options" dropdown with better icon and supporting text

This has been done now (SS 4.3). I think this can be closed off, feel free to reopen if someone disagrees.
