### ISSUE TITLE
SearchForm results() function exposed as controller action

### ISSUE THREAD

**Issue by rotassator** [silverstripe/silverstripe-cms#2125]
Browsing to a page ending in `~/results` causes the following error:
```
[User Error] Uncaught ArgumentCountError: Too few arguments to function ContentControllerSearchExtension::results(), 1 passed in ~/framework/core/Object.php on line 749 and exactly 3 expected
```

This occurs when using `FulltextSearchable::enable()` (or related).

Using SilverStripe 3.6.5.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-cms/pull/2126
