### ISSUE TITLE
Get rid of toast notifications

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-cms#2128]
Popup notifications are currently utilised in the CMS for things submitted into the system via ajax submitted requests.
This is a rather subjective opinion of course, but these are far more annoying than they are helpful - and I feel that this will not be an uncommon subjective opinion.

For example:
After saving or publishing a page, I wish to browse to the settings or some other tab (e.g. to alter access rights).
However this is blocked by the toast popup and I must wait for it (and all others in the queue) to subside before I am able to complete my task.

**Comment by chillu** [comment]
@newleeland @clarkepaul Can you weigh in here? It looks like we're establishing a pattern of persistent, but clearable notifications that are full width, e.g. [validation messages on tabs](https://github.com/silverstripe/silverstripe-cms/issues/2081). Not sure how that works across tabs though, and if there should be notifications for stuff like "successfully saved".

**Comment by clarkepaul** [comment]
First off its probably best to explain the use case for each notification.
1. The popup notifications should only be shown when a chosen action is successful (saving, publishing, archiving... ) and should always be temporary and be dismissible. This suits actions which are regularly triggered. 

2. The in page alert is used when actions, links, or additional information needs to be read/provided. This notification doesn't suit actions like "save" as they make the page content jump which causes a cognitive load to reassess the page.

I think its still a good idea to keep the temporary notification but I would be open to suggestions for the placement of it and the size/contents (eg. we could move it to the top middle and keep it at a 4 word limit with reduced size). 
I personally don't like the placement of the top right tabs and I would eventually like to remove/move them (eg left align the tabs or move these top level tabs to main left menu), as they are overlooked by people learning the UI especially when viewed on a large screen as they are not in the line normal line of site of the top left, so I wouldn't want to make that the sole reason for moving the popups.

We don't have consistent loading states on all buttons and actions within the CMS and some sort of a response is required to actions.

Some guidance is available under Components/Alerts on the style guide https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe

**Comment by chillu** [comment]
OK, so given there's no clear way forward, and @clarkepaul doesn't seem too keen to create alerts different from the DMS (without a more wide-ranging UI redesign), I'm going to close this issue. Can be revisited as part of a redesign, but I don't see how this particular concern from @NightJar can be actioned.

@NightJar if you have a specific toast message that's NOT dismissable, that sounds like a UX bug - please raise it separately.
