### ISSUE TITLE
$SilverStripeNavigator returning escaped HTML

### ISSUE THREAD

**Issue by rsmclaren** [silverstripe/silverstripe-cms#2130]
Using a fairly bare bones SilverStripe 4.1.0 install. Added $SilverStripeNavigator to Page.ss and its returning escaped HTML

**Comment by dhensby** [comment]
Hmm, ok, looks like we need to make sure we return the content as `DBField::create_field('HTMLFragment', $content);` instead of as a string

**Comment by dhensby** [comment]
@rsmclaren have you experienced this in 4.0 ?

**Comment by rsmclaren** [comment]
I just tried it in a 4.0.0-beta2 install and same result, escaped HTML.

**Comment by dhensby** [comment]
thanks
