### ISSUE TITLE
Not working "Insert image/link from files" 

### ISSUE THREAD

**Issue by Martin25699** [silverstripe/silverstripe-cms#2131]
![2018-03-22 16 30 27](https://user-images.githubusercontent.com/10417137/37768138-635a9f06-2dee-11e8-86a4-549bb659d6dc.png)

When clicking nothing happens, the console is empty
Maybe I forgot something, tell me please

**Comment by dhensby** [comment]
SS version? steps to reproduce? can you replicate on a vanilla install?

**Comment by Martin25699** [comment]
the reason was in the 'resources' directory at the root of the project, all symlinks will remove from magic. If you delete the directory with symlinks 'resources' and then cancel the deletion, the symlinks are replaced with the directories to which they referred
