### ISSUE TITLE
Pages can't be held to the same standard of data validation as non-page data objects

### ISSUE THREAD

**Issue by dmcb** [silverstripe/silverstripe-cms#2133]
Silverstripe offers up a very strong way of ensuring data is validated on a model (https://docs.silverstripe.org/en/4/developer_guides/model/validation/) and explains why it is a superior approach:

> Traditionally, validation in SilverStripe has been mostly handled on the controller through form validation.
> 
> While this is a useful approach, it can lead to data inconsistencies if the record is modified outside of the controller and form context.
> 
> Most validation constraints are actually data constraints which belong on the model. SilverStripe provides the DataObject::validate() method for this purpose.

However, pages can't utilize this method because I believe SS saves an empty draft first when a page is created, so the validation is triggered on an empty set of data and will likely fail. This architectural decision is unfortunate because it means pages arbitrarily can't be held to the same standard of data validation as non-page data objects, and have to fall back on the controller form validation approach, which the article notes is less desirable.

**Comment by dmcb** [comment]
To clarify: I don't want to suggest the behaviour of pages where an empty draft is saved on creation should be changed, if anything this behaviour should be extended to all data objects so that relationships can be leveraged when making new records and gridfield items.

What I am suggesting needs fixing is that the behaviour for the model validation method can accommodate this empty-draft approach.

**Comment by dhensby** [comment]
IMO this approach of validation is broken for pages (or any object that can be in draft mode) because there should be no constraint on draft items to be "valid"; as a CMS author I'd want to be able to save a "draft" copy of any object in any state so I can save my work and return to it later; I shouldn't have to arbitrarily fill certain fields with (correct) data to save a draft.

**Comment by dmcb** [comment]
That's a fair point. Though I also feel like it would be frustrating to hit publish only to find out a bunch of your fields are incorrect. I'm not sure which direction I'd prefer, I just know what pages and other data objects should have the ability to use the same type of model validation at write time.

**Comment by dmcb** [comment]
Yep, totally fair point, I could support either direction. It makes a lot of sense that this model validation method only applies when an object is to be published, and that approach would solve this issue.

**Comment by dhensby** [comment]
There's currently a disconnect between validation on a model and validation when writing to a stage; maybe that's where the change needs to come in

**Comment by GuySartorelli** [comment]
Great idea but it's a super old issue that we're not going to do anything with any time soon. Closing. If someone is keen for this and wants to put in the work to implement it, `@` me and we can revisit.
