### ISSUE TITLE
"Insert from Media" doesn't have a loading indicator

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-cms#2134]
I'm a little bit peeved about that. We've just redeveloped the feature, and didn't consider that there needs to be an indication while the oEmbed is fetched. Our UX baseline needs to get better...

/cc @newleeland @clarkepaul 

## PR

- [ ] https://github.com/silverstripe/silverstripe-admin/pull/481

**Comment by clarkepaul** [comment]
That it does :/, have you experienced that it takes time to load as for me its pretty instant, I'm sure there are reasons for it not loading quickly. 
You wont be happy about this but there is also no error messages if the URL is not finding anything—seems to just insert a doc thumbnail as if everything is good 
![image](https://user-images.githubusercontent.com/555033/38065504-2458e282-3360-11e8-899c-fe7ced5c5310.png)

**Comment by chillu** [comment]
Grrrrrr! OK, I've raised that as https://github.com/silverstripe/silverstripe-cms/issues/2136.
