### ISSUE TITLE
"Insert from Media" doesn't show an error message when oEmbed fails

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-cms#2136]
See https://github.com/silverstripe/silverstripe-cms/issues/2134#issuecomment-377094181

## Acceptance Criterea

- If the embed type that is created from the URL provided in the first step of the 'Inset from Media' form is 'Link', the form does not continue to the second step and an error is displayed.
- Current rendering of 'Link' type embeds is retained to maintain rendering of existing embeds

## PRs

- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/770
- [x] https://github.com/silverstripe/silverstripe-admin/pull/491

**Comment by lukereative** [comment]
This isn't actually oEmbed failing but we intentionally fall back to the generic file icon when the embed does not have an image.
So this is more about deciding wether the embed not having a related image is an error or warning worth passing on to the user.

/cc @chillu

**Comment by chillu** [comment]
Still trying to get my head around what the oEmbed lib does. I guess there's a few cases:

 * Insert video with specific player embed support (Youtube and Vimeo)
 * Insert video without player embed support (show preview image?)
 * Insert hotlinked image
 * Insert audio with player embed support (e.g. Soundcloud) = https://soundcloud.com/robot-heart/oona-dahl-robot-heart-10-year-anniversary-burning-man-2017 gives a server error
 * Insert specialised viewers like Slideshare (https://www.slideshare.net/silverstripe/the-future-of-content-delivery-81488557)  - seems to work
 * Insert website URL with HTML response (takes first image found and links it?)
 * Insert unsupported URL (e.g. https://www.linkedin.com/in/ingoschommer/)

@clarkepaul Which URL did you try to embed that didn't work for you?

It seems to do some graceful behaviour by default, but also acts weirdly: If you insert a HTML URL like https://www.silverstripe.org/blog/marketers-site-of-the-month-so-resi/, it'll show you an image in the editor, but the website title with a link (and no image) in the actual rendered content. This might be a separate issue though.

**Comment by clarkepaul** [comment]
@chillu don't know exactly anymore but try https://www.youtube.com/watch?v=bTY63efkiF as it returns the same result (doc icon without error messages)
