### ISSUE TITLE
file section: usage tab not working

### ISSUE THREAD

**Issue by katieelks** [silverstripe/silverstripe-cms#2172]
the usage counter for files seems to be broken. published images, both inside and outside content blocks, are not tracked, seems to always say 0 page(s)

**Comment by chillu** [comment]
Thanks Katie - what version of SilverStripe is this on? We've improved image and link tracking in the (unreleased) 4.2 - would be good if you can get one of your devs to check that? https://github.com/silverstripe/silverstripe-framework/blob/4/docs/en/04_Changelogs/4.2.0.md

**Comment by robbieaverill** [comment]
This is using CWP 2.0 (rc) which is SS 4.1

**Comment by dnsl48** [comment]
Cannot reproduce this one with `CWP 2.2`, `SS 4.3`.
I believe the issue has been fixed. Please reopen if it hasn't.
