### ISSUE TITLE
Extra MetaData RightTitle not displaying correct characters

### ISSUE THREAD

**Issue by korthjp17** [silverstripe/silverstripe-cms#2179]
It looks like this is rendering `<` as `&lt;`. We are using 4.1.0

![image](https://user-images.githubusercontent.com/3858661/40734933-7c62b794-63ff-11e8-9a6e-4d17223e49ce.png)

https://github.com/silverstripe/silverstripe-cms/blob/6c616f5f7a4d2611e7a8f2cbb66360079c3edb6b/code/Model/SiteTree.php#L1970

**Comment by robbieaverill** [comment]
Oh yeah! Field descriptions and titles that contain HTML need to be casted i.e. `DBField::create_field('HTMLFragment', 'content here')` - fancy a pull request? 😄

**Comment by muskie9** [comment]
@robbieaverill would this be something like `->setDescription(DBField::create_field('HTMLFragment', 'content here'))`?

**Comment by robbieaverill** [comment]
Yep! Or you could add a casting value for it too, like these examples:

https://github.com/silverstripe/silverstripe-cms/blob/6c616f5f7a4d2611e7a8f2cbb66360079c3edb6b/code/Model/SiteTree.php#L236

**Comment by muskie9** [comment]
I ran through a fresh install of `4.0.x-dev`, `4.1.x-dev` and `4.x-dev` and didn't seem to get the `&lt;`. We'll re-confirm with our installation that we don't have anything conflicting with the casting at which point we'll issue a pull request or note this to be closed.

**Comment by korthjp17** [comment]
After doing some digging, it seems to be an issue with something we are doing in a project. It appears to be correct with a base installation.
