### ISSUE TITLE
SS 3.7 bug - SiteTree doesn't load

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-cms#2183]
Upgraded a site from SS 3.6.6 to SS 3.7.0

A CWP NewsHolder page with over 50 child CWP NewsPage's no longer showed all the children when I clicked the expand arrows in the CMS SiteTree to show all of the children

Running CWP 1.8.2 and not using lumberjack

**Comment by robbieaverill** [comment]
Potentially related: https://github.com/silverstripe/silverstripe-subsites/issues/286

**Comment by phptek** [comment]
@emteknetnz There is a YML config limit that is configurable, for controling the number of child objects that can be shown. Have a look at, and experiment with: `Hierarchy::$node_threshold_total` and `Hierarchy::$node_threshold_leaf`.

**Comment by robbieaverill** [comment]
@azt3k has added some useful background information on https://github.com/silverstripe/silverstripe-framework/issues/8169

**Comment by kinglozzer** [comment]
Looks like a regression from https://github.com/silverstripe/silverstripe-framework/pull/7035 (see comment here https://github.com/silverstripe/silverstripe-framework/pull/7035#issuecomment-318040805). We should’ve opened an issue with an appropriate milestone so it wasn’t forgotten 😖

**Comment by robbieaverill** [comment]
We've reverted the change and will release it in 3.7.1

Reference: https://github.com/silverstripe/silverstripe-framework/pull/8196
