### ISSUE TITLE
Silverstripe 4.1 Gridfield with lots of columns breaks the CMS layout 

### ISSUE THREAD

**Issue by robertclarkson** [silverstripe/silverstripe-cms#2188]
I have 12 columns in the summary fields on my data object. When viewing the gridfield in the CMS the layout of the whole CMS breaks. See attached screen shot.
https://imgur.com/a/inWPZYs

**Comment by dhensby** [comment]
perhaps a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/3742

**Comment by maxime-rainville** [comment]
We've got a lot of work coming up on the Gridfield. I'm thinking this one might not be worth fixing in this context.

**Comment by robertclarkson** [comment]
Yes looks like a duplicate.
