### ISSUE TITLE
[SS 3.x] Defaults not applied on page type change. Wrong ClassName used when calling DataObject::newClassInstance from CMSMain::save

### ISSUE THREAD

**Issue by JoshuaCarter** [silverstripe/silverstripe-cms#2194]
https://github.com/silverstripe/silverstripe-cms/blob/7052170e89799051344d45fd8b851bd004e0bd03/code/controllers/CMSMain.php#L976

Discovered as a result of investigating an issue with the ListingPage module here (for context):
https://github.com/nyeholt/silverstripe-listingpage/issues/23

#### Issue:

When changing page type and triggering a `write` from the CMS (saving to draft, etc), the page object's default's aren't applied to the DB.

#### Findings:

Initially was looking into why `populateDefaults`, `onBeforeWrite`, and `onAfterWrite` weren't being called on the `ListingPage` object after changing page type from `Page` to `ListingPage` and saving to draft in the CMS.

Instead I found that these were all being called on `Page` object instead. On looking into why, I found that `DataObject::newClassInstance` was being given the new/original `ClassName` the wrong way around.

So, when changing from `Page` to `ListingPage`, `newClassInstance` is called with a 'new' class of `Page` and an 'original' class of `ListingPage` (even though it's never been a ListingPage at this point). `newClassInstance` creates a new instance with the `ClassName` of 'Page', and then calls `setClassName` and `populateDefaults` on it. Something similar occurs regarding `on{Before/After}Write`, etc.

#### Cause:

Refer to top link (CMSMain#L976). The comments here make it clear that it's assumed that `ClassName` will have already been set to the new value via `$form->saveInto`, and thus can be retrieved from `$record` rather than `$data`. But you can see below, on line #985, that `saveInto` is called after the fact.

This can be juxtaposed with the SS4 equivalent, which solves the problem by effectively retrieving `ClassName` from `$record` and `$data` in the opposite order. See link:

https://github.com/silverstripe/silverstripe-cms/blob/7c3dba283c47a1db06da3571879d49e973045b95/code/Controllers/CMSMain.php#L1676

I presume this can be fixed in a similar manner for SS 3.7

Thanks.

**Comment by dhensby** [comment]
We'll be releasing 3.7.1 very soon, if you want to get a fix into that, would you be able to get a PR to us?

**Comment by JoshuaCarter** [comment]
Done, please find it here:
https://github.com/silverstripe/silverstripe-cms/pull/2195
