### ISSUE TITLE
Adding images via the HTMLEditorField sets image to "draft" state and doesn't change

### ISSUE THREAD

**Issue by Codesesh** [silverstripe/silverstripe-cms#2200]
I am using SS 4.1.2 - When adding an image into the `HTMLEditorField`, the image saves in a `draft` state, but when hitting save or publish it isn't publishing and it's state is staying as draft. Meaning when I am logged in I can see the image showing, when logged out image is broken and not showing.

One test I did was adding an `HTMLEditorField` to the SiteConfig area, add an image into it, hit save. Image's state is still draft.

If I go into the Files tab, select the image and click the "Publish" button in the bottom right it works after that.

Is this a bug or am I missing something?

**Update**

This is happening when using the Elemental block module as well, I have created an issue on their github as well: https://github.com/dnadesign/silverstripe-elemental/issues/247

When creating a standard page and using the `HTMLEditorFIeld` it seems to work fine.

**Comment by bummzack** [comment]
This has already been reported here: https://github.com/silverstripe/silverstripe-versioned/issues/75
Should be fixed with 4.2, once it's released.

**Comment by dhensby** [comment]
closing as duplicate
