### ISSUE TITLE
Image placement should replicate actual position in TinyMCE

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-cms#2202]
@clarkepaul commented on [Tue Jun 19 2018](https://github.com/silverstripe/cwp/issues/120)

For CWP themes the CMS doesn't detect the position of image alignment, so there is a disconnect between the preview and whats displayed in TinyMCE. 

![image](https://user-images.githubusercontent.com/555033/41576650-bb42effa-73dc-11e8-9571-ed3f19f00a9a.png)

Image provided during CMS training.

**Comment by robbieaverill** [comment]
Initially raised as a CWP bug, I've replicated this on the CMS demo site (running 4.1.0).

Notes:

* Images that have a "center" alignment chosen when inserting them from files are correctly centered on the frontend
* Images that are center aligned via WYSIWYG button for test are not center aligned correctly in the frontend
* WYSIWYG center aligns images by applying margin-left/margin-right: auto style definitions to them which get lost when saving the page

**Comment by lukereative** [comment]
I can't seem to replicate this on a fresh 4.1.0 install with cwp-starter + watea. My images get the `center` class applied appropriately and the result is displayed correctly.

**Comment by lukereative** [comment]
@robbieaverill is there any clarification you can give on this

**Comment by robbieaverill** [comment]
@lukereative insert an image, click on it, click "Center" in the WYSIWYG alignment options - see it's not honoured.

I think you're right in that silverstripe/silverstripe-asset-admin#801 has resolved the bug when aligning via the dropdown in the image details modal - that looks like it's working now.

I'm testing this on demo.silverstripe.org FYI

**Comment by lukereative** [comment]
@robbieaverill Oh I get you now, I didn't realise those buttons controlled image position. I thought they were for text only – it seems a bit broken that they insert inline styles separate to using the alignment classes that the file dialogue uses. I guess changing these buttons to instead use those 'right', 'left', 'centre' classes is the correct fix.

**Comment by robbieaverill** [comment]
Fixed in https://github.com/silverstripe/silverstripe-framework/pull/8351
