### ISSUE TITLE
SS4 - When hovering over page name in site tree, page type is not displayed anymore.

### ISSUE THREAD

**Issue by Codesesh** [silverstripe/silverstripe-cms#2204]
In SS 4.1.2 when you hover over a page name then page type is not displayed anymore, I found this quite good to quickly see what that page is using without having to go into the pages settings etc. Any chance of adding this back in?

**Comment by Codesesh** [comment]
@robbieaverill - Apologies - just doubled checked version of SS for this project and its 4.1.1 - I will upgrade :)

**Comment by robbieaverill** [comment]
Great! Thanks =)
