### ISSUE TITLE
Newly created anchors not listed in insert link / Anchor on a page dialog

### ISSUE THREAD

**Issue by jareddreyer** [silverstripe/silverstripe-cms#2216]
If a user adds an anchor via the anchor button in TinyMCE, the Insert Link dialog/ 'Anchor on a page' does not list newly created anchors. 

They only show up if the user firstly; creates an anchor, then saves the page (either draft or publish) and then refreshes the edit page from their browser.

SilverStripe version(s): 4.0.3 ~ 4.1.2
Browser: Firefox (latest) & Chrome (latest)
PHP version: 5.6
Operating System: Windows 10
Any installed SilverStripe modules: default Silverstripe 4 install

**Comment by brynwhyman** [comment]
Expecting this would be resolved by #2268 so we'll track the work there. Feel free to re-open if you disagree.

**Comment by NightJar** [comment]
This was addressed and fixed in #2469 :)
