### ISSUE TITLE
SS4: Unpublish & archive throwing internal server error when deleting a page

### ISSUE THREAD

**Issue by Codesesh** [silverstripe/silverstripe-cms#2233]
When trying to unpublish & archive a page from the site tree it is throwing a internal server error. I made a video to demonstrate:

https://cl.ly/2q3W3H0q152v

If you delete the page whilst you are on it by using the shortcut down the bottom it works fine. (Also shown in the video.

Using SS 4.2.0

**Comment by robbieaverill** [comment]
@Codesesh can you please provide the specific version of SS4 you're using?

**Comment by prij** [comment]
I'm also experiencing this issue with Batch Actions

**Comment by liamchowneydev** [comment]
I am also having this same issue

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-admin/pull/605

**Comment by dhensby** [comment]
is this a dupliate of https://github.com/silverstripe/silverstripe-admin/issues/579 and fixed by https://github.com/silverstripe/silverstripe-admin/pull/581 ?

**Comment by robbieaverill** [comment]
Yep, fixed by https://github.com/silverstripe/silverstripe-admin/pull/581
