### ISSUE TITLE
Feature Request for SS3: Backport SS4 null operator in limit

### ISSUE THREAD

**Issue by digitall-it** [silverstripe/silverstripe-cms#2236]
@kinglozzer says 

> `<% loop $Items.Limit(999999, 1) %>`, or if you’re using SS4 I _think_ you can use `$Items.Limit(null, 1)`

I think the second syntax, if the statement is true, can be backported in SS3 safely and easily.

**Comment by kinglozzer** [comment]
@digitall-it Sorry, I know I said to open an issue - I thought you meant an issue about updating the examples in the docs to include the `$offset` parameter 😅

We won’t backport any functionality to 3.x now as 3.x is only receiving security fixes.
