### ISSUE TITLE
Date doesn't work in other languages

### ISSUE THREAD

**Issue by Misagh90** [silverstripe/silverstripe-cms#2240]
The Date Filed doesn't work in another languages
![screenshot 226](https://user-images.githubusercontent.com/6697222/44520785-2c41d180-a6e6-11e8-8737-4be662d006f5.png)
![screenshot 227](https://user-images.githubusercontent.com/6697222/44520797-3237b280-a6e6-11e8-93e9-7b0db11e0676.png)

**Comment by robbieaverill** [comment]
Thanks for reporting. I _think_ this is a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/8339, so I'm going to close this in favour of that. Please follow that issue.
