### ISSUE TITLE
Insert Link window has shrunk (IE11 only)

### ISSUE THREAD

**Issue by katieelks** [silverstripe/silverstripe-cms#2246]
This is a consequesnce of the CWP 1.2 upgrade as it is not happening in other environments

To reproduce: (IE11 only)

From the wysiwyg highlight some text and click the insert some text button
select 'Page on this site'
Result:
The window is much smaller now/weird looking (see screenshots)
This makes adding a page on the site much more difficult to navigate

![ie11-wisywig-editor](https://user-images.githubusercontent.com/38870753/44890433-59b5fd00-ad2e-11e8-97d9-cf3af9dc74eb.PNG)
![link to a page](https://user-images.githubusercontent.com/38870753/44890435-5a4e9380-ad2e-11e8-8b26-d39e35f7d53f.GIF)

## PRs
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/640
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/835

**Comment by bergice** [comment]
Good to merge this as soon as the merge conflict is resolved: https://github.com/silverstripe/silverstripe-admin/pull/640

**Comment by bergice** [comment]
Merged.
