### ISSUE TITLE
Batch Actions: Database Error

### ISSUE THREAD

**Issue by kiwidood** [silverstripe/silverstripe-cms#2254]
On a base install of SS 4.2.1 Batch Actions throws a 500 Internal Server Error.

Inspecting the request to /admin/pages/edit/batchactions/unpublish reports the following error:
`ERROR [Emergency]: Uncaught SilverStripe\ORM\Connect\DatabaseException: Couldn't run query:

SELECT DISTINCT "SiteTree_Versions"."ClassName", "SiteTree_Versions"."LastEdited", "SiteTree_Versions"."Created", "SiteTree_Versions"."CanViewType", "SiteTree_Versions"."CanEditType", "SiteTree_Versions"."Version", "SiteTree_Versions"."URLSegment", "SiteTree_Versions"."Title", "SiteTree_Versions"."MenuTitle", "SiteTree_Versions"."Content", "SiteTree_Versions"."MetaDescription", "SiteTree_Versions"."ExtraMeta", "SiteTree_Versions"."ShowInMenus", "SiteTree_Versions"."ShowInSearch", "SiteTree_Versions"."Sort", "SiteTree_Versions"."HasBrokenFile", "SiteTree_Versions"."HasBrokenLink", "SiteTree_Versions"."ReportClass", "SiteTree_Versions"."ParentID", "SiteTree_Versions"."RecordID" AS "ID", 
			CASE WHEN "SiteTree_Versions"."ClassName" IS NOT NULL THEN "SiteTree_Versions"."ClassName"
			ELSE 'SilverStripe\\CMS\\Model\\SiteTree' END AS "RecordClassName", "SiteTree_Versions"."RecordID", "SiteTree_Versions"."WasPublished", "SiteTree_Versions"."WasDeleted", "SiteTree_Versions"."WasDraft", "SiteTree_Versions"."AuthorID", "SiteTree_Versions"."PublisherID"

FROM "SiteTree_Versions"
INNER JOIN             (
           
SELECT "SiteTree_Versions"."RecordID",
                MAX("SiteTree_Versions"."Version") AS "LatestVersion"
           
FROM "SiteTree_Versions"
           
WHERE "SiteTree_Versions"."WasDeleted" = 0
           
GROUP BY "SiteTree_Versions"."RecordID"
            )                                 AS "SiteTree_Versions_Latest" ON             "SiteTree_Versions_Latest"."RecordID" = "SiteTree_Versions"."RecordID"
            AND "SiteTree_Versions_Latest"."LatestVersion" = "SiteTree_Versions"."Version"

WHERE ("RecordID" IN (?))
 AND ("SiteTree_Versions"."WasDeleted" = ?)

ORDER BY "SiteTree_Versions"."Sort" ASC

23000-1052: Column 'RecordID' in where clause is ambiguous
IN POST /admin/pages/batchactions/unpublish
Line 64 in /home/vagrant/silverstripe/vendor/silverstripe/framework/src/ORM/Connect/DBConnector.php

Source
======
  55:          if (!empty($sql)) {
  56:              $formatter = new SQLFormatter();
  57:              $formattedSQL = $formatter->formatPlain($sql);
  58:              $msg = "Couldn't run query:\n\n{$formattedSQL}\n\n{$msg}";
  59:          }
  60:  
  61:          if ($errorLevel === E_USER_ERROR) {
  62:              // Treating errors as exceptions better allows for responding to errors
  63:              // in code, such as credential checking during installation
* 64:              throw new DatabaseException($msg, 0, null, $sql, $parameters);
  65:          } else {
  66:              user_error($msg, $errorLevel);
  67:          }
  68:      }
  69:  
  70:      /**

Trace
=====
SilverStripe\ORM\Connect\DBConnector->databaseError(Couldn't run query:

SELECT DISTINCT "SiteTree_Versions"."ClassName", "SiteTree_Versions"."LastEdited", "SiteTree_Versions"."Created", "SiteTree_Versions"."CanViewType", "SiteTree_Versions"."CanEditType", "SiteTree_Versions"."Version", "SiteTree_Versions"."URLSegment", "SiteTree_Versions"."Title", "SiteTree_Versions"."MenuTitle", "SiteTree_Versions"."Content", "SiteTree_Versions"."MetaDescription", "SiteTree_Versions"."ExtraMeta", "SiteTree_Versions"."ShowInMenus", "SiteTree_Versions"."ShowInSearch", "SiteTree_Versions"."Sort", "SiteTree_Versions"."HasBrokenFile", "SiteTree_Versions"."HasBrokenLink", "SiteTree_Versions"."ReportClass", "SiteTree_Versions"."ParentID", "SiteTree_Versions"."RecordID" AS "ID", 
			CASE WHEN "SiteTree_Versions"."ClassName" IS NOT NULL THEN "SiteTree_Versions"."ClassName"
			ELSE 'SilverStripe\\CMS\\Model\\SiteTree' END AS "RecordClassName", "SiteTree_Versions"."RecordID", "SiteTree_Versions"."WasPublished", "SiteTree_Versions"."WasDeleted", "SiteTree_Versions"."WasDraft", "SiteTree_Versions"."AuthorID", "SiteTree_Versions"."PublisherID"

FROM "SiteTree_Versions"
INNER JOIN             (
           
SELECT "SiteTree_Versions"."RecordID",
                MAX("SiteTree_Versions"."Version") AS "LatestVersion"
           
FROM "SiteTree_Versions"
           
WHERE "SiteTree_Versions"."WasDeleted" = 0
           
GROUP BY "SiteTree_Versions"."RecordID"
            )                                 AS "SiteTree_Versions_Latest" ON             "SiteTree_Versions_Latest"."RecordID" = "SiteTree_Versions"."RecordID"
            AND "SiteTree_Versions_Latest"."LatestVersion" = "SiteTree_Versions"."Version"

WHERE ("RecordID" IN (?))
 AND ("SiteTree_Versions"."WasDeleted" = ?)

ORDER BY "SiteTree_Versions"."Sort" ASC

23000-1052: Column 'RecordID' in where clause is ambiguous, 256, SELECT DISTINCT "SiteTree_Versions"."ClassName", "SiteTree_Versions"."LastEdited", "SiteTree_Versions"."Created", "SiteTree_Versions"."CanViewType", "SiteTree_Versions"."CanEditType", "SiteTree_Versions"."Version", "SiteTree_Versions"."URLSegment", "SiteTree_Versions"."Title", "SiteTree_Versions"."MenuTitle", "SiteTree_Versions"."Content", "SiteTree_Versions"."MetaDescription", "SiteTree_Versions"."ExtraMeta", "SiteTree_Versions"."ShowInMenus", "SiteTree_Versions"."ShowInSearch", "SiteTree_Versions"."Sort", "SiteTree_Versions"."HasBrokenFile", "SiteTree_Versions"."HasBrokenLink", "SiteTree_Versions"."ReportClass", "SiteTree_Versions"."ParentID", "SiteTree_Versions"."RecordID" AS "ID", 
			CASE WHEN "SiteTree_Versions"."ClassName" IS NOT NULL THEN "SiteTree_Versions"."ClassName"
			ELSE 'SilverStripe\\CMS\\Model\\SiteTree' END AS "RecordClassName", "SiteTree_Versions"."RecordID", "SiteTree_Versions"."WasPublished", "SiteTree_Versions"."WasDeleted", "SiteTree_Versions"."WasDraft", "SiteTree_Versions"."AuthorID", "SiteTree_Versions"."PublisherID"
 FROM "SiteTree_Versions" INNER JOIN             (
            SELECT "SiteTree_Versions"."RecordID",
                MAX("SiteTree_Versions"."Version") AS "LatestVersion"
            FROM "SiteTree_Versions"
            WHERE "SiteTree_Versions"."WasDeleted" = 0
            GROUP BY "SiteTree_Versions"."RecordID"
            )                                 AS "SiteTree_Versions_Latest" ON             "SiteTree_Versions_Latest"."RecordID" = "SiteTree_Versions"."RecordID"
            AND "SiteTree_Versions_Latest"."LatestVersion" = "SiteTree_Versions"."Version"
 WHERE ("RecordID" IN (?))
 AND ("SiteTree_Versions"."WasDeleted" = ?)
 ORDER BY "SiteTree_Versions"."Sort" ASC, Array)
PDOConnector.php:398

SilverStripe\ORM\Connect\PDOConnector->prepareResults(256, SELECT DISTINCT "SiteTree_Versions"."ClassName", "SiteTree_Versions"."LastEdited", "SiteTree_Versions"."Created", "SiteTree_Versions"."CanViewType", "SiteTree_Versions"."CanEditType", "SiteTree_Versions"."Version", "SiteTree_Versions"."URLSegment", "SiteTree_Versions"."Title", "SiteTree_Versions"."MenuTitle", "SiteTree_Versions"."Content", "SiteTree_Versions"."MetaDescription", "SiteTree_Versions"."ExtraMeta", "SiteTree_Versions"."ShowInMenus", "SiteTree_Versions"."ShowInSearch", "SiteTree_Versions"."Sort", "SiteTree_Versions"."HasBrokenFile", "SiteTree_Versions"."HasBrokenLink", "SiteTree_Versions"."ReportClass", "SiteTree_Versions"."ParentID", "SiteTree_Versions"."RecordID" AS "ID", 
			CASE WHEN "SiteTree_Versions"."ClassName" IS NOT NULL THEN "SiteTree_Versions"."ClassName"
			ELSE 'SilverStripe\\CMS\\Model\\SiteTree' END AS "RecordClassName", "SiteTree_Versions"."RecordID", "SiteTree_Versions"."WasPublished", "SiteTree_Versions"."WasDeleted", "SiteTree_Versions"."WasDraft", "SiteTree_Versions"."AuthorID", "SiteTree_Versions"."PublisherID"
 FROM "SiteTree_Versions" INNER JOIN             (
            SELECT "SiteTree_Versions"."RecordID",
                MAX("SiteTree_Versions"."Version") AS "LatestVersion"
            FROM "SiteTree_Versions"
            WHERE "SiteTree_Versions"."WasDeleted" = 0
            GROUP BY "SiteTree_Versions"."RecordID"
            )                                 AS "SiteTree_Versions_Latest" ON             "SiteTree_Versions_Latest"."RecordID" = "SiteTree_Versions"."RecordID"
            AND "SiteTree_Versions_Latest"."LatestVersion" = "SiteTree_Versions"."Version"
 WHERE ("RecordID" IN (?))
 AND ("SiteTree_Versions"."WasDeleted" = ?)
 ORDER BY "SiteTree_Versions"."Sort" ASC)
PDOConnector.php:363

SilverStripe\ORM\Connect\PDOConnector->preparedQuery(SELECT DISTINCT "SiteTree_Versions"."ClassName", "SiteTree_Versions"."LastEdited", "SiteTree_Versions"."Created", "SiteTree_Versions"."CanViewType", "SiteTree_Versions"."CanEditType", "SiteTree_Versions"."Version", "SiteTree_Versions"."URLSegment", "SiteTree_Versions"."Title", "SiteTree_Versions"."MenuTitle", "SiteTree_Versions"."Content", "SiteTree_Versions"."MetaDescription", "SiteTree_Versions"."ExtraMeta", "SiteTree_Versions"."ShowInMenus", "SiteTree_Versions"."ShowInSearch", "SiteTree_Versions"."Sort", "SiteTree_Versions"."HasBrokenFile", "SiteTree_Versions"."HasBrokenLink", "SiteTree_Versions"."ReportClass", "SiteTree_Versions"."ParentID", "SiteTree_Versions"."RecordID" AS "ID", 
			CASE WHEN "SiteTree_Versions"."ClassName" IS NOT NULL THEN "SiteTree_Versions"."ClassName"
			ELSE 'SilverStripe\\CMS\\Model\\SiteTree' END AS "RecordClassName", "SiteTree_Versions"."RecordID", "SiteTree_Versions"."WasPublished", "SiteTree_Versions"."WasDeleted", "SiteTree_Versions"."WasDraft", "SiteTree_Versions"."AuthorID", "SiteTree_Versions"."PublisherID"
 FROM "SiteTree_Versions" INNER JOIN             (
            SELECT "SiteTree_Versions"."RecordID",
                MAX("SiteTree_Versions"."Version") AS "LatestVersion"
            FROM "SiteTree_Versions"
            WHERE "SiteTree_Versions"."WasDeleted" = 0
            GROUP BY "SiteTree_Versions"."RecordID"
            )                                 AS "SiteTree_Versions_Latest" ON             "SiteTree_Versions_Latest"."RecordID" = "SiteTree_Versions"."RecordID"
            AND "SiteTree_Versions_Latest"."LatestVersion" = "SiteTree_Versions"."Version"
 WHERE ("RecordID" IN (?))
 AND ("SiteTree_Versions"."WasDeleted" = ?)
 ORDER BY "SiteTree_Versions"."Sort" ASC, Array, 256)
Database.php:168

SilverStripe\ORM\Connect\Database->SilverStripe\ORM\Connect\{closure}(SELECT DISTINCT "SiteTree_Versions"."ClassName", "SiteTree_Versions"."LastEdited", "SiteTree_Versions"."Created", "SiteTree_Versions"."CanViewType", "SiteTree_Versions"."CanEditType", "SiteTree_Versions"."Version", "SiteTree_Versions"."URLSegment", "SiteTree_Versions"."Title", "SiteTree_Versions"."MenuTitle", "SiteTree_Versions"."Content", "SiteTree_Versions"."MetaDescription", "SiteTree_Versions"."ExtraMeta", "SiteTree_Versions"."ShowInMenus", "SiteTree_Versions"."ShowInSearch", "SiteTree_Versions"."Sort", "SiteTree_Versions"."HasBrokenFile", "SiteTree_Versions"."HasBrokenLink", "SiteTree_Versions"."ReportClass", "SiteTree_Versions"."ParentID", "SiteTree_Versions"."RecordID" AS "ID", 
			CASE WHEN "SiteTree_Versions"."ClassName" IS NOT NULL THEN "SiteTree_Versions"."ClassName"
			ELSE 'SilverStripe\\CMS\\Model\\SiteTree' END AS "RecordClassName", "SiteTree_Versions"."RecordID", "SiteTree_Versions"."WasPublished", "SiteTree_Versions"."WasDeleted", "SiteTree_Versions"."WasDraft", "SiteTree_Versions"."AuthorID", "SiteTree_Versions"."PublisherID"
 FROM "SiteTree_Versions" INNER JOIN             (
            SELECT "SiteTree_Versions"."RecordID",
                MAX("SiteTree_Versions"."Version") AS "LatestVersion"
            FROM "SiteTree_Versions"
            WHERE "SiteTree_Versions"."WasDeleted" = 0
            GROUP BY "SiteTree_Versions"."RecordID"
            )                                 AS "SiteTree_Versions_Latest" ON             "SiteTree_Versions_Latest"."RecordID" = "SiteTree_Versions"."RecordID"
            AND "SiteTree_Versions_Latest"."LatestVersion" = "SiteTree_Versions"."Version"
 WHERE ("RecordID" IN (?))
 AND ("SiteTree_Versions"."WasDeleted" = ?)
 ORDER BY "SiteTree_Versions"."Sort" ASC)
Database.php:222

SilverStripe\ORM\Connect\Database->benchmarkQuery(SELECT DISTINCT "SiteTree_Versions"."ClassName", "SiteTree_Versions"."LastEdited", "SiteTree_Versions"."Created", "SiteTree_Versions"."CanViewType", "SiteTree_Versions"."CanEditType", "SiteTree_Versions"."Version", "SiteTree_Versions"."URLSegment", "SiteTree_Versions"."Title", "SiteTree_Versions"."MenuTitle", "SiteTree_Versions"."Content", "SiteTree_Versions"."MetaDescription", "SiteTree_Versions"."ExtraMeta", "SiteTree_Versions"."ShowInMenus", "SiteTree_Versions"."ShowInSearch", "SiteTree_Versions"."Sort", "SiteTree_Versions"."HasBrokenFile", "SiteTree_Versions"."HasBrokenLink", "SiteTree_Versions"."ReportClass", "SiteTree_Versions"."ParentID", "SiteTree_Versions"."RecordID" AS "ID", 
			CASE WHEN "SiteTree_Versions"."ClassName" IS NOT NULL THEN "SiteTree_Versions"."ClassName"
			ELSE 'SilverStripe\\CMS\\Model\\SiteTree' END AS "RecordClassName", "SiteTree_Versions"."RecordID", "SiteTree_Versions"."WasPublished", "SiteTree_Versions"."WasDeleted", "SiteTree_Versions"."WasDraft", "SiteTree_Versions"."AuthorID", "SiteTree_Versions"."PublisherID"
 FROM "SiteTree_Versions" INNER JOIN             (
            SELECT "SiteTree_Versions"."RecordID",
                MAX("SiteTree_Versions"."Version") AS "LatestVersion"
            FROM "SiteTree_Versions"
            WHERE "SiteTree_Versions"."WasDeleted" = 0
            GROUP BY "SiteTree_Versions"."RecordID"
            )                                 AS "SiteTree_Versions_Latest" ON             "SiteTree_Versions_Latest"."RecordID" = "SiteTree_Versions"."RecordID"
            AND "SiteTree_Versions_Latest"."LatestVersion" = "SiteTree_Versions"."Version"
 WHERE ("RecordID" IN (?))
 AND ("SiteTree_Versions"."WasDeleted" = ?)
 ORDER BY "SiteTree_Versions"."Sort" ASC, Closure, Array)
Database.php:170

SilverStripe\ORM\Connect\Database->preparedQuery(SELECT DISTINCT "SiteTree_Versions"."ClassName", "SiteTree_Versions"."LastEdited", "SiteTree_Versions"."Created", "SiteTree_Versions"."CanViewType", "SiteTree_Versions"."CanEditType", "SiteTree_Versions"."Version", "SiteTree_Versions"."URLSegment", "SiteTree_Versions"."Title", "SiteTree_Versions"."MenuTitle", "SiteTree_Versions"."Content", "SiteTree_Versions"."MetaDescription", "SiteTree_Versions"."ExtraMeta", "SiteTree_Versions"."ShowInMenus", "SiteTree_Versions"."ShowInSearch", "SiteTree_Versions"."Sort", "SiteTree_Versions"."HasBrokenFile", "SiteTree_Versions"."HasBrokenLink", "SiteTree_Versions"."ReportClass", "SiteTree_Versions"."ParentID", "SiteTree_Versions"."RecordID" AS "ID", 
			CASE WHEN "SiteTree_Versions"."ClassName" IS NOT NULL THEN "SiteTree_Versions"."ClassName"
			ELSE 'SilverStripe\\CMS\\Model\\SiteTree' END AS "RecordClassName", "SiteTree_Versions"."RecordID", "SiteTree_Versions"."WasPublished", "SiteTree_Versions"."WasDeleted", "SiteTree_Versions"."WasDraft", "SiteTree_Versions"."AuthorID", "SiteTree_Versions"."PublisherID"
 FROM "SiteTree_Versions" INNER JOIN             (
            SELECT "SiteTree_Versions"."RecordID",
                MAX("SiteTree_Versions"."Version") AS "LatestVersion"
            FROM "SiteTree_Versions"
            WHERE "SiteTree_Versions"."WasDeleted" = 0
            GROUP BY "SiteTree_Versions"."RecordID"
            )                                 AS "SiteTree_Versions_Latest" ON             "SiteTree_Versions_Latest"."RecordID" = "SiteTree_Versions"."RecordID"
            AND "SiteTree_Versions_Latest"."LatestVersion" = "SiteTree_Versions"."Version"
 WHERE ("RecordID" IN (?))
 AND ("SiteTree_Versions"."WasDeleted" = ?)
 ORDER BY "SiteTree_Versions"."Sort" ASC, Array, 256)
MySQLDatabase.php:387

SilverStripe\ORM\Connect\MySQLDatabase->preparedQuery(SELECT DISTINCT "SiteTree_Versions"."ClassName", "SiteTree_Versions"."LastEdited", "SiteTree_Versions"."Created", "SiteTree_Versions"."CanViewType", "SiteTree_Versions"."CanEditType", "SiteTree_Versions"."Version", "SiteTree_Versions"."URLSegment", "SiteTree_Versions"."Title", "SiteTree_Versions"."MenuTitle", "SiteTree_Versions"."Content", "SiteTree_Versions"."MetaDescription", "SiteTree_Versions"."ExtraMeta", "SiteTree_Versions"."ShowInMenus", "SiteTree_Versions"."ShowInSearch", "SiteTree_Versions"."Sort", "SiteTree_Versions"."HasBrokenFile", "SiteTree_Versions"."HasBrokenLink", "SiteTree_Versions"."ReportClass", "SiteTree_Versions"."ParentID", "SiteTree_Versions"."RecordID" AS "ID", 
			CASE WHEN "SiteTree_Versions"."ClassName" IS NOT NULL THEN "SiteTree_Versions"."ClassName"
			ELSE 'SilverStripe\\CMS\\Model\\SiteTree' END AS "RecordClassName", "SiteTree_Versions"."RecordID", "SiteTree_Versions"."WasPublished", "SiteTree_Versions"."WasDeleted", "SiteTree_Versions"."WasDraft", "SiteTree_Versions"."AuthorID", "SiteTree_Versions"."PublisherID"
 FROM "SiteTree_Versions" INNER JOIN             (
            SELECT "SiteTree_Versions"."RecordID",
                MAX("SiteTree_Versions"."Version") AS "LatestVersion"
            FROM "SiteTree_Versions"
            WHERE "SiteTree_Versions"."WasDeleted" = 0
            GROUP BY "SiteTree_Versions"."RecordID"
            )                                 AS "SiteTree_Versions_Latest" ON             "SiteTree_Versions_Latest"."RecordID" = "SiteTree_Versions"."RecordID"
            AND "SiteTree_Versions_Latest"."LatestVersion" = "SiteTree_Versions"."Version"
 WHERE ("RecordID" IN (?))
 AND ("SiteTree_Versions"."WasDeleted" = ?)
 ORDER BY "SiteTree_Versions"."Sort" ASC, Array, 256)
DB.php:445

SilverStripe\ORM\DB::prepared_query(SELECT DISTINCT "SiteTree_Versions"."ClassName", "SiteTree_Versions"."LastEdited", "SiteTree_Versions"."Created", "SiteTree_Versions"."CanViewType", "SiteTree_Versions"."CanEditType", "SiteTree_Versions"."Version", "SiteTree_Versions"."URLSegment", "SiteTree_Versions"."Title", "SiteTree_Versions"."MenuTitle", "SiteTree_Versions"."Content", "SiteTree_Versions"."MetaDescription", "SiteTree_Versions"."ExtraMeta", "SiteTree_Versions"."ShowInMenus", "SiteTree_Versions"."ShowInSearch", "SiteTree_Versions"."Sort", "SiteTree_Versions"."HasBrokenFile", "SiteTree_Versions"."HasBrokenLink", "SiteTree_Versions"."ReportClass", "SiteTree_Versions"."ParentID", "SiteTree_Versions"."RecordID" AS "ID", 
			CASE WHEN "SiteTree_Versions"."ClassName" IS NOT NULL THEN "SiteTree_Versions"."ClassName"
			ELSE 'SilverStripe\\CMS\\Model\\SiteTree' END AS "RecordClassName", "SiteTree_Versions"."RecordID", "SiteTree_Versions"."WasPublished", "SiteTree_Versions"."WasDeleted", "SiteTree_Versions"."WasDraft", "SiteTree_Versions"."AuthorID", "SiteTree_Versions"."PublisherID"
 FROM "SiteTree_Versions" INNER JOIN             (
            SELECT "SiteTree_Versions"."RecordID",
                MAX("SiteTree_Versions"."Version") AS "LatestVersion"
            FROM "SiteTree_Versions"
            WHERE "SiteTree_Versions"."WasDeleted" = 0
            GROUP BY "SiteTree_Versions"."RecordID"
            )                                 AS "SiteTree_Versions_Latest" ON             "SiteTree_Versions_Latest"."RecordID" = "SiteTree_Versions"."RecordID"
            AND "SiteTree_Versions_Latest"."LatestVersion" = "SiteTree_Versions"."Version"
 WHERE ("RecordID" IN (?))
 AND ("SiteTree_Versions"."WasDeleted" = ?)
 ORDER BY "SiteTree_Versions"."Sort" ASC, Array)
SQLExpression.php:115

SilverStripe\ORM\Queries\SQLExpression->execute()
DataList.php:733

SilverStripe\ORM\DataList->toArray()
DataList.php:844

SilverStripe\ORM\DataList->getIterator()
CMSBatchAction.php:106

SilverStripe\Admin\CMSBatchAction->batchaction(SilverStripe\ORM\DataList, doUnpublish, Unpublished %d pages)
CMSBatchAction_Unpublish.php:23

SilverStripe\CMS\BatchActions\CMSBatchAction_Unpublish->run(SilverStripe\ORM\DataList)
CMSBatchActionHandler.php:158

SilverStripe\Admin\CMSBatchActionHandler->handleBatchAction(SilverStripe\Control\HTTPRequest)
RequestHandler.php:320

SilverStripe\Control\RequestHandler->handleAction(SilverStripe\Control\HTTPRequest, handleBatchAction)
RequestHandler.php:202

SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest)
RequestHandler.php:226

SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest)
Controller.php:212

SilverStripe\Control\Controller->handleRequest(SilverStripe\Control\HTTPRequest)
LeftAndMain.php:755

SilverStripe\Admin\LeftAndMain->handleRequest(SilverStripe\Control\HTTPRequest)
AdminRootController.php:123

SilverStripe\Admin\AdminRootController->handleRequest(SilverStripe\Control\HTTPRequest)
Director.php:361

SilverStripe\Control\Director->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest)
VersionedHTTPMiddleware.php:40

SilverStripe\Versioned\VersionedHTTPMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
BasicAuthMiddleware.php:68

SilverStripe\Security\BasicAuthMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
AuthenticationMiddleware.php:61

SilverStripe\Security\AuthenticationMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
CanonicalURLMiddleware.php:188

SilverStripe\Control\Middleware\CanonicalURLMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
HTTPCacheControlMiddleware.php:42

SilverStripe\Control\Middleware\HTTPCacheControlMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
ChangeDetectionMiddleware.php:27

SilverStripe\Control\Middleware\ChangeDetectionMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
FlushMiddleware.php:29

SilverStripe\Control\Middleware\FlushMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
RequestProcessor.php:66

SilverStripe\Control\RequestProcessor->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
SessionMiddleware.php:20

SilverStripe\Control\Middleware\SessionMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
AllowedHostsMiddleware.php:60

SilverStripe\Control\Middleware\AllowedHostsMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
TrustedProxyMiddleware.php:176

SilverStripe\Control\Middleware\TrustedProxyMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
HTTPMiddlewareAware.php:65

SilverStripe\Control\Director->callMiddleware(SilverStripe\Control\HTTPRequest, Closure)
Director.php:370

SilverStripe\Control\Director->handleRequest(SilverStripe\Control\HTTPRequest)
HTTPApplication.php:48

SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest)

call_user_func(Closure, SilverStripe\Control\HTTPRequest)
HTTPApplication.php:66

SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest)

call_user_func(Closure, SilverStripe\Control\HTTPRequest)
ErrorControlChainMiddleware.php:56

SilverStripe\Core\Startup\ErrorControlChainMiddleware->SilverStripe\Core\Startup\{closure}(SilverStripe\Core\Startup\ErrorControlChain)

call_user_func(Closure, SilverStripe\Core\Startup\ErrorControlChain)
ErrorControlChain.php:236

SilverStripe\Core\Startup\ErrorControlChain->step()
ErrorControlChain.php:226

SilverStripe\Core\Startup\ErrorControlChain->execute()
ErrorControlChainMiddleware.php:69

SilverStripe\Core\Startup\ErrorControlChainMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\HTTPApplication->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
HTTPMiddlewareAware.php:65

SilverStripe\Control\HTTPApplication->callMiddleware(SilverStripe\Control\HTTPRequest, Closure)
HTTPApplication.php:67

SilverStripe\Control\HTTPApplication->execute(SilverStripe\Control\HTTPRequest, Closure, )
HTTPApplication.php:49

SilverStripe\Control\HTTPApplication->handle(SilverStripe\Control\HTTPRequest)
index.php:25`

**Comment by robbieaverill** [comment]
Hi @kiwidood, thanks for reporting. We've already fixed this in https://github.com/silverstripe/silverstripe-admin/pull/581 and it will be available in the next release. Cheers =)
