### ISSUE TITLE
Adding fields to link modals

### ISSUE THREAD

**Issue by Zazama** [silverstripe/silverstripe-cms#2273]
Hello,
I'm using SS 4.2.1, is there any way to add fields to the link modals in the HTML editor?

I've tried extending the InternalLinkFormFactory.php's getFormFields function and the InternalLinkModalExtension's editorInternalLink function but new fields don't show up.

```php
class InternalLinkFormFactoryExtension extends Extension {
    protected function getFormFields($controller, $name, $context)
    {
        $fields = parent::getFormFields();

        $fields->addFieldToTab(TextField::create('testabv', 'testabv'));

        return $fields;
    }
}
```

```yml
SilverStripe\CMS\Forms\InternalLinkFormFactory:
  extensions:
    - InternalLinkFormFactoryExtension
```

## Pull requests

- [ ] https://github.com/silverstripe/silverstripe-admin/pull/661
- [ ] https://github.com/silverstripe/silverstripe-cms/pull/2274

**Comment by robbieaverill** [comment]
You probably want to use the updateFormFields hook since it’s an Extension class

**Comment by Zazama** [comment]
I've tried updateFormFields too, but there is no change.

**Comment by robbieaverill** [comment]
Oh, those factories aren't extensible at all! I'll make a PR to add extension hooks. For now you're going to need to overload the class with Injector and make your modifications that way

**Comment by robbieaverill** [comment]
PRs added to the issue description
