### ISSUE TITLE
use of create_function() is deprecated in PHP7.2

### ISSUE THREAD

**Issue by RoyalPulp** [silverstripe/silverstripe-cms#2275]
affects v3 (with php7.2)

create_function() should not be used anymore, instead ->  Anonymous Function (aka Closure) 

-> SiteTree.php: Line 2116
-> VirtualPage.php: Line 177
-> SearchForm.php: Lines 134, 137

[I got PHP Error in Backend -> Settings of a page ]

**Comment by RoyalPulp** [comment]
I try - but I am not 100% sure I get it right - after changing "create_funtion()" to an anonymous function, there seem to be more deprecations in SearchForm: each() is also deprecated -> Line 179

Would this be right for SearchForm???
`$andProcessor = (function($matches){
    return  $matches[2] . " +" . $matches[4];});

$notProcessor = (function($matches){
    return " -" . $matches[3];});`

I am lacking time for a deeper look this week - so I think, as these messages occur in dev environments only (warning level shows all info/warning/error messages) , while on live Servers it seems to work, so it is not that urgent

**Comment by sminnee** [comment]
Should we update our build matrix to include PHP 7.2?

**Comment by robbieaverill** [comment]
Ideally, yes. Last time I tried it (with a module) all hell broke loose with the Object/SS_Object compatibility files. That's not really a sustainable excuse though, we need it (and 7.3) in SS3 builds between now and SS3's EOL

**Comment by robbieaverill** [comment]
Closing as fixed, feel free to reopen if anyone finds more PHP 7.2 incompatibilities

**Comment by nimeso** [comment]
I have this issue in SS3 and I can't upgrade this client to SS4... any chance to fix it?

**Comment by nimeso** [comment]
@robbieaverill cheers ears. I'll try out 3.7.x.dev and let ya know.
