### ISSUE TITLE
Use Injector to get reference to CMSMain controllers instead of `::singleton`

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-cms#2284]
Some projects would like to override `CMSMain` or other related controllers with their own implementation. However they are a few places where we do calls like `CMSMain::singleton()->Link()` which will always return our core implementation.

These should be substituted with Injector calls instead.

**Comment by robbieaverill** [comment]
Asking for a singleton goes through injector, I’m not sure why this is a problem =/

**Comment by robbieaverill** [comment]
@blueo sanity check that MyCMSPageAddController extends CMSPageAddController?

**Comment by blueo** [comment]
ah 🤦‍♂️ thanks @robbieaverill . I did not know about singleton either so all the learns....

**Comment by blueo** [comment]
feel free to close this

**Comment by maxime-rainville** [comment]
Mistakes were made.
