### ISSUE TITLE
BUG(?): v4.2.1 CMSMain::duplicate() permission requirements

### ISSUE THREAD

**Issue by chrispenny** [silverstripe/silverstripe-cms#2285]
Enhancement or bug, I'm really not sure.

## The issue

`CMSMain::duplicate()` requires that a user can both `edit` and `create` a record in order to duplicate it:
```
if ($page && (!$page->canEdit() || !$page->canCreate(null, array('Parent' => $page->Parent())))) {
    return Security::permissionFailure($this);
}
```

I believe that only checking for `canCreate` is the appropriate behaviour here.

I understand the reasoning for checking both. "Why duplicate a Page if you're not going to be able to edit it afterwards", but the ability to edit or not might be based on the state of the `DataObject`, and at a project level, you might be implementing `onBeforeDuplicate()` and removing some of that state.

I think it would be good if the concerns around duplicating and editing were separate.

I'm not sure if it would be better still to have a `canDuplicate` check(?).

Cheers, team!

## Pull requests 

- [ ] https://github.com/silverstripe/silverstripe-cms/pull/2289

**Comment by robbieaverill** [comment]
I agree with making it only check for `canCreate`, because by duplicating a record you're _creating_ a new one. You're not really editing it at that point, and `canEdit` checks will prevent you from doing that later if you don't have permission to.

**Comment by robbieaverill** [comment]
cc @clarkepaul - do you agree with my reasoning?

**Comment by robbieaverill** [comment]
cc @silverstripe/core-team

**Comment by clarkepaul** [comment]
Tricky one, I'm pretty torn on this one. I can see the reasoning for using `canCreate` so as to not complicate matters too much for both the UI settings and for developing. I agree with your comments @robbieaverill

**Comment by robbieaverill** [comment]
@clarkepaul @kinglozzer @flamerohr and myself from the core team have indicated that we could remove the canEdit() checks here, so I'll do that =)
