### ISSUE TITLE
PJAX Error

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-cms#2301]
Using 4.2.1 (With CWP modules @2.2.1) and attempting to run an "Unpublish" batch-action, I see an HTTP 400 "Bad Request". The specific message in the console is:

`Ajax requests to this URL require an X-Pjax header.` I didn't realise the CMS still used PJAX. In fact, I don't believe I ever discovered what it really was...

This happens in two separate codebases, one of which I just hard-out upgraded from 4.0 to 4.2.1 (Using CWP 2.2.1 packages) to see what would happen.

**Comment by maxime-rainville** [comment]
I didn't manage to replicate this on SS4.3 with the CWP kitchen sink. I was trying to do on the site tree. Am I looking at the right place?

Also if you could post the exact HTTP request that's triggering the error by looking at the network tab in your browser console, that would be helpful.

**Comment by noizyboy** [comment]
Same issue here (with similar setup as @phptek - CWP 2.1.1 / SS 4.2.1)

When I select a coupe of pages to unpublish and archive, this request is initially fired:
admin/pages/edit/batchactions/archive/applicablepages/?csvIDs=0%2C1%2C4%2C5%2C14%2C15%2C16%2C17%2C18%2C19%2C21%2C22%2C23

And comes back with this responsse
[1,15,16,4,5,14,17,18,19,21,22,23]

At this point, hitting 'Go' fires off a request to the /archive URL, but that's instantly replaced in my network inspector by the /pages URL, which returns the `Ajax requests to this URL require an X-Pjax header` error. 

![bulk-edit](https://user-images.githubusercontent.com/416980/49545344-3a88c600-f942-11e8-9c34-7da83afdc326.jpg)

![bulk-response](https://user-images.githubusercontent.com/416980/49545357-3fe61080-f942-11e8-82a2-ad98932b9713.jpg)

**Comment by maxime-rainville** [comment]
It's present in SS 4.2.1, but not in 4.2.2. Just update to that patch release and it solve the problem.

I'll close this for now, but let us know if upgrading to 4.2.2 doesn't fix the issue and I'll reopen

**Comment by noizyboy** [comment]
thanks @maxime-rainville. We're using the CWP recipe as supplied by gitlab.cwp.govt.nz, which makes things fiddly when trying to upgrade to that specific version. These are the default composer.json requirements...

```
"name": "cwp/cwp-installer",
    "type": "silverstripe-recipe",
    "description": "CWP Project Template",
    "license": "BSD-3-Clause",
    "require": {
        "php": ">=5.6.0",
        "silverstripe/recipe-plugin": "^1",
        "cwp/cwp-recipe-core": "2.1.1@stable",
        "cwp/cwp-recipe-cms": "2.1.1@stable",
        "silverstripe/recipe-blog": "1.1.1@stable",
        "silverstripe/recipe-form-building": "1.1.1@stable",
        "silverstripe/recipe-authoring-tools": "1.1.1@stable",
        "silverstripe/recipe-collaboration": "1.1.1@stable",
        "silverstripe/recipe-reporting-tools": "1.1.1@stable",
        "cwp/cwp-recipe-search": "2.1.1@stable",
        "silverstripe/recipe-services": "1.1.1@stable",
        "silverstripe/subsites": "2.1.1@stable",
        "tractorcow/silverstripe-fluent": "4.1.4@stable",
        "silverstripe/registry": "2.1.0@stable",
        "cwp/starter-theme": "2.0.2@stable"
    },
```
...so what would we be tweaking to get the build to use the SilverStripe 4.2.2  framework?

**Comment by maxime-rainville** [comment]
You're probably best of waiting for the next CWP release, which should be coming before the end of the year. You'll probably just need to update your recipes to the "X.1.2" version.

**Comment by phptek** [comment]
@noizyboy CWP 2.2.0-rc1 is [available](https://www.cwp.govt.nz/developer-docs/en/2/releases_and_changelogs/cwp_2.2.0-rc1/), but unstable release upgrades have bitten me on the arse several times for CWP2, so I'll not be advocating we do this until it's stable.

**Comment by noizyboy** [comment]
@maxime-rainville , @phptek - thanks guys. Will wait for the next stable CWP release.
