### ISSUE TITLE
New Page Still in Draft/Modified after Published

### ISSUE THREAD

**Issue by pxwee5** [silverstripe/silverstripe-cms#2309]
## Affected Version
Composer settings: "silverstripe/framework": "4.2.x-dev",
Composer info: silverstripe/framework            4.x-dev c23d21a

## Description
![image](https://user-images.githubusercontent.com/14123790/38348728-947ce3b4-38f7-11e8-8111-656bc783f037.png)

Edited pages still display as draft/modified after I published the page. 

## Steps to Reproduce
1. Create a page
2. Change title
3. Press publish

This issue wasn't around in 4.1 I think, I wanted to use the `setContentCSS` method in TinyMCEConfig so I had to upgrade SS framework. After I upgrade, this bug was introduced.

**Comment by cwchong** [comment]
Am experiencing this, not quite sure what's causing this, because I can see the pages in the database under SiteTree_Live so they should be picked up as published.

The "More Options" button at the foot also will not reflect the publish status of the page.

I think this is quite a breaking UI bug in the CMS.

**Comment by ScopeyNZ** [comment]
Can you provide some more detail about the relationships on the pages that are not publishing correctly? Are you using a module like `silverstripe-elemental`?

**Comment by amolswnz** [comment]
I have similar issue
Tested on versions 4.2.1 and 4.3.3 (no additional modules installed)

Steps to reproduce
1. Create new Page type and Save (do not Publish).
2. Create new child page and leave in draft mode. 
3. Add another child page and leave in draft mode. 
4. Publish the top level page. 
5. Publish the child level pages. 

Site tree will show all the pages as DRAFT
If you skip step 3 then only child page will show as DRAFT

**Comment by amolswnz** [comment]
Another issue is the bulk publishing (If the parent page is in draft mode)

SilverStripe 4.2.1 - Bulk publishing error is thrown.
None of the pages are published.
Request URL: http://example.com/admin/pages/
Request Method: GET
Status Code: 400 Bad Request
Response `Ajax requests to this URL require an X-Pjax header.`

SilverStripe 4.3.3 - Bulk publishing no error thrown
Parent and child pages are published. But child pages are shown as Draft in CMS.

**Comment by amolswnz** [comment]
I have tested this on SilverStripe 4.4.0 and the issues does not seems to replicate.

**Comment by chillu** [comment]
Thanks Amol!
