### ISSUE TITLE
Fatal error when deleting subpage of draft only page as non-admin

### ISSUE THREAD

**Issue by sb-relaxt-at** [silverstripe/silverstripe-cms#2311]
If a non-admin user tries to delete a draft of a page which parent page is not published, there will be a fatal error:

<b>Fatal error</b>:  Call to undefined method SS_HTTPResponse::forTemplate() in <b>/***/silverstripe/framework/admin/code/LeftAndMain.php</b> on line <b>579</b><br />

The page will be deleted nevertheless.

Steps to reproduce:
- Silverstripe 3.1.5
- Create a user with limited rights (member of Content Authors)
- Login as this author
- Create a page (A) with draft only version (not published)
- Create a subpage (B) on this page and save draft only version
- Delete draft of page B

**Comment by maxime-rainville** [comment]
Hi @sb-relaxt-at. Sorry it took us so long to get to this issue.

Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

I tried replicating the issue in SilverStripe 4 and didn't manage to.
