### ISSUE TITLE
jstree highlights wrong element when doing a drag and drop reordering in some circumstances

### ISSUE THREAD

**Issue by ss23** [silverstripe/silverstripe-cms#2315]
(this is logged here because jstree is in framework, not cms)

Assume you have 3 pages in the root. Select Page with ID 1. Click and drag Page with ID 2 to a new position in the site tree.

Expected: The content is still of Page 1. The URL is still of Page 1. Page 1 shows as selected in the jstree.
Actual: The content is still of Page 1. The URL is still of Page 1. Page 2 shows as selected in the jstree.

We're currently running the lasted version of jstree of the .1 branch (though it has been monkeypatched), and my JS skills aren't enough to fix it myself.
![ux](https://cloud.githubusercontent.com/assets/191510/11084827/a8dae258-88a4-11e5-8349-82c440c5b57a.png)

**Comment by maxime-rainville** [comment]
Just had a look in SS4. Looks like this is still present ... sort of. That's the interaction I have https://youtu.be/iBQEWx2S55g

Looks like we provide a slight highlight of the currently selected page. I wouldn't call this highlight a "selection marker". I would consider it more like "here's the last thing you interacted with".

I don't think this is a bug per se. Probably more of a UX question. @clarkepaul

**Comment by bergice** [comment]
Tested on SS `4.6`, looks to no longer be an issue. SS `3` is now in limited support so I'll close for now.

Reopen if this is still an issue in SS `4`.
