### ISSUE TITLE
Submitting the URLSegment field triggers a page save

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-cms#2321]
**Version: 4.3.0-rc1**

![image](https://user-images.githubusercontent.com/5170590/48340074-5adea100-e672-11e8-9c52-fdcd74a139f5.png)

* Create a new page
* Edit the URL segment
* While still focussed in the text field, press Enter key

Expected: the URL segment is saved

Actual: the whole page is saved

I realise that the enter key should trigger the first submit action for the form in HTML terms, but in terms of UX here I'd expect the OK button to be triggered for the URL segment field instead (because it's green/primary).

_Component rewrite split to #2516 to allow addressing this bug separately._

**PRs**

- [ ] #2517

**Comment by brynwhyman** [comment]
Noted that this is currently not in the DSM, @clarkepaul can you help track it down

**Comment by clarkepaul** [comment]
We need to create the pattern and add it to DSM, it's on our do to list.

**Comment by sachajudd** [comment]
Updated designs can be found in the [CMS style guide](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/folder/components/5c68f96ffb26bb0018525d10) under 'Forms - Input fields and groups'. Any questions about the design let me know, they are slightly different from what we have now so may have to be split up into a separate issue 🙂

**Comment by Cheddam** [comment]
I've split the component rewrite work into a separate issue, as it would massively increase the scope of the work (`effort/easy` would not cover it) and so that we could resolve the bug itself separately (PR at #2517).

**Comment by Cheddam** [comment]
Fixed in #2517.
