### ISSUE TITLE
Secondary actions popup is empty when page is archived

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-cms#2325]
**Version: SS 4.3.0-rc1** (in CWP 2.2.0-rc1 context)

* Create a page
* Save it
* Archive it

Notice that the secondary options list is empty, but the presence of the meatballs button indicates that there are options in it.

We should hide the menu when the page is archived (cc @clarkepaul for input)

![image](https://user-images.githubusercontent.com/5170590/48344455-c9752c00-e67d-11e8-8771-16ccb5897187.png)

**Comment by clarkepaul** [comment]
Pretty sure I've already raised this issue, perhaps in the wrong repo. I'll take a look.

**Comment by clarkepaul** [comment]
Same issue https://github.com/silverstripe/silverstripe-cms/issues/2083

**Comment by robbieaverill** [comment]
Sorry =)
