### ISSUE TITLE
CMS ^4.3 should require framework ^4.3

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-cms#2328]
`CMSMain::SiteTreeAsUL()` calls `Hierarchy::prepopulateTreeDataCache()`:

https://github.com/silverstripe/silverstripe-cms/blob/45b092c12123c24b2744eab6c661ec37df8bc3d6/code/Controllers/CMSMain.php#L505

That method doesn’t exist in framework versions prior to `4.3.0-rc1` (it was added in https://github.com/silverstripe/silverstripe-framework/pull/8380)

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-cms/pull/2332

**Comment by kinglozzer** [comment]
Fixed in https://github.com/silverstripe/silverstripe-cms/pull/2332
