### ISSUE TITLE
"Add new page" when another page in the site tree is selected

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-cms#2339]
# Version affected
4.3 and above. 4.2 looks OK.

# Description
While using the CMS to edit an existing page, if you click the _Add New_ button to add a new page, you'll be redirected to the page to pick a page type before quickly being redirected to a blank page.

# Steps to reproduce
* Access the CMS.
* Using the site tree pick an existing page to view.
* Click the _Add New_ button.

Expected behavior: You should see the new page dialog with the page that was being viewed set up as the new page's parent in Step 1.

Actual behavior: The new page dialog is briefly displayed before being redirected to a blank page.

https://youtu.be/VHnCfzmUB-4

# Pull Requests
- [x] https://github.com/silverstripe/silverstripe-admin/pull/765
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2346
- [x] https://github.com/silverstripe/silverstripe-admin/pull/771

**Comment by maxime-rainville** [comment]
If don't select page and click add new, you can make it to the dialog. However if you try to select a parent page from the tree dropdown field, you get the same behavior.

Looks like the `admin/pages/add/childfilter?ParentID=6` request is breaking the site somehow.

**Comment by ScopeyNZ** [comment]
I just noticed this and was about to raise it. I'd almost say it's worth a `critical` tag because it just feels broken to get a blank page when clicking "Add Page"

**Comment by maxime-rainville** [comment]
I flagged it to @chillu and @rupachup on Slack.

There's a workaround, which involves right-clicking on the parent page and using the contextual menu, but it's very awkward.

I'm happy to call this critical.

**Comment by bergice** [comment]
This is caused by the `Under another page` select field when you change the selected option.

Having the `ParentID` as a query argument will automatically change the select option, which is why this is happening when clicking `Add New` from an existing page.

![image.png](https://images.zenhubusercontent.com/5b638eee8b0c845c280580cb/a6c28420-8cd4-417d-8852-7d19a96e83d4)

**Comment by robbieaverill** [comment]
Just chiming in, if there's a workaround then it shouldn't be critical

**Comment by dnsl48** [comment]
Just wondering whether `a really tricky workaround, not really obvious to users` counts as a workaround? :)

**Comment by ScopeyNZ** [comment]
This is fixed now right? With @bergice's fix to loading indicators: silverstripe/admin#765

**Comment by bergice** [comment]
Yeah, just need that test merged.

**Comment by dnsl48** [comment]
The second PR is good to go

**Comment by chillu** [comment]
Please manually create a 4.3.0 release branch based on 4.3.0-rc1 and merge this hotfix into there.

**Comment by chillu** [comment]
Can you please add a Behat test for this fairly major usage path? I think we only have one for "add new page", but not "add new page under other page"

**Comment by dnsl48** [comment]
Yeah, that's exactly what the second PR actually was - to implement this behat test.

**Comment by ScopeyNZ** [comment]
> Please manually create a 4.3.0 release branch based on 4.3.0-rc1 and merge this hotfix into there.

We will need to merge this hotfix, and also the hotfix that this PR addresses: https://github.com/silverstripe/silverstripe-admin/pull/756

Personally I think we should also merge my PR silverstripe/silverstripe-admin#771 because it's essentially part of this PR (removing the possibility of console errors caused by the code in this patch)

**Comment by maxime-rainville** [comment]
All done.
