### ISSUE TITLE
SS4: Invalid cache key for tinymce field with an image using base URL with special chars

### ISSUE THREAD

**Issue by a2nt** [silverstripe/silverstripe-cms#2340]
When the website URL contains special chars it breaks archived version preview when those chars presented as argument of image tag.

To repeat this issue:
1) host the website at the URL like http://127.0.0.1/~bla-bla/ (there's special char ~)
2) Create a page with following content:
[image src="/~bla-bla/assets/Uploads/images/8a0aa7b130/test.png" id="109" width="384" height="102" class="center ss-htmleditorfield-file image" title="Test"]
3) Archive page
4) Preview archived version

You will get following error:
```
[Emergency] Uncaught Symfony\Component\Cache\Exception\InvalidArgumentException: Cache key "Archive.2018-11-26 15:49:46.Stage, 1#ac84522b2e8758bb60b1093b5a2b9a9b#dcca48101505dd86b703689a604fe3c4_26fb33bfe067e64685e662d36ad2d0f7" contains reserved characters {}()/\@:
GET /~bla-bla/bla-bla-bla/?stage=Stage&archiveDate=2018-11-26%2015:49:46
Line 162 in /home/bla-bla/ss/vendor/symfony/cache/CacheItem.php
```

**Comment by robbieaverill** [comment]
I just ran into this too, I'll make a PR

**Comment by maxime-rainville** [comment]
silverstripe/silverstripe-assets#196 fixed this. I don't think it will be in the initial 4.3.0 release however.

It will have to wait for 4.3.1.
