### ISSUE TITLE
Vanishing sidebar in IE11

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-cms#2345]
# Affected version
Tested in SilverStripe 4.3

# Description
Using IE 11, after you navigate pages in the CMS with the left nav set to auto collapse, the left nav sometimes goes away entirely. Other admin areas seem unaffected

If you fix the nav in open position, you are fine.

# Steps to reproduce
* Access any Page in the CMS.
* Navigate to an other page.

https://youtu.be/mD40YjdnWcE

**Comment by Cheddam** [comment]
Several IE 11 layout fixes have been merged over the last few days, so it'd be worth re-testing whether this is an issue @maxime-rainville (I can't reproduce the issue myself).

**Comment by maxime-rainville** [comment]
I was still seeing it last week, but your PR may have fixed it.

**Comment by maxime-rainville** [comment]
We've adjusted other part of how this panel works. 

I can't reproduce this issue in IE11 any more using SS4.6 core or SS4.6 kitchen sink.

We'll call this one fixed.
