### ISSUE TITLE
"Add a Custom Summary" should be uncollapsed by default if it is filled

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-cms#2347]
"Add a Custom Summary" is at the bottom of the form, and collapsed by default. That's fine if it is not used, but less fine if it /is/ used. It becomes especially problematic if a translation module such as Fluent is used, because then you'll happily translate the Title and Content, but forget about the Custom Summary. 

After all, it says "*Add* a Custom Summary", so there's no visual indication whatsoever that something is filled in there. 

My suggestion is to simply uncollapse it (onload) if it has any content.

**Comment by chillu** [comment]
I'm not sure what this refers to, don't think it's a feature of the CMS. Might be in fluent, or in your custom code?

**Comment by JorisDebonnet** [comment]
Oh now that you mention it ... this is a blog issue. Apologies, I'll refile this there!
