### ISSUE TITLE
"Cancel draft changes" in secondary actions doesn't have a loading indicator

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-cms#2350]
**SS 4.3.x-dev**

The "Cancel draft changes" option in the secondary CMS actions menu has a confirmation dialog but no progress or loading indicator. If you have a large site where this operation could take a while, you have no idea what is happening or whether it's working or broken.

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-cms/pull/2351

**Comment by ScopeyNZ** [comment]
Closed in #2351
