### ISSUE TITLE
CMS tree highlights incorrect "active" page after performing save/publish

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-cms#2355]
CMS/Framework 4.3.0 - I’ve recreated this on two sites, nothing custom going on that I think could affect this.

<img width="291" alt="screenshot 2018-12-18 at 14 17 33" src="https://user-images.githubusercontent.com/1655548/50160145-71f75b00-02d0-11e9-9988-4af0f8656c4f.png">

In the above screenshot, I’m editing the “Windows 10 Migration” page - the tree view automatically expands to show all child pages, all good so far.

After hitting _Save_ or _Publish_, the ‘active’ page changes to the last child page - despite the fact I’m still editing the “Windows 10 Migration” page:

<img width="295" alt="screenshot 2018-12-18 at 14 17 45" src="https://user-images.githubusercontent.com/1655548/50160213-a1a66300-02d0-11e9-9608-b13d737f991c.png">

---

If I edit the top-level “Services” page and hit _Save_ or _Publish_, all child nodes are automatically expanded (showing level 3), and the “last” grandchild page is highlighted:

<img width="291" alt="screenshot 2018-12-18 at 14 27 59" src="https://user-images.githubusercontent.com/1655548/50160425-3dd06a00-02d1-11e9-8f22-36c132831612.png">

# Pull Requests
- [x] https://github.com/silverstripe/silverstripe-admin/pull/932

**Comment by kinglozzer** [comment]
Come to think of it, is the entire tree supposed to reload each time you switch which page you‘re editing? It didn’t in 4.2.x

**Comment by maxime-rainville** [comment]
I've confirmed the behaviour on SS4.3 and that this wasn't present in SS4.2. We made a bunch of performance tweaks to speed up the treeview rendering. This maybe a side affect we didn't notice.
