### ISSUE TITLE
SiteTree search for '+' in a URLSegment has unexpected behaviour

### ISSUE THREAD

**Issue by jakxnz** [silverstripe/silverstripe-cms#2359]
## Version

silverstripe/cms 4.3.x-dev 309dc97

## Description

When `URLSegment` is available in the CMS SiteTree search (`pages/`), if searching for a URL with a `+` in it, including `+` in the search string yields no result.

**Please Note: SilverStripe does not preserve `+` symbols in URLs by default**

## Prerequisites

1. SilverStripe configured so that `+` symbols can be used in `URLSegment` 
2. SilverStripe CMS, with `URLSegment` available in `SiteTree`'s searchable fields, and in the CMS search form.
3. An existing Page with a URLSegment that contains a `+` e.g `url+segment`

## Steps

1. Log into the CMS
2. Browse to the `pages/` section
3. Click the Search icon
4. Expand the form to input a value for a specific search field
3. Type `+segment` into the "URL Segment" input
4. Submit

### Expected result

The existing Page with `URLSegment` `url+segment` is visible amongst the search results

### Actual result

The existing Page with `URLSegment` `url+segment` does not appear

## Notes

I notice that any search value that is submitted this way has `+` replaced with ` ` (space). I also notice that if the replacement is bypassed, when `%2Bsegment` or `+segment` is submitted via get params the value is parsed as `+segment`, but the `URLSegment` value is stored with URL encoding - so this is a non-result as well. The value needs to be parsed as a url encoded `+` (`%2B` in order to yield a result).

**Comment by maxime-rainville** [comment]
How did you manage to a put a `+` sign in your URL segment? When I try to do that it automatically gets swapped out for a dash, which I think is the intended behaviour.

Looks like special characters are not being URL encoded on the front end when submitting the site tree search, which should be a simple fix.

**Comment by jakxnz** [comment]
Ah, yes, sorry @maxime-rainville, our project has allowed `+` symbols in `URLSegment`. It would be fantastic if the posterity of submitted search parameters could be preserved in one way or another.

**Comment by maxime-rainville** [comment]
Cool ... can you post the code snippet that would allow us to enable + signs in URL Segment for reference?

**Comment by mfendeksilverstripe** [comment]
This issue can be closed as it was fixed via https://github.com/silverstripe/silverstripe-cms/pull/2593
