### ISSUE TITLE
SiteTree mouseover transforms PageType

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-cms#2371]
silverstripe/cms 4.3 / CWP 2.2.0

When mousing over an item in the Site Tree in the CMS, a tooltip is displayed, showing users the name of the Page Type. However, the case of the characters is being transformed somewhere.

Example:

```
class XmlPage extends Page
{
}
```

...is shown as "Page type: XML Page" in the tooltip. This should be left alone, and as such should display "Page type: Xml Page" and be displayed exactly as coded in the class signature.

Possibly there's scope here to improve the CMS author abstraction from logic, that SilverStripe was pedicated on by adding a config static on `SiteTree` that permits devs to change what is shown in the tooltip, possibly even used in the CMS search in the "Page type" dropdown, to make that list a little more user-friendly.

For now, preventing the class-name transformation in the site-tree will suffice.

**Comment by bergice** [comment]
I'm unable to replicate this issue with the versions provided.

Could you do a `composer show` and let us know if there is anything in your project that might cause this?

**Comment by dnsl48** [comment]
Need more information to reproduce the issue, so I'm closing it for now.
Please reopen if the issue still happens.
