### ISSUE TITLE
Modal UX inconsistency

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/silverstripe-cms#2381]
Just noticing some inconsistency between modals we have throughout the CMS and the designs we use to showcase them in our Styleguide.

Current CMS modals: 
![image](https://user-images.githubusercontent.com/24258161/51881111-cd902a80-23de-11e9-87ee-438aa384679c.png)

See the [Styleguide](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5bdf8561a927a20011a0bb77) for modal dimensions and designs.

Some quick differences spotted:
* Modal background colour
* Modal header color
* Bottom action toolbar border-line to be removed
* Modal widths
* Modal dimensions (padding around modal and between inputs)
* Modal large doesn't seem to work. Files modal should be it's own custom size and XL should still be available to use cc @clarkepaul

**Comment by sachajudd** [comment]
@ScopeyNZ I heard that these fixes were done in 4.4, is that correct? If so can we close this?

**Comment by ScopeyNZ** [comment]
Yes it has been updated as seen here:

https://github.com/silverstripe/silverstripe-admin/pull/890

Please re-open the issue if you find more inconsistency.

**Comment by sachajudd** [comment]
Reopening until back ported into 4.3.

**Comment by ScopeyNZ** [comment]
It's backported

**Comment by sachajudd** [comment]
Speed 🏎
