### ISSUE TITLE
Anchors are always marked with `ss-broken` if not using Content Field

### ISSUE THREAD

**Issue by blueo** [silverstripe/silverstripe-cms#2393]
The link tracking functionality marks all anchor links as broken (class `ss-broken`) if your content is not located on $page->Content. The logic appears to be in the parser on line 72. https://github.com/silverstripe/silverstripe-cms/blob/019bb52a2445fe08e7e0cc2152b68cc3f1f79369/code/Model/SiteTreeLinkTracking_Parser.php#L72

So when using something like elemental, the check always fails. Might be easier to disable to the check for anchor links - or just check the page, in these cases. This could be a config option.

**Comment by robbieaverill** [comment]
Related: https://github.com/silverstripe/silverstripe-externallinks/issues/49 https://github.com/silverstripe/silverstripe-externallinks/issues/37

**Comment by maxime-rainville** [comment]
The current link tracking implementation leaves a lot to be desired. We probably should have another look at it.

This is issue is related to this one https://github.com/silverstripe/silverstripe-cms/issues/2327

**Comment by GuySartorelli** [comment]
This is no longer the case. The logic was updated in #2697 to use `getAnchorsOnPage()`.
Closing this issue.
