### ISSUE TITLE
GridFieldConfig_RecordEditor doesn't show unlink

### ISSUE THREAD

**Issue by hklitzke** [silverstripe/silverstripe-cms#2394]
With 4.2.x using GridFieldConfig_RecordEditor::create() shows an unlink icon and I can add a delete icon (GridFieldDeleteAction) as well.

In 4.3.x it only shows the delete icon and I can not add an unlink icon (GridFieldDeleteAction(true)).

```
// This will do nothing:
$config = $gridField->getConfig()->addComponents(
		        new GridFieldDeleteAction(true)
	        );
```

Relating DataObject uses Versioned::class.

Did something change here from 4.2 to 4.3?

**Comment by thats4shaw** [comment]
This is related to https://github.com/silverstripe/silverstripe-versioned/issues/200.

**Comment by chillu** [comment]
Assuming your relation here is a many_many, I'm closing this as a duplicate
