### ISSUE TITLE
Link types are not ordered intuitively

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#2395]
The most common link type should be displayed first (e.g. link to page). They were ordered correctly at one stage but have since been mixed up. For such a regular task its small changes like this which will make a big difference in the intuitiveness of the UI.

Its proposed to remove anchor links as a selection on another issue so haven't numbered that one.
<img width="109" alt="pasted_image_4_03_19__11_44_am" src="https://user-images.githubusercontent.com/555033/53703122-1c643080-3e73-11e9-8fec-15480dc41052.png">

**Comment by ScopeyNZ** [comment]
Covered/superseded by #2379
