### ISSUE TITLE
Untangle direct link to HomePageForDomainExtension 

### ISSUE THREAD

**Issue by altwohill** [silverstripe/silverstripe-cms#2401]
Hello! I've just taken over custodianship of `silverstripe-homepagefordomain` and it's living here https://github.com/twohill/silverstripe-homepagefordomain

We need to namespace this module, but it relies on a piece of code within the `RootURLController` 

https://github.com/silverstripe/silverstripe-cms/blob/c1c9d7706a097fb0b8a15fe30cece87df5a8c916/code/Controllers/RootURLController.php#L45

As a short term fix to avoid breaking semver I will be aliasing `Twohill\HomepageForDomain\HomepageForDomainExtension` to `HomepageForDomainExtension` however I think it would be best to refactor this piece of code out of core.

I think it would be best to make `get_homepage_link()` extendable. Thoughts?

**Comment by robbieaverill** [comment]
>I think it would be best to make get_homepage_link() extendable. Thoughts?

Yep, this is a good approach in the short term. I think you should be able to alias the old class name for backwards compatibility in your module against existing core SilverStripe releases, add the extension point to that method in the `4` branch (as an enhancement), and add a new extension to your module which would be inert until SilverStripe 4.4 (or whatever it gets released in) is used.

If you are interested in picking this up, could you please also remove the Translatable code as well? We may want to open an issue in the Translatable repository during the process of removing that code to point out what's been removed.

I think the method you've pointed out should look like this:

```php
public static function get_homepage_link()
{
    if (!self::$cached_homepage_link) {
        $link = $this->config()->get('default_homepage_link');
        $this->extend('updateHomepageLink', $link);
        self::$cached_homepage_link = $link;
    }
    return $link;
}
```

**Comment by robbieaverill** [comment]
@altwohill FYI I've marked the old package as abandoned in packagist: https://packagist.org/packages/silverstripe/homepagefordomain

**Comment by robbieaverill** [comment]
Fixed with https://github.com/altwohill/silverstripe-cms/commit/dcfb502e5c66345c99ed64c03f7df0ac77ca66dc, thanks @altwohill
