### ISSUE TITLE
Missing "From" address on lostpassword action

### ISSUE THREAD

**Issue by elliot-sawyer** [silverstripe/silverstripe-cms#2412]
Versions affected:
SS 4.3.3

Steps to reproduce:
1. Visit /Security/lostpassword
2. Enter a valid email address to trigger the email

Description:
I'm using Sentry for error reporting and it grabs the following user_error: `[error-log] Uncaught Exception Swift_TransportException: "Cannot send message without a sender address" at ... `. 
The email that gets sent from the LostPasswordHandler::sendMail method does not contain a `From:` address. This prevents the email from being sent. 

As a workaround, you can set the following in your YML config:
```
SilverStripe\Control\Email\Email:
  send_all_emails_from: 'do-not-reply@example.com'
```

Unfortunately, that setting applies to _all_ emails, including those you've configured in your own codebase that may have a different reply-to address. It's not a requirement to set this variable up to run SilverStripe, but it seems nobody can trigger  a password reset email until one is set.

**Comment by robbieaverill** [comment]
Perhaps we need to make it mandatory? As a developer I'd probably be more confused if no emails were sent at all (silently ignoring them if no sender email is configured).

**Comment by elliot-sawyer** [comment]
For this particular email, could the `From:` address match the `To:` address? It would meet the requirement to send, but I'm not sure what the implications for that would be. There might be a higher chance of the emails not being received, or marked as spam. 

It's an easy code fix but I wasn't sure what the value should be. Where should the value come from, and how can a developer change it? Making it mandatory would clear up ambiguity.

**Comment by kinglozzer** [comment]
I believe the `SilverStripe\Control\Email\Email.admin_email` setting is the “default” from address if one isn’t explicitly set.

We’ve forgotten this before, and sometimes emails still get through (depends partly on the server config - e.g. `sendmail` config) and sometimes they don’t. I’m not sure what the best course of action is here, perhaps a dev-mode warning before sending if no `From:` is set?

**Comment by jonom** [comment]
Related to this - it would be nice if you could specifically set the email address that forgot password emails come from, instead of just using `admin_email`. I just ran in to an issue where I wasn't expecting to have to send email *from* this address, so it wasn't authenticated.

**Comment by GuySartorelli** [comment]
I think silverstripe/silverstripe-framework#10236 addresses the main issue being discussed here - though it doesn't add the functionality requested by @jonom.

**Comment by michalkleiner** [comment]
https://github.com/silverstripe/silverstripe-framework/pull/10251 adds an extension point and it could be possible to check for the current controller and the current action to update the email as needed.

**Comment by GuySartorelli** [comment]
Oh that's a fair point!
