### ISSUE TITLE
Failed to load content css: editor.css

### ISSUE THREAD

**Issue by spekulatius** [silverstripe/silverstripe-cms#2413]
Hello SilverStripers,

In a client project I get error messages about failed loading of the editor.css (emitted by the MCE editor). The file is accessible and loads as expected, if accessed directly in the browser. Also the "Network" tab in the browser console shows the file as successfully loaded (200) with the expected content. I'm not sure how to start debugging this further. Any suggests?

SS Version (CMS, FW, recipe-cms and recipe-core) is 4.3.0

Here are some screenshots of the messages:

![image](https://user-images.githubusercontent.com/8433587/56786333-e021d080-6822-11e9-8143-3b8caa2b89f7.png)

![image](https://user-images.githubusercontent.com/8433587/56786369-f3cd3700-6822-11e9-8ecd-248b5ee38c8e.png)

Would be great if someone could give me hint on where to look for the issue.

cc @robbieaverill @NightJar 

Cheers,
Peter

**Comment by robbieaverill** [comment]
I'm not sure if themes will work (at this stage) for editor.css files in the CMS, since frontend and backend themes are different configuration. Are you able to store it in the `app` folder for now?

**Comment by NightJar** [comment]
https://github.com/silverstripe/silverstripe-admin/blob/8e76d64a24ed4cda9615b3a863b92b40c554d029/code/LeftAndMain.php#L738-L743

https://github.com/silverstripe/silverstripe-framework/blob/4155b9f48376e84ecb365f35822afb11c271cc15/src/Forms/HTMLEditor/TinyMCEConfig.php#L708-L713

Here's where it should work.
Do you think you'd like to help debug @spekulatius ?

**Comment by robbieaverill** [comment]
@NightJar the lines you've highlighted will return backend themes - frontend themes aren't included by default

**Comment by NightJar** [comment]
Sorry, I'll include a bigger snippet.
The editor config is has themes set _before_ the admin themes are set, replacing all others.
https://github.com/silverstripe/silverstripe-admin/blob/1/code/LeftAndMain.php#L738-L746

As a potential work around @spekulatius you could try `user_themes`
https://github.com/silverstripe/silverstripe-framework/blob/4155b9f48376e84ecb365f35822afb11c271cc15/src/Forms/HTMLEditor/HTMLEditorConfig.php#L109-L119
But this would have to rely on the theme list being empty, not set to something you don't want.

**Comment by spekulatius** [comment]
Hello @robbieaverill and @NightJar 

thanks for responding. I've had a try by defining the theme in the `app/_config.php`:

    \SilverStripe\Forms\HTMLEditor\HtmlEditorConfig::get('cms')->setThemes(['theme-name']);

This didn't change the behaviour. Did I misunderstand the intent or got a mistake in there?

Robbie, can you explain where exactly I need to place the file?

Thank you for your help Robbie & Dylan!

Cheers,
Peter

**Comment by robbieaverill** [comment]
Hey @spekulatius, I think what you're doing is correct. I've tested it on 4.3.x-dev with the simple theme, doing the following:

* Ensure `themes/simple/css/editor.css` exists and add `body { background-color: red !important; }` to it
* Ensure everything is exposed (`"extra": { "expose": [ "css" ] }` in theme's composer.json then `composer vendor-expose`)
* Add `HTMLEditorConfig::get('cms')->setThemes(['simple']);` to `app/_config.php`
* Open TinyMCE in a page in the CMS

Perhaps you need to run the expose command?

**Comment by spekulatius** [comment]
Hello @robbieaverill 

thanks for the detailed description. I've tried this out a few things based on your example:

1. Currently the theme is part of the same repo and not composer managed. So I've configured `composer vendor-expose` a little different. Doesn't adding the expose of the theme directories achieve the same:

![image](https://user-images.githubusercontent.com/8433587/57176543-712c2380-6e83-11e9-9c40-0142340d0f05.png)

2. I've went to the live server, edited editor.css to append `body { background-color: red !important; }` the red background got applied and the error still showed 🤔️

![image](https://user-images.githubusercontent.com/8433587/57176706-52c72780-6e85-11e9-8355-e648e41614f3.png)

When I copy the exact URL from the message and open it in a new tab it's showing the content as expected. This is still puzzling me. The file is there, the console shows 200 and still I get the error.

Peter

**Comment by NightJar** [comment]
>The file is there, the console shows 200 and still I get the error.

What is the contents of the response of the `200 OK` you get before "Failed to load content css" shows up?
Sounds like it might be a `200 NOT OK` - I suspect the response will be `assets/error-404.html`or similar ;)

This is turning into a support thread - if a bug cannot be identified then it's likely to be closed.

**Comment by spekulatius** [comment]
Hello @NightJar 

the content is the CSS file comes back - that's why I feel it's a bug. The request goes through, comes back with 200 OK and the minified CSS - and it even gets applied (see background red test above).

Do you know if there is an option to suppress the TinyMCE messages? cc @robbieaverill 

Peter

**Comment by michalkleiner** [comment]
Could it be CORS? Is the returned MimeType right?

**Comment by NightJar** [comment]
is there some kind of parse error in the returned CSS?

**Comment by spekulatius** [comment]
Hello @michalkleiner & @NightJar,

thanks for jumping in Michal! The CORS shouldn't apply it all on the same domain name (exact matching - both are www.company.com). The Mime Type is correct too - same as all the other CSS files:

![image](https://user-images.githubusercontent.com/8433587/57290063-dcc1fb00-70e6-11e9-991e-f6fb84ee5b9e.png)


The CSS is valid: 

![image](https://user-images.githubusercontent.com/8433587/57290037-d03da280-70e6-11e9-9fff-db3dcd4d0b74.png)

@robbieaverill @NightJar @michalkleiner, do you know any ways to suppress the messages from TinyMCE?


Peter

**Comment by NightJar** [comment]
Hang on, sorry have I misunderstood?

Does the error message display, but the styles actually still load and apply to the content?

I can't think why hiding the message would help otherwise :/

As to questions about TinyMCE configuration - I can only point at the [TinyMCE documentation](https://www.tiny.cloud/docs-4x/) - the PHP class is only a loose wrapper around generating settings as documented there.

**Comment by spekulatius** [comment]
Hey @NightJar 

exactly hahaha - I've added `background: red !important` as suggested by @robbieaverill and uploaded the `editor.css`-file back onto the live server - and the background was red 😲️ So, yes, the styles load *and* get applies, the error message appears to b incorrect.

Thanks for pointing me to the TinyMCE docs, I'll have a look and see if I find something for this problem.

Peter

**Comment by NightJar** [comment]
Much bizarre then, sorry I'm all out of ideas.
I thought the styles weren't loading at all 😅 
Best of luck, I find the TinyMCE docs are a ... "maze of limited value" 😞

**Comment by spekulatius** [comment]
Yeah, very confusing. I'll see if I find a solution somehow and document it
back here 👍️

**Comment by michalkleiner** [comment]
Is it replicable? Can you create a minimal installable test case so we can have a look as well?

**Comment by spekulatius** [comment]
I can give it a try, but it might be quite a lot of work to get it
"working" hahah

**Comment by spekulatius** [comment]
I've tried a few more things until I couldn't justify more research. I've taken out the message, no negative side-effects so far.

**Comment by spekulatius** [comment]
Client has confirmed it's fine. Thanks for your help @robbieaverill, @NightJar & @michalkleiner 🙏️ 🙏️ 🙏️ Let's close this for now :)
