### ISSUE TITLE
CMS is too slow to allow effective drag and drop reordering of pages

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-cms#2418]
Steps to create:

- `composer create cwp/cwp-recipe-kitchen-sink cwp230 2.3.x-dev`
- do normal setup steps & log in to CMS as admin
- Create a new `Home Page`, with a Hero item with an image, save and publish.
- Create a new `Page` beneath this new home page. Save and publish
- Attempt to drag this new Page above the Home Page in the site tree (so it is a sibling preceeding it, rather than a child under it).
- 👀 Observe text selection while dragging.
- 👀 Observe dropping the page does not update the controls - #2323 
- ❓ Come back to this step later - immediately proceed to the next step for now
- Click "save and publish" anyway
- 👀 Observe this action takes forever
- 👀 Observe strange toast notifications, publish may happen before reorder
- load incognito window to see front end
- 👀 Observe no change
- Hard Reload CMS
- 👀 Observe the site tree reflecting the old state

Repeating the above but switching ❓ out for the following should work as normal (except for the text selection visual nonsense):
...
- ❓ Wait until "Reordered the site tree successfully" shows as a toast pop up
- 👀 Observe this action takes forever
- Click "save and publish"
- 👀 Observe this action also takes forever
...

Note that at this point my simple test environment does _not_ have much data in it at this high level - framework test has added a few pages, but all from a single root level node.

![image](https://user-images.githubusercontent.com/778003/57202662-271a7d80-6ffc-11e9-8c1b-83089703a6d8.png)

**Comment by dnsl48** [comment]
This might be not a generic CMS issue per se. I've just been testing drag-n-drop with IE11 on BrowserStack with  kitchen 2.3.x-dev, and it worked fine for me. Also, seems to be working fine on `ss/installer`. Might need to narrow down the problem a little bit.

**Comment by kinglozzer** [comment]
I can’t say I’ve noticed this one before, I guess it’s related to server response time though?

**Comment by NightJar** [comment]
Yeah it'll be response time related. This issue is probably more alarm bell than anything super serious (i.e. impact low)

**Comment by ScopeyNZ** [comment]
Would you agree that we should close this in favour of #744 noting in that issue that "being fast enough" should be a non-technical requirement?

**Comment by michalkleiner** [comment]
I can weigh in on the issue side — we've noticed slowness when reorganising the sitetree on several sites, with the results sometimes being the page jumping back where it was or users having difficulties placing it where they wanted it etc.

#744 may address that, but as it's open for 6 years now...

**Comment by NightJar** [comment]
@ScopeyNZ I fear that the issues are with the SilverStripe powered back end for making this adjustment, rather than the presentation library used. By speed here I'm generally talking about request response time.

I would hope that by the time a new library comes alone that this would no longer be an issue.

In short: yes and no. And what @michalkleiner said; 6 years.

**Comment by kinglozzer** [comment]
What’s realistically actionable on this ticket? If there are slow pieces of code related to re-ordering the tree that can be improved then that would be welcomed, otherwise this probably just falls under the “make it faster” category of issues

**Comment by NightJar** [comment]
Sure does :)
