### ISSUE TITLE
SilverStripe 3 - Preview/split view page links do not get ?stage=Stage suffixed to them

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-cms#2429]
SS 3.7.3

To replicate:

Create a pair of unpublished pages:

Page A content contains a link to Page B

In the preview/split view, the link to page b is : /page-b

It should be /page-b?stage=Stage

What this means is that when I click on the link to /page-b, instead of navigating to the new page and the CMS edit form updating to Page B, I get a 404

**Comment by ScopeyNZ** [comment]
Thanks for the report. 

Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

You're welcome to raise a PR to fix this issue.
