### ISSUE TITLE
Editing in IE 11 breaks at resolutions below 1400px

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-cms#2432]
**Affected versions:** SilverStripe 4.2 and later (testing incomplete, screenshots are from 4.4-RC1)

When loading a Page in the Edit Mode view in IE 11, at resolutions below 1400px wide, the resulting UI will be this:

![IE11 in 4.4-RC1](https://user-images.githubusercontent.com/242621/57903837-e62a3080-7867-11e9-8174-da7b6c17b9fe.PNG)

Resizing the window in either direction fixes this issue, although at widths 750px or less, the UI is permanently broken:

![IE11 in 4.4-RC1 at 749px wide](https://user-images.githubusercontent.com/242621/57903937-81230a80-7868-11e9-8db7-b868884ae1f8.PNG)

The resizing fix doesn't always work, and the UI breaks again when opening a different page for editing. This appears to affect all pagetypes (Elemental-powered or not).

There are a couple of existing issues related to editing pages in IE 11 (#2245 and #2345), and I'd summarise the current state of editing in IE 11 (on displays below 1440px wide) as "unsupported".

**Comment by robbieaverill** [comment]
I’ve triaged this as critical because IE11 is a supported browser, and this makes it unusable. Happy for someone to argue otherwise and reduce it though.

**Comment by brynwhyman** [comment]
We'll look at this after looking to resolve #2245

**Comment by NightJar** [comment]
During testing I'm able to "restore order" by clicking the "show the site tree" button
![image](https://user-images.githubusercontent.com/778003/62840645-2e83ae00-bcf2-11e9-8f9b-4f691297d3e7.png)

**Comment by Cheddam** [comment]
This issue has been resolved, and the related fixes are available in SilverStripe 4.4.3.
