### ISSUE TITLE
[4.4] Enforce creation of _resources dir inside webroot, if composer.json resides outside

### ISSUE THREAD

**Issue by ghost** [silverstripe/silverstripe-cms#2433]
In the index.php, I have added absolute path to vendor dir. I can access admin and flush settings. I can execute dev/build.

I have shifted app+vendor+silverstripe-cache dir outside of website (one step) and let remain the index.php, htaccess and assets dir in webroot. When I create composer vendor-expose or dev/build, _resources dir is created only in the same hierarchy, where the file composer.json resides. 

But composer.json is outside of webroot like here:
.htaccess--->redirect--->public_html
composer.json
public_html/index.php
public_html/.default.silverstripe.htaccess

I require _resource dir to be created under the webroot.

Using Silverstripe 4.4.0-rc-1

In composer, there is no chance to change the key name to consist of public_html/_resources.

Am I doing something wrong here or is this a special case, what I have done?

**Comment by maxime-rainville** [comment]
I don't think this is a set up we want to support and the user has been deleted any way, so we don't have a way of getting more info.
