### ISSUE TITLE
Cannot edit a link if markup is in the link text

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-cms#2439]
## Description

Currently if there's a link in a TinyMCE (`HtmlEditorField`) that has markup within the `<a>` tag then you cannot edit it again. You don't get the little popover with edit/remove options. It's a little more nuanced, there doesn't seem to be a click handler on children on the `<a>` tag. You can still trigger the popover if you are clicking the `a` tag and not a child element of the `a` tag.

## Steps to reproduce

- Add some text to the TinyMCE field and highlight it
- Bold the text
- Add a link to that highlighted text
- Note that you can't edit the text

## Notes

- Tested with CWP 2.3.0-rc1 and silverstripe/installer@4.4.x-dev
- Tested on TinyMCE's site with their demos - it works a little differently - there's no popover, but it does work.
- The workaround is to either edit the source and remove inner HTML of the anchor tag or you can use the buttons (like the bold button) to remove the markup.
- Un-bolding anrd re-bolding the text fixes the issue.

## PRs

- https://github.com/silverstripe/silverstripe-cms/pull/2993
- https://github.com/silverstripe/silverstripe-admin/pull/1814

**Comment by obj63mc** [comment]
We have run into this issue on a site that is utilizing a span tag inside links to handle button animation.  Is there any chance this gets fixed in SS5.x or even v6?

**Comment by GuySartorelli** [comment]
PR merged - will be automatically tagged by GitHub actions
