### ISSUE TITLE
Add new page page is unusable with too many page types

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-cms#2445]
Steps to reproduce: 

1. Log into the SS CMS
2. right click a page type with a decent number of allowable page types to be created

In SS3.X, you had a two column layout which made this a little bit more tolerable. But sadly in SS4 with more than 6 or so page types, it becomes unusable:

![toolong](https://user-images.githubusercontent.com/67215/58916050-a5db1580-8776-11e9-811a-d4e5c12735e7.png)

Perhaps being able to scroll will fix this?

**Comment by ScopeyNZ** [comment]
Thanks for the report. I think this is covered by #2318. Please feel free to re-open if you disagree.
