### ISSUE TITLE
"Add page" contextual menu cut off with very long list

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-cms#2451]
If you have a long list of Page Type, when you try adding a page to the site tree using the contextual menu, your list of page type will be cut off.

Not sure if it's possible  to scroll through that list.

![Screenshot from 2019-06-25 14-26-40](https://user-images.githubusercontent.com/1168676/60065963-ba994080-9759-11e9-9bb2-bff8f2e558f6.png)

**Comment by maxime-rainville** [comment]
@silverstripeux ^

**Comment by sachajudd** [comment]
@maxime-rainville duplicate issue of #2318 & 2445

**Comment by maxime-rainville** [comment]
Weird ... Elvis didn't tell me about that other one.

**Comment by maxime-rainville** [comment]
This Elvis https://silverstripe-github-issues.now.sh/

Not this one https://media.giphy.com/media/PVJ29hwRF1DsQ/giphy.gif

**Comment by clarkepaul** [comment]
The one and the same Elvis, the King of rock and SS issues.
