### ISSUE TITLE
Broken page / Broken link reports do not work with elemental content area

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-cms#2453]
# Description

The "broken link" and "page with broken file" report do not include page with elemental area containing broken links.

# Steps to reproduce
* Create a new elemental page
* Add content block.
* Add a link to a new file in the content block
* Add a link to a new page in the content block
* Publish the elemental page
* Archived the new page and delete the new file.
* Go look at the reports

Expected behavior: The elemental page should appear the broken link report and the page with broken files report.

Actual behaviour: It doesn't.

**Comment by brynwhyman** [comment]
Related: https://github.com/silverstripe/silverstripe-externallinks/issues/37

**Comment by chillu** [comment]
This issue should live in elemental repo, could you recreate it there?

**Comment by maxime-rainville** [comment]
Moved to https://github.com/dnadesign/silverstripe-elemental/issues/689
