### ISSUE TITLE
IE11 error - Object doesn't support this action

### ISSUE THREAD

**Issue by amolswnz** [silverstripe/silverstripe-cms#2459]
### Steps

- Use IE 11 on Windows 7, 8, 10
- Login cms in http://demo.silverstripe.com/admin/ (SilverStripe 4.4)
- Edit content of any page.

### Console error
SCRIPT445: Object doesn't support this action
File: bundle.js, Line: 1, Column: 171462
This error repeats after every keystroke

![Screen Shot 2019-07-19 at 9 35 52 AM](https://user-images.githubusercontent.com/20012807/61497665-614cc600-aa14-11e9-8560-8b5ead91e908.png)

**Comment by ScopeyNZ** [comment]
(It was me: https://github.com/silverstripe/silverstripe-admin/blob/a85b7cd5bee87573a1588cd0ac8f33785614a292/client/src/legacy/HtmlEditorField.js#L101)

**Comment by ScopeyNZ** [comment]
Am I right in assuming this doesn't have observable effect other than errors in the console? (I've triaged as impact/low assuming this).

**Comment by ScopeyNZ** [comment]
Also, weirdly, it's supposed to support `dispatchEvent`: https://caniuse.com/#search=dispatchEvent

**Comment by NightJar** [comment]
> Also, weirdly, it's supposed to support `dispatchEvent`: https://caniuse.com/#search=dispatchEvent

Although generally very good, unfortunately CanIUse is not a definitive resource :/

![image](https://user-images.githubusercontent.com/778003/63813807-c6d09280-c982-11e9-9328-6d59514bbcca.png)

**Comment by robbieaverill** [comment]
I can confirm #951 fixes this issue

**Comment by robbieaverill** [comment]
Fixed in SilverStripe 4.4.x. Thanks @bergice!
