### ISSUE TITLE
Create Documentation for Broken Links Report (SS3)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-cms#2465]
Migrated from https://github.com/silverstripe/silverstripe-framework/issues/1546

/cc @vanlawrence

created by: @vanlawrence (clawrence)
created at: 2012-07-24
original ticket: http://open.silverstripe.org/ticket/7697

---

Pertaining to userhelp ([http://3.0.userhelp.silverstripe.org/]), documentation needs to be created for SilverStripe3.0.x, usage and administration of the Broken Links reporting feature, native to the CMS.

Documentation should explain and detail the following:
- what types of broken links are found and which types of links are not detected
- whether the report is up to date or runs, say, once a day etc
- explain the various reports (compare/ contrast/ describe)

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
