### ISSUE TITLE
Insert media modal background not showing in IE11

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-cms#2472]
In IE 11, the Media Insert modal body does shows. This affect SS4.3 and up.

![image](https://user-images.githubusercontent.com/1168676/64225088-fd338200-cf2d-11e9-9748-44955b9a5f22.png)

**Comment by emteknetnz** [comment]
.insert-embed-modal .modal-body { background-color: #fff; }

**Comment by emteknetnz** [comment]
PR: https://github.com/silverstripe/silverstripe-asset-admin/pull/1049

**Comment by emteknetnz** [comment]
TODO:
- merge PR above
- merge up to "1" branch, then run yarn build - possibly want a separate PR for this (ask team first about process)

**Comment by robbieaverill** [comment]
I've merged your PR, will leave the merge up for the team as per your comment
