### ISSUE TITLE
Perpetual toast notification when restoring page

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-cms#2474]
# Description
When restoring an archived page you might get a perpetually repeating toast notification telling you the treeview has been reorganised.

# Steps to reproduce
* Archive a page
* Refresh the page (you don't get the behaviour if you immediately restore the page)
  * The archive page will show as the last element in the site tree
* Restore the page
  * The page is restored in it's old position in the site tree

Expected behaviour: A single toast notification gets displayed
Actual behaviour: An unending stream of toast notifications get displayed.

Tested with SS4.5 in Firefox and IE11.

https://youtu.be/uqUnJWMZo0M
![image](https://user-images.githubusercontent.com/1168676/64226111-2bb35c00-cf32-11e9-91fc-af8ced3f0f17.png)

# Pull Requests

- [ ] https://github.com/silverstripe/silverstripe-admin/pull/985

**Comment by brynwhyman** [comment]
Related/duplicate issue: https://github.com/silverstripe/silverstripe-admin/issues/953

**Comment by brynwhyman** [comment]
I believe this is a regression in 4.5.x-dev. I'm raising the impact of this to `high`

**Comment by maxime-rainville** [comment]
I'm getting it on a plain regular publish now when publishing a page with a child page.

**Comment by maxime-rainville** [comment]
There's no errors in the console logs. However there's a bunch of successive calls to `/admin/pages/edit/updatetreenodes` and `/admin/pages/edit/savetreenode`.

![image](https://user-images.githubusercontent.com/1168676/67734012-cfb61100-fa64-11e9-8241-ca75c3c1df08.png)

**Comment by maxime-rainville** [comment]
Fixed by https://github.com/silverstripe/silverstripe-admin/pull/985
