### ISSUE TITLE
Silverstripe 4.4 using text alignment in the html editor field doesn't align the text in the WYSIWYG or on the frontend.

### ISSUE THREAD

**Issue by robertclarkson** [silverstripe/silverstripe-cms#2479]
Steps to reproduce:
Create new Silverstripe project, right align some text, see no right alignment on the frontend or backend.

Analysis:
Seems to be adding bootstrap classes to the text block but by default the bootstrap classes aren't loaded.

**Comment by kinglozzer** [comment]
Sounds like the same issue as https://github.com/silverstripe/silverstripe-framework/issues/8785, thanks for reporting @robertclarkson!
