### ISSUE TITLE
Modifying BreadcrumbsTemplate.ss (as per docs) unexpectedly effects CMS

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-cms#2480]
As per [the docs](https://docs.silverstripe.org/en/4/developer_guides/templates/common_variables/#breadcrumbs) you can override the `BreadcrumbsTemplate.ss` template to customise the behaviour of the `$Breadcrumbs` variable in templates.

However, in doing so you unexpectedly affect the CMS. As it seems to use the Breadcrumbs function in [CMSMain's `ListViewForm()`](https://github.com/silverstripe/silverstripe-cms/blob/4/code/Controllers/CMSMain.php#L1699).

The result is that depending on your changes to the template, unexpected things happen in CMS tree list view, e.g.

Before:
![Before](http://spdr.me/fAlQJW+)

After:
![After](http://spdr.me/X5gRZn+)

This seems to have been caused by this commit: https://github.com/silverstripe/silverstripe-cms/commit/fca3ba73f52e2712b40538b015ebf250407edbd0 where @phalkunz added breadcrumbs to the list view when used for search results, e.g.:

![](http://spdr.me/irfN72+)

I wouldn't expect modifications to this template, which is meant for frontend use to have an effect on the CMS, so would suggest updating the list view code to not use the Breadcrumbs template.

# Pull requests
* [x] https://github.com/silverstripe/silverstripe-framework/pull/9280

**Comment by maxime-rainville** [comment]
I think the problem here is with the doc. The doc is telling people to put the Breadcrumb in their `app/templates` folder which will override the Breadcrumb template in the CMS and in the front end. We should be telling people to only override the Breadcrumb template in their theme so it only affects the front end.

**Comment by purplespider** [comment]
@maxime-rainville Ah. So where should the custom `BreadcrumbsTemplate.ss` file be placed?

I've tried putting it in my theme dir, but it doesn't seem to be getting picked up. (`app/templates/PurpleSpider/SiteName/BreadcrumbsTemplate.ss`)

**Comment by kinglozzer** [comment]
@purplespider It’d be either:

- `app/templates/BreadcrumbsTemplate.ss` or;
- `themes/themename/templates/BreadcrumbsTemplate.ss`

**Comment by purplespider** [comment]
@kinglozzer Yup, I had it in `app/templates/BreadcrumbsTemplate.ss` as per [the docs](https://docs.silverstripe.org/en/4/developer_guides/templates/common_variables/#breadcrumbs)  (along with my other templates) but in this location, it effects the CMS (as well as the frontend).

**Comment by kinglozzer** [comment]
D’oh, that’ll teach me for skim reading!

In that case, it should be in `themes/themename/templates/BreadcrumbsTemplate.ss`. I’m not sure why the docs suggest `app/`...

**Comment by michalkleiner** [comment]
What if the site doesn't use themes and has all front-end stuff in `app/templates` and `app/client` for assets?

**Comment by maxime-rainville** [comment]
> What if the site doesn't use themes and has all front-end stuff in `app/templates` and `app/client` for assets?

There's not really an elegant solution I can think off with this set up. I know it's popular approach in some corners for people who don't want to split their project into `app` and `themes`. However, it has the downside that you can't override core templates in the frontend without overriding them in the backend as well.

**Comment by purplespider** [comment]
> I know it's popular approach in some corners

Ah, I was under the impression this was now best practice, as it's the way the official lessons do it: https://github.com/silverstripe/silverstripe-lessons-v4/tree/master/Lesson-04-begin

I still think using `BreadcrumbsTemplate.ss` in the CMS should be re-considered. It was added in 4.0.0 I believe, and the code seems to 'hack' the template quite a bit anyway with `preg_replace` and `sprintf` to stript out and add HTML in order to make it work in the CMS: https://github.com/silverstripe/silverstripe-cms/blob/4/code/Controllers/CMSMain.php#L1701

Perhaps a `CMSBreadcrumbsTemplate.ss` would be a better approach? Could then remove the `preg_replace` and `sprintf` calls and it wouldn't clash with a custom frontend breadcrumbs template.

**Comment by maxime-rainville** [comment]
Added a PR to tweak the doc https://github.com/silverstripe/silverstripe-framework/pull/9280

**Comment by kinglozzer** [comment]
I really don’t think we should advocate putting templates for _themes_ in `app/templates`... surely you’ll run into the exact same issue if you try to customise form field templates?! IMO the solution here is to update the docs/tutorials to consistently recommend using `themes/`

**Comment by purplespider** [comment]
> I really don’t think we should advocate putting templates for _themes_ in `app/templates`

I honestly thought this was the new best practice, as this is how the [updated lessons](https://www.silverstripe.org/learn/lessons/v4/migrating-static-templates-into-your-theme-1) tell you to do it.

But now I'm aware that there are downsides and that it's not recommended the practice, so I agree, it sounds like the location for `templates` just needs to made consistent in the docs and lessons.

**Comment by maxime-rainville** [comment]
I remember Aaron mentioning he prefers putting his templates in `app/templates`. @unclecheese would you care explaining/defending your wicked ways?

**Comment by emteknetnz** [comment]
The [linked PR](https://github.com/silverstripe/silverstripe-framework/pull/9280) which updated the docs has been merged, closing this issue now
