### ISSUE TITLE
Overlapping datefield in page search

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-cms#2481]
## Overview
UX issue with datefield
![image](https://user-images.githubusercontent.com/15868440/65398658-a58d8580-de0c-11e9-8693-8db37bae2acf.png)

## Version
4.4.3

## To reproduce
1. Navigate to Pages
2. Select search icon
3. Select dropdown to refine search, observe the 'To' datefield overlaps the border.

**Comment by phptek** [comment]
Just spotted this myself today, 4.4.3

**Comment by brynwhyman** [comment]
Closing as a duplicate of the newer https://github.com/silverstripe/silverstripe-admin/issues/1036 (as that has a PR)
