### ISSUE TITLE
Duplicate page is sometimes called multiple times

### ISSUE THREAD

**Issue by adrhumphreys** [silverstripe/silverstripe-cms#2484]
A user can right click in the jstree, get the context menu and then select to duplicate a page. This sends a get request to /duplicate/page-id which will start duplicating a page. 

Some times this request will be triggered twice, a user can press back in the browser and it will take them to the duplicate url which is a get request which will again duplicate a page etc

A page duplication can take longer than 30 seconds causing a timeout in the browser in which it will make the request to the URL again as it's just a get request to a page

I think we need to add some kind of preventative to accidentally ending up with multiple duplicate pages

**Comment by ScopeyNZ** [comment]
I'm not sure whether something like this is considered a bug or an enhancement to be honest.

**Comment by adrhumphreys** [comment]
I'd say a bug, if a user clicks "duplicate page" and receives multiple duplicates that is not the expected outcome
