### ISSUE TITLE
Add publish validation (No DataObject validation on publish)

### ISSUE THREAD

**Issue by davejtoews** [silverstripe/silverstripe-cms#2487]
This is related to, but not identical to #2133.

In many cases I would like to enforce validation on publish, but not on save. It should be possible to save a draft with missing/incorrect fields. However using `DataObject::validate()` enforces it whenever a model is saved. A `validateOnPublish()` method would be much appreciated.

**Comment by dnsl48** [comment]
Well, technically publishing is `save + copy the draft version to live stage`.
As long as you have a draft saved it should be possible to make it live, otherwise it wouldn't make sense to users.
Could you tell a bit more details about your particular use case? Maybe that's not exactly validation you're after?

**Comment by davejtoews** [comment]
> Well, technically publishing is save + copy the draft version to live stage.

In that case I'm asking for a validation step when it's copied to the live stage. I don't see why this would be confusing to users as long as the validation messages are appropriate.

My use case is rather general. CMS users often begin building pages and other pieces of the site before having all the content. I'd like to allow them to save a draft while they gather the remaining pieces, but prevent publication unless it's complete. 

Say this is a layout block with a text field and an image, and it will look broken without the image. Currently I can do one of three things: 

1. prevent them from saving without the image, meaning they will have to enter the text again once they have tracked down an appropriate image. 
2. I can allow them to publish without the image and just not display the block until they add one
3. I can allow them to publish and display a broken block.

Option 1 makes my CMS users complain so I inevitably end up at 2, which confuses them because they don't get told the image is required but they don't see the text they've entered on the front end. If they complain loudly enough about that I can give them option 3, but then since they still aren't getting validation messages they end up putting broken layouts live.

It was suggested to me in the SilverStripe Slack that I override `canPublish()` to prevent publication when fields are missing, and then write a `validate()` method that checks against `isPublished()` but this approach both seems hacky and has holes in it that still allow for publishing w/ missing content.

Another user suggested I look into `onBeforePublish()` but since it doesn't return a `ValidationResult` it seems like I would at that point be implementing my own independent validation system and I don't want to do that.

**Comment by davejtoews** [comment]
I mention issue #2133 above because it sounds to me like these two issues might be resolved by the same fix.

**Comment by dnsl48** [comment]
/cc @silverstripeux

In that case we still may want to perform such a validation not only on publish, but on save as well to show a notification that it's saved, but may not be published "as is".
I would even consider showing such a notification independently of any user actions as a part of the UI.

**Comment by clarkepaul** [comment]
I see the benefits of this and have even experienced this issue myself. A reminder that certain content is missing would be good. I think the grading of impact/med is a good fit. I probably wouldn't be mocking any UI for this unless I knew it was going to be picked up, but happy to do otherwise.

**Comment by dnsl48** [comment]
My main point is I don't think we could simply *hijack* the publish button and add some extra validation there as it would be bad user experience.
As such, this issue cannot be solved as a simple API improvement, but rather may require some UI amendments and should be treated as a new feature.
Unless the core team decides to pick it up (e.g. it might be a part of the experience debt) we'll need to move it to the ["feature ideas" on the forums](https://forum.silverstripe.org/c/feature-ideas) (more details explained in the [contribution guides](https://docs.silverstripe.org/en/4/contributing/issues_and_bugs/)).

**Comment by davejtoews** [comment]
I don't see myself working on a PR in the near future, but whenever I have some downtime I may take a look at that.

**Comment by dnsl48** [comment]
I'm closing for now.
Anyone who wants to pick this up please feel free to reopen.
