### ISSUE TITLE
WYSIWYG fails to render image shortcode if `title` parameter is empty

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-cms#2489]
To reproduce, have an image shortcode in a content area which has the `title` parameter set, but empty. e.g.:

`[image src="/assets/image.jpg" title="" id="123" width="100" height="100"]`

_(The `TagsToShortcode` task produces shortcodes with empty title tags like this, if the original `img` tag had an empty `title` attribute.)._

While the image will render correctly when viewing the page. It fails to render in the WYSIWYG editor, and instead, the shortcode is just displayed:

![](http://spdr.me/agUua2+)

Note the 4 quote marks for the `title` parameter.

I've noticed that when a user inserts an image via the CMS and empties the Title field, the `title` attribute is just omitted from the shortcode altogether. So one alternative workaround could be to update the `TagsToShortcode` task to only add the `title` parameter if it isn't empty. But I'd imagine it's best to fix whatever is causing an empty `title` tag to cause it to not render in the WYSIWYG.

# Pull request
- [ ] https://github.com/silverstripe/silverstripe-assets/pull/474

**Comment by purplespider** [comment]
For anyone else experiencing this issue after upgrading a site to Silverstripe 4, I've found the easiest fix is to just take a dump of the database (after the upgrade) and then do a find and replace to remove all instances of `title=\"\"`.

I welcome discussion of whether the issue should be resolved by either:
- Updating the `TagsToShortcode` task to only add the `title` parameter if it isn't empty.
- Updating the WYSIWYG shortcode handling so it doesn't get tripped up by empty title tags.

**Comment by purplespider** [comment]
Just upgraded a site from Silverstripe 3.7 to 4.6.1 and this is still an issue.

**Comment by micschk** [comment]
I know I'm a bit late to the game, but I also just ran into this issue. Seems it's also the case with empty alt tags (probably any empty tag?).

I'd say this should be fixed in the WYSIWYG rendering instead of the `TagsToShortcode` task (where I fixed it for the time being).

**Comment by maxime-rainville** [comment]
https://github.com/silverstripe/silverstripe-framework/pull/9872 will have fixed this issue.

If not, let me know and I'll reopen.

**Comment by purplespider** [comment]
Sorry @maxime-rainville, this doesn't look to be fully resolved yet. If the `title` attribute is empty, it now seems to change it to `title="title"`, rather than `title=""`.

To reproduce:
1. Add `[image src="/assets/image.jpg" title="" id="123" width="100" height="100"]` to a Content field in the database.
2. Open the page in the CMS, note that the title of the image is now set to "title", and is applied when the page is saved.

_Reproduced in Silverstripe 4.9_

**Comment by maxime-rainville** [comment]
https://github.com/silverstripe/silverstripe-assets/pull/474 should fix this.
