### ISSUE TITLE
Config to set view mode in the CMS. 

### ISSUE THREAD

**Issue by Rhym** [silverstripe/silverstripe-cms#2494]
I have a use case that pops up more often these days where I use Silverstripe as a headless CMS, but by default when a client logs into their account for the first time the split view is present by default.

I'm proposing a config to allow you to disable certain views, or set one by default as in this use case the preview, and split views have nothing to do with the project and can only cause confusion to the user.

**Comment by clarkepaul** [comment]
Sounds like a good setting, there is nothing planned for this as far as I know.

We have considered/talked about how the preview could be repurposed to display raw HTML structures (no CSS) and also whether the headless view (or multiple views) could be embedded into the preview instead of the default, but no visual concepts as yet.

**Comment by Rhym** [comment]
Excellent, currently I hide it with css injected with an extension but would be good to have a more native option.

**Comment by clarkepaul** [comment]
Maybe I should add a few notes here about how I see this actually panning out for the future. I've always wanted the site tree to be able to toggle over to list view and preview. This would get rid of the ganky "View mode" toggle and the need for going four panels deep in the CMS, which also means we can get rid of the main menu sticky action. Then I would think its more of a matter of removing the preview option from the toggle. Just some thoughts for the future.

**Comment by clarkepaul** [comment]
Related https://github.com/silverstripe/silverstripe-cms/pull/2492

**Comment by ScopeyNZ** [comment]
I've merged #2492. I'm pretty sure that covers this. Please let me know if I'm mistaken.

**Comment by Rhym** [comment]
Fantastic! So will this be available in the next release?

**Comment by ScopeyNZ** [comment]
Sort of. I think the RCs are already tagged for 4.5 so it won't be out until 4.6.

**Comment by Rhym** [comment]
I hear what you're saying, but will $3.50 change your mind?

**Comment by ScopeyNZ** [comment]
There's some composer extensions that allow you to apply arbitrary patches to your codebase. You could export #2492 as a patch, and then use https://github.com/vaimo/composer-patches to apply it without actually forking CMS. It should be compatible with 4.5 (or probably even 4.4)
