### ISSUE TITLE
Move 'Access' Settings into the Security area instead

### ISSUE THREAD

**Issue by neilcreagh** [silverstripe/silverstripe-cms#2497]
I use the Settings area for site-wide items (not tied to any specific page) such as Google Analytics code & Footer details (address, social media links etc.) but allowing Content Editors access to this area means hiding the 'Access' Tab. 

'Who can view pages on this site? Who can edit pages on this site? Who can create pages in the root...' - should these be moved into the Security area?

**Comment by robbieaverill** [comment]
They’re in the security area as well. The page level gives you a bit more fine tuned control though. You could always move them to a different tab or remove them entirely with an extension

**Comment by Cheddam** [comment]
Unfortunately I don't think this would be achievable in SilverStripe 4, as it would likely break any existing extensions relying on the current location of the Access tab. It might warrant a re-think of how these permissions are handled, too. Perhaps this would be best marked as an RFC.

**Comment by GuySartorelli** [comment]
Interesting idea but it's an old issue that we're not going to do anything with any time soon. Closing. If someone is keen for this and wants to put in the work to implement it, `@` me and we can revisit.
