### ISSUE TITLE
Image size presets UI broken when embedding media

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-cms#2498]
### Overview
There was some recent work in 4.5 to improve image size presets when inserting images via the WYSIWYG. This allows user to select from 'Best fit' and 'Original'.

These options are also appearing in the 'Insert media via URL' modal. Here,
* the original size gives no values; and
* the buttons are overlapping existing labels.

![image](https://user-images.githubusercontent.com/15868440/68911084-b9c08400-07b8-11ea-901d-6ae0d0072407.png)

### Version
CMS 4.5.alpha-1

## To reproduce
1. Embed an image
2. Embed a video (identify the broken preset view)

_Note: Step 1 is necessary to reproduce this issue_

### Expected result
The present links are not present in this modal.

**Comment by brynwhyman** [comment]
The 'original' preset might be breaking based on this issue: https://github.com/silverstripe/silverstripe-cms/issues/1921

**Comment by Cheddam** [comment]
@brynwhyman Do you think the solve here is tidying and fixing the functionality for this context, or removing it entirely? I'm leaning towards the latter, especially since it only appears situationally at the moment and wasn't intended to be available in this view.

**Comment by clarkepaul** [comment]
Removing it for videos sounds like the best approach. If we want it for media we should look into a bit more research and testing prior to saying if the design is fit for purpose.

**Comment by brynwhyman** [comment]
We'll want to raise a separate issue to tackle re-implementing it in the future.

**Comment by emteknetnz** [comment]
Just to clarify, it's not just videos that it's messed up on, it's any sort of remote file including images:

![image.png](https://images.zenhubusercontent.com/5dcb6f9e3c55460001028c42/28fcd5db-a299-4d92-8663-1e31b9d6e6e7)

**Comment by Cheddam** [comment]
Fixed in #1055.

**Comment by maxime-rainville** [comment]
I think you meant https://github.com/silverstripe/silverstripe-asset-admin/pull/1055, not #1055.

**Comment by Cheddam** [comment]
@maxime-rainville Good point, thanks!
