### ISSUE TITLE
RedirectorPage.php, line 139, protected? public?

### ISSUE THREAD

**Issue by leochenftw** [silverstripe/silverstripe-cms#2507]
After updating SS to 4.5, I'm getting below:

```
[php7:error] [pid 2109] [client *.*.*] PHP Fatal error:  Access level to SilverStripe\\CMS\\Model\\RedirectorPage::onBeforeWrite() must be public (as in class Page) in /var/www/WWWROOT/vendor/silverstripe/cms/code/Model/RedirectorPage.php on line 0
```

The solution is to change line 139: `protected function onBeforeWrite()` to `public function onBeforeWrite()`

I'm not sure if I'm gonna get more issues, but for now changing protected to public is doing just fine

**Comment by Cheddam** [comment]
Hey @leochenftw, do you have `public function onBeforeWrite()` defined in your `Page` class? The root `onBeforeWrite` method (in `DataObject`) is `protected`, so every subclass should match this visibility level.

**Comment by leochenftw** [comment]
> Hey @leochenftw, do you have `public function onBeforeWrite()` defined in your `Page` class? The root `onBeforeWrite` method (in `DataObject`) is `protected`, so every subclass should match this visibility level.

Thanks @Cheddam ! And yes, I do have onBeforeWrite function in my Page class. I've been doing this since SS4.1, and it didn't throw errors before SS4.5, so I assume onBeforeWrite function was added to RedirectorPage page recently?

**Comment by kinglozzer** [comment]
Yeah this was caused by https://github.com/silverstripe/silverstripe-cms/pull/2463, I mistakenly thought this would only affect subclasses of `RedirectorPage`.

I’d be against reverting that change though - whether it’s `RedirectorPage` or another module (e.g. blog) that extends `Page`, _something_ will probably trigger the same notice at some point during the 4.x release cycle. The only real fix is changing `public function onBeforeWrite()` to be `protected` so it matches `DataObject::onBeforeWrite()`

**Comment by leochenftw** [comment]
> Yeah this was caused by #2463, I mistakenly thought this would only affect subclasses of `RedirectorPage`.
> 
> I’d be against reverting that change though - whether it’s `RedirectorPage` or another module (e.g. blog) that extends `Page`, _something_ will probably trigger the same notice at some point during the 4.x release cycle. The only real fix is changing `public function onBeforeWrite()` to be `protected` so it matches `DataObject::onBeforeWrite()`

Thanks @kinglozzer . Thank god I don't have many projects that are using `public function onBeforeWrite()` in `Page.php`, although some subclasses that extend `Page::class` are.  It wouldn't be fun to go through them and make changes, but thanks for the clarification.

Cheers
Leo
