### ISSUE TITLE
"Insert external link" changes selected text to 'undefined' in IE11 and Edge 18

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe/silverstripe-cms#2512]
Adding a link to a selected text via the WYSIWYG editor in Edge ~19~ 18 changes the selected text to 'undefined'.

Steps to reproduce:

1. In Edge ~19~ 18
2. Open SS 4.4 demo at https://demo.silverstripe.org
3. Create a generic page
4. Type some text into the WYSIWYG
5. Select the text
6. Insert external link via the chain link icon (SS plugin)
7. Observe new link created with the text changed to 'undefined'

<img width="1005" alt="Screen Shot 2020-01-13 at 9 16 00 PM" src="https://user-images.githubusercontent.com/233342/72241037-a0b64100-364a-11ea-9972-7ecd1d41d249.png">

[IE11 recording of this issue](https://youtu.be/uLrr0TzACmg)

# Pull Requests

- [ ] https://github.com/silverstripe/silverstripe-admin/pull/1059

**Comment by brynwhyman** [comment]
I don't think there is a stable version of Edge 19? (Happy to be corrected though!) Are you perhaps running an insider preview or the new Chromium-Edge beta?

**Comment by lerni** [comment]
As it looks on caniuse.com after 18, 76 'll follow (15th of april AFAIK) and this version 'll be chromium based.

**Comment by michalkleiner** [comment]
Apologies, Edge 18 as in the title

**Comment by michalkleiner** [comment]
Looking at changes related to the 'Insert link' feature since 4.4.3, this is the only relevant imho, though haven't tested whether reverting it fixes the issue.

https://github.com/silverstripe/silverstripe-cms/commit/8ba444332adc11bd1d4453e6b966ef737199d20b#diff-50c48f8411e61104e6fffa513bcf2bff

**Comment by intotheweb101** [comment]
@michalkleiner have you found a solution to this issue ?
We have just found this issue in one of our new sites, and the client uses IE11 as the main browser

Thanks

**Comment by axllent** [comment]
We're also experiencing this same issue for a CWP client who use Edge (18) internally.

**Comment by michalkleiner** [comment]
No, haven't been looking into it, sorry @intotheweb101.
Same as for @axllent, it's a CWP client of ours.
Perhaps it could be resolved through the shared pool of hours, but someone would need to raise it there.

**Comment by Cheddam** [comment]
The related PR has been merged, so this fix will go into CMS Recipe 4.5.3 and 4.6.1 (missed the boat on 4.6.0 unfortunately).
