### ISSUE TITLE
composer.json dependancies for some core modules are out of date

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-cms#2521]
## Overview

Some core modules currently have out of date `composer.json` dependencies, including:

* Incorrect / missing minimum PHP version
* The minor versions haven't been kept in lock-step, i.e. `silverstripe/cms 4.5.x` is incorrectly requiring `silverstripe/framework 4.3.x`

## Acceptance criteria (in task order)
- [ ] All supported versions of our core modules are updated to be in lock-step at a minor level. Note, the modules are still okay to be out of lock-step at a patch level, i.e. `silverstripe/cms 4.4.1` requiring `silverstripe/framework 4.4.5` is fine.
- [x] the `silverstripe/framework 4.5.x` module has it's PHP constraint updated to "php": ">=7.1". This will mean other core modules inherit the constraint without the need to apply it everywhere.
- [ ] Our release documentation is updated to make it clear that when a minor release is prepared, all core modules should have their core dependancies bumped to be in a minor lock-step.

## Note

- We're only considering core modules as part of this issue.
- Details on keeping core modules in a minor lock-step was a decision made as part of the following RFC: https://github.com/silverstripe/silverstripe-framework/issues/8970

## PRs

- [x] ~~silverstripe/admin~~ (Already up to date)
- [ ] [silverstripe/assets](https://github.com/silverstripe/silverstripe-assets/pull/369)
- [ ] [silverstripe/asset-admin](https://github.com/silverstripe/silverstripe-asset-admin/pull/1056)
- [ ] [silverstripe/campaign-admin](https://github.com/silverstripe/silverstripe-campaign-admin/pull/156)
- [ ] [silverstripe/cms](https://github.com/silverstripe/silverstripe-cms/pull/2524)
- [x] ~~silverstripe/config~~ (Depended on by framework directly, not in lockstep with the rest of core)
- [ ] [silverstripe/errorpage](https://github.com/silverstripe/silverstripe-errorpage/pull/46)
- [ ] [silverstripe/reports](https://github.com/silverstripe/silverstripe-reports/pull/123)
- [ ] [silverstripe/siteconfig](https://github.com/silverstripe/silverstripe-siteconfig/pull/108)
- [ ] [silverstripe/versioned](https://github.com/silverstripe/silverstripe-versioned/pull/256)
- [ ] [silverstripe/versioned-admin](https://github.com/silverstripe/silverstripe-versioned-admin/pull/147)
- [ ] [silverstripe/framework (documentation update)](https://github.com/silverstripe/silverstripe-framework/pull/9404)

________

### Old description for note sake

Because that is the minimum requirement [of PHP 7.1 was applied] since around mid June 2019.  Enforcing this means that  systems still running php 5.6 or 7.0 do not try and install this version

This issue affects dozens of supported silverstripe modules, not just this one

It's fairly common for applications to use carets e.g. "silverstripe/cms": "^4" - unfortunately this means that older tagged versions without the constraint e.g. 4.5.0 will still get incorrectly installed on php 5.6 systems.  It's too late to retrospectively fix this though.

We should probably release this as a patch instead of a minor so that we don't imply that 4.6.x is php 7.1 only while 4.5.x doesn't have the requirement.  Having 4.5.1 requires php 7.1 is more in line with "there was a bug that we are now fixing"

Note: We're going to look at making sure all core modules are lock-stepped at a minor-release level too. (Will update notes to be more detailed)

**Comment by robbieaverill** [comment]
We have this constraint in framework, rather than having it in multiple places. I don't think there's anything to do here, unless I'm missing something?

**Comment by emteknetnz** [comment]
Yeah agree, seems like we cannot fix this retrospectively in a good way.  It would require removing tags, fixing up the composer.json and republishing the tags.  I don't think this issue warrants doing that.

**Comment by robbieaverill** [comment]
Agreed, removing tags is not really an option

**Comment by brynwhyman** [comment]
I've updated the title and description to combine this issue with https://github.com/silverstripe/silverstripe-framework/issues/9395

**Comment by emteknetnz** [comment]
@Cheddam noticed that while you sorted out the lockstepping, the require "php": ">=7.1" was missing from all the PR's.  You'll want to add that in.  You'll also want to raise 2 new PR's for silverstripe/admin and silverstripe/config

**Comment by emteknetnz** [comment]
Also a PR for silverstripe/login-forms to add php >=7.1 as per this comment https://github.com/silverstripe/silverstripe-framework/pull/9404#discussion_r377995892

**Comment by robbieaverill** [comment]
-1 for adding that PHP dependency, it's not necessary since framework already has it

**Comment by emteknetnz** [comment]
See rationale for adding it here https://github.com/silverstripe/silverstripe-campaign-admin/pull/156#discussion_r378002730
