### ISSUE TITLE
OldPageRedirector doesn't work properly with multiple pages having same URLSegment

### ISSUE THREAD

**Issue by t3hn0** [silverstripe/silverstripe-cms#2522]
We have multiple news list pages with same URLSegment and we noticed if we changed URLSegments of News (children of news listing pages) redirects didn't work.

I found a problem in OldPageRedirector::find_old_page. As it starts to look for old URL it doesn't necessarily start with ParentID=0 (root) as it's not requested and then it just picks first/random page (order by _Sort_ column) with the same URLSegment.

This lines:
```php
        if ($parent) {
            $pages = $pages->filter(array(
                'ParentID' => $parent->ID,
            ));
        }
```

should have a fallback to look on root level if no $parent is set:
```php
        if ($parent) {
            $pages = $pages->filter(array(
                'ParentID' => $parent->ID,
            ));
        } else {
            $pages = $pages->filter(array(
                'ParentID' => 0,
            ));
        }
```

I'm using SilverStripe v4.4.4, with Fluent 4.4. 

**Test case:**
1. Create page on root, Title "Test page" (URLSegment: "test-page") and publish it. In my case gets ID #19354, Sort=50
    _/test-page_
2. Create subpage on previously created page, Title "Goals" (URLSegment: "goals") and publish it. In my case gets ID #19355, Sort=1
    _/test-page/goals_
3. Create page on root, Title "Goals" (URLSegment: "goals") and publish it. In my case gets ID #19356, Sort=51
    _/goals_
4. Update URLSegment of "Goals" page (ID #19356) from previous line to "goals-new" and publish it
5. if you open _/goals_ you get redirected to _/test-page/goals/_ but it should redirect you to _/goals-new_

**Comment by t3hn0** [comment]
Created pull request #2523  if bug is confirmed.

**Comment by t3hn0** [comment]
May I ask will this be released in 4.5.x or branch?
I tried upgrading SS (with default installer) and looks like Recipe CMS is using different branch - I guess branch 4.5.

**Comment by dhensby** [comment]
No, it will be in the next minor release (4.6) as the PR was opened against that branch (4) and merged into it

**Comment by t3hn0** [comment]
I see. Do you have any info when 4.6 would be released?
