### ISSUE TITLE
link to anchor always opens in new tab

### ISSUE THREAD

**Issue by guyvanbael** [silverstripe/silverstripe-cms#2525]
Silverstripe 4.5
In the TinyMce editor, the link always gets "target="_blank", even when option to open in a new tab is unchecked

**Comment by scott1702** [comment]
@guyvanbael Could you confirm if you were viewing your site through the CMS preview/split mode?

The CMS will attach `target="_blank"` to any links while viewing the site through the preview intentionally. However this shouldn't happen when viewing your site outside of the CMS.

**Comment by guyvanbael** [comment]
@scott1702 Even when i 'm not logged in, the link opens in a new tab
<img width="1549" alt="Schermafbeelding 2020-02-12 om 09 38 07" src="https://user-images.githubusercontent.com/3098809/74317308-73f56680-4d7b-11ea-963c-7c379cae5323.png">

**Comment by brynwhyman** [comment]
Hi @guyvanbael, I can't recreate this issue with anchor links on a live site (using version 4.5.0 of the Silverstripe Installer) so I'm going to close this issue.

If you can provide further information confirming this is a bug in the CMS, I'll reopen the issue. Thanks for posting.

**Comment by guyvanbael** [comment]
That's weird. I'm having the issue on my mamp stack and on the live site of
my client. Using ss 4.5 and trying to link to an anchor on the same page.
Even removing it from the code doesn 't work, it 's being put back in when
publishing the page. Any ideas on how to debug this?

Op vr 14 feb. 2020 03:03 schreef Bryn Whyman <notifications@github.com>:

**Comment by brynwhyman** [comment]
Confirming that I tested this for anchor links within a page and they're not opening in another tab unexpectedly. 

The ability to _create_ anchors in TinyMCE was introduced/enabled with version 4.4.3 via https://github.com/silverstripe/silverstripe-cms/issues/2268. Is it possible that this site was using something custom for creating anchors before then?
