### ISSUE TITLE
HTMLText editor, cannot re-add link to text after removal

### ISSUE THREAD

**Issue by rychere** [silverstripe/silverstripe-cms#2530]
Problem: In HTMLText field, cannot add link to text that has had the link removed.
Browser: Chrome 80.0.3987.132
Version: silverstripe/cms version 4.5.1 using a clean install of Silverstripe installer

Reproduction steps:
  - Install CMS
 - Edit Home Page
 - Click on link e.g. "default homepage" in the Content field
 - Click "remove link"
 - Highlight text
 - Right click -> Insert link -> page on this site
 - Select a page

Result: text is not highlighted / link is not saved. There is no link in the source view, no link is added on save/publish.

## Notes from Silverstripe review session before picking up issue:
- It could a problem with our custom plugin (in our codebase, easier to fix)
- It could be a problem with tinymce (much harder to fix)
- Steve has seen this behavior before on a different issue - https://github.com/silverstripe/silverstripe-asset-admin/pull/1115 

# Pulls requests
- [ ] https://github.com/silverstripe/silverstripe-admin/issues/1082

**Comment by emteknetnz** [comment]
Thank you for reporting this.  In terms of getting this resolved in a timely manner, just letting you know that the team at Silverstripe Ltd set bugfix priorities based on the impact of the bug with critical being the highest, so at this stage we cannot say when we’ll get a chance to look at this further.

If other people are experiencing this same issue then we'd encourage them to share their experiences here, which can help raise the priority on getting this issue resolved.  Please follow the guide about what is useful when making [bug reports](https://docs.silverstripe.org/en/4/contributing/issues_and_bugs/).

Community help creating a pull-request for this is most welcome, so perhaps this is something that you could do?  Read more about [contributing code](https://docs.silverstripe.org/en/4/contributing/code/) or where you may be able to [request help or support](https://docs.silverstripe.org/en/4/#getting-support) from the open-source community.

**Comment by brynwhyman** [comment]
I'm bumping the impact label of this one to `high`. For a content editor there's no clear and straightforward workaround (for what should be a basic task). Note that the above comment is still true.

**Comment by emteknetnz** [comment]
The linked PR has been merged, closing this one now
