### ISSUE TITLE
Weird behavior when page title / url segment includes "public"

### ISSUE THREAD

**Issue by jinjie** [silverstripe/silverstripe-cms#2552]
# Steps to reproduce

- Create a new page with the title "Publications"
- URLSegment is "publications"
- Save & Publish

# Issue

After Save & Publish, you will be presented with Error 404,
- The page is not accessible by http://example.com/publications.
- All links have "/public" in the url now. 
- The new page is accessible with http://example.com/public/publications

# Workaround

- Change URL segment that do not include the word "public"

Not sure if this is some htaccess rule somewhere.

**Comment by kinglozzer** [comment]
This sounds very similar to https://github.com/silverstripe/silverstripe-framework/issues/9459, could you test 4.6.0-beta1?

**Comment by jinjie** [comment]
Yes! That seem to fix the issue. Closing this issue and looking forward to 4.6!
