### ISSUE TITLE
SiteType (ClassName) as FQN if lang != EN in page-settings feels/looks wrong

### ISSUE THREAD

**Issue by lerni** [silverstripe/silverstripe-cms#2557]
In [SiteTree.php:2632](https://github.com/silverstripe/silverstripe-cms/blob/4/code/Model/SiteTree.php#L2632-L2637) there is:
```
  // If we're in translation mode, the link between the translated pagetype title and the actual classname
  // might not be obvious, so we add it in parantheses. Example: class "RedirectorPage" has the title
  // "Weiterleitung" in German, so it shows up as "Weiterleitung (RedirectorPage)"
  if (i18n::getData()->langFromLocale(i18n::get_locale()) != 'en') {
      $result[$class] = $result[$class] .  " ({$class})";
  }
```
Since namespacing is a thing it results in a dropdown like bellow and there is no way around it, except if you happen to use `en` as locale. It feels odd that `i18n_singular_name` is suffixed with the FQN in any other language than english - in the example a pretty short ClassName is used.

![ClassName-Dropdown](https://user-images.githubusercontent.com/472115/84234050-cd845c80-aaf3-11ea-850b-098d26b2538e.png)

I would prefer option A – any other views?
- A :thumbsup: remove class in brackets for other languages than english altogether
- B :nerd_face: show just last part like `end(explode('\\', $class))` for non `en` languages
- C :facepunch: show last part like `end(explode('\\', $class))` for all languages
- D :-1: do not change anything

**Comment by robbieaverill** [comment]
cc @silverstripeux

**Comment by lerni** [comment]
https://github.com/silverstripe/silverstripe-cms/pull/2558
