### ISSUE TITLE
SiteTree::get_by_link returns null instead of the homepage if passed the homepage absolute URL

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-cms#2580]
Passing the homepage's absolute URL (excluding the home path e.g. `https://example.co.nz/`, not `https://example.co.nz/home/`) to `SiteTree::get_by_link` returns null.
I believe this should return the SiteTree object which represents the home page.

silverstripe-cms version: 4.5.1

**Comment by chillu** [comment]
Sorry, but the PHPDoc on this method gives an example of a relative link. Accepting absolute URLs sounds useful, but we generally don't keep low impact enhancements in our bug tracker. You're welcome to submit a pull request for this (incl. a unit test). Until then, I'm closing this issue.

**Comment by GuySartorelli** [comment]
"the PHPDoc on this method gives an example of a relative link"
This statement seems irrelevant to me. The method specifically calls `Director::makeRelative` which ensures it handles all absolute URLs with the exception of a URL that omits a path. This method _can and should_ handle absolute URLs.

What's more, the example in the PHPDoc is specifically an example of a nested link. It does not seem to me that the example is intended to indicate an exclusion of support for absolute URLs.

**Comment by chillu** [comment]
Sounds like you care strongly enough about this to either clarify the current behaviour more clearly in the PHPDoc, or make this enhancement via a PR? :)

**Comment by emteknetnz** [comment]
Linked PR has been merged
