### ISSUE TITLE
Translation to Slovenian

### ISSUE THREAD

**Issue by tomaszpirc** [silverstripe/silverstripe-cms#2605]
Translation to Slovenian is ready in Transifex. Can you please pull it.

**Comment by dnsl48** [comment]
Hi! Thanks for doing that! The new translations should land automatically to all the following releases. We're planning to release `4.7-beta1` soon, and the new translations should be there.
I'll close this issue for now and we can reopen it as a bug if they don't make it for some reasons to any of the releases.

**Comment by tomaszpirc** [comment]
@dnsl48 Could you please let me know if you can somehow include also latest corrections (mainly better usability) I did in 4.6? We just upgraded our projects to 4.6 and I would appreciate it if we can have the latest translations included. Thnx.

**Comment by dnsl48** [comment]
Hi @tomaszpirc, we usually don't backport any translations, but if you'd like to contribute a PR, we could merge it to 4.6 as it's still a supported branch.

**Comment by tomaszpirc** [comment]
Sure I can do it. But if it is easier for you everything is updated on the transifex. (Honestly I have no clue what means less fuss for you. If PR is better option I will prepare it tomorrow so you can merge it.) Thnx.

**Comment by dnsl48** [comment]
> But if it is easier for you everything is updated on the transifex.

Our scripts would just pull everything for all languages, which might be an overkill (and we would have to manually check all the messages in 4.6 are provided, because transifex doesn't keep our branches in mind).
Here I assumed you wanted to pull some particular Slovenian translations?

**Comment by tomaszpirc** [comment]
Yes. And now I understand a bit more ... I'll prepare PR with just sl.yml tomorrow. Cheers.
