### ISSUE TITLE
Duplicating a page does not duplicate viewer/editor groups

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-cms#2609]
# Steps to reproduce
- Create a page.
- Set some viewer groups and editor groups
- Duplicate the page

Expected result: The same groups are assigned as editors and viewers.
Actual result: No group is assigned.

## Acceptance criteria
- When duplicating a page, the duplicate retains the same canView and canEdit groups.
- Fix is targeted to the next minor of CMS 5 and is called out in the changelog. 

## PR
- https://github.com/silverstripe/silverstripe-cms/pull/2859
- https://github.com/silverstripe/silverstripe-framework/pull/10806
- https://github.com/silverstripe/developer-docs/pull/282
- https://github.com/silverstripe/silverstripe-cms/pull/2858
- https://github.com/silverstripe/developer-docs/pull/280

**Comment by emteknetnz** [comment]
PRs have been merged
