### ISSUE TITLE
Database values in formfield attributes don't update correctly when saving.

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-cms#2622]
## Version
4.6.0

## Problem
Attributes set on a field which take the database value do _not_ show the correct value when saving a new value on the field. The value of the attribute will always be taken from the _previous_ save, unless you refresh the whole page.

## Steps to reproduce
1. Implement an Extension class that adds a new field, and sets an attribute using the database value:
```php
$db = [
    'SomeField' => 'Varchar(255)'
];

public function updateCMSFields(FieldList $fields)
{
    $dbValue = $this->owner->dbObject('SomeField')->getValue();
    $fields->addFieldToTab('Root.Main',
        TextField::create('SomeField')->setAttribute('data-db-value', $dbValue)
    );
}
```
2. Apply the extension to Page (it's possible the above directly in Page will also exhibit this issue - I haven't checked)
3. Create a new page. Check the field - the attribute is missing.
4. Set a value on the field and save, then check the field again. The attribute is still be missing despite a value having been saved to the database.
5. Set a different value on the field and save, then check the field again. The attribute has the value from step 4! It should have the value that you just saved.
6. Refresh the page and check the field. The attribute now shows the correct value.

**Comment by lerni** [comment]
This may well be related to https://github.com/silverstripe/silverstripe-framework/issues/9124

**Comment by emteknetnz** [comment]
I tried replicating this in 4.7.x-dev as well as 4.6.0, though I was unable to replicate this issue.  The `data-db-value="myvalue"` is updating as I would expect it to

Code used:

```mysite.yml
---
Name: myproject
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app
Page:
  extensions:
    - PageExtension
```


```php
<?php

use SilverStripe\ORM\DataExtension;
use SilverStripe\Forms\FieldList;
use SilverStripe\Forms\TextField;

class PageExtension extends DataExtension
{
    private static $db = [
        'SomeField' => 'Varchar(255)'
    ];

    public function updateCMSFields(FieldList $fields)
    {
        $dbValue = $this->owner->dbObject('SomeField')->getValue();
        $fields->addFieldToTab('Root.Main',
            TextField::create('SomeField')->setAttribute('data-db-value', $dbValue)
        );
    }
}
```

Is there any other details you can provide to help replicate this issue?

**Comment by dhensby** [comment]
Closing as we can't replicate and no response from OP

**Comment by GuySartorelli** [comment]
Sorry, somehow missed this until now.
I haven't been able to reproduce it so I'm not sure what was causing it... this can stay closed.
