### ISSUE TITLE
Anchor on external link get squash on when prefix with a #

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-cms#2634]
# Steps
- Access the CMS and edit a regular page
- Insert a "Link to external URL" in the content area
- Provide all fields
  - In the _Anchor_ field provide a value with a `#` character. e.g. `#heading1`
 - Publish the page
 - View the published page and note that the URL contains a double `#` character
 - Go back to the CMS and edit the link again. Note the value in the anchor field.

**Expected**
- The form should be clever enough to strip the redundant `#` character
- When editing the link again, your provided value should be present

**Actual**
- The frontend doubles up the `#`
- When editing the link again, the anchor field comes back blank

[YouTube video](https://youtu.be/UVRr1sb9C8Q)

### PR
- [x] https://github.com/silverstripe/silverstripe-admin/pull/1180

**Comment by maxime-rainville** [comment]
It's not quite clear to me why we even have a dedicated field for the anchor. Would it not make more sense to have people enter the anchor directly in the main URL field as a fully form URL?

**Comment by maxime-rainville** [comment]
@silverstripeux

**Comment by clarkepaul** [comment]
According to our designs, for external URLs we are supposed to be removing the anchors. Anchors are still needed for internal pages but we used to be able to detect anchors on a page and suggest them to users, or to create new ones. Similar UI as the [Link Field ](https://projects.invisionapp.com/dsm/silver-stripe/silverstripe-cms/nav/5fa7cb5f8c012000183561a5/asset/5fbc290f18fe3a63a15b5111/tab/design?mode=edit). We probably already have an issue to redesign the link options and forms but might have been hidden in an epic which never happened.

I'd be happy if this issue was just for removing anchors on external links. Any objections?

**Comment by michalkleiner** [comment]
For local links, before elemental, the system used to collect anchors from content fields and populate to dropdown to select them. For external links, it was a freetext field that would get added to the link as expected. The list of local anchors stopped working with elemental. I would still expect the anchor field for external links to work, it's a valid part of a link. The system shouldn't discard it completely.

**Comment by maxime-rainville** [comment]
I added some ACs to the top card. If you're happy with it I can have a quick crack at implementing it

**Comment by clarkepaul** [comment]
Maybe it makes sense to approach a few admins to see what makes more sense to them before doing any changes. I'll see if I can get some thoughts today.

**Comment by maxime-rainville** [comment]
I made a simple PR that simply strips any `#` the user manually puts into the anchor.

https://github.com/silverstripe/silverstripe-admin/issues/1180

When we pick up, https://github.com/silverstripe/silverstripe-cms/issues/2440 we can look at rethinking the AnchorField and using that as well.

**Comment by emteknetnz** [comment]
Waiting on @clarkepaul's reply, will move to external peer review for now

**Comment by clarkepaul** [comment]
Perfect :), happy with the approach. Feedback from a single user was positive about using the URL for anchors but that wasn't enough info to base reworking the whole thing.

**Comment by brynwhyman** [comment]
We've removed the following ACs that covered removing the field altogether:

Acceptance criteria
* [ ] The "HTML Editor External Link" Modal does not contain a dedicated "anchor" field
* [ ] An anchor can be provided in the main URL filed of the "HTML Editor External Link" Modal
* [ ] When editing an existing external link, the anchor part of the URL is loaded into URL field.
* [ ] The Modal for other link type remain unchanged and still offer an anchor field it was available previously.

**Comment by emteknetnz** [comment]
Linked PR has been merged
