### ISSUE TITLE
Possible React replacement for CMS site tree component?

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe/silverstripe-cms#2636]
This looks interesting at least as an inspiration for the future-to-be React version fo the site tree component in the CMS: https://github.com/frontend-collective/react-sortable-tree

**Comment by maxime-rainville** [comment]
There's a more in-depth discussion about this topic on https://github.com/silverstripe/silverstripe-cms/issues/2636

That's probably a better place for that discussion.

**Comment by michalkleiner** [comment]
That loop-redirects back here, do you have the correct issue number you were referring to, @maxime-rainville? Thanks!

**Comment by maxime-rainville** [comment]
Oups ... copy-paste fail :facepalm:

https://github.com/silverstripe/silverstripe-cms/issues/744
