### ISSUE TITLE
BUG VirtualPage creates second canonical tag in MetaTags

### ISSUE THREAD

**Issue by muskie9** [silverstripe/silverstripe-cms#2637]
This cropped up on an SEO report from a client of ours. It seems `VirtualPage` simply appends the `CopyContentFrom` page's relative URL to the `parent::MetaTags()` string value. The parent method seems to have already established the canonical URL value, so appending creates a second tag.

There are a couple options I think as a resolution:
- Confirm whether the `MetaTags` method is needed for `VirtualPage`. If the `parent` call generates the anticipated canonical it may not be needed at all.
- If the canonical from the `parent` method is not correct, replace the existing canonical with the correct canonical generated by the `VirtualPage`.

I'm happy to create a pull request for this issue once it's determined which option (or if other options) is preferred.

**Comment by michalkleiner** [comment]
If the premise is that a virtual page makes appear content of another page under a different URL, then it should update the canonical to the different URL too. But I can see a valid argument for both.

Add a Settings option to make it CMS user-configurable with a default of "Use proxied page's content" as probably originally expected.

**Comment by muskie9** [comment]
I'd agree the canonical should point to the original page. I just found it odd that it's appending a second canonical without trying to scrub the first from the string returned from the parent call.

I double checked the resulting canonical in our instance and it appears the canonical from the parent call is the absolute URL of the Virtual Page. The Virtual Page then appends a relative URL to the `CopyContentFrom` page. So it may be two issues:
1. Generating an additional canonical when it should replace it
2. Should the generated value on a Virtual Page for the canonical be an absolute URL like a normal page

**Comment by muskie9** [comment]
This is semi time sensitive for us, and as mentioned I can provide an initial PR for feedback. Would this be targeted against the 4.7 or 4 branch? I know a release may not occur right away, however we can patch on our side until a release is made knowing a fix would be included.

**Comment by kinglozzer** [comment]
@muskie9 I’ve just tested this on CMS 4.7.1 and I only get one canonical tag. I’m not sure how the parent call would generate a canonical, or why it would need to?

**Comment by lerni** [comment]
VirtualPage does ReadonlyTransformations on fields. As CMS-user I would expect a VirtualPage to show the Canonical-Tag from the linked Page regardless if it points to itself or a different URL.

I use the module linked bellow and I see two canonical tags - probable the module should not set one in case of a VirtualPage or the other way round, VirtualPage should respect it, if there already is one.
https://github.com/DorsetDigital/silverstripe-canonical

If a relative Canonical-Link is a good idea after all is another question. Since the CMS doesn’t know it's own Canonical-Domain it probable is the only choice, but personally I would rather like to see no Canonical-Tag added especially if anything is present already - but haven't even checked which is first.
https://stackoverflow.com/questions/8467938/do-canonical-links-require-a-full-domain

**Comment by kinglozzer** [comment]
I think the best case here would be to update `VirtualPage` so we move the canonical tag generation from `MetaTags()` to the new(er) `MetaComponents()` method. That way, the linked module could at least check for (and remove) the meta tag in its extension hook

**Comment by muskie9** [comment]
@kinglozzer it looks like I completely missed a module we have installed that's generating the canonical for non-Virtual Page types. I'll take a look at the `MetaComponents()` method and work out a PR. We've done quite a bit of meta work lately for a couple projects so it's good to know the newer method exists for our other use cases.

@lerni I don't think we've used that module, but it seems the result is the same for any module that adds a canonical to the Meta Tags. Good to know it's not just our implementation I guess.

**Comment by maxime-rainville** [comment]
@muskie9 Matt said you would like some feedback on which branch to target your PR to. If it's just a bug fixes that can be addressed without adding new APIs, it's perfectly fine to target the PR at `4.7`. 

If it adds new functionality and/or adds new API it's better to target `4`.

If you're not sure, you can start your PR and target it to 4.7. If in the course of peer review, we decide it's not something we want to ship in a patch release, it's quite easy to retarget to `4`.

Does that make sense?

**Comment by muskie9** [comment]
Thanks @maxime-rainville, makes sense. It's mainly moving the meta generation to the `MetaComponents()` method, but I do add a new `$db` value (which I think is less the question). The uncertainty is mainly in shifting from one method to another for generating the meta tag while both are supported API's I guess. So likely 4.7 in this case; I'll PR against that branch and we'll see what happens I guess :slightly_smiling_face:

**Comment by brynwhyman** [comment]
Looks like this was resolved by https://github.com/silverstripe/silverstripe-cms/pull/2647
