### ISSUE TITLE
Broken build - Publish a page behat test

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-cms#2641]
Happens on both GraphQL 3 + GraphQL4 jobs, so probably unrelated to graphql

https://travis-ci.com/github/silverstripe/silverstripe-cms/jobs/490659470

tests/behat/features/publish-a-page.feature:74

Same failure is happening on the admin repo travis build which runs the same cms test

Broken on:
4.6.x-dev, 4.7.x-dev, 4.x-dev

### PRs
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2642

**Comment by maxime-rainville** [comment]
Fixed by #2642
