### ISSUE TITLE
4.7.3 APCu issue

### ISSUE THREAD

**Issue by pine3ree** [silverstripe/silverstripe-cms#2650]
With a fresh composer installation of ss 4.7.3 (php-7.3.x) I get an error (toast message: Service Unavailable) when I visit the `/admin/pages` admin route with APCu enabled (both locally and in my cpanel service provider space). Other admin areas seem to be not affected.

**Comment by dhensby** [comment]
Do you have any specific errors from the PHP logs that could be helpful?

**Comment by pine3ree** [comment]
Hello @dhensby , unfortunately I don't see any error log (neither php log with max error reporting and an active ss notice logger). I only get a 503 response when the apcu extension is loaded. For a short time, switching from "live" to "dev", it started to work normally again, but after a while I experience the same error. For me this is not an issue, since I don't use APCu, I stumble into it accidentally. But  still it seems strange. kind regards.

**Comment by dhensby** [comment]
Ok. Well, I don't think there is much we can do on this one without recreating the environment and I don't think that's a high priority for us.
