### ISSUE TITLE
Broken build - multiple behat failures

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-cms#2657]
--- Failed scenarios:
    tests/behat/features/apply-formatting.feature:12
    tests/behat/features/apply-formatting.feature:20
    tests/behat/features/edit-a-page.feature:18
    tests/behat/features/insert-a-link.feature:16
    tests/behat/features/insert-a-link.feature:29
    tests/behat/features/insert-a-link.feature:46
    tests/behat/features/insert-a-link.feature:63
    tests/behat/features/insert-a-link.feature:75
    tests/behat/features/insert-a-link.feature:89

https://travis-ci.com/github/silverstripe/silverstripe-cms/jobs/504140630

Noting that the same failures were reported for admin - so they're most likely related.

## Notes
- The admin failures are already being investigated in this issue: https://github.com/silverstripe/silverstripe-admin/issues/1198

**Comment by brynwhyman** [comment]
I understand this might look a bit spammy, but raising issues for behat failures (and other failing tests) is very helpful to record the interdependencies of our complex test matrices and then try to manage resolving them!

**Comment by bergice** [comment]
> I understand this might look a bit spammy, but raising issues for behat failures (and other failing tests) is very helpful to record the interdependencies of our complex test matrices and then try to manage resolving them!

A lot of the same errors are also happening on different modules, which also have issues created for them. I would suggest creating an issue for each error, along with links to all failed builds instead of creating issues for all failed builds individually.

**Comment by bergice** [comment]
This is resolved.
