### ISSUE TITLE
RedirectorPage - (4.11) Redirect to file

### ISSUE THREAD

**Issue by Dennisderuijter** [silverstripe/silverstripe-cms#2747]
commit in latest version: [NEW add ability to redirect to a file on the website](https://github.com/silverstripe/silverstripe-cms/pull/2639/commits/ee69d75904b41850ff2786996a9ab9a411a30021)

Added "redirect to file" radio button doesn't toggle the UploadField, field is always visible.
Selector `$('#Form_EditForm_LinkToFileID_Holder')` doesn't respond because the holder id is `#Form_EditForm_LinkToFile_Holder`.

## PRs
- https://github.com/silverstripe/silverstripe-cms/pull/2748

**Comment by kinglozzer** [comment]
Fixed by https://github.com/silverstripe/silverstripe-cms/pull/2748
