### ISSUE TITLE
#Need Docker installation support

### ISSUE THREAD

**Issue by AkshayraviC09YC47** [silverstripe/silverstripe-cms#2751]
Hello maintainer, it would be helpful if we get easy oneclick installation via docker composer, so can you add docker-composer support pls!, thanks😇

**Comment by GuySartorelli** [comment]
Hi,

This isn't something we're intending to explicitly offer at this time. There is [an old blog post](https://www.silverstripe.org/blog/construct-a-better-development-environment-with-docker/) about containerising Silverstripe CMS with Docker which uses [this docker image](https://hub.docker.com/r/brettt89/silverstripe-web/#!) - it looks like that hasn't been updated in a little while but it could be a good starting point for you. A quick [search on docker hub](https://hub.docker.com/search?q=silverstripe) also reveals some other images.

At the end of the day though, it's just a PHP framework that can theoretically be run on your server architecture of choice - you can always set up your own docker compose setup based on the [documented server requirements](https://docs.silverstripe.org/en/4/getting_started/server_requirements/).
