### ISSUE TITLE
Model Admin Pagination Does NOT remember state after edit!!!!

### ISSUE THREAD

**Issue by dajeinc** [silverstripe/silverstripe-cms#2785]
This is an old issue that has been talked about, should have  a relatively simple solution yet remains.

If I browse to a model admin and get a paginated list and then browse to the 3rd page of that list and then click a record to edit:

upon browser back or cms back button the paginated list should render the 3rd page that i came from! 

SilverStripe is one of the best CMS options to sell a client but it makes it extremely hard to sell when simple usability is not there for users. 

What is the solution?

**Comment by GuySartorelli** [comment]
This is resolved by https://github.com/silverstripe/silverstripe-admin/issues/1315 and https://github.com/silverstripe/silverstripe-admin/issues/1314 which will be released in 4.12.0.
