### ISSUE TITLE
Remove legacy tasks

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-cms#2789]
Follow on from https://github.com/silverstripe/silverstripe-framework/issues/10466

The following classes are legacy and should be removed
- [code/Tasks/MigrateSiteTreeLinkingTask](https://github.com/silverstripe/silverstripe-cms/blob/4/code/Tasks/MigrateSiteTreeLinkingTask.php) (supposed to run when upgrading to 4.2.0)
- [code/Tasks/RemoveOrphanedPagesTask](https://github.com/silverstripe/silverstripe-cms/blob/4/code/Tasks/RemoveOrphanedPagesTask.php) (ancient task that extends Controller)
- [code/Tasks/SiteTreeMaintenanceTask](https://github.com/silverstripe/silverstripe-cms/blob/4/code/Tasks/SiteTreeMaintenanceTask.php) (ancient task that extends Controller)

### Acceptance Criteria
- [x] Confirm there is no use for these legacy tasks
- [x] Remove the classes
- [x] Remove associated any tests and yml fixtures
- [x] Updates routes.yml
- [x] Tasks are deprecated in CMS4
 
### PRs
- https://github.com/silverstripe/silverstripe-cms/pull/2818
- https://github.com/silverstripe/silverstripe-cms/pull/2819

**Comment by maxime-rainville** [comment]
All ACs have been met.
