### ISSUE TITLE
CMS 5 Pattern library doesn't work anymore

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-cms#2842]
When upgrading Admin for CMS5 we didn't update the pattern library.

## Acceptance criteria
- Pattern library is updated to work with CMS5
- Storybook is updated to the latest version
- All existing stories are functional.
- All modules using storybook are updated.
- https://silverstripe.github.io/silverstripe-pattern-lib is generated from the CMS5 branches.
- Add a dedicated doc page explaining what the pattern library does and how to use it.

## Notes
- `yarn pattern-lib` to build the the pattern library.
## Related issue
- https://github.com/silverstripe/silverstripe-admin/issues/1516

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1489
- https://github.com/silverstripe/silverstripe-pattern-lib/pull/3
   #### Sabina's PRs
   - https://github.com/silverstripe/silverstripe-admin/pull/1514
   - https://github.com/silverstripe/silverstripe-tagfield/pull/244
   - https://github.com/silverstripe/silverstripe-asset-admin/pull/1361
   - https://github.com/silverstripe/silverstripe-session-manager/pull/145

**Comment by emteknetnz** [comment]
I spent the better part of a day on this, it seems like it's fairly difficult to get this going

Recommend whoever picks this up again (if we even bother) approaches this from a "rebuild" mentality rather than an "upgrade" mentality

**Comment by emteknetnz** [comment]
@sabina-talipova I've merged the PRs you created - there's still this draft PR though - https://github.com/silverstripe/silverstripe-pattern-lib/pull/3

https://github.com/silverstripe/silverstripe-pattern-lib is used to build a static version of the pattern-lib each day which is hosted on a github page at https://silverstripe.github.io/silverstripe-pattern-lib/ - are you happy to ensure this is working as it should?

**Comment by sabina-talipova** [comment]
I have created new ticket to fix 4 spaces indent issue and make additional enhancement.
- https://github.com/silverstripe/recipe-cms/issues/75

**Comment by sabina-talipova** [comment]
All PRs have been merged. Close this issue.
