### ISSUE TITLE
admin jQuery is gone, $SilverStripeNavigator breaks site for authors, devs, etc.

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-cms#2853]
Not sure what to do with this. I'm not a fan of remote script inclusion, as it has knock-on effects with e.g. CORS, etc.
I have [worked around it](https://gist.github.com/NightJar/7d3c0053c89f6fbc6c7de9dccfb32d83) instead, should anyone else want a 'drop in' solution for the time being.

https://github.com/silverstripe/silverstripe-cms/blob/2afad17237080b7335834b2a20bf0164bdeccad4/code/Controllers/ContentController.php#L324

## PR
- https://github.com/silverstripe/silverstripe-cms/pull/2854

**Comment by GuySartorelli** [comment]
Thanks for opening this. It has been in the back of my mind for a while but this has lit a fire under me, PR incoming.
