### ISSUE TITLE
VirtualPage uses hardcoded 'admin' in the edit link

### ISSUE THREAD

**Issue by mirche97** [silverstripe/silverstripe-cms#2881]
VirtualPage uses hardcoded 'admin' in the edit link:

https://github.com/silverstripe/silverstripe-cms/blob/5/code/Model/VirtualPage.php#L249

This breaks if AdminRootController's url_base is changed.

## PRs
- https://github.com/silverstripe/silverstripe-cms/pull/2882
- https://github.com/silverstripe/silverstripe-cms/pull/2888

**Comment by GuySartorelli** [comment]
Hi,

Thanks for reporting that. Would you like to try raising a pull request to fix this bug?

**Comment by mirche97** [comment]
Yes, I have already done it in https://github.com/silverstripe/silverstripe-cms/pull/2882

**Comment by GuySartorelli** [comment]
A fix has been merged and will be automatically tagged by GitHub Actions
