### ISSUE TITLE
CMS 5.1.0-beta1. Regression testing: Broken UI for "URL segment" buttons "OK" and "Cancel"

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-cms#2885]
## Description
Click Edit for Change URL segment results with graphics by OK and Cancel buttons (see attachment)
-https://studio.cucumber.io/projects/301855/test-runs/835224/folder-snapshots/8880145/scenario-snapshots/30498378/test-snapshots/41412650

![screencapture-cmstestm-prod-sites-silverstripe-admin-pages-edit-show-1542-2023-09-11-15_41_15](https://github.com/silverstripe/silverstripe-cms/assets/87288324/9823cd11-e7dc-479b-8f35-b6f8ed8d7152)

## PR
- https://github.com/silverstripe/silverstripe-admin/pull/1581
- https://github.com/silverstripe/silverstripe-cms/pull/2886

**Comment by GuySartorelli** [comment]
Please include the image in a way that it can be viewed on GitHub instead of a private zenhub image,

**Comment by maxime-rainville** [comment]
All done
