### ISSUE TITLE
Cancel draft changes UI component doesn't show up for draft changes on owned models

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-cms#2892]
# Cancel draft changes UI component doesn't show up for draft changes on owned models

Cancel draft changes action is a really useful UI component. Unfortunately, it doesn't work with any owned models such as but not limited to content blocks which arguably is the majority case.

![Screenshot 2023-10-09 at 4 00 18 PM](https://github.com/silverstripe/silverstripe-cms/assets/26395487/d2132dae-f280-4be8-ac2b-e4aab084bcdd)

Tested on CMS `4.13`.

## Thoughts on solution

The only issue with this component is the display condition otherwise the functionality is fine and will work with nested models.

```php
$stagesDiffer = $this->stagesDiffer(); <--- change this to stagesDifferRecursive()


// "rollback"
if ($isOnDraft && $isPublished && $canEdit && $stagesDiffer) {
    $moreOptions->push(
        FormAction::create('rollback', _t(__CLASS__.'.BUTTONCANCELDRAFT', 'Cancel draft changes'))
            ->setDescription(_t(
                'SilverStripe\\CMS\\Model\\SiteTree.BUTTONCANCELDRAFTDESC',
                'Delete your draft and revert to the currently published page'
            ))
            ->addExtraClass('btn-secondary')
    );
}
```

## Related PRs

https://github.com/silverstripe/silverstripe-versioned/pull/328

**Comment by maxime-rainville** [comment]
CLosed in favour of https://github.com/silverstripe/silverstripe-admin/issues/1593
