### ISSUE TITLE
TODO: Should ContentController::LoginForm() return all available log-in forms?

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-cms#2897]
## Description
Check if ContentController::LoginForm() should return just the default log-in form or all available log-in forms(also OpenID...)

See: https://github.com/silverstripe/silverstripe-cms/blob/58a2d5817398cb41cb983e609c879aab73c57f28/code/Controllers/ContentController.php#L306-L307

**Comment by GuySartorelli** [comment]
I think it's fine to just continue with the existing behaviour.
