### ISSUE TITLE
TinyMCE - Adding a link to a page on this site and then clicking through to the immediate child pages takes you down two levels rather than one

### ISSUE THREAD

**Issue by jack-nzl** [silverstripe/silverstripe-cms#2930]
### Module version(s) affected

5.2.0

### Description

When attempting to add a link to a page in the TinyMCE editor and clicking through to the immediate children of a page, if there are multiple levels, it directs to the third level of child pages instead of the second. However, holding down the mouse button when clicking through to the immediate child pages seems to work as expected. 

https://github.com/silverstripe/silverstripe-cms/assets/14326708/db952558-a51b-44dd-b703-92d51dbf6cb9

#### Reproduction steps

Will require that you have a parent page with at least two levels of child pages

1. Go to any TinyMCE content block on the site
2. Select the **Insert link** and then select **Page on this site**
3. Select the **Select a page** dropdown
4. Select the arrow to view a pages child pages, if it has more than one child, then you should be directed to the second level instead of the first level of child pages

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1732
- https://github.com/silverstripe/silverstripe-cms/pull/2931

**Comment by emteknetnz** [comment]
Linked PRs have been merged and will be autotagged shortly
