### ISSUE TITLE
Form field validation/error doesn't highlight the tab where the error occurred

### ISSUE THREAD

**Issue by mark-a-j-adriano** [silverstripe/silverstripe-cms#2944]
### Module version(s) affected

5.2.1

### Description

An EmailField validating the input does not cascade into a Page Error.

<img width="861" alt="Screenshot 2024-05-21 at 10 58 45 AM" src="https://github.com/silverstripe/silverstripe-cms/assets/11882563/143e6974-8142-494f-a024-4efbd98397fc">

As you can see below when the Field is required then it will show a Tab notification icon and a page error on top

<img width="854" alt="Screenshot 2024-05-21 at 10 58 30 AM" src="https://github.com/silverstripe/silverstripe-cms/assets/11882563/f6924563-1265-40f7-a392-2bf7d9cccaab">

More context: https://silverstripe-users.slack.com/archives/CCP2NDQTX/p1716246349181239

AC:
- It would be good if we could cascade Field errors to display like the Page error for consistency and better user experience. (Both errors display differently but we only trigger the `Save` button. )
- OR fix this line as it seems not to correctly validate the fields:  https://github.com/silverstripe/silverstripe-framework/blob/76bdc59cf5c5f6c80c69f205119cce2184ec5881/src/ORM/DataObject.php#L2573

### How to reproduce

```php 
<?php

namespace ThisIsASample\Page;

use Page;
use SilverStripe\Forms\CompositeValidator;
use SilverStripe\Forms\EmailField;
use SilverStripe\Forms\RequiredFields;

class SamplePage extends Page
{
    private static string $table_name = 'Samples';

    private static array $db = [
        'Title' => 'Varchar',
        'Email1'  => 'Varchar',
    ];

    private static bool $show_in_sitetree = true;

    private static bool $can_be_root = true;

    /**
     * Returns a FieldList with which to create the main editing form.
     *
     * @return FieldList
     */
    public function getCMSFields()
    {
        $fields = parent::getCMSFields();

        $fields->addFieldToTab('Root.SampleTab', EmailField::create('Email1'));

        return $fields;
    }

    public function getCMSCompositeValidator(): CompositeValidator
    {
        $validator = parent::getCMSCompositeValidator();
        $validator->addValidator(RequiredFields::create([
            'Email1',
        ]));
        return $validator;
    }
}

```

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-frameworktest/pull/180
- https://github.com/silverstripe/silverstripe-admin/pull/1751

**Comment by GuySartorelli** [comment]
Thanks for raising this. It's definitely a bug.

I'm not sure what you mean by "page error". We have two validation error messages here:
1. `EmailField` form field validation error message - this is a form validation error
2. `RequiredFields` validator error message - this is a form validation error

The only difference I can see between the two with a quick glance is that one uses the "required" message type, and the other uses the "validation" message type - but both should definitely display the same way.

I would expect a "page error" to be one that comes from the `validate()` method on your page. Did you check whether that one indicates the tab or not?

You've raised this against the `silverstripe/silverstripe-cms` repository - does this mean you have confirmed that these both behave/display the same way when editing records in a `GridField` (e.g. in a `ModelAdmin`)?

**Comment by GuySartorelli** [comment]
Turns out the gridfield edit form doesn't have the tab highlight functionality, so this is specific to editing `SiteTree`.
Confirmed that this is only incorrect when using validation from form fields, which for some reason use "validation" as the error type, which isn't technically a valid type (should use one of the consts on `ValidationResult`), but it's been there forever so we can't just change that in a patch.

I'll make a PR with the minimal change required to fix this.
