### ISSUE TITLE
Remove old installer logic from ContentController

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-cms#2958]
We used to have an installer that could be use to set up your environment file via a browser form.

We got rid of that some time ago, but there's bits of logic left in Content Controller to handle that. At first glance, these bits look mildly scary because they are printing out credentials, pinging back some silverstripe domain and deleting files. Glancing at the fine print of the code, I don't think there's any risk. But it's certainly not code we should be keeping around.

I don't think there's anything useful that can be done with this code anyway, so we can probably removed it in CMS 5.

https://github.com/silverstripe/silverstripe-cms/blob/56646af3602c78f7963e459095c9dabe48476470/code/Controllers/ContentController.php#L442-L515

## Acceptance criteria
- `successfullyinstalled` and `deleteinstallfiles` are removed from `ContentController` in CMS6 and deprecated in CMS 5.
- Matching actions and routes are removed.
- Any related unit test are removed.

## CMS 5 PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11275
- https://github.com/silverstripe/silverstripe-cms/pull/2962

## CMS 6 PRs
**NOTE** Don't merge these until the CMS 5 PRs have been merged in and up - this is to ensure we don't get deprecation notices popping up in weird places due to bad mergeups.
- https://github.com/silverstripe/silverstripe-framework/pull/11274
- https://github.com/silverstripe/silverstripe-cms/pull/2961
- https://github.com/silverstripe/silverstripe-siteconfig/pull/166

**Comment by emteknetnz** [comment]
Reassigning to Guy to merge-up and update CMS 6 PRs
