### ISSUE TITLE
PageType Selector does not put current page on top, instead the last items in the array is put on top

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-cms#3005]
### Module version(s) affected

5.2.0

### Description

For the "Page Type" field in the settings tab (main) of a page, the current Page Type is supposed to be on top (see code changed). The code did not actually do that though and instead just placed the "last" entry in the list on top. That does not make any sense so I fixed it.

### How to reproduce

Open any SS website, go to the settings of a page and look at the list of Page Type options. You will see they are in alphabetical order, but the last one (e.g. the one that starts with last letter in the alphabet is listed first). The current page type is supposed to be listed first!

### Possible Solution

see https://github.com/silverstripe/silverstripe-cms/pull/3004

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment]
PR merged.
