### ISSUE TITLE
Missing Deprecation imports

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-cms#3037]
Missing Deprecation import in some classes means CMS 6.0 is not installable

ERROR [Emergency]: Uncaught Error: Class "SilverStripe\CMS\Model\Deprecation" not found

https://github.com/silverstripe/silverstripe-totp-authenticator/actions/runs/12265856242/job/34222842013?pr=180

## Kitchen sink CI
- https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/12266785900

## PR
- https://github.com/silverstripe/silverstripe-cms/pull/3038
- https://github.com/silverstripe/silverstripe-admin/pull/1870

**Comment by GuySartorelli** [comment]
PRs merged
