### ISSUE TITLE
[2011-04-04] File Sync adds Case Sensitive Files as new ones

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#313]
created by: spankmaster79
created at: 2011-04-04
original ticket: http://open.silverstripe.org/ticket/6582

---

Having two files in a folder which have the same name but different character case, causes Silverstripe to delete one of the files from the database first and then adds it back in with a new file ID.

 http://open.silverstripe.org/ticket/71  /sapphire/filesystem/Folder.php 

Name Column in Database should be Varbinary or a case sensitive collation that prevents that.

http://dev.mysql.com/doc/refman/5.0/en/case-sensitivity.html

**Comment by chillu** [comment]
We're no longer supporting file syncing in the asset abstraction layer of 4.x
