### ISSUE TITLE
[2011-05-09] Resized images in the wysiwyg editor are not recreated after doing a /dev/tasks/FlushGeneratedImagesTask

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#318]
created by: gavinbruce
created at: 2011-05-09
original ticket: http://open.silverstripe.org/ticket/6638

---

When using the WYSIWYG editor in the CMS & inserting images and resizing them, they are saved into the _resampled directory with a filename such as assets/Uploads/blogs/Editorial/evokke-magazine-pia-muhlenbeck/_resampled/resizedimage400533-image005.jpg into the appropriate directory. 

This occurs on the saving of a page in the CMS, and the file /sapphire/forms/HtmlEditorField.php handles this in the saveInto function on the lines 105 - 138

However, if you flush the images cache by visiting /dev/tasks/FlushGeneratedImagesTask  these resized images will not be re-created unless you go into the admin and save the page again. 

There should probably be a check to see if the file_exists when loading the page on the front end, and if it doesn't re-create it on the fly.

**Comment by dio5** [comment]
So what happened to this? Still having the issue on a 3.1.6 site, and haven't seen a fix in the changelog for later versions?

**Comment by kinglozzer** [comment]
@dio5 The fix was merged into master, which since then has become 3.2, so the fix will be released in 3.2

**Comment by dio5** [comment]
Ok, awesome thanks.

**Comment by MattyBalaam** [comment]
I have been having this issue on 3.3

**Comment by tractorcow** [comment]
@MattyBalaam please raise a new ticket with your issue on 3.3.
