### ISSUE TITLE
[2011-06-29] iframe becomes self-closed when there's no content

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#323]
created by: dio5
created at: 2011-06-29
original ticket: http://open.silverstripe.org/ticket/6674

---

example: 

When you embed a YouTube-video with an iframe the iframe get stripped of its closing tag and becomes self-closed, which is a problem.

The issue can be worked around by adding in a blank space or some dummy content.

The problem is in HTMLValue.php by using DOMDocument->saveXML(), which makes all the tags that have no content self-closing.

**Comment by chillu** [comment]
The recommended way to embed youtube content in SS 3.x and 4.x is through the "insert media" panel which uses oembed, which will generated valid HTML.
