### ISSUE TITLE
[2011-09-06] roles and permissions confusing in UI

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#328]
created by: nicolaas
created at: 2011-09-06
original ticket: http://open.silverstripe.org/ticket/6709

---

when you add a role to a security group, the permissions are also shown in another tab.  For an  inexperienced user it is very unclear if the roles OR the permissions or BOTH or ???? apply tot this group.  This is important to be clarified, because it is a security issues

**Comment by chillu** [comment]
Stale enhancement suggestion, closing
