### ISSUE TITLE
[2011-09-09] Replace/update Diff.php engine in core

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#330]
created by: @chillu (ischommer)
created at: 2011-09-09
original ticket: http://open.silverstripe.org/ticket/6715

---

Boys and girls, I present to you the epic tale of Diff.php in SilverStripe.

We're using a third party lib Diff.php, and customized it over the years: http://open.silverstripe.org/log/modules/cms/trunk/code/Diff.php
Its original addition was least 4 years ago, before we open sourced. Can't trace it back further unfortunately.

The main motivation for writing this is getting an upgraded and tested
Diff engine into core, but also to resolve a licensing issue: The included file states "You may copy this code freely under the conditions of the GPL." - thats very ambiguous, and has been changed to LGPL in a later version. But in this form, you could argue that we're not allowed to redistribute/modify the library with a BSD license.

The third party code has since evolved as follows:
 * (Since 2004) Text_Diff on Pear: http://pear.php.net/package/Text_Diff/
 * (Since 2009) Text_Diff was then taken over by the Horde project: http://pear.horde.org/ - and has hardwired dependencies like Horde_String in it, so not easy for us to reuse

Alternatives I've found so far:

 * Pretty-Diff (https://github.com/austincheney/Pretty-Diff): JS-only
 * DaisyDiff (Java): http://code.google.com/p/daisydiff/
 * DaisyDiff port to PHP, used by MediaWiki: http://www.mediawiki.org/wiki/Visual_Diff, http://gitorious.org/htmldiff, http://svn.wikimedia.org/svnroot/mediawiki/trunk/phase3/includes/diff/WikiDiff3.php - unfortunately with an incompatible license: GPL v2

Other relevant info:

 * Discussion of DaisyDiff integration in Drupal: http://drupal.org/node/458672
 * Some modified version of Horde's Text_Diff is used in Wordpress: http://core.svn.wordpress.org/trunk/wp-includes/Text/Diff.php
 * http://stackoverflow.com/questions/31722/anyone-have-a-diff-algorithm-for-rendered-html
 * http://stackoverflow.com/questions/4513815/using-a-diff-on-a-document-containing-html

Recommended approach: Find out what changed in the library since we've started using it,
and if our customizations are still necessary. Upgrade to the latest Text_Diff from Pear,
or review how Wordpress got the Horde version to work for their purposes.

**Comment by chillu** [comment]
Closing since its not a high maintenance or high visibility aspect of the framework. Can be looked at as part of a wider review of the way we present content changes, but low value to change in isolation.
