### ISSUE TITLE
[2012-02-19] Broken link tracking doesn't pick up corrupted internal links

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#342]
created by: @sminnee (sminnee)
created at: 2012-02-19
original ticket: http://open.silverstripe.org/ticket/6866

---

The broken links report focuses on identifying internal links that have broken.  However a corrupted `[sitetree_link ...]` code doesn't get picked up and therefore the broken link can get missed.

I would recommend amending the broken link detection (in `HtmlEditorField::saveInto()`) to mark as broken any link that can't be parsed, as well as any external link that resolves to a 404.

Checking external links may need to be something that is optionally enabled, since resolving those links could cause problems in certain configurations.  It would be nice if the resolution of external links could be put into a message queue, but this isn't critical.

**Comment by tractorcow** [comment]
This seems like an enhancement, which may be useful, but hasn't been picked up in some time. Let's close this?
