### ISSUE TITLE
[2012-02-29] More fluid layout for CMS form input elements

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#343]
created by: @chillu (ischommer)
created at: 2012-02-29
original ticket: http://open.silverstripe.org/ticket/6871

---

Currently, form elements in the CMS are set to "width: 100%; max-width: 512px".
Because the width in this case applies to the whole form width (as no containing element overrides it),
the max-width of 512px always applies. Including the label space of ~180px, this
makes for a minimum form width of around 700px - much larger than necessary for most fields.
This is particularly a problem in smaller forms such as the file info on uploaded fields (in UploadField).
- Find a way to have fields shrink to widths around 500px (any lower is not a requirement)
- Investigate "display: table" for this purpose (IE8+ only, so needs some basic IE7 fallbacks)
- Ensure labels still float correctly into multiple lines
- Ensure it works with "full-width" fields that don't have labels
- Ensure it works with more complex fields like chosen.js dropdowns
- Ensure it works with "form.small" and "form.stacked" styles (see _form.scss)
- Bonus points for having the ".stacked" form styles automatically apply for widths lower than 500px

Use the https://github.com/silverstripe-labs/silverstripe-frameworktest module to ensure all combinations of fields work correctly with any style changes.

Remember: The goal is to make field styles easier to customize (e.g. indent+nest field groups visually),
not to add a big pile of CSS to make it pixel perfect. Ideally we end up with less CSS than we have at the moment.

**Comment by chillu** [comment]
Yay, @clarkepaul has done this via bootstrap form styles in 4.x now
