### ISSUE TITLE
[2012-02-29] Better user feedback on faulty Ajax responses

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#344]
created by: @chillu (ischommer)
created at: 2012-02-29
original ticket: http://open.silverstripe.org/ticket/6872

---

Provide better visual feedback on application errors, which can occur by loading a new page/panel,
but also on other user actions, most of them involving Ajax (e.g. reordering tree nodes).

Currently we use the jQuery.notice plugin for this (http://code.google.com/p/jquery-notice/wiki/Implementation). It shows up as a grey box (like the growl plugin for OSX). It doesn't indicate an error well, and is a bit "out of sight" (top right). Those messages are triggered through the global statusMessage() and errorMessage() methods.

We have two "types" of alerts, "good" and "bad". I suggest that we follow
the Twitter Bootstrap conventions here (http://twitter.github.com/bootstrap/components.html#alerts)
and use "error", "success" and "info" instead, each with their own styling.

I suggest that we center the message, fade out after 3 secs, give the user an option to close explicitly.
The fadeout should be disabled if the user hovers over the item, to give him a chance to read the whole text.
The text is usually a handful of words, but particularly in development mode might
be much longer (up to an A4 page of text). 

Note: An easy way to simulate a server error is to add "throw Exception('My exception')'"
in the first line of the show() method in LeftAndMain.php, and try to open a page from admin/pages.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4570
