### ISSUE TITLE
[2012-03-01] Better UploadField disabled/readonly view when no files are selected

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#345]
created by: @chillu (ischommer)
created at: 2012-03-01
original ticket: http://open.silverstripe.org/ticket/6881

---

https://skitch.com/chillu/8gcw3/silverstripe-cms-edit-page

It should show the same white box as with other UploadFields,
and maybe just a label stating "No file selected". Anything that looks less broken, really :)

**Comment by chillu** [comment]
Damian has redone the uploadfield views for 4.x, and it looks a lot better now
