### ISSUE TITLE
[2012-03-01] Disable expansion hints in files tree when node has no children folders

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#346]
created by: @chillu (ischommer)
created at: 2012-03-01
original ticket: http://open.silverstripe.org/ticket/6883

---

It seems to get confused by the fact that the node has children at all, although they're all files.
https://skitch.com/chillu/8gcst/silverstripe-cms-files

**Comment by chillu** [comment]
That's been fixed a loooong time ago
