### ISSUE TITLE
[2012-03-01] TreeDropdownField expand on click (unless it has search)

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#347]
created by: @chillu (ischommer)
created at: 2012-03-01
original ticket: http://open.silverstripe.org/ticket/6884

---

https://skitch.com/chillu/8gcs6/silverstripe-cms-settings

Those are generic improvements, just demonstrated on the "settings" section.
The "remove separator" should only apply to this specific form though.

Ensure that making the whole dropdownfield expand-on-click doesn't disturb
its operation when used with inline search (the area is an input field in this case, and click shouldn't expand).

**Comment by chillu** [comment]
We're redoing the UX of this field completely (based on `react-select`), so while this technically still applies, it's unlikely to get fixed
