### ISSUE TITLE
[2012-03-07] Log CMS preview toggle in HTML5 history

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#351]
created by: @chillu (ischommer)
created at: 2012-03-07
original ticket: http://open.silverstripe.org/ticket/6900

---

With ?cms-preview=1 maybe?.

And ensure it is restored correctly when the user navigates back/forward in history (via ajax handling),
as well as when the user opens the URL itself (non-ajax).

**Comment by chillu** [comment]
I haven't heard any complaints about this since the enhancement was filed - and I kind of disagree with my past self there: It's kind of weird to have a browser back button close the "preview" window.
