### ISSUE TITLE
[2012-03-07] Write form field descriptions for core (dev+UX collaboration)

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#352]
created by: @chillu (ischommer)
created at: 2012-03-07
original ticket: http://open.silverstripe.org/ticket/6903

---

The framework now allows to add a description to each form field, which is separate from its label.
At the moment, this shows up as a built-in browser tooltop, but will be replaced by a questionmark trigger (see  http://open.silverstripe.org/ticket/6898 ).

Go through the core interface and add useful descriptions.
If a field is sufficiently described by its label already, don't bother with a description.

Here's an example for the "Show in search" checkbox (in Page -> Settings):
- Bad: "Show in search results"
- Good: "Show this page as part of search results (only applicable if search is enabled)".

Can be a collaboration between a PM-type role (somebody that worked a lot with clients using the CMS),
and a dev who knows about the actual behaviour of form fields, and can change the fields in PHP.

**Comment by chillu** [comment]
@clarkepaul can pick this up again as part of a wider usability review, but for now I think we're good
