### ISSUE TITLE
[2012-03-07] Don't record HTML5 history event on 4xx or 5xx responses

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#353]
created by: @chillu (ischommer)
created at: 2012-03-07
original ticket: http://open.silverstripe.org/ticket/6906

---

At the moment, the shown URL doesn't match the displayed content (which is still the old one).

**Comment by tractorcow** [comment]
Outdated as html history has been replaced with page.js + react router. Re-raise if this issue re-occurs with the new routing.
