### ISSUE TITLE
[2012-03-08] Allow priority sorting in CMSBatchActionHandler::register()

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#354]
created by: @chillu (ischommer)
created at: 2012-03-08
original ticket: http://open.silverstripe.org/ticket/6909

---

Spun off from https://silverstripe.onjira.com/browse/SSF-59

It already is sorted in the correct order, and you can influence that by the ordering of register() calls already.
We have an issue when a module wants to add actions at a specific position relative to the core actions, but thats kind of theoretical at the moment.

**Comment by chillu** [comment]
It's been a theoretical issue for five years, let's close ;)
