### ISSUE TITLE
[2012-03-09] Add User - Drag and Drop Image - Dropping another image goes to browser

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#362]
created by: lpercy
created at: 2012-03-09
original ticket: http://open.silverstripe.org/ticket/6968

---

'''Description'''

More of a usability issue - but when adding an image to a users profile, it's possible to drag and drop the image in - Unfortunately generally all the browsers default behavior for dropping images onto the content space results in an image being displayed.

So, if a user adds a photo, relises its not the one they wanted initially and attempts to drop another one to replace it, it will show in the browser instead of uploading and attaching to the profile

[[Image(Imagedrop.png)]]

'''Test Scenario'''
''Platform: OSX - Chrome''
1. Visit http://two.ss3.test.silverstripe.com/admin/
2. Select Users
3. Select 'Add User' 
4. Enter a First Name, Last Name and Email
5. Drag and Drop an Image to the AImage box
6. Observe the Image Uploads and attaches to the profile
7. Drag and Drop another image over the same box

Actual Result:

Browser opens the image

Expected Result:

Image should be replaced when another is dropped over it.

**Comment by tractorcow** [comment]
UploadField has now been superseded by react uploadfield.
