### ISSUE TITLE
[2012-03-12] iPad - Actions drop down squashed in interface

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#364]
created by: @smagnusson (smagnusson)
created at: 2012-03-12
original ticket: http://open.silverstripe.org/ticket/6984

---

Actions drop down needs more space in default landscape iPad when filter area open

Vertical iPad orientation not a problem

Screenshot

**Comment by chillu** [comment]
Can't reproduce
