### ISSUE TITLE
[2012-03-12] Tree drag drop broken on iPad

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#365]
created by: @smagnusson (smagnusson)
created at: 2012-03-12
original ticket: http://open.silverstripe.org/ticket/6985

---

On ipad, Drag drop tree sitemap feature scrolls page around and has no affect on the menu

Drag drop in HTML on iPad has long been possible eg http://www.gotproject.com/blog/post2.html

Look to resolve this wherever drag drop is used :)

**Comment by tractorcow** [comment]
Not realistically going to implement ipad support for ss3. Maybe in future ss4 releases?

**Comment by chillu** [comment]
I don't think this issue provides a lot of value at this point. We'll need to look at touch abilities of the CMS UI in a wider sense, with a drag/drop tree being one of many affected areas. Closing for now.
