### ISSUE TITLE
[2012-03-12] Altering iPad orientation must change screen app size

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#366]
created by: @smagnusson (smagnusson)
created at: 2012-03-12
original ticket: http://open.silverstripe.org/ticket/6986

---

Load CMS into horizontal view on iPad; rotate iPad to vertical orientation: CMS is now in a random zoomed in state as shown by attachment

Instead resize app so then width of app takes up width of screen AND do same for height.

Lomg term, responsive design could be used to modIfy widths and layout of various panels; Felipe go nuts!

**Comment by tractorcow** [comment]
Apparenly fixed with https://github.com/silverstripe/silverstripe-framework/pull/244
