### ISSUE TITLE
[2012-03-12] iPad can't edit own CMS user profile in cms

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#367]
created by: @smagnusson (smagnusson)
created at: 2012-03-12
original ticket: http://open.silverstripe.org/ticket/6987

---

Cannot edit own profile in CMS using iPad as there is no downward scroll bar  nor touch drag gesture works, see screenshot

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/244
