### ISSUE TITLE
[2012-03-12] iPad has gross flash of unstyled content (FoUC)

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#369]
created by: @smagnusson (smagnusson)
created at: 2012-03-12
original ticket: http://open.silverstripe.org/ticket/6989

---

When loading CMS you discover for the first time an iPad can display less than himanaty's finest artistic wonders. As in, the partially rendered blobs of SS3, see attached. Looks unprofessional.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/244
