### ISSUE TITLE
[2012-03-12] Select Special Character and table operations in TinyMCE open new tab needlessly on iPad

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#370]
created by: @smagnusson (smagnusson)
created at: 2012-03-12
original ticket: http://open.silverstripe.org/ticket/6991

---

On ipad the insert special character field works functionally but opens new tab

Just make it open popup on existing tab, although it's current plain full screen operation is actually a real treat to use, so don't make the pop up smaller! :) 

 (i.e. the characters are large enough to touch individually).

Note: same goes with other pop ups like insert table, insert row, table cell properties, etc.

**Comment by tractorcow** [comment]
Upgraded to tinymce4 in ss4. Re-open if issue persists.
