### ISSUE TITLE
[2012-03-12] Js prompt when leavingUnsaved  changed user on iPad

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#371]
created by: @smagnusson (smagnusson)
created at: 2012-03-12
original ticket: http://open.silverstripe.org/ticket/6994

---

Open user, change it. Don't save, click to leave screen, blank prompt shows up as attached

**Comment by tractorcow** [comment]
Should be easy to test. Needs confirmation this issue persists.

**Comment by tractorcow** [comment]
Duplicate of https://github.com/silverstripe/silverstripe-cms/issues/383, not specific to ipad.
