### ISSUE TITLE
[2012-03-12] Field labels can't be touched, iPad tree view

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#372]
created by: @smagnusson (smagnusson)
created at: 2012-03-12
original ticket: http://open.silverstripe.org/ticket/6995

---

Field labels "Drsg n drop" and ""multi selection" cannot be touched and force you to touch the field circle icon instead

Safari on mac instead let's you click on field labels so this is an issue between safari iOS and safari osx

**Comment by tractorcow** [comment]
UX has been replaced since this issue was raised. Batch actions UI should be usable, and drag-drop is covered by https://github.com/silverstripe/silverstripe-cms/issues/365.
