### ISSUE TITLE
[2012-03-12] hide tinymce fields that aren't available (e.g. cut copy paste on iPad)

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#373]
created by: @smagnusson (smagnusson)
created at: 2012-03-12
original ticket: http://open.silverstripe.org/ticket/6996

---

TinyMCE functions Cut, Copy, Paste, are not possible to be used on the iPad, and this is also true of other browsers of the desktop variety. This is old school. Rather than falsely advertise their existence to users, hide or grey them out.  (Oh, and it looks silly to tell me to use keyboard shortcuts on a machine without a keyboard. Oh how the times change...)

**Comment by tractorcow** [comment]
Maybe kill this issue; or re-look at it when we improve mobile support.

**Comment by dhensby** [comment]
surely tinymce 4 has better mobile support now. killing
