### ISSUE TITLE
[2012-03-12] History items not touchable on iPad

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#374]
created by: @smagnusson (smagnusson)
created at: 2012-03-12
original ticket: http://open.silverstripe.org/ticket/6998

---

You cannot access the historical pages because they don't react to your touch. (Have tested and you can click them on Safari on MacOSX, this is a iOS Safari novelty)

**Comment by tractorcow** [comment]
It works now! :D
