### ISSUE TITLE
[2012-03-13] File search results - can't see which folder a file is in

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#376]
created by: @ajoneil (aoneil)
created at: 2012-03-13
original ticket: http://open.silverstripe.org/ticket/7005

---

When searching for files in the CMS using the filter on the left hand panel, the results don't show which folder a file is from. A folder or path should be added to the search results.

**Comment by tractorcow** [comment]
To confirm; If this is still necessary in new asset-admin module.

See https://github.com/silverstripe/silverstripe-asset-admin/issues/684

**Comment by tractorcow** [comment]
Closed in https://github.com/silverstripe/silverstripe-asset-admin/issues/684#issuecomment-342371122
