### ISSUE TITLE
[2012-03-15] Empty warning message when navigating away from modified record

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#383]
created by: muzdowski
created at: 2012-03-15
original ticket: http://open.silverstripe.org/ticket/7032

---

How to replicate:
- go to modeladmin-managed section
- open record for editing
- modify any field (checked on TextField and DropdownField)
- try to navigate away with back button in the CMS, or some other link
- the message should pop up with no text in it

**Comment by tractorcow** [comment]
javascript i18n._t() should now fall back to default locale strings if not present in current locale.
