### ISSUE TITLE
[2012-03-15] "archive mode" page view in CMS causes weird tree view

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#386]
created by: @chillu (ischommer)
created at: 2012-03-15
original ticket: http://open.silverstripe.org/ticket/7050

---

Reproduce: Create a page, don't publish it, then delete it from draft. Observe the tree.
Only reproducible if you have a good mix of unpublished, published and deteled from draft pages.

**Comment by tractorcow** [comment]
Seems like a minor ux inconvenience. I might keep this open if the description was something more specific than "weird" and wasn't 5 years old.
