### ISSUE TITLE
[2012-03-26] Edit Profile - Admin name doesn't update after save [Firefox 7.0.1]

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#391]
created by: @jbridson (jbridson)
created at: 2012-03-26
original ticket: http://open.silverstripe.org/ticket/7075

---

When you edit admin name in the edit profile popup and then click save, it does not update in the main CMS navigation. It doesn't change until the page is refreshed. This is confusing as it doesn't give appropriate feedback to the user and seems as though it did not save.

**Comment by chillu** [comment]
I doubt this is going to be fixed until we rewrite the menu to be React based, at which point we hopefully have a canonical client-side representation of a user record which then auto-updates after the profile form is submitted.

**Comment by flamerohr** [comment]
It's not often that you'll rename your profile, so I've marked this as low impact

**Comment by chillu** [comment]
I'll close this, since I can't see it being fixed anytime soon.
