### ISSUE TITLE
[2012-03-27] Only keep actions at bottom if page is scrollable

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#393]
created by: @chillu (ischommer)
created at: 2012-03-27
original ticket: http://open.silverstripe.org/ticket/7080

---

UX suggestion from Felipe, migrated from https://silverstripe.onjira.com/browse/SSF-118
- designs should follow the screenshot
- if the field area is longer than the resolution available the buttons fixed
- positioned over the fields (when that happen the action bar could have a 80% opacity black bg)

**Comment by chillu** [comment]
@clarkepaul Do you think this is still valid? The technical part for layout management is a bit easier now, but I'm not sure if it's still a good idea.

**Comment by clarkepaul** [comment]
na I think we should just keep the actions at the bottom for consistency and ease to maintain. I would like to increase the south toolbar making them more obvious in the near future though. I can understand how he wanted it but I don't see it as high enough priority amongst other things.

Closing issue
