### ISSUE TITLE
[2012-03-27] User CSV import: Fix success message and validation error styling

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#394]
created by: @chillu (ischommer)
created at: 2012-03-27
original ticket: http://open.silverstripe.org/ticket/7082

---

https://skitch.com/chillu/8pu58/silverstripe-cms-users
https://skitch.com/chillu/8pu43/silverstripe-cms-users

**Comment by tractorcow** [comment]
Seems ok to me.

![image](https://cloud.githubusercontent.com/assets/936064/26053003/580037b0-39bb-11e7-8449-a2753c41bafe.png)

![image](https://cloud.githubusercontent.com/assets/936064/26053036/692523e8-39bb-11e7-89ea-e5c8747f161a.png)
