### ISSUE TITLE
[2012-03-27] Reload members list after CSV import in admin/security

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#396]
created by: @chillu (ischommer)
created at: 2012-03-27
original ticket: http://open.silverstripe.org/ticket/7084

---

The GridField listing needs to refresh, as the import is handled through an iframe.

Alternatively, switch the logic to UploadField which can upload files via Ajax,
and has simpler interactions (same DOM tree), but might end up being more work
to hook the actual import into the UploadField.

**Comment by tractorcow** [comment]
Actually this seems fixed in v4.
