### ISSUE TITLE
[2012-04-04] Buttons in CMS are cut off if wrapping into multiple lines

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#401]
created by: @chillu (ischommer)
created at: 2012-04-04
original ticket: http://open.silverstripe.org/ticket/7106

---

The problem here is that the layout calculates the dimensions for the button container _before_ the jQuery button styles are applied, so it gets less height. As that's a completely different entwine selector, its hard to make synchronous enough to apply before the layout calculations.

Marking as critical as it affects pretty much any user viewing the CMS at ~1280px width or less,
in the most prominent place of the CMS.

**Comment by wilr** [comment]
Haven't seen this for 4.0 so far. Flex box may have made this redundant.
