### ISSUE TITLE
[2012-04-11] Change datepicker in Filter side panel to match designs on Github.

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#403]
created by: @jbridson (jbridson)
created at: 2012-04-11
original ticket: http://open.silverstripe.org/ticket/7128

---

At the moment the datepicker appears when you click in the text field. There should be an icon next to the text field which brings up the datepicker and the text field should be for the purpose of typing in a chosen date.

Designs here - https://github.com/silverstripe/silverstripe-design/blob/master/Design/ss3-ui_pages-list-view.jpg

**Comment by chillu** [comment]
Datepickers are native browser UIs in SS4 now
