### ISSUE TITLE
[2012-04-12] Single Node Actions in the Site Tree

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#404]
created by: alexb
created at: 2012-04-12
original ticket: http://open.silverstripe.org/ticket/7134

---

Design is here: https://github.com/silverstripe/silverstripe-design/blob/master/Design/ss3-ui_pages-tree-view-complex.jpg
- Ditch the right-click menu
- Cog wheel icon shown next to tree node on mouse hover
- Clicking on cog-wheel brings up context menu for that tree node
- The menu only shows actions which are allowed on this node
- Menu options / single-node actions can be extended using an API

Do not attempt to modify the jstree to respond to left-clicks. I cannot be done without modifying the core component code. Instead use one of these two jQuery libraries:
http://medialize.github.com/jQuery-contextMenu/demo.html
http://jursza.net/dev/jjmenu/#

Comments from Ingo (Chillu):
The limitation to allowed actions only could get tricky, as it's too performance heavy to perform these checks on the initial tree rendering. We should create CMSBatchActionHandler->handleApplicableActions($pageIDs) similar to the existing handleApplicablePages(), just the other way around. This can be checked through ajax when the context menu is first opened for a specific node.
I would suggest that the "ditch the right click menu" only means "disabling the right click event", but continues to use the actual menu UI component built into jstree. Building our own one is a distraction, and not as easy as it might look (collision control etc).

Comments from Julian:
I had a look at using the JSTree right click menu and turning it into a cogwheel. I spent about a day trying and failing to figure out how to hack the jstree to do that. We can do it if we change the core jstree javascript, but not in an add-on component. The jstree is hard-wired to display the menu only on a right-click. Hacking the jstree core limits our ability to upgrade it in the future, so I wouldn't want to do that. 

I would therefore suggest using a more flexible pop-up menu component that allows trigger with a left click.

**Comment by chillu** [comment]
Closing this, touch support and the tree need a larger look - but this enhancement hasn't been actioned in five years.
