### ISSUE TITLE
[2012-04-16] Files section - Changing users on the same machine remembers the previous users last view

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#408]
created by: rohara
created at: 2012-04-16
original ticket: http://open.silverstripe.org/ticket/7152

---

After a user who has browsed into the Files section logs out and then signs in as another user. The new user is directed to the last viewed section from the previous user when they open the files page.

**Comment by tractorcow** [comment]
Files section has been replaced with react js section which no longer has this behaviour.
