### ISSUE TITLE
[2012-04-18] "Pages" UI: Lazyload tree/list views based on active tab

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#411]
created by: @chillu (ischommer)
created at: 2012-04-18
original ticket: http://open.silverstripe.org/ticket/7175

---

Currently both of them are loaded in the background, which is a bit wasteful,
and also causes clientside processing overhead - particularly if you're using the list view,
which is much more lightweight than the tree view.

Ensure the list/tree views have natural URL endpoints: admin/pages/listview and admin/pages/treeview,
and set the current tab based on that.

**Comment by th3hamm0r** [comment]
This is really a blocker for pages with a large amount of files in their folders.
We just ran into the issue that it exhausted the PHP memory.

As a quick fix we have extended `AssetsAdmin` and replaced `SiteTreeAsUL()` to return an empty string.

(The whole marking-logic is also a reason why we replaced the "Pages" admin with a ModelAdmin!)

**Comment by tractorcow** [comment]
The asset admin section will be addressed in 4.0.

Maybe we could fix the pages section to use paged-list-view instead of trying to pre-load the whole tree.

**Comment by chillu** [comment]
I'm keen to action this soon, because it'll be a major driver for people appreciating the power of the pages list view - I think it's a much better solution for large websites, particularly if you combine it with advanced search filters like taxonomy

**Comment by tractorcow** [comment]
The endpoints aren't both loaded in the background anymore; listview is only loaded when you switch to that tab, and refreshing listview doesn't load the tree until you switch back to it. The original concern of this issue no longer exists, even if the whole pages section could still use some optimisation.

**Comment by chillu** [comment]
Created a follow up ticket: https://github.com/silverstripe/silverstripe-cms/issues/2012
