### ISSUE TITLE
[2012-04-19] iPad: Expand arrow disapears when touched on tree view

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#412]
created by: @clarkepaul (clarkepaul)
created at: 2012-04-19
original ticket: http://open.silverstripe.org/ticket/7177

---

Detected on files area for ipad

**Comment by lukereative** [comment]
Closing as this is no longer an issue (Tested on iPad with iOS 11 in Safari)

**Comment by lukereative** [comment]
Closing as this is no longer an issue (Tested on iPad with iOS 11 in Safari)
