### ISSUE TITLE
[2012-04-19] Ability to arrange files by size

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#413]
created by: @clarkepaul (clarkepaul)
created at: 2012-04-19
original ticket: http://open.silverstripe.org/ticket/7179

---

It seems that arrange files by size is missing or still to come. Raised as part of the usability review by users.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

We've got an SS4 specific issue for this which has more context.
