### ISSUE TITLE
[2012-04-23] Add "show more" trigger on large pages tree nodes

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#414]
created by: @normann (nlou)
created at: 2012-04-23
original ticket: http://open.silverstripe.org/ticket/7198

---

Limit pages tree to showing 20 sub pages if it has more than 20 children, include an item "show all" which switches to list view of the page. This could improve loading performance as well as make the tree view as neat as possible if a page has thousands of child items, like a blog

Design at https://github.com/silverstripe/silverstripe-design/blob/master/Design/ss3-ui_pages-tree-view-simple.jpg

**Comment by chillu** [comment]
We've done this a while ago
