### ISSUE TITLE
[2012-04-26] Move page filters panel from sidebar to top of content area

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#418]
created by: rohara
created at: 2012-04-26
original ticket: http://open.silverstripe.org/ticket/7211

---

== This is to be looked at for v3.1 ==

By moving the filters panel this will create more of a connection between the actual content and what is being filtered. 

Suggest repositioning the filter panel to the top right of the content area where the drag and drop radio buttons were located and create a dropdown or panel to appear above results.

**Comment by wilr** [comment]
Done in 3.3
