### ISSUE TITLE
[2012-04-27] Expand a folder instead of linking in tree-view

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#421]
created by: rohara
created at: 2012-04-27
original ticket: http://open.silverstripe.org/ticket/7224

---

When clicking on a folder name in tree-view. Expand the contents of this instead of linking it to the list-view. This will solve issues with having to select the tiny arrow to open and close the folder.

**Comment by tractorcow** [comment]
Related https://github.com/silverstripe/silverstripe-cms/issues/448

**Comment by chillu** [comment]
We no longer have a tree view in 4.x assets.
