### ISSUE TITLE
[2012-05-01] iPad: Hide keyboard when clicking in "form background"

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#423]
created by: @chillu (ischommer)
created at: 2012-05-01
original ticket: http://open.silverstripe.org/ticket/7254

---

Followup from  http://open.silverstripe.org/ticket/7178 . Listen for click events on all form area that's not a form field, and defocus the current input field (if any). Clicking in "empty space" is a common UI pattern on touch screens. That's not so simple though, as some more complex input fields work with their own DOM structures (e.g. chosen.js), where a click shouldn't defocus.

**Comment by tractorcow** [comment]
To test with 4.0 mobile compatibility; This perhaps may no longer be an issue.

**Comment by lukereative** [comment]
Closing as this no longer seems to be an issue (Tested on iPad and iPhone, SS4, iOS11)
