### ISSUE TITLE
[2012-05-02] CTRL-V on IE8 yields a permission dialog box (TinyMCE)

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#424]
created by: muzdowski
created at: 2012-05-02
original ticket: http://open.silverstripe.org/ticket/7259

---

Pressing ctrl-v to paste content into the TinyMCE throws a dialog box asking for permission every time a new page has been loaded. 

This becomes very annoying during the normal workflow on bigger sites (load page - edit - load page - edit, repeat).

Would be great if we could find a way to alleviate this in SOME way - e.g. at least make the dialog box appear only once per session or something.

**Comment by sminnee** [comment]
Can't reproduce in SS4; assume this has been fixed.
