### ISSUE TITLE
[2012-05-03] Better default location for new pages

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#425]
created by: @sminnee (sminnee)
created at: 2012-05-03
original ticket: http://open.silverstripe.org/ticket/7267

---

Right now, when you add a new page without specifying a place in the tree, it defaults to creating a page at the top-level.  This is probably the least-likely and most-damaging place to set as the default (often templates aren't designed to handle arbitrary inclusion of additional top-level pages very well) and so it's a bad default.  But there's not currently an alternative.

A better solution would be to have a bucket of "unplaced pages" or "uncategorised pages" or "pages not yet in tree" (we'll need to think over the language).  The idea is that you can write a piece of content first, and then later decide where to put it.

We would probably make it impossible to publish an unplaced page.

One place where this is particularly intuitive is when someone who isn't the regular site admin is asked to write content.  They can log in, click "add page", and start typing - much easier!  To look at it another way, page location is an unnecessarily mandatory field.

This might have a few elements:
- Under the hood, we could use ParentID = -1 to distinguish these from pages in the root.
- I'm not sure how you would navigate to these pages.  They could appear in a list below the site tree, for example, which would be fine as long as there was usually only a handful of unplaced pages.
- The page location field would need to have an extra option for selecting this location.
- The page location field might get moved to the Content panel for unplaced pages, so that people knew to update it.

Categorising as a medium enhancement, as it is a bit of a nice to have.  If this ticket is still open 1 year after I post it, feel free to close as a stale enhnacement. ;-)

**Comment by chillu** [comment]
> If this ticket is still open 1 year after I post it, feel free to close as a stale enhnacement.

Does five years count? :D
