### ISSUE TITLE
[2012-05-14] Upload a file directly from the Insert Link box

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#428]
created by: @purplespider (purplespider)
created at: 2012-05-14
original ticket: http://open.silverstripe.org/ticket/7322

---

One of the biggest points of confusion for my clients is the procedure required to insert a link to a new file, as it currently involves leaving the page edit view to go to the File & Images tab and upload the file, and then switch back to the edit page view to add the link, having to then browse or search for the just uploaded file.

To vastly improve this for all users, there should be the ability to upload the file straight from within the Insert Link box. Similar to how users can upload an image from the Insert Image box.

**Comment by purplespider** [comment]
Now in 3.2-beta1. This issue can be closed.
