### ISSUE TITLE
[2012-05-17] Anchors not listed in insert-link dialogue

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#429]
created by: @smagnusson (smagnusson)
created at: 2012-05-17
original ticket: http://open.silverstripe.org/ticket/7338

---

Richtext editor...

If anchors exist on a page, they are supposed to be shown in drop down in the 'create link' dialogue.

They are not, list is blank :-/

**Comment by wilr** [comment]
Anchor exists in 3.3.
