### ISSUE TITLE
[2012-05-18] Sticky :hover on gridfields on iPad

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#433]
created by: @robert-h-curry (rcurry)
created at: 2012-05-18
original ticket: http://open.silverstripe.org/ticket/7348

---

The browser on the iPad tries to be clever in how it applies the :hover pseudoclass. Sometimes it steps on its own tail though, such as this case:
- In the files section, make sure you have at least two folders with two files each.
- Tap on the first folder.
- Before the page loads, you'll see the row get highlighted with a light yellow - this is the :hover style. (this is intended behaviour).
- When the folder's contents load, you'll see that the first file's row is highlighted still, as if it's just been clicked on. '''BUG, WILL ROBINSON, BUG!
- Return to the root of the files section.
- Tap on the second folder, see the highlight again (as intended).
- When the files are loaded, you'll see the second file in the gridfield is now highlighted. '''BUG!

**Comment by tractorcow** [comment]
Since rewriting all of CMS styles in bootstrap, I'm going to close this unless found to re-occur in ss4.
