### ISSUE TITLE
[2012-05-18] One upload function, Two different UIs

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#434]
created by: @smagnusson (smagnusson)
assigned to: @adrexia (adrexia)
created at: 2012-05-18
original ticket: http://open.silverstripe.org/ticket/7352

---

Uploading in files area vs Uploading in Page area has different UI/functionality but should be uniform. Uniformity = intuitive = happy users. (Also, might mean you only have one bit of code doing both things).

One idea would be to have the Files Area use the popup. It doesn't need a full screen interface, and doesn't need the Edit & Organise Vs Add Image items in left hand menu.

E.g. Files says "Uploaded", Pages area doesn't. Files area area has "Edit" at right, Pages has (x) icon.

**Comment by wilr** [comment]
Closing as a bit of legacy. Upload field and the asset admin changes have been vast since.
