### ISSUE TITLE
[2012-05-18] Add confirmation after bulk actions

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#435]
created by: @smagnusson (smagnusson)
created at: 2012-05-18
original ticket: http://open.silverstripe.org/ticket/7358

---

When you perform a bulk action, like publish lots of pages, show a message to say it has been successful. It's useful to know the number of pages affected.

**Comment by tractorcow** [comment]
Pretty sure we've had this for years.

![image](https://user-images.githubusercontent.com/936064/32419486-404c9994-c2df-11e7-8350-34aed11bcd39.png)
