### ISSUE TITLE
[2012-05-20] Batch actions for "Files & Images" (AssetAdmin)

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#438]
created by: @chillu (ischommer)
assigned to: @vanlawrence (clawrence)
created at: 2012-05-20
original ticket: http://open.silverstripe.org/ticket/7367

---

Migrated from https://silverstripe.onjira.com/browse/SSF-119

As a CMS author I want to edit or delete multiple files at once
in order to manage large numbers of files efficiently

Acceptance Criteria:

 * I can select multiple files in the gallery view through shift-clicking
 * I can select multiple files in the gallery view drawing a selection rectangle
 * I can unselect files in the gallery view by shift-clicking on previously selected items
 * I can select multiple files in the tree view through checkboxes
 * I can select multiple files in the list view through checkboxes
 * I can choose an action to apply to those selected files

Notes:

 * Existing design: https://github.com/silverstripe/silverstripe-design/blob/master/Design/ss3-ui_files-manager-gallery-view.jpg
 * The only applicable action will be "delete" for now, and "publish" (versioned files) is not implemented yet
 * The multi-selection logic for the gallery view should be reusable outside of AssetAdmin (and ideally outside of the CMS), at least on a level like $('.my-gallery .item.selected').map(function() {return $(this).data('id');});

**Comment by hafriedlander** [comment]
This is underway in https://github.com/silverstripe/silverstripe-asset-admin
