### ISSUE TITLE
CMS auto-saving

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#446]
created by: @sminnee (sminnee)
created at: 2012-05-29
original ticket: http://open.silverstripe.org/ticket/7411

---

Raised by Sig as a frequent source of pain when using SS3 for a whole day...

Web applications aren't as stable as desktop apps, and when they crash, it's very frustrating if you lose your content.

There are two ways this could be implemented:
- Auto-click the save button.  This has the disadvantage of adding extra network traffic, but prevents multiple copies of content from appearing.  However, given the CMS lacks record locking this could lead to accidental overwrites if multiple people were logged into the CMS with the same page open.  The best way to address that might be with record locking.
- Save content to localStorage.  This limits the extra network traffic and the chance of accidental overwrites, but it does mean that there are now 2 copies of the content, which might get out of sync.  Presumably the best way of addressing this would be to discard local content if the record had be subsequently modified, but that may lead to data-loss.  It would still be helpful for the use case of "the browser crashed and I logged back in".  Unless the glitch that caused you to restart the browser also cleared out local storage.  Bugs in server-side auto-saving would at least let you go back through historical versions.

Although I'd be happy to see either approach, I'd probably go with record-locking + server-side auto-saving.  The fact that we need record-locking to stop it from being horrible makes it a non-trivial change, though.
- Prerequisite:  http://open.silverstripe.org/ticket/7452  (Reducing / eliminating the page refreshes upon saving)

**Comment by tractorcow** [comment]
I like the idea of localstorage persisting unsaved changes; Maybe 5.0 / react cms?

**Comment by unclecheese** [comment]
Digging up this old chestnut, as it's been on my radar lately. Have moved it to [an RFC](https://github.com/silverstripe/silverstripe-framework/issues/7877). Would love everyone's feedback.

**Comment by unclecheese** [comment]
Closing, as migrated to [RFC](https://github.com/silverstripe/silverstripe-framework/issues/7877)
