### ISSUE TITLE
[2012-06-08] Min-width for CMS to avoid ugly UI linebreaks

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#454]
created by: @chillu (ischommer)
created at: 2012-06-08
original ticket: http://open.silverstripe.org/ticket/7435

---

Add a min-width to the CMS panels which ensures we don't have to optimize the layout for extreme small panel sizes, e.g. <~400px for the edit form. 
- Try to minimize the amount of scrollbars required, we already have some in the sidebar panel (e.g. for longer tree node titles), as well as the edit form view.
- Ensure it works consistently with expanded/collapsed menu, and tree/filter sidebar
- Should work on iPad (non-retina) without horizontal scrolling, both in horizontal and vertical orientation (so 768px/1024px width)
- Prepare for usage with side-by-side "edit page" and preview (which means we can't simply add a min-width to the body tag)

This is mainly seen as a way to make it less likely for the breadrumb navigation + tabs to break into two or more lines, see Paul's comments on http://open.silverstripe.org/ticket/6882#comment:13 and  http://open.silverstripe.org/ticket/7412  for side-by-side preview

**Comment by chillu** [comment]
Looks much nicer in 4.x now
