### ISSUE TITLE
Add "edit image" button in TinyMCE on existing images / Fix right click image action

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#455]
# Acceptance Criteria

 * As a content author, I have an obvious way to edit an image inserted into TinyMCE
 * I can get an edit action trigger when selecting the image
 * I see an edit action in the context menu when right clicking on the image
 * Either action triggers opening of the "edit image" dialog
 * This works for both images and media embeds

# Background

created by: @chillu (ischommer)
created at: 2012-06-08
original ticket: http://open.silverstripe.org/ticket/7436

---

Should appear on hover, and when the image is selected. Toggles the dialog overlay.
Hook up the existing "insert/update image" link in the context menu (right click on image) to the same logic, or at least remove it from there. Followup from  http://open.silverstripe.org/ticket/6972 

## Notes

 * Track under ORB-175

## PRs

- [ ] https://github.com/silverstripe/silverstripe-admin/pull/637
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/833
- [ ] https://github.com/silverstripe/silverstripe-cms/pull/2258

**Comment by tractorcow** [comment]
This seems to be an enhancement suggestion that was never implemented. With the upgrade to tinymce 4 we could re-visit this.

@clarkepaul do you have any feeling on how relevant this is still?

**Comment by chillu** [comment]
I think given how frequently images are edited in the rich text area of the CMS, this is old yet a critical enhancement - re-adding label.

**Comment by clarkepaul** [comment]
Yup, I think this is one of those things which is going to provide a lot of benefits for the amount of work needed to add the feature. Added a 4.0 milestone to issue but I'll leave it with @chillu as to whether this makes a beta milestone. I will come up with a mockup prior to development.

**Comment by newleeland** [comment]
Hey @chillu I've created a prototype to a possible solution, 
Essentially, When an image is clicked/selected, an "edit" icon on the top right appears, which, when clicked, will opens the image edit modal that slides down from the top.

Prototype: https://invis.io/PBBX712X5#/236147876_Edit_Image

**Comment by clarkepaul** [comment]
Two things we should consider is showing the icon on hover (as well as when it's selected).
The icon covers the drag handle so perhaps it makes sense to have the link outside the image box far top right (like a tab).

**Comment by newleeland** [comment]
Looking at vanilla TinyMCE, there is an "Edit image" button that appears adjacent to the image when the image is pressed. Maybe we should use this instead or creating our own edit image functionality.  There is an example on https://www.tinymce.com/ Homepage hero. 
![screen shot 2017-07-25 at 2 31 08 pm](https://user-images.githubusercontent.com/8085295/28553093-f532a452-7145-11e7-8146-784c7959aa10.png)

Also note, that the hamburger button (FAR RIGHT) leads to "image settings" that we would use, and the EDIT button (2ND FROM RIGHT) leads editing the image (cropping, contrast, colour levels).

Obviously we don't have all the other features, so it would look more like this:
![screen shot 2017-07-25 at 2 34 22 pm](https://user-images.githubusercontent.com/8085295/28553199-8813feba-7146-11e7-840e-99ef10c38954.png)

**Comment by chillu** [comment]
I really want this feature, but it's less important than finishing the campaign UX flows - removing milestone. 

@newleeland regarding the image tools from the TinyMCE demo, I'm not sure that'll give us too much of an advantage - it seems like there's very few configuration options: https://www.tinymce.com/docs/plugins/imagetools/. We'd just reuse the hover trigger, not the actual editing screen (that's a separate and more complex issue).

**Comment by clarkepaul** [comment]
We have our own custom tooltip so perhaps we could re-use that. 
![image](https://user-images.githubusercontent.com/555033/30790592-3ebfa55e-a209-11e7-9728-298e42c30bf1.png)

**Comment by clarkepaul** [comment]
I'd like us to use the TinyMCE dropdown if possible and reuse their icons so it looks like it has the same sizing etc as what they have (if we didn't want those styles/icons then we should override them altogether—probably not priority in the near future though).

**Comment by chillu** [comment]
I like the inline view from Jared's designs better (button in top right corner), since it doesn't obscure content below the image. But I'm easy either way, whatever is the quickest to implement.

**Comment by clarkepaul** [comment]
Ah yeah forgot about that design, that was my initial design. Would be good to get an idea of the effort for the different approaches. The earlier design works best as a hover but would need to work on selection as well were-as the built in TinyMCE approach is upon selection of the image.

**Comment by maxime-rainville** [comment]
Might I humbly suggest we look at https://github.com/silverstripe/silverstripe-assets/issues/131 simultaneously?

There's not much point making it easier for people to edit existing image, if we blast existing values.

**Comment by clarkepaul** [comment]
Talked to @lukereative and it looks like the default TinyMCE editor image popover is best to use, its handy to have image alignment options in the mix which looks like it will also work well.

**Comment by lukereative** [comment]
The edit action is just named 'Image' – because Tinymce uses the same action to create as it does edit (and there isn't a nice way of contextually changing the label)

They use the same action as the buttons in the toolbar so I don't think we need tests for that.

**Comment by chillu** [comment]
Can you please provide a video demo of how this works (trigger via icon, trigger via context menu), for PO-level signoff?
