### ISSUE TITLE
[2012-06-08] "Insert from web" (oEmbed): Validation, progress and failure indicator, fix alignment

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#456]
created by: @chillu (ischommer)
created at: 2012-06-08
original ticket: http://open.silverstripe.org/ticket/7437

---
- Validate URL format, and show validation error if failing
- Show failure notification if URL can't be resolved (currently only done as generic CMS growl overlay, too easy to miss)
- When adding a URL, the viewfile action takes a couple of seconds to complete, since its calling an external service. Add a spinner next to the URL text field.
- Expand view of loaded file info automatically, there's no point in leaving it collapsed
- Move "plus" icon into same line as URL text field
- Clear out URL field after successful insertion, to more clearly communicate that multiple inserts can take place

**Comment by hafriedlander** [comment]
Some of these are still valid, but some aren't

Still valid:
- URL needs validating
- Failure badly handled
- Expended view by default *
- Plus icon placement is weird *
- URL text could be cleared after insertion *

No longer valid:
- Spinner is present

New:
- On failure, spinner remains spinning

* means optional (I'd be happy with just fixing the new issue and maybe adding some simple client side validation). @clarkepaul What do you feel about default collapsed / open info box after insertion?

**Comment by clarkepaul** [comment]
I'm fine with it being collapsed, you can also add multiple items. This whole thing hasn't been implemented to a design, although I think there is a few CSS fixes which would be good on top of what has been mentioned earlier.

Random space at top of modal
Alignment of "Add url" action
Toggle down arrow needs a line-height of 16px applied
Random divider lines could be removed
![pasted_image_3_05_16__4_26_pm](https://cloud.githubusercontent.com/assets/555033/14974702/767af114-114c-11e6-8bdd-9d9805d99960.png)

**Comment by clarkepaul** [comment]
This has already been implemented, should be fixed by https://github.com/silverstripe/silverstripe-framework/issues/6480
