### ISSUE TITLE
[2012-06-08] "Insert from web" (oEmbed): Add description about supported services

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#457]
created by: @chillu (ischommer)
created at: 2012-06-08
original ticket: http://open.silverstripe.org/ticket/7439

---

In the "insert image" dialog, there's currently only an empty URL field. Not very friendly or descriptive, given how much magic happens behind the scenes (and how powerful that feature is).
- Add one sentence as intro ("Insert images, video and audio directly by pasting their link. We'll try to auto-detect how to embed them. For images, simply paste the URL". That's crap wording, needs work.
- List supported services in a smaller font by extracting the domains from OEmbed::get_providers(), without protocol to keep it short. Example. "Supported services: flickr.com, vimeo.com, ..."

**Comment by tractorcow** [comment]
This entire interface has been redeveloped.

![image](https://user-images.githubusercontent.com/936064/32419521-122084b2-c2e0-11e7-8f36-4e60eaaa9208.png)

More or less addresses the above concerns.
