### ISSUE TITLE
[2012-06-08] "Insert media": Thumbnail and "file info" alignment

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#458]
created by: @chillu (ischommer)
created at: 2012-06-08
original ticket: http://open.silverstripe.org/ticket/7440

---

https://skitch.com/chillu/891s7/silverstripe-edit-page

Move "file info" box up to consistently flow next to the thumbnail, not underneath it (more efficient space usage). Ensure that's the case with long filenames as well. Ensure it works both on inserting and updating images as well as "insert from web". Ensure it doesn't break the main file view in admin/assets, should share as much CSS as possible (same problem there effectively)

**Comment by wilr** [comment]
Closing as this is no longer valid with asset-admin
