### ISSUE TITLE
[2012-06-08] "Insert from web": oEmbed takes small thumbnail as image, rather than main URL

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#460]
created by: @chillu (ischommer)
created at: 2012-06-08
original ticket: http://open.silverstripe.org/ticket/7442

---

That's OK for video embeds like youtube, since the thumbnail is 300px wide and only shown in the editor.
But not for flickr URLs, where thumbnails are 75x75, and the inserted image is the actual representation of what's on the website. Use the "url" rather than "thumbnail_url" property retrieved through oEmbed.

**Comment by tractorcow** [comment]
new embed library solves this issue.
