### ISSUE TITLE
[2012-06-08] "Insert media" Show [embed] shortcode when no oEmbed thumbnail is available

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#461]
created by: @chillu (ischommer)
created at: 2012-06-08
original ticket: http://open.silverstripe.org/ticket/7443

---

E.g. for Twitter, uses off-scaled default image which looks ... broken.
https://skitch.com/chillu/89unj/silverstripe-edit-page

**Comment by tractorcow** [comment]
Doesn't seem to be an issue anymore; UX allows user to customise the embedded media before insert. It's not perfect but the original concern seems addressed.
