### ISSUE TITLE
[2012-06-13] Reduce or eliminate refreshing upon page save.

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#463]
created by: @smagnusson (smagnusson)
created at: 2012-06-13
original ticket: http://open.silverstripe.org/ticket/7452

---

Saving or Publishing a page causes a interruptive refresh of the editor. Look at ways to reduce or eliminate such refreshes.

Interim solution as example;
1. Don't refresh page when the only change has been to a rich text editor. This is a very common time to click save. Potentially, you could still refresh the page if need-be when Publishing the page.

It might still be acceptable to refresh page when changing the page type  (but perhaps do the refresh immediately rather than at the next save.), and perhaps when the value of a field affects whether another field should be shown or hidden.

This could be considered a prerequisite for autosaving  silverstripe/silverstripe-cms#446  and would make side by side editing nicer  http://open.silverstripe.org/ticket/7412

**Comment by tractorcow** [comment]
Superseded by our move from entwine to react based forms, which take responsibility for front-end form rendering.
