### ISSUE TITLE
[2012-06-14] history.html4.js doesn't respect existing hashes on load

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#468]
created by: @chillu (ischommer)
created at: 2012-06-14
original ticket: http://open.silverstripe.org/ticket/7464

---

Open admin/pages/#admin/pages/edit/show/1 in IE. This should load the admin tree view, but then load in the edit form of record  http://open.silverstripe.org/ticket/1  via ajax.

**Comment by wilr** [comment]
CMS using native window.history for 4.0
