### ISSUE TITLE
[2012-06-14] Unclear that a folder was added in AssetAdmin

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#469]
created by: @halkyon (sharvey)
created at: 2012-06-14
original ticket: http://open.silverstripe.org/ticket/7465

---

In 2.4, when a folder was created, you get redirected to the folder so you can start adding files in there.

In 3.0, the folder is created and no redirection occurs. However the user isn't told that a new folder was created.

Maybe we could add some sort of notification 'Folder "blah" created in "Uploads"' or something, like when you've saved a ModelAdmin record?

**Comment by wilr** [comment]
4.0 new asset admin has a better UI for this.
