### ISSUE TITLE
[2012-06-15] Icons and grouping of batch actions

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#472]
created by: @chillu (ischommer)
created at: 2012-06-15
original ticket: http://open.silverstripe.org/ticket/7484

---

Migrated from https://silverstripe.onjira.com/browse/SSF-114
See designs at https://github.com/silverstripe/silverstripe-design/blob/master/Design/ss3-ui_dialogs.jpg
Ideally can be achieved with standard Chosen.js means (no custom overlay necessary)

**Comment by wilr** [comment]
Fixed in 3.3 for grouping in a dropdown.
