### ISSUE TITLE
[2012-06-18] Internal Server Errors when trying to upload images

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#475]
created by: neilcreagh
created at: 2012-06-18
original ticket: http://open.silverstripe.org/ticket/7500

---

Problem exists when adding an image to content as well as uploading an image in the 'Files' area. 

In both cases the progress bar completes but then there is an internal server error:

GET http://www.fuel.ie/SS3/admin/assets/add/getEditForm/field/AssetUploadField/item/7/
500 (Internal Server Error)

Note: I had one warning when setting up: Running PHP 5.3 instead of 5.4 - but I don't think this is related to that.?

If you click to 'Edit' the file that has just been uploaded:
Clicking 'edit' on the uploaded image results in:

[User Notice] Sorry, your PCRE extension does not support UTF8 which is needed for the I18N core
GET /SS3/admin/pages/EditorToolbar/MediaForm/field/AssetUploadField/item/5/edit

Line 769 in /var/www/vhosts/fuel.ie/httpdocs/SS3/framework/thirdparty/Zend/Locale/Format.php

Source

760      \* Parse date and split in named array fields
761      *
762      \* @param   string  $date     Date string to parse
763      \* @param   array   $options  Options: format_type, fix_date, locale, date_format. See {@link setOptions()} for details.
764      \* @return  array             Possible array members: day, month, year, hour, minute, second, fixed, format
765      */
766     private static function _parseDate($date, $options)
767     {
768         if (!self::_getUniCodeSupport()) {
769             trigger_error("Sorry, your PCRE extension does not support UTF8 which is needed for the I18N core", E_USER_NOTICE);
770         }
771 
772         $options = self::_checkOptions($options) + self::$_options;
773         $test = array('h', 'H', 'm', 's', 'y', 'Y', 'M', 'd', 'D', 'E', 'S', 'l', 'B', 'I',
774                        'X', 'r', 'U', 'G', 'w', 'e', 'a', 'A', 'Z', 'z', 'v');
775 
Trace

**Comment by tractorcow** [comment]
Super out dated as we've replaced i18n with php-intl and symfony.
