### ISSUE TITLE
[2012-06-28] Folder class should use DataObjects to create & delete File records

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#488]
created by: Jules
created at: 2012-06-28
original ticket: http://open.silverstripe.org/ticket/7582

---

It's not possible to effectively use the File object's onBeforeWrite & OnBeforeDelete hooks with Files & Images (/admin/assets).  AssetAdmin creates & deletes File records by calling methods of the Folder class which execute SQL, bypassing DataObjects.

e.g. in sapphire/filesystem/Folder.php, Folder::syncChildren has...
DB::query("DELETE FROM \"File\" WHERE \"ID\" = $unwantedDbChild->ID");
...where it should have...
$unwantedDbChild->delete();

Folder::constructChild also uses an SQL insert.

The same code is in all versions I checked from 2.4.4 to 3.0.0-rc3.

I came across this problem investigating why the Lucene search index is not updated when documents are added & removed.  If this change was made, new documents would be indexed immdiately & automatically.  The Lucene plugin documentation recommends scheduling a task to update the entire index, presumably nightly for large document archives.

There are many other good reasons to hook into file management e.g:  automatically optimise high res images uploaded from users' digital cameras, keep track of disk quotas, for security/moderation reasons.  None are possible because the hooks aren't called.

Please change the code in keeping with SilverStripe's principle of extendability.

Thanks,
Jules

**Comment by wilr** [comment]
File system in 4.0 has been overhauled.
