### ISSUE TITLE
[2012-07-02] Filter options lack some real-world use cases

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#491]
created by: @smagnusson (smagnusson)
created at: 2012-07-02
original ticket: http://open.silverstripe.org/ticket/7605

---

Page filter lacks some real-world options people need, and there's a minor issue with an existing field;
1. Date field doesn't have a popup calendar nor any sort of date validation it seems.
2. Add new column "Pages underneath" -> and show a Site Tree. This filters to pages only within a certain area of the tree. Important when using with Listview.
3. "Edited by" (Drop down/auto complete? of authors). Reveals a list of pages edited by someone (preferably looks up version table), top option should be "Me (Sigurd Magnusson") to make finding yourself easy.

**Comment by GuySartorelli** [comment]
Closing as this is super old, may not be relevant anymore and even if it is we're not going to do it any time soon
