### ISSUE TITLE
[2012-07-04] AssetAdmin: File breadcrumb doesn't update when changing folder

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#495]
created by: @chillu (ischommer)
created at: 2012-07-04
original ticket: http://open.silverstripe.org/ticket/7619

---

We need to set the "current record" in AssetAdmin when the folder ID changes on a record.
In addition, we should modify AssetAdmin->getList() to return only files in the folder set through "current record" to avoid this inconsistency in the first place.

To reproduce:

 - Upload file.jpg into folder1
 - Edit file.jpg (correct breadcrumbs: "folder1 => file.jpg")
 - select 'folder2' from the dropdown. 
 - Save  (wrong breadcrumbs: "folder1 => file.jpg")

**Comment by wilr** [comment]
Figure 4.0 will fix this related issue.
