### ISSUE TITLE
[2012-07-05] TinyMCE font styles/format preview broken

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#497]
created by: @smagnusson (smagnusson)
created at: 2012-07-05
original ticket: http://open.silverstripe.org/ticket/7622

---

TinyMCE is supposed to show the actual styles of Styles and Formats in the dropdown. We've disabled that setting for some reason and should activate it. It's so much easier to choose a style when you can see the options before having to click them all...

http://www.tinymce.com/tryit/full.php shows you the expected style preview in the DropDown-- see screenshot.

**Comment by tractorcow** [comment]
Seems to work in 4.0.
