### ISSUE TITLE
[2012-07-05] TinyMCE - enable ordered list variations

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#498]
created by: @smagnusson (smagnusson)
created at: 2012-07-05
original ticket: http://open.silverstripe.org/ticket/7623

---

TinyMCE supports a user selecting different types of ordered list options - see screenshot.

We've not enabled this; do so.

Demo is this working: http://www.tinymce.com/tryit/full.php

(Note: There is also an option to enable UNordered list options but I don't think this is useful; it merely changes the visual style of the bullets and I believe that this style is best set by a designer setting the typography for a website. So, my suggestion is to keep the UNordered list style dropdown disabled, like we have currently.)

**Comment by tractorcow** [comment]
@clarkepaul can you make a call on whether we need this? At the moment we have this:

![image](https://user-images.githubusercontent.com/936064/32419772-898e6150-c2e4-11e7-84e0-f0efcfb6b122.png)

But this ticket wants us to switch to this:

![image](https://user-images.githubusercontent.com/936064/32419783-b41fbca2-c2e4-11e7-997f-c7cebdda9a62.png)

My personal preference is the simpler one, but I could understand if someone wants a more complex form. :)

**Comment by clarkepaul** [comment]
Feels like an extension for TinyMCE. Do we have any TinyMCE extensions available that are plug-n-play or is TinyMCE easy enough to configure out of the box?

**Comment by tractorcow** [comment]
It's out of the box, we would just have to set the config array to the latter option.

**Comment by clarkepaul** [comment]
I mean, isn't this easy enough for dev's to customise for their clients if they want the feature? I don't think its needed out of the box for all CMS installations.

**Comment by tractorcow** [comment]
Fair enough!
