### ISSUE TITLE
[2012-07-05] Session timeout breaks CMS interface (logged out due to inactivity)

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#499]
created by: @smagnusson (smagnusson)
created at: 2012-07-05
original ticket: http://open.silverstripe.org/ticket/7625

---

A frustrating session timeout occurs if you leave the CMS for a period of time (not sure exactly how long, perhaps an hour) and you have NOT ticked the "[ } Remember me next time?" button.

The consequence is the interface is left in a dead, unresponsive frozen fashion, with no prompts. You have to close or refresh the browser window to fix. This will of course lose any unsaved work, and your place in the CMS where you were.

Solution: When the session has timeout, automatically darken the screen, and show a popup to log back in. Use ajax, don't redirect elsewhere. This ensures the user's session can be restored, and the interface can happily continue to used precisely where the user last left.

See screenshot.

**Comment by wilr** [comment]
Damian's session logout popup should fix this interface dead. If it's not working as per designed a new ticket should be opened up with more specific information.
