### ISSUE TITLE
[2012-07-09] Ensure Title and Navigation don't disappear on larger tables

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#501]
created by: @vanlawrence (clawrence)
created at: 2012-07-09
original ticket: http://open.silverstripe.org/ticket/7639

---

When displaying larger tables of data, ensure that you can always see the navigation, either by having a sticky bottom navigation and sticky titles on the top, or by limiting row counts.

---

Was: Sticky Title and Navigation

When displaying larger tables of data, it would be useful to have a sticky bottom navigation and sticky titles on the top.

**Comment by tractorcow** [comment]
CMS forms seem to scroll already, leaving the left and top navigation intact, as well as action buttons.
