### ISSUE TITLE
[2012-07-09] Filter Panel should refresh the data with AJAX rather than pageload.

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#502]
created by: @vanlawrence (clawrence)
created at: 2012-07-09
original ticket: http://open.silverstripe.org/ticket/7640

---

When using the filter panel, data on the right hand side is reloaded using a pageload.  Using Ajax would be more contemporary.

**Comment by bergice** [comment]
Closing as resolved/irrelevant.
