### ISSUE TITLE
[2012-07-10] Retain pages list view state (pagination, filters) when returning from detail view

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#503]
created by: @chillu (ischommer)
created at: 2012-07-10
original ticket: http://open.silverstripe.org/ticket/7642

---

Followup from  http://open.silverstripe.org/ticket/7589 

The pages list view loses its state when navigating into a page detail view, and then going back
via browser back button. This is due to the information being stored in GridState in the PHP session,
associated to the field by a unique ID. 

Same problem for ModelAdmin (originally described in  http://open.silverstripe.org/ticket/7416 )

There's four different ways we can persist this information. None of them are great.
@Hamish/Stig: Could use some feedback here :)

== Cookies ==

Any state is view specific, so at the least tied to the URL.
This pretty much disqualifies cookie storage, since we'd need to keep too much information.
To illustrate this, if you edit 50 pages in the course of a session (each with a GridField),
you'd have around a 1000 key/value pairs from GridFields.

== URL GET parameter or HTML5 history state ==

URL storage is not as easy as it sounds: The HTML5 History API
forces us to reload a URL via ajax unconditionally.
Take a pagination request for GridField (paraphrased)
POST admin/pages/edit/show/2/field/MyGridField State=<id>&action=next_page
This loads the table only, and advances the current page in the PHP session.
If we push this to the history stack, and a user navigates back to this page later on,
it should load the full CMS view instead of the field, and _not_ advance the current page.
There's history.replaceState(), but it still triggers a reload with the same problems.
Same goes for pushing to the history state object, rather than URL GET parameters.

== HTML5 sessionStorage ==

HTML5 sessionStorage is a more heavy duty replacement for cookies, so still clientside.
So we'd need to wait for the GridField to render, then look up its state ID,
and request the view with this stored state. Not ideal.

== PHP session ==

Still would need to be keyed to the currently viewed URL,
but we can initiate the GridField with the current state automatically without a refresh.
This is not the cleanest solution, but most attractive in terms of loading performance.

## Related

 - [x] https://github.com/silverstripe/silverstripe-cms/issues/632
 - [x] https://github.com/silverstripe/silverstripe-framework/issues/9380

**Comment by sminnee** [comment]
Confirmed still a problem in ss4

**Comment by xini** [comment]
Any chance this gets looked at some time soon?

**Comment by chillu** [comment]
I doubt we'll get around to this before moving GridField into a React component, where that behaviour will be easier to attain (more state managed on the client). If you want to have a crack at it, start with `GridFieldEditButton->getColumnContent()` which renders the link. Form submissions will make this a bit tricky, you might need to implement `BackURL` there.

**Comment by xini** [comment]
Thanks, @chillu.

**Comment by GuySartorelli** [comment]
This was resolved in https://github.com/silverstripe/silverstripe-admin/issues/1314
