### ISSUE TITLE
[2012-07-12] Alignment of validation errors in CMS

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#505]
created by: @chillu (ischommer)
created at: 2012-07-12
original ticket: http://open.silverstripe.org/ticket/7654

---

See https://skitch.com/chillu/egmrg/silverstripe-edit-page

- Align the message with the field itself.
- Ensure that it works well on all field types (date fields with separate D/M/Y, dropdowns, radiobuttons)
- Use https://github.com/silverstripe-labs/silverstripe-frameworktest to test the field variations
- Ensure it works when using the "stacked" class on form (rendering labels above fields rather than aside)
- Ensure the message doesn't overlap into the field, there's some input + padding weirdness, it seems.

An easy way to activate validation in the CMS is by adding this to the Page class,
which will mark the "Navigation Title" field as required.

```
function getCMSValidator() {
		return new RequiredFields('MenuTitle');
	}
```

**Comment by wilr** [comment]
Validation errors have been tided up with 3.3 and I assume 4.0 will tidy it up again so closing.
