### ISSUE TITLE
[2012-07-12] Insert Image from CMS gridfield filter styling is broken and should be below the sortable header

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#506]
created by: @jbridson (jbridson)
created at: 2012-07-12
original ticket: http://open.silverstripe.org/ticket/7657

---

When inserting an image "from the CMS" the gridfield filter styling is broken. The clear filter button drops below the magnifying glass. Also the entire filter row should sit below the sortable header like in the - settings "users" gridfield (see screenshot). 

Came about after http://open.silverstripe.org/ticket/7603 was fixed.

**Comment by sminnee** [comment]
This has been rewritten in ss4; this bug is no longer relevant.
