### ISSUE TITLE
[2012-07-13] Adding a page drops your filter

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#508]
created by: @smagnusson (smagnusson)
created at: 2012-07-13
original ticket: http://open.silverstripe.org/ticket/7667

---

Two ways to re-produce. (No not referring to sex and artificial insemination.)
1. In Pages view of CMS: Set up a filter, e.g. "About" as page title, showing a filter of one result.
2. Click a page to edit it. Now click [Add New]; once you get to the page editing of your new page you'll see your filter has gone.
   --or--
3. Click [Add New] while still on the large site tree. Once you get to the page editing of your new page you'll see your filter has gone.

Solution: The page filter should remain. It should be tested with both listview and tree view. It may cause the new page to not be visible in the filtered results. (And due to technical complexlity I wonder if it would show up in the filter even if it does match, or if only begins to match after you've made changes and saved the page. That can be another ticket )

Rationale: Large sites with thousands of pages could work slowly/poorly when the tree reverts, and besides, you're losing a filter the user has worked hard to set up ;)

**Comment by sminnee** [comment]
Confirmed still a problem in ss4

**Comment by sminnee** [comment]
In 4.3 or later this has been rendered irrelevant by the UI – the search results are no longer shown in the tree. Closing this issue.
