### ISSUE TITLE
[2012-07-18] Use $('.cms-tree').updateNode() in batch actions

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#511]
created by: @chillu (ischommer)
created at: 2012-07-18
original ticket: http://open.silverstripe.org/ticket/7679

---

Currently, batch actions reflect their state changes in the tree via a JSON map with three elements: "modified", "deleted" and "error". The "modified" data only contains a new tree title (including flags). Depending on the batch action performed, that might not be sufficient. For example, a batch action might change the page type, which influences the page icon (outside of the tree title). It also doesn't reflect changes to the sorting or page hierarchy.

Use the new updateNode() logic to process the full state of the node,
see https://github.com/silverstripe/sapphire/pull/650#issuecomment-7057211

**Comment by GuySartorelli** [comment]
This is super old and we haven't done anything with it - that's not going to change any time soon so closing.
