### ISSUE TITLE
[2012-07-18] File admin: after edit folder name renders CMS unresponsive

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#512]
created by: micschk
created at: 2012-07-18
original ticket: http://open.silverstripe.org/ticket/7680

---

After changing the name of a directory in the File admin area, on clicking save the CMS returns all tabs in one and becomes unresponsive to further clicks. (refresh required)

**Comment by sminnee** [comment]
The rewrite of assets in SS4 has dealt to this.
