### ISSUE TITLE
[2012-07-19] TreeMultiselectField Positioning after scroll

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#514]
created by: @frankmullenger (frankmullenger)
created at: 2012-07-19
original ticket: http://open.silverstripe.org/ticket/7683

---

The TreeMultiselectField dropdown in the CMS seems to position itself according to where the field was originally positioned on the page on load. 

So if you scroll the cms-content-fields div, the dropdown does not take the scroll into consideration when positioning the dropdown on the page.

The result is a gap between the field and the dropdown values div corresponding to the amount the cms-content-fields div has been scrolled.

This might effect TreeDropDownField too.

**Comment by sminnee** [comment]
Seems to work in ss4
