### ISSUE TITLE
[2012-07-19] Scrollbar on sitetree pushes buttons together

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#515]
created by: @frankmullenger (frankmullenger)
created at: 2012-07-19
original ticket: http://open.silverstripe.org/ticket/7684

---

When the site tree is long enough to generate a vertical scroll bar on the cms-content-tools div (the sitetree displayed when editing a page) - the buttons for "Add new" and "Edit tree" are pushed together and overlap.

This occurs for me in:

*Mac 10.6:
- Chrome 20.0.1132.57
- Firefox 13.0.1
- Safari 5.1.7

Windows 7:
- IE 9
- IE 8 (via IETester)
- IE 7 (via IETester)

**Comment by sminnee** [comment]
Not a problem in ss4.
