### ISSUE TITLE
[2012-07-25] It should be possible for TreeDropdownField to be part of a composite field

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#517]
created by: @drzax (drzax)
created at: 2012-07-25
original ticket: http://open.silverstripe.org/ticket/7703

---

The TreeDropdownField fails when included as part of a composite field because the field name of the actual dropdown doesn't match the name of the field on the model.

It turns out there's actually a fairly simple javascript fix for this, but the route cause should be addressed.

var $tree = $this.find('.TreeDropdownField');
$tree.data('urlTree', $tree.data('urlTree').replace('[PageID]',''));

**Comment by chillu** [comment]
That's fixed now by virtue of moving the field into a React-based implementation
