### ISSUE TITLE
[2012-07-26] HTMLEditorField can't be nested inside a ToggleCompositeField

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#518]
created by: @drzax (drzax)
created at: 2012-07-26
original ticket: http://open.silverstripe.org/ticket/7705

---

Attempting this results in TinyMCE being displayed with the ToggleCompositeField title as content within the editor.

**Comment by lukereative** [comment]
Closing as this does not affect SS4, and SS3 is now in security only support.
