### ISSUE TITLE
[2012-08-10] Date validation on Swedish install not working

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#530]
created by: kewngen
created at: 2012-08-10
original ticket: http://open.silverstripe.org/ticket/7775

---

Was running through the tutorials on a Swedish install and created a datefield in the NewsPage with "showcalendar". When I tried to save the page after picking a date in the calendar I got a validation error, about the formatting of the date.

**Comment by flamerohr** [comment]
Closing, date handling have been through a few revisions since 3.0
