### ISSUE TITLE
[2012-08-24] HTMLEditorField tiny mce isn't initializing in front end forms

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#538]
created by: jonshutt
created at: 2012-08-24
original ticket: http://open.silverstripe.org/ticket/7811

---

adding an HTMLEditorField to a form in the front end gets the tiny mce javascript files included, but it's not initialising. 

If i add the init stuff manually to the page it works:
"<script type="text/javascript">  tinyMCE.init({ ...."

**Comment by tkiehne** [comment]
For those arriving here that use SS 4.x, things work a little differently.  Using an HtmlEditorField on the frontend will still generate and load the required TinyMCE configs, but won't init the editor. The official docs regarding adding the Modals didn't cut it for me (and I'm not usign the file or link browsers on the frontend anyway), but I was able to get a frontend TinyMCE instance to initialize using this Requirements call:

`Requirements::customScript("(function(){ $('textarea.htmleditor').each(function(){  var conf =  $.parseJSON($(this).attr('data-config'));  conf.selector = '#' + $(this).attr('id');  tinyMCE.init(conf); });})();");`

Plays well with the Extension interface if you have a situation where you have to alter a form in a module.
