### ISSUE TITLE
[CORE] [2012-09-07] Windows: Installer reports rewrite doesn't work post-install, but it actually does

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#546]
created by: @halkyon (sharvey)
created at: 2012-09-07
original ticket: http://open.silverstripe.org/ticket/7846

---

Might be something that checks the rewrite response "OK" in install.php5

**Comment by sminnee** [comment]
I believe that this is enough of an edge-case that we can close as wontfix or assume that it's been fixed.
