### ISSUE TITLE
[2012-09-20] Pushing Enter on a TextField triggers Unpublish behaviour

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#552]
created by: elliot.sawyer
created at: 2012-09-20
original ticket: http://open.silverstripe.org/ticket/7890

---

We've discovered an issue where if a CMS user presses the Enter key on a TextField input, it will submit the form. Since the first button is Unpublish, the page will be unpublished. If the user does it again on a Draft, the draft will be removed. 

To reproduce this behaviour on the Demo site.
1. Login as an admin at http://ss3.demo.silverstripe.org.
2. Find the BasicFields page in the SiteTree and open it for editing
3. Open Numeric tab
4. Click any of the text input fields
5. Press Enter.

**Comment by sminnee** [comment]
Confirmed that it saves draft in ss4, which is in keeping with HTML UI norms and is reasonably benign if done accidentally, so considering it bug-fixed. If we wanted to change the behaviour (e.g. do nothing or skip to next field) I'd want justification for that to come from user testing.
