### ISSUE TITLE
[2012-09-27] Prevent CMS popup dialogues with scrollbars from rendering scrollbars beneath the draggable icon

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#558]
created by: rmichell
created at: 2012-09-27
original ticket: http://open.silverstripe.org/ticket/7910

---

All CMS popups display a scrollbar to the right when content overflows the fixed height of the popup along with a draggable icon to the bottom-right to expand the popup's size.

A very minor point, but the scrollbar runs beneath the semi-transparent drag icon. This obviously differs from the behaviour being replicated - that of installable desktop computer software and their window-drag behaviour.

Solution would be to either render the drag icon as non-transparent or to render the icon on a separate <div> below the main content-area which implements the scrollbar so the scrollbar never runs beneath.

**Comment by lukereative** [comment]
Closing as this does not affect SS4, and SS3 is now in security only support.
