### ISSUE TITLE
[2012-10-01] Anchor links are producing deprecated html

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#560]
created by: @adrexia (adrexia)
created at: 2012-10-01
original ticket: http://open.silverstripe.org/ticket/7919

---

The name value of the a tag has been deprecated since xhtml (and is invalid html5), but the CMS uses this to produce anchors. The standard way of producing anchors is to assign an id to an attribute already on the page and link to that.

**Comment by wilr** [comment]
TinyMCE updated in 4.0

**Comment by adrexia** [comment]
👍
