### ISSUE TITLE
[2012-10-11] Edit view of page loses "modified" tags on tree

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#563]
created by: @halkyon (sharvey)
created at: 2012-10-11
original ticket: http://open.silverstripe.org/ticket/7939

---

Going to "admin/pages/" shows a tree, which has tags of "new" and "modified" next to tree items, correctly displayed.

However, when you go into the edit view for a page, e.g. "admin/pages/edit/show/1" the tree to the left loses all the "modified" and "new" tags, *unless* you hover over the tree nodes individually, in which case they appear then disappear after unhovering.

**Comment by jonom** [comment]
This has been fixed for 3.2 but don't think it will ever make it down to 3.1 so suggest this is closed.

**Comment by dhensby** [comment]
Agreed
