### ISSUE TITLE
[2012-10-19] Improve ways to add a folder to the files area

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#568]
created by: @clarkepaul (clarkepaul)
created at: 2012-10-19
original ticket: http://open.silverstripe.org/ticket/7957

---

[https://www.evernote.com/shard/s24/sh/c166cd91-cd1c-46d5-88b0-7e35538f57ea/1496fb5d7c200a6909369fea0451a4c9]

There should be a more consistent way of adding a folder to the files area

**Comment by clarkepaul** [comment]
Closing as no longer relevant with the new insert file modal
