### ISSUE TITLE
[2012-10-25] Assets Gridfield edit folder, opens the folder

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#571]
created by: @adrexia (adrexia)
created at: 2012-10-25
original ticket: http://open.silverstripe.org/ticket/7971

---

Clicking the edit icon on a folder within gridfield (ie AssetAdmin) should allow you to edit the details of the folder. Current behaviour is just to open the folder.

http://www.evernote.com/shard/s210/sh/1fe1e2a0-58f8-419d-88fd-f5e2e7c7c944/f13adeedefbecf4207427e396e8c9455

**Comment by chillu** [comment]
We've completely rewriting AssetAdmin in 4.x (see https://github.com/silverstripe/silverstripe-asset-admin), so won't fix this 3.x issue - see https://github.com/silverstripe/silverstripe-cms/pull/1590 for more context.
