### ISSUE TITLE
[2012-11-02] Can't remove fields or tabs from custom RedirectorPage

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#579]
created by: socks
created at: 2012-11-02
original ticket: http://open.silverstripe.org/ticket/7992

---

If I extend RedirectorPage, I'm not able to remove tabs or fields that I've created via removeByName or removeFieldsFromTab.

I am able to remove default fields.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-cms/pull/1822
