### ISSUE TITLE
[2012-11-05] AssetAdmin broken on Folder change

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#582]
created by: blu42media
created at: 2012-11-05
original ticket: http://open.silverstripe.org/ticket/8000

---

The only way to move a file between folders in the CMS is by editing its assigned folder.  However, after attempting to change the folder and pressing save, the page refreshes and the layout becomes broken.  It might be nice to either go back to the old folder so more files could be moved.

Bringing something into play like KickAssets would be super sweet ... but fixing the item above would be quite nice to keep things tidy.

**Comment by chillu** [comment]
We've completely rewriting AssetAdmin in 4.x (see https://github.com/silverstripe/silverstripe-asset-admin), so won't fix this 3.x issue - see https://github.com/silverstripe/silverstripe-cms/pull/1590 for more context.
