### ISSUE TITLE
[2012-11-07] Make tree keyboard accessible

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#584]
created by: @chillu (ischommer)
created at: 2012-11-07
original ticket: http://open.silverstripe.org/ticket/8004

---
- [X] Show focus rings, so the user gets a visual indicator what's currently selected.
- [ ] Allow toggle of subnodes, ideally without focusing an extra element, but through keyboard shortcuts.

We _could_ do this through the "hotkeys" plugin for jstree (http://www.jstree.com/documentation/hotkeys),
but would have to review the library behind it first: https://github.com/jeresig/jquery.hotkeys/.
Its two years old, and has a dozen pull requests outstanding, so pretty much abandoned.
Some of these requests seem important, e.g. avoid keyboard listeners on password fields.
Also need to figure out if its compatible with newer jQuery versions.

**Comment by bergice** [comment]
Partially complete. Still need to be able to open/close nodes.

**Comment by GuySartorelli** [comment]
This is super old and hasn't been touched. If we have an accessibility epic in the future this will likely be reopened (or recreated) but in the meantime I'm closing it.
