### ISSUE TITLE
[2012-11-08] Cannot delete page if required CMS field is not filled in

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#586]
created by: Friksel
created at: 2012-11-08
original ticket: http://open.silverstripe.org/ticket/8009

---

Cannot delete a page if a required CMS field (with getCMSValidator) is not filled in. It's impossible to delete the page, because the CMS field that's not filled in has changed to read only....

Error message that appears on the topright after clicking 'delete' says 'Validation error'.

Restoring the page doesn't work either and throws the same error message.

Silverstripe 3.0.3-rc1

**Comment by robby-nzta** [comment]
Is there any progress with this?

**Comment by kinglozzer** [comment]
@robby-nzta I think https://github.com/silverstripe/silverstripe-cms/pull/863 was supposed to resolve this (amongst other issues) but it looks like I may have missed the `unpublish` action. Is this issue occurring when attempting to unpublish?

**Comment by robby-nzta** [comment]
Thanks, Yes, this is working on Page type. 
After reading through my case, the validation is used  RequiredFields. 
So finally, I should write custom validation for my case. 

I have two action doUnpublish and doDelete should bypass validation in my requirement.

Cheers

**Comment by patricknelson** [comment]
If it helps anyone else:

It appears that this is resolved for me by taking into account @kinglozzer's fix above for #863 with one tiny little change: Adding `delete` action. 

**My particular situation** (which may vary from others): This occurs when, for example, I create a new page type that does have validation of any sort, but immediately decide that I want to delete that accidental creation. Adding the `delete` action in there solves this for me. Thankfully this is safely (and well) exposed via the `->setValidationExemptActions()` and `->getValidationExemptActions()` duo on `CMSForm`.

**Comment by patricknelson** [comment]
By the way, I should share my actual solution (duh): I'm easily able to work around this without modifying any core code via an `Extension` of `CMSForm` using the `->updateEditForm()` method in my extension. For example:


```php
class CMSMainExtension extends DataExtension {

	/**
	 * Update actions to disable validation so that we don't get validation errors when
	 * deleting things that have validation since, of course, they don't need it.
	 *
	 * @param Form $form
	 */
	public function updateEditForm(Form $form) {
		if ($form instanceof CMSForm) {
			$actions = array_merge($form->getValidationExemptActions(), ['delete']);
			$form->setValidationExemptActions($actions);
		}
	}

}
```

Logically you'd need to register the extension as well, like in your `config.yml`:

```yml
CMSMain:
  extensions:
    - CMSMainExtension
```

**Comment by patricknelson** [comment]
Setup PR #1287 to address this directly.

**Comment by dhensby** [comment]
assuming this was fixed in https://github.com/silverstripe/silverstripe-cms/pull/1297

**Comment by patricknelson** [comment]
Yep, it was.
