### ISSUE TITLE
[2012-11-23] Top CMS filter/add/batch actions refactoring

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#594]
created by: muzdowski
assigned to: muzdowski
created at: 2012-11-23
original ticket: http://open.silverstripe.org/ticket/8043

---

Rearrange and unify the actions available on the Edit Tree screen, and in the sidebar of the Edit Form in Pages section. Actions in both cases will be the same, slightly restyled to fit in the sidebar.

Designs:

-https://github.com/silverstripe/silverstripe-design/blob/master/Design/Page%20options%20dropdown-15.png
-https://github.com/silverstripe/silverstripe-design/blob/master/Design/Page-options-dropdown-16.png

Discussion: https://groups.google.com/forum/?fromgroups=#!topic/silverstripe-dev/3u2IGWzvJoM

**Comment by wilr** [comment]
This has pretty much been implemented or customised in 3.3

**Comment by chillu** [comment]
Agreed, it's as good as its going to get for now. A shortcut for "add page" without leaving the UI would be nice, but that's been a stale enhancement for four years now. Closing
