### ISSUE TITLE
[2012-12-11] BEHAT: Create a feature file and script for Gridfield pagination in Asset Admin

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#610]
created by: @jbridson (jbridson)
created at: 2012-12-11
original ticket: http://open.silverstripe.org/ticket/8087

---

As an Content Editor I would like to be able to page through a list of folders and files in the "Files" section in the CMS.

Acceptance Criteria:
- I can log in as a "Content Editor" or "Administrator"
- I can click on "Files" in the left navigation 
- I can see a list of files and folders in the root 
- I can only see files/folders that are in the current folder 
- Files/folders in subfolders are not visible unless I drill down 
- If there are more than 15 folders or files I can see the pagination 
- I can navigate to the next pages to see the remaining files/folders 
- I can navigate back to the previous pages 
- I can see how many files there are total and where I am incontext 
- Sorting should not change when paging through files/folders 

```
  Scenario: I can view multiple pages of files/folders in the Asset Admin section
    Given I am logged into the CMS either as a "Content Editor" or as an "Administrator" 
    And I go to /admin/assets
    And I have more than 15 files or folders in my Asset Admin root folder 
    Then I should see the pagination at the bottom of the table 
    And I should be able to navigate to the next page 
    And I should be able to navigate back to the previous page 
    And I should be able to navigate to the last page 
    And I should be able to navigate back to the first page 
    And I should be able to type in what I page I want to go to and hit enter to navigate to that page

```

**Comment by sminnee** [comment]
Obsolete.
