### ISSUE TITLE
[2012-12-11] Add history.js support to side-by-side

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#611]
created by: muzdowski
created at: 2012-12-11
original ticket: http://open.silverstripe.org/ticket/8090

---

Currently the side-by-side preview feature does not play well (or rather at all) with the history.js as used by other parts of the CMS.

From Ingo at https://github.com/silverstripe/sapphire/pull/966#discussion_r2329148:
"All form elements should be contained in a form, which at least supports the basic feature on submission. In this case, it would mean redirecting to a URL with the correct preview GET params set, which in turn means toggling the initial layout based on those GET params (and ideally history.js support). Not required for now, just thought its worth pointing out, since its a basic CMS design principle."

**Comment by lukereative** [comment]
Closing as history preview works in SS4.
