### ISSUE TITLE
[2012-12-11] UI enhancement for split mode of side-by-side previews

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#612]
created by: muzdowski
created at: 2012-12-11
original ticket: http://open.silverstripe.org/ticket/8091

---

Handle the situation when we are in split mode but the display falls back to content mode because of lack of space. 

The user could become confused by the fact the split mode is enabled, but the preview does not appear. Add some kind of a visual feedback to show that the system acknowledges the option selection, but hasn't got enough space to show the preview.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4587
