### ISSUE TITLE
[2012-12-11] Side-by-side allow configurability of the column sizes

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#613]
created by: muzdowski
created at: 2012-12-11
original ticket: http://open.silverstripe.org/ticket/8094

---

Improve the API by allowing consumer developers to configure the threeColumnCompressor algorithm options easily (see https://github.com/silverstripe/sapphire/blob/master/docs/en/reference/layout.md#layout-options).

For example they should be able to set the minPreviewWidth to a larger number, which currently assumes that the site is responsive and shows nicely in 400px.

**Comment by GuySartorelli** [comment]
Great idea but it's a super old issue that we're not going to do anything with any time soon. Closing.
