### ISSUE TITLE
[2012-12-18] Batch actions - Deleting a published page from Draft and then publishing it causes it to be blank

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#624]
created by: @jbridson (jbridson)
created at: 2012-12-18
original ticket: http://open.silverstripe.org/ticket/8137

---

[Chrome version 23.0.1271.101]
- Take a published page and select it using the multiselect on /admin/pages
- Delete it from the draft site
- Then select it again using multiselect
- Now publish it (even though technically it is already published)
- The page name will disappear as if it has been wiped. 
- If you try and click on the blank page it tries to take you to the edit page screen but will revert to the home page. 

I know there is validation that Felipe did designs for, and that has yet to be implemented, but certainly a page which is already published should not be allowed to be published again (especially in this case where it breaks the page completely).

See screenshot

**Comment by kinglozzer** [comment]
“Remove from draft” doesn’t exist anymore. I’ve played around with the batch actions and I can’t recreate anything like this with the remaining actions
