### ISSUE TITLE
[2012-12-18] BEHAT: Create a feature file and script for Batch Actions Multi Select

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#625]
created by: @jbridson (jbridson)
created at: 2012-12-18
original ticket: http://open.silverstripe.org/ticket/8138

---

BEHAT: Create a feature file and script for Batch Actions on page tree

As an administrator I want top be able to edit multiple pages at once using Batch Actions

Acceptance Criteria:
1. I can access "Pages"
2. I can access the "Page tree"
3. I can toggle "multiselect"
4. I can select multiple pages
5. I can perform batch actions on selected pages

https://gist.github.com/a75e55062b78c1af63f4

For definitions of the difference between "Un-publish" and "Delete from published site" see ticket

http://open.silverstripe.org/ticket/6924

**Comment by chillu** [comment]
There's lots of features which aren't Behat tests, I don't think tracking our guilty conscience through enhancement tickets is going to change that :D
