### ISSUE TITLE
[2012-12-19] Image $has_one allowing multiple when attached from files

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#629]
created by: @axllent (axllent)
created at: 2012-12-19
original ticket: http://open.silverstripe.org/ticket/8145

---

There seems to be an issue (bug?) when using the $has_one for an Image in the CMS. When a new image "'''from your computer'''" is added it allows only one (as it should), however when an image is selected "'''from files'''", a new image dialogue is created under the added image.

It seems similar to http://open.silverstripe.org/ticket/7903, however I think that issue was fixed as it seemed to relate to all added images I believe.

I've also tried adapting the code below with $upload->setConfig('allowedMaxFileNumber', 1); which made no difference either.

```
    static $has_one = array(
        'Image' => 'Image'
    );

    public function getCMSFields() {
        $fields = parent::getCMSFields();
        $fields->removeByName('MenuTitle');
        $fields->addFieldToTab("Root.Main", new UploadField('Image', 'Lesson Image'), 'Content');
        return $fields;
    }
```

**Comment by kinglozzer** [comment]
Can’t recreate this in 3.5.3, or in 4.0.0-alpha7
