### ISSUE TITLE
[2012-12-24] delete options need to be simplified

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#631]
created by: nicolaas
created at: 2012-12-24
original ticket: http://open.silverstripe.org/ticket/8157

---

Hi

I am listing this enhancement as critical, because it has been "bugging" me for so long and it is just soooooooooooo confusing to a simple user. 

It should be fairly easy to implement and it will be a much needed improvement. 

I am happy to help with this. If the concept is approved then I will create a patch. 

See attachment for details.

**Comment by clyonsEIS** [comment]
Bump, this got me today.  An unsuspecting content author chose 'delete from draft', assuming it would also unpublish.  They were left with a problematic page, live in Production, with no way to reach it in the CMS to edit or unpublish.  

The only recourse afaict is to manually insert the record into SiteTree, or manually remove from SiteTree_Live.  Is there a plan for this?

**Comment by clarkepaul** [comment]
Well good news is that this is being worked on as we speak. The team will provide an update soon.

**Comment by dhensby** [comment]
This was fixed in 3.3 :) #1203
