### ISSUE TITLE
[2013-01-10] UploadField with a many_many doesn't correctly initialise files for display in the CMS

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#635]
created by: @nyeholt (marcus)
assigned to: @nyeholt (marcus)
created at: 2013-01-10
original ticket: http://open.silverstripe.org/ticket/8177

---

Code example on http://stackoverflow.com/questions/12977231/silverstripe-3-multiple-uploadfield-issue

The getItems() method only ->customise()s the file objects if $this->items is null or empty, which means that a many_many relationship with existing files is never customised.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
