### ISSUE TITLE
[2013-01-16] Form validation breaks ModelAdmin on save

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#637]
created by: @markguinn (markguinn)
created at: 2013-01-16
original ticket: http://open.silverstripe.org/ticket/8192

---

In ModelAdmin, if I create a new record and enter invalid data into a form field, the layout of the page breaks. In my case it was adding a comma to a NumericField that triggered it. If you drop the attached TestModel and TestAdmin classes into a bare 3.1.x-dev installation you'll be able to reproduce. 

If you enter anything invalid in that numeric field, the layout get messed up (see screenshot attached). The following javascript error is triggered: "Uncaught Error: cannot call methods on tabs prior to initialization; attempted to call method 'select' " which I traced to framework/admin/javascript/LeftAndMain.EditForm.js line 95. If you comment out that line everything works fine.

**Comment by sminnee** [comment]
This has been fixed in ss4.
