### ISSUE TITLE
[2013-01-19] the model admin search form (filter form) is not wide enough and the resulting horizontal scroll-bar can not be accessed.

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#638]
created by: nicolaas
created at: 2013-01-19
original ticket: http://open.silverstripe.org/ticket/8203

---

the model admin search form (filter form) is not wide enough and the resulting horizontal scroll-bar can not be accessed.

**Comment by sminnee** [comment]
Redesign in ss4 addresses this nicely.
