### ISSUE TITLE
[CORE] [2013-01-24] WAMP Issues after finishing installation

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#640]
created by: @arnhoe (ARNHOE)
created at: 2013-01-24
original ticket: http://open.silverstripe.org/ticket/8216

---

There is a problem when finshing the installation on a WAMP Server. All the requirements are a pass, mod_rewrite are on. Basically SilverStripe works perfect expect for this part.

As soon as the installation is busy with configuring, so making the _config.php, friendly urls and testing, they are all a pass. Then you will get redirected to, http://mysite.com/home/successfullyinstalled?flush=1 after that the page will go to "Fout 101 (net::ERR_CONNECTION_RESET): De verbinding is opnieuw ingesteld.".

I tried to reach that url in multiple ways, but it simply just gives a not found page.

**Comment by sminnee** [comment]
From the linked ticket:

> I think an interesting observation, I tested the new VPS - Windows 2014 R2, IIS, yesterday. Installation SS 3.1.8 with no problems.

I don't see us improving this any more, closing the ticket.
