### ISSUE TITLE
[2013-01-31] "Insert link to" dialog usability issues

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#643]
created by: @jbridson (jbridson)
created at: 2013-01-31
original ticket: http://open.silverstripe.org/ticket/8229

---

[Chrome version 24.0.1312.56 and IE version 10.0.9200.16384] 

This ticket stems from a previous ticket from 3.0.0 beta2 - http://open.silverstripe.org/ticket/7288

These are the issues:
- "Page on this site" - Giving the user the option to link to an anchor when linking to a page is a confusing extra step most users would not need to preform unless they actually request adding a link to an anchor. It currently looks like you should fill the anchor field in when creating a link to a page. Maybe this could be solved by adding another link option which is "anchor on another page".
- "anchor on this page" - Checkbox for "open link in a new window?" should not be visible as it doesn't make sense for this to a default for an anchor on this page. It makes sense to have this option for "anchor on another page" (currently not an option - see bullet above)
- "another website" - The default seems to be to open the link in a new tab/window regardless of whether the "open link in a new window?" is checked. Either remove this default functionality or default the checkbox to be checked to match how it functions - then the user can uncheck it if they don't want this to happen.

**Comment by chillu** [comment]
Looks like this will be fixed with Paul's redesign of the panel (https://github.com/silverstripe/silverstripe-framework/issues/5947), so closing this issue
