### ISSUE TITLE
[2013-02-19] Security Controller doesn't call onAfterInit

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#655]
created by: mtils
created at: 2013-02-19
original ticket: http://open.silverstripe.org/ticket/8267

---

I try to build a mobile login-area. This is not possible because MobileSiteControllerExtension hooks into onAfterInit.
In Security.php in every public controller method a custom Controller is created via Page_Controller::create() (Line 354)
onAfterInit is called in Controller::handleRequest().
Controller::handleRequest() is never called in Security in this manual creation of an second Controller so its impossible to hook into the mobile theme.

**Comment by tractorcow** [comment]
Fixed with making init() protected, and wrapping with doInit() which enforces before/init/after
