### ISSUE TITLE
[2013-02-20] Pages that a user doesnt have permission to create, can't be reordered

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#657]
created by: @dhensby (Pigeon)
created at: 2013-02-20
original ticket: http://open.silverstripe.org/ticket/8271

---

At the moment, if a user fails the 'canCreate' function, then they are unable to reposition the page within the sitetree with the CMS drag & drop.

It seems that 'disallowedChildren' hints in the HTML includes classes that can't be created and this is stopping the pages being re-ordered or re-arranged

This is an issue for me because the canCreate() dictates pages that can only have one instance in the sitetree at a time. So pages that should only appear once then can't be created again. These pages can't be re-ordered because canCreate returns false.

Really, canEdit should be used to check for reordering in the CMS.

**Comment by purplespider** [comment]
Has there been any further progress with this?

**Comment by nfauchelle** [comment]
@purplespider 
I put in a pull request 1125 but there is a minor regression where the 'create page' option shows in the menu even if you don't have permission to do it - hasn't effected me or the sites I've been done and have been using my change.

I do plan on doing a more complete fix 'soon'.

**Comment by oldirony** [comment]
Any news about this?

**Comment by giovdk21** [comment]
Hello,
we're having this problem also with the 3.3.0-rc2

thanks

**Comment by tractorcow** [comment]
Tested in 3.x and master branches and it seems to no longer be an issue. I can re-order pages with canCreate() false.

**Comment by purplespider** [comment]
I've just reproduced this issue in both 4.0.0-alpha7 and 4.0.0-master.
````
<?php

use SilverStripe\CMS\Model\SiteTree;

class MyPage extends SiteTree
{
	private static $db = array(
	);

	private static $has_one = array(
	);
	
	function canCreate($member = null, $context = array()) {
		return false;
	}
}
````
Simply adding the canCreate and refreshing the CMS, means CMS users cannot drag and drop pages of this type.

**Comment by tractorcow** [comment]
That's odd, that's exactly what I used to test. I wonder what I missed?

**Comment by pine3ree** [comment]
I can confirm it affects 3.6.x as well. kind regards.

**Comment by lukereative** [comment]
I'm with @tractorcow on this, I've tested on 4.2 using the method outlined by @purplespider – also if it's still an issue in 3.x we've moved to security only fixes on SS3 so we won't fix on 3.x

**Comment by lukereative** [comment]
I'm with @tractorcow on this, I've tested on 4.2 using the method outlined by @purplespider – also if it's still an issue in 3.x we've moved to security only fixes on SS3 so we won't fix on 3.x
