### ISSUE TITLE
[2013-02-21] Search field value attribute is populated by default

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#658]
created by: @drzax (drzax)
created at: 2013-02-21
original ticket: http://open.silverstripe.org/ticket/8273

---

The default search form generated in ContentControllerSearchExtension when FulltextSearchable is enabled populates the value attribute of the TextField with the string 'Search' by default.

Value attributes should not be used for displaying pseudo-placeholder text.

The $fields and $actions generated in ContentControllerSearchExtension can probably be removed entirely because they're almost identical (with the exception of the bug reported in this ticket) to the fallback fields in the SearchForm constructor. The value will still need to be populated if a search has just been performed.

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-cms/pull/2334
- [x] https://github.com/silverstripe-themes/silverstripe-simple/pull/62

**Comment by tractorcow** [comment]
Still an issue and needs fixing in all versions. Easy to fix though. :)

**Comment by robbieaverill** [comment]
All merged
