### ISSUE TITLE
[2013-02-28] Manage roles link in securty section returns error

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#659]
created by: @mandrew (mandrew)
created at: 2013-02-28
original ticket: http://open.silverstripe.org/ticket/8291

---

To find this link go to the Security section, then click on the Groups tab and select a group. Then select the Roles tab. You should see a section like the attached image, with a blue link to 'Manage roles'.

The error you get is as follows:
[User Error] Uncaught LogicException: getIDList can't be called on an UnsavedRelationList.
GET /admin/security/show/root
Line 298 in /mnt/share/greggs/framework/model/UnsavedRelationList.php

It looks like the link isn't pointing to the edit roles section properly.

**Comment by tractorcow** [comment]
Current 3.x branch seems to not have any issues.
