### ISSUE TITLE
[2013-03-15] Thumbnails in admin/assets cut off rather than resized

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#666]
created by: @Josua2012 (josua)
created at: 2013-03-15
original ticket: http://open.silverstripe.org/ticket/8326

---

Some images are not fully displayed in the list of 'Files'.

 Last version 3.1 from github:

 https://github.com/silverstripe/silverstripe-cms/tree/3.1

 https://github.com/silverstripe/sapphire/tree/3.1

See attached images.

Regards,
Jose A.

**Comment by tractorcow** [comment]
Assets admin has been rebuilt. Image resampling has been replaced in any case.
