### ISSUE TITLE
compare versions not highlighting differences, lists wrong version above content area (3.1beta3)

### ISSUE THREAD

**Issue by cloph** [silverstripe/silverstripe-cms#687]
In 3.1beta3, comparing versions **doesn't highlight changes between revisions properly**, and also **lists wrong version** above content area.
![compare](https://f.cloud.github.com/assets/477936/406957/7e12c59a-aacb-11e2-8621-6383aed8be34.png)
See it compares version 5 (published) and 6 (unpublished), but the description reads "Comparing versions 6 (view) and 1 (view)"

![5](https://f.cloud.github.com/assets/477936/406959/a25a44f0-aacb-11e2-954f-0fcf4003abb1.png)
For reference content of version 5 - "moved." is last word, so I'd expect all of the "fasdfasd"-text in the comparison to be highlighted, but there are only two very narrow indicators for the empty paragraphs.

![6](https://f.cloud.github.com/assets/477936/406962/f2838fea-aacb-11e2-9ed4-58cc4caec36d.png)
For reference content of version 6 viewed as a single item  (note that also the "show unpublished" toggle doesn't reflect the view - it has to be toggled off and on again to show all the unpublished revisions)

**Comment by tractorcow** [comment]
I was hoping I could close this issue, but change detection still looks a bit jankey.

Change detection detects changes to paragraphs, but not ADDED or REMOVED paragraphs in content blocks.

I've tracked this to an issue with `<ins>` wrapping block level elements such as `<p>`.

`<ins><p>New Paragraph</p></ins>` gets re-written to `<ins></ins><p>New Paragraph</p>`.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

Silverstripe CMS 4 version management UI has been completely refactored, so I don't think this affects it.
