### ISSUE TITLE
[2007-11-23] Improve image alignment options

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#706]
created by: @smagnusson (smagnusson)
assigned to: phalkunz
created at: 2007-11-23
original ticket: http://open.silverstripe.org/ticket/1877

---

Currently image alignment requires the manipulation of both "image alignment" as well as "paragraph alignment". Revise this to have 5 options, as icons for clarity, in the image editor as shown in the screenshot.

This makes it much quicker to intrept the alignment options than wordy sentances.

In the screenshot, I would advocate making images smaller; I've just taken them from MSWord and edited them slightly, so we'd need to get some button artwork done.

**Comment by bergice** [comment]
Resolved by https://github.com/silverstripe/silverstripe-asset-admin/pull/801
