### ISSUE TITLE
[2008-04-18] Filesystem error when creating directories still adds record to File table

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#708]
created by: mpeel
assigned to: @chillu (ischommer)
created at: 2008-04-18
original ticket: http://open.silverstripe.org/ticket/2439

---

Reproduce this error:
- chown your assets directory to a user other than www-data (so you get a Permission denied error when you mkdir assets/some-directory)
- Create a directory via the admin/assets/ admin panel.
- Note that the directory doesn't get created, you're returned an error, but the Folder object is created in the File table.

**Comment by sminnee** [comment]
SS4 assets rewrite has addressed this — folders aren't created on the filesystem at all.
