### ISSUE TITLE
[2009-01-15] All TinyMCE styles dropdown to be modified by a theme

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#714]
created by: @mandrew (mandrew)
assigned to: @sminnee (sminnee)
created at: 2009-01-15
original ticket: http://open.silverstripe.org/ticket/3391

---

The user can add styles to text in the content area of the CMS using the 'Styles' dropdown, however the default styles are included as part of blackcandy and sometimes removed when creating a new theme. The default styles and their icons should be part of the CMS as not to break every time a new theme is made. 

There should be a way of allowing the theme to modify the styles listed in the "Style" dropdown.

**Comment by lukereative** [comment]
Closing as I think we're comfortable with the current avenue for modifying this list through the HTMLEditorConfig.
