### ISSUE TITLE
[2009-05-14] Virtual page continues to show content after source page is deleted

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#716]
created by: sibylle
created at: 2009-05-14
original ticket: http://open.silverstripe.org/ticket/4066

---

If you delete a page whose content is also being pulled in by a virtual page, the virtual page continues to show the content. However there is no way to edit the content (the "edit" link doesn't go anywhere since we just deleted its target), and if you try to select a new page to pull content from, you get an error. Confusing.

I suggest that deleting a page also deletes any associated virtual page(s). It would be good if there was an easy way to see if a page has virtual pages using, and letting the user know that deleting the pages affects the virtual pages as well.

**Comment by sminnee** [comment]
OK — the status quo in SS4 is that the virtual page is unpublished and so won't show on the live site, but that the draft page remains, which is probably a good thing.

However, it doesn't let you pick from a new source page, the dropdown throws a 500 error.

So there's still a bug here.

**Comment by sminnee** [comment]
The final bug has been fixed.
