### ISSUE TITLE
[2009-06-02] Underscores removed from filename when file is uploaded

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#719]
created by: andy_steel
created at: 2009-06-02
original ticket: http://open.silverstripe.org/ticket/4184

---

This is an odd unexpected behaviour.

See this related post:
http://silverstripe.org/archive/show/33981#post33981

**Comment by pinkp** [comment]
Could you please explain how you overwrite these settings? I'm trying to leave underscores in the filenames. I'm not 100% as my attempts don't make a difference. Thanks

**Comment by tractorcow** [comment]
@pinkp you can do this in your _config.php to adjust the replacement filter.

```php
Config::inst()->remove('FileNameFilter', 'default_replacements');
Config::inst()->update('FileNameFilter', 'default_replacements',
array(
		'/\s/' => '-', // Default
		'/[^A-Za-z0-9+.\-_]+/' => '', // Same as default, but allow underscores
		'/[\-]{2,}/' => '-', // Default
		'/^[\.\-_]+/' => '', // Default
	)
);
```

Disclaimer: I haven't tested this so you'll need to test and adjust accordingly.

**Comment by tractorcow** [comment]
Can we remove the underscore -> dash rule in 4.0? There's no harm in allowing these characters anymore, since there's no "risky" distinction needed between hidden / visible filepaths (visibility is handled explicitly rather than via filename).

**Comment by sminnee** [comment]
Seems fine to me, @tractorcow

**Comment by tractorcow** [comment]
ok, then call to action is to remove that rule.

I suppose I can do it. :)

**Comment by mikenz** [comment]
We've been using underscores in 4.0 without issues for a year. No issues.

**Comment by sminnee** [comment]
Related to this, we can probably also drop the practise of treating folders with a leading underscore as hidden. This kind of behaviour can now be better implemented with direct use of DBFile.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-assets/pull/39
