### ISSUE TITLE
[2009-08-27] moving pages in CMS sitetree leads to confusing state for people who dont work with draft site

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#721]
created by: nicolaas
created at: 2009-08-27
original ticket: http://open.silverstripe.org/ticket/4528

---

While the draft option in SS is awesome, you will find that 85%+ of people working with the CMS will save and publish rather than just save in most instances. Hence, they will be unfamiliar with the concept of a draft page. 

When moving a page in the CMS sitetree using the handy drop and drag feature, we end up with "draft move".  

I reckon it might be nice if we had a method where you could move and publish at the same time.  Perhaps an alert box "do you want to publish this move" or would that be too direct?

Perhaps we can get rid of the "allow pages to be drop and dragged" checkbox - and have a confirm move as draft  / as published instead.

**Comment by tractorcow** [comment]
Maybe we can address this with the changeset publishing system. https://github.com/silverstripe/silverstripe-framework/issues/4932

**Comment by clarkepaul** [comment]
It would be good to be able to save a re-organized tree without publishing the changes on those pages. Would be good to re-assess the impact of this issue @chillu.

**Comment by dhensby** [comment]
The ability to publish some specific changes whilst keeping current draft changes in tact would be a very powerful and helpful feature.. perhaps some way to "stash" the current draft changes and re-apply them over the top of a new publish event would be helpful.

I've often seen a pattern where an action on a parent page may require some data to be added to child pages and blindly publishing those can lead to unexpected draft changes being published.

**Comment by chillu** [comment]
Marked it as `impact/high`, assuming that the actual implementation isn't too bad.

**Comment by GuySartorelli** [comment]
Great idea but it's a super old issue that we're not going to do anything with any time soon. Closing.
