### ISSUE TITLE
[2010-01-25] Allow usage of Member::$unique_identifier_field in Security->lostpassword()

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#727]
created by: @chillu (ischommer)
assigned to: gmunn
created at: 2010-01-25
original ticket: http://open.silverstripe.org/ticket/4960

---

Followup from r97270. We should implement this identifier field consistently, which means making it work with Security->lostpassword(). 

This means getting the member by this identifier, and only sending out an email if the column is populated. We'll have to change the MemberLoginForm->forgotPassword() logic to NOT disclose the email address, as this might become a privacy issue (e.g. knowledge of a nickname shouldn't lead to email knowledge for anonymous visitors)

If the Email property is not the "unique identifier", it might occur multiple times in the database. For now, lets just return the first found member.

**Comment by robbieaverill** [comment]
>We'll have to change the MemberLoginForm->forgotPassword() logic to NOT disclose the email address, as this might become a privacy issue

It has an we have removed this in 4.x.

If this ticket is asking that the "unique_identifier_field" be used as the key when looking up the member for the lost password, then LostPasswordHandler does this in 4.x:

```php
        if (!empty($data['Email'])) {
            $uniqueIdentifier = Member::config()->get('unique_identifier_field');
            return Member::get()->filter([$uniqueIdentifier => $data['Email']])->first();
        }
```

It's still expecting an email as input, but I don't think that is the request in this issue. Feel free to reopen this if you think I've misunderstood it @chillu, but I think this is done
