### ISSUE TITLE
[2010-07-30] Impossibility for non Admin users to create Groups in Security tab

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#734]
created by: mirkosassetti
created at: 2010-07-30
original ticket: http://open.silverstripe.org/ticket/5890

---

While setting up permissions for editors and administrators, it seems impossible, for a member who doesn't have full administration rights, to create groups in the Security tab (while he can create and edit roles). The only way to achieve a group to create groups is to actually check the full admin checkbox.

**Comment by sminnee** [comment]
Confirm still an issue

**Comment by maxime-rainville** [comment]
Duplicate of https://github.com/silverstripe/silverstripe-admin/issues/551
