### ISSUE TITLE
[2010-09-23] ModelAdmin Delete Button invokes Form Validation

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#736]
created by: dswnz
created at: 2010-09-23
original ticket: http://open.silverstripe.org/ticket/6032

---

When viewing a record via the ModelAdmin (ajax url: http://my.silverstripe.site/admin/mymodeladmin/MyDataObject/6/edit) and deciding to delete it (ajax url: http://my.silverstripe.site/admin/mymodeladmin/MyDataObject/6/EditForm?action_doDelete=Delete) ModelAdmin decides to validate the data before deleting it.

The "MyDataObject" has been set up with a '''getCMSValidator()''' function which returns '''new RequiredFields('Name')'''
and the Form contains an '''EmailField()'''

Screenshot: Result of clicking the Delete Button.
[[Image(http://grab.by/grabs/12b68fdf791be27625fc846a26638ed6.png)]]

**Comment by patricknelson** [comment]
For anyone interested, please see #586 for more information on a potential fix (in case this is directly related or a duplicate) and PR #1287 for a solution that address it directly in the `3.1` branch of `silverstripe-cms`.

**Comment by wilr** [comment]
Fixed
