### ISSUE TITLE
AssetAdmin::getList() not returning all records when requestVar('ID') == '0'

### ISSUE THREAD

**Issue by halkyon** [silverstripe/silverstripe-cms#747]
Issue started in https://github.com/ajshort/silverstripe-versionedfiles/issues/14.

d42c0041d27bfe079a7691ddea046c1fe1e8432c changed getList() to only return an unfiltered list when request->requestVar('ID') is strictly NULL, however, when a POST request is done to a field inside GridFieldDetailForm, requestVar('ID') returns string '0', and returns a filtered list is returned instead, which was not intended. This means the specific record can't be found by GridFieldDetailForm and a 404 is thrown instead of the proper request.

Should this strict NULL check be changed to !requestVar('ID') instead? It's a bit unclear how the filtering is supposed to work, especially when you mix in the session stuff!

EDIT: Further debugging reveals UploadField.js now sends ID = 0 off instead of null, this might be a problem: b57f2bd02205dcb9d2bd0b38eab80432a637d46f

**Comment by chillu** [comment]
We've completely rewriting AssetAdmin in 4.x (see https://github.com/silverstripe/silverstripe-asset-admin), so won't fix this 3.x issue - see https://github.com/silverstripe/silverstripe-cms/pull/1590 for more context.
