### ISSUE TITLE
"Duplicate with children" doesn't create new children in tree (until hard refresh)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-cms#763]
Referring to https://github.com/silverstripe/silverstripe-cms/pull/297 and #689 

The LeftAndMain.Tree.js logic uses `admin/pages/updatetreenodes` to load any nodes into the tree which it doesn't have yet. This is also used after a newly duplicated page is loaded, which is expected. But the logic isn't smart enough to also load in the whole subtree. We don't do this by default to avoid the performance penalty (e.g. the tree node is refreshed every time you save a page in order to get the new status flags).

The easy way would be to trigger a refresh on the whole tree on "duplicate with children".

**Comment by tractorcow** [comment]
It's working now in any case.
