### ISSUE TITLE
Page isn't labeled as "Modified" after reverting to a version from history.

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-cms#766]
**To reproduce:**
1. Select a page in the CMS that has some history
2. Click the **History** tab
3. Select a version to roll back to
4. Click **Revert to this version**

**What happens:**
The version contents are now copied into that page's draft, but it does not show as "Modified" to let the user know that the draft and live versions are not the same, and that the page probably requires Publishing.

**What should happen:**
The page should be labelled as "Modified" in the site tree.

Reproduced in the latest 3.1 master.

**Comment by purplespider** [comment]
Still an issue in 3.2-beta1

**Comment by tractorcow** [comment]
Is this still an issue in 3.1.13?

**Comment by tractorcow** [comment]
On second thoughts I'll leave this on 3.1.x... we should fix it on as early a version as possible.

**Comment by purplespider** [comment]
Resolved in SilverStripe 4.
