### ISSUE TITLE
Undeleted page temporarily disappears from site tree after clearing filter

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-cms#767]
**To reproduce:**
1. **Delete** a page from the **draft & live** sites
2. **Refresh the CMS** to simulate coming back at a later date.
3. Go to Pages, expand filter, select **All pages, including deleted** from Pages dropdown
4. Click **Apply Filter**
5. Click on the deleted page in the site tree
6. Click **Restore**
7. Click **Clear Filter** in the site tree, to hide the deleted pages again.

**What happens:**
Despite the page being restored it vanishes from the site tree, and requires a full CMS refresh for it to appear again.

**What's expected to happen:**
The page should still be listed in the site tree after clearing the filter, as it is no longer a deleted page.

Reproduced in the latest 3.1 master.

**Comment by purplespider** [comment]
Still present in 3.2-beta1, now called an "archived" page.

**Comment by sminnee** [comment]
@tractorcow I think it's fine to fix this in 3.2 beta 2—I'd probably focus on more critical bugs for 3.1

**Comment by tractorcow** [comment]
Sounds good. :D

**Comment by tractorcow** [comment]
Sorry @purplespider we weren't able to fix this in time for beta2.

**Comment by purplespider** [comment]
This still seems to occur in 3.3.0-beta1 however, it appears to be less likely to occur as clicking "Clear filter" now stays in Edit view, and doesn't return to /admin/pages anymore.

To reproduce in 3.3.0-beta1, you need to restore the page, then click on the Pages tab to go to /admin/pages, where the page won't appear in the site tree until after a reload.

**Comment by tractorcow** [comment]
Maybe we can fix it for 3.3.0 stable. (Or, someone enterprising could have a go at it? ) :P

**Comment by purplespider** [comment]
This seems to be resolved in SilverStripe 4.
