### ISSUE TITLE
Impossible to create nested Virtual Pages where parent restricts allowed_children

### ISSUE THREAD

**Issue by spronkey** [silverstripe/silverstripe-cms#773]
I encountered this situation with subsites, but it occurs with standard VirtualPages as well.

Steps:
1. You need to have a nested page hierarchy somewhere you wish to duplicate with virtualpages. This hierarchy needs to have the parent restrict $allowed_children i.e. = array('SomeOtherPageTypeOnly');
2. Create root VirtualPage, point to top level of existing hierarchy (works fine)
3. Attempt to create virtual page beneath the virtual page created above
4. Error occurs (type Page not allowed here)

What's going on:
1. Virtual Pages are first created without a CopyContentFromID target.
2. When SiteTree::validate() is called when saving the nested VPage (in 3), that VirtualPage's CopyContentFrom() returns a new SiteTree(), which obviously does not meet the allowed page type of SomeOtherPageTypeOnly, and fails the check.

Potential fix:
SiteTree::validate() needs to check whether the *subject* actually exists. It's not good enough to check $this->isEmpty() either, because the validation() gets run twice on save - once where isEmpty is true, and once where isEmpty is false, but before the CopyContentFromID gets set (and thus validation fails again).

For example, on SiteTree:1529

```php
$subject = ($this instanceof VirtualPage) ? $this->CopyContentFrom() : $this;
if(!($this instanceof VirtualPage) || $subject->Exists()) {
  // now check allowed page types
}
```

**Comment by kinglozzer** [comment]
Closed via c6684559f6514ed3f8216f75898317fb0e7fdc65
