### ISSUE TITLE
Infinite loop in tree display when B childof A on live and A childof B on stage.

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-cms#776]
If you have a situation in the tree like this:
- A
  - B

And then you make changes on stage so that it's like this:
- B
  - A

Then you trigger an infinite loop when trying to load this subtree in the CMS.

The underlying cause is that the live-children of A are included in the tree, which includes B.  This means that children deleted from stage but still on live are displayed.  This "get the live nodes" script needs to exclude any pages that are still present on stage and have merely been moved to another location.

This occurred in 3.0.

**Comment by tractorcow** [comment]
@dhensby were you going to help back-port the fix for this to 3.x? 

See https://github.com/silverstripe/silverstripe-framework/issues/5876 for main issue.

**Comment by tractorcow** [comment]
See my gist at https://gist.github.com/tractorcow/540a3056cfce5d45f0d5c680372dad0c

**Comment by dhensby** [comment]
fixed by #1838
