### ISSUE TITLE
[3.1] Nested tabs not working in SiteConfig

### ISSUE THREAD

**Issue by simonwelsh** [silverstripe/silverstripe-cms#777]
I've added a TabSet with two child Tabs to the SiteConfig via a DataExtension. The parent tab correctly shows in the list of tabs, however all the fields from both Tabs and the TabSet's switcher are always showing at the bottom of every other tab.

The second-level tab switcher doesn't update its states at all.

Sample code:
```php
<?php

class SiteConfigExtension extends DataExtension {
	public function updateCMSFields(FieldList $fields) {
		$set = new TabSet(
			'test tab set',
			new Tab(
				'tab a',
				TextField::create('TabAContent')
			),
			new Tab(
				'tab b',
				TextField::create('TabABontent')
			)
		);
		$fields->addFieldToTab('Root', $set);
	}
}
```

How it ends up: ![screen shot 2013-06-20 at 10 12 49](https://f.cloud.github.com/assets/125915/678179/6bf26916-d92d-11e2-8ea7-622eea4a89a8.png)

**Comment by wilr** [comment]
Site Config moved out of CMS module
