### ISSUE TITLE
Insert Media (IE11): Selecting more than 1 image to upload, results in "Empty file upload result" errors

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-cms#787]
**To reproduce (In IE11 Desktop):**
1. Click **Insert Media**
2. Click **Choose files to upload...**
3. Select a few image files, and click **Open**

Only 1 image will successfully upload, the rest will return "Empty file upload result" errors:
![](http://spdr.me/ieCV+)

Tested in latest 3.2-beta1, in Windows 8, IE11.
Works fine in Firefox & Chrome. IE9 didn't allow selecting multiple images at once.

**Comment by purplespider** [comment]
Still an issue in 3.2-beta1.

**Comment by colymba** [comment]
Seems to be a similar issue than in this PR? Thought it would have fixed it? https://github.com/silverstripe/silverstripe-framework/pull/3499

**Comment by purplespider** [comment]
I saw that PR too, but unfortunately not:

![](http://spdr.me/1a6Qf+)

**Comment by colymba** [comment]
That PR https://github.com/silverstripe/silverstripe-framework/pull/3499 actually fixed the same problem for normal uploadfield. Unfortunatly this only solved 1 part of the issue for asset admin.

From what I can see, in Asset Admin, the form do send all the files in one POST request (as it should with iFrameTransport) but those files don't get passed on to the Form or UploadField, only one gets through (hence the emptyFileUploadResult). I just don't know where in handling the form request the form files get trimmed...

**Comment by tractorcow** [comment]
html media dialog has been replaced in 4.x with a react based one. The scope of the original issue doesn't exist anymore.
