### ISSUE TITLE
Permissions - unexpected behaviour 

### ISSUE THREAD

**Issue by feejin** [silverstripe/silverstripe-cms#794]
Allowing a group to "edit any page" overrides any page which has "only these users" settings applied, this isn't very clear.

**Comment by flamerohr** [comment]
maybe @clarkepaul could provide some input :)
This affects both 3.x and 4.x

**Comment by clarkepaul** [comment]
If I'm understanding this correctly my thought is that page permissions should override group permissions and not the other way as it would more likely be a subset of it. I think I need to play with the permissions properly, I'll see if I can do that today.

**Comment by clarkepaul** [comment]
I have some mockups I will share here soon. In short, I feel that page permissions should be able to override global page permissions and page permissions should show what global permissions are in place. In the global permissions area, we can provide help text to inform users permissions can be overridden on a page/section basis.

**Comment by newleeland** [comment]
Here is a prototype paul was referring to:
Prototype: https://projects.invisionapp.com/share/CMBUN7LXE#/screens/235315642_Global_Permissions_-Admin-

There TWO options, a solution and a quickfix that changes the label to inform the user who is has access to this page.

**Comment by chillu** [comment]
> If I'm understanding this correctly my thought is that page permissions should override group permissions and not the other way as it would more likely be a subset of it.

That's incorrect. I've just confirmed that a member with "edit any page" permissions can edit (and delete) all pages regardless of page-specific settings. The "edit any page" permission is basically a "sub-admin" which stands above the page-level permissions, but doesn't have access to the security sections etc.

> Our recommended solution which changes the functionality of this field so that it shows what has been set in Security/Groups on the page, it also provides the ability add additional groups or remove groups (even the ones set in Security/Groups).

That's a bit difficult to implement: If you remove a group with "Can edit all pages" permissions from this list field, does it unset the permissions. If you disallow removing it, can you also add the group explicitly into the field? How is that difference communicated visually? It's all solveable (we can add disabled options to `ListboxField` already), but sounds like a lot of work.

I propose we just list the groups underneath the field:

![image](https://cloud.githubusercontent.com/assets/111025/26674144/75ff8e86-4713-11e7-86df-86ef7d4c03ea.png)

Note that the global permissions already have help text on hover:

> Ability to view any page on the site, regardless of the settings on the Access tab.  Requires the "Access to 'Pages' section" permission

https://github.com/silverstripe/silverstripe-siteconfig/pull/59
https://github.com/silverstripe/silverstripe-cms/pull/1840

**Comment by tractorcow** [comment]
See https://github.com/silverstripe/silverstripe-framework/issues/4861

**Comment by clarkepaul** [comment]
> That's a bit difficult to implement: If you remove a group with "Can edit all pages" permissions from this list field, does it unset the permissions.

I think we could explain with some additional text in Security permissions that these can be overridden on a page basis.

**Comment by clarkepaul** [comment]
I need to read up on the other issue/solution silverstripe/silverstripe-framework#4861, maybe there is more to this :/

**Comment by newleeland** [comment]
Ideally, we would want page permission to override group permissions, as theres a large number possibilities of how user would use pages permissions with different groups and individual. So permissions on per page basis, will give users the flexibility to customise to their preference. 

I've update the prototype, to make global groups appear on page permission, but unremovable. 
Prototype: https://projects.invisionapp.com/share/CMBUN7LXE#/screens/235315642_Global_Permissions_-Admin-

**Comment by clarkepaul** [comment]
I've left a comment on the mockup with a recommendation of a text change @newleeland

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-cms/pull/1840. Can be improved upon later.
