### ISSUE TITLE
Top of CMS chopped off when linking to a tab (3.1 Regression)

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-cms#797]
When following a link that takes you **directly to a specific tab** on a page in the CMS in 3.1, the top of the interface gets chopped off:

Example URL: **/admin/pages/edit/show/14#Root_Events**
![](http://spdr.me/Va4w+)

This didn't happen in 3.0:
![](http://spdr.me/6ynK+)

It is not possible to scroll up, and requires navigating to a different page in the CMS to fix.

These links are common in modules such as UncleCheese's Dashboard module.

**Comment by wilr** [comment]
Still an issue in 3.3

**Comment by purplespider** [comment]
Resolved in SilverStripe 4.
