### ISSUE TITLE
Old Page Redirector will break if you nest more than ~3 times

### ISSUE THREAD

**Issue by ss23** [silverstripe/silverstripe-cms#812]
Currently, it looks at three URL parameters when it does a redirect from site.com/old-page/ to site.com/new-page, thus, if you go to site.com/old-page/this/is/nested/yo/look/at/my/nest, you'll be redirected to site.com/old-page/this/is/nested instead.

The entire redirector logic will need rewriting, and would suggest merging in #801 first to make it easier (if someone wants to finish that).

**Comment by tractorcow** [comment]
OldPageRedirector seems to now be recursive where it wasn't before, so I assume the max depth of 3 issue is at least no longer the current issue. :)
