### ISSUE TITLE
Insert Media from web doesn't parse URL when it starts with a space

### ISSUE THREAD

**Issue by madmatt** [silverstripe/silverstripe-cms#845]
In SS3.1 latest, if a URL that you paste in starts with whitespace, the Javascript that detects whether the URL starts with 'http://' or similar doesn't run, and so when you try to 'Add URL', it tries to parse something like "http:// http://www.youtube.com/xxx"

I haven't tested this in earlier versions of SS3 as yet, and can produce a screencast if desired. I'll also try fixing this myself, as it seems pretty easy ;)

**Comment by ss23** [comment]
https://github.com/silverstripe/silverstripe-framework/pull/3783 - this is the fix

**Comment by flamerohr** [comment]
Pointer: In the `RemoteFileFormFactory` php class, it could trim the Url before creating the Embed object, I think
The javascript could also trim before submitting in the `InsertEmbedModal` component

**Comment by maxime-rainville** [comment]
https://github.com/silverstripe/silverstripe-asset-admin/pull/799 fixed the issue server side.

Not sure there's much value in fixing it client side as well. I'll close this.
