### ISSUE TITLE
ENHANCEMENT: Client side oEmbed

### ISSUE THREAD

**Issue by cam-findlay** [silverstripe/silverstripe-cms#856]
"As a content author I can embed rich media into my wysiwyg editor while behind a firewall so that the CMS works as publicised"

Since the oEmbed call seems to be made via the RestfulService class it is the server making the call out to 3rd parties to receive the details for a piece of content and attributes. 

However, this is a problem when the server is behind a firewall which does not allow calls out to services such as YouTube, Vimeo etc. If you try to use it it throws errors and freaks out your content editors and breaks one of the publicised benefits, that of just being able to copy a URL to embed media.

Perhaps a browser based, client side javascript implementation either as the primary method for oEmbed or as a fall back if a server cannot talk to the outside world...

I can see this becoming more of an issue as more Govt agencies start to see SS as a good platform to adopt (and perhaps used internally rather than on the CWP).

I struck this problem on a recent project and thought I would make a note of it.

Any thoughts?

**Comment by Firesphere** [comment]
I'm not sure how a Clientside call would solve the issue. As the eventual rendering still has to be done on the server, and if YouTube is blocked, it won't work one way or another, right?

**Comment by dhensby** [comment]
Also, isn't a user more likely to be behind a firewall than the server?

**Comment by dhensby** [comment]
The fact this issue has been open for 3 years and no one cared enough to pursue it means it's worth closing
