### ISSUE TITLE
Wrong preview URL when changing Url and saving to draft

### ISSUE THREAD

**Issue by northcreation-agency** [silverstripe/silverstripe-cms#865]
When changing the URLsegment on a page and saving to draft, the Preview panel on the right shows "The page cannot be found". It turns out that the SilverstripeNavigator dataobject named "SilverStripeNavigatorItem_LiveLink" uses that same URL  as the stageLink. 

The fix:
In file SilverStripeNavigator.php, on line 341. Replace the line

return Controller::join_links($this->record->PreviewLink(), '?stage=Live');

with 

return this->record->getAbsoluteLiveLink();

Or, even better. 
Change the PreviewLink function in SiteTree.php so It knows if it should return the URLsegment from stage or from live.

# Pull Requests
* [x] https://github.com/silverstripe/silverstripe-cms/pull/2287

**Comment by chillu** [comment]
Can't reproduce in 4.x

**Comment by sb-relaxt-at** [comment]
This issue still exists (tested in 4.2.1) as the relevant code has not been changed since SilverStripe 3.

**Comment by maxime-rainville** [comment]
I'm reopening. There indeed is some weird behaviour when you change the url segment without publishing.

* If you switch from "Draft" to "Published" in the preview window you get redirected to the 404 error page.
* If you click on the URL Segement field hoping to view the draft in the front end, you get sent to a 404 error page.

https://youtu.be/VbQS1pv2Cwc

**Comment by maxime-rainville** [comment]
Fixed by #2287
