### ISSUE TITLE
Pages that link to themselves shouldn't show in dependent pages tab

### ISSUE THREAD

**Issue by mandrew** [silverstripe/silverstripe-cms#890]
Created a link in the content area on a homepage, pressed save and the page appeared in the dependent pages tab.

I'm not sure if this is supposed to be the case so it should be ignored in the dependent pages list.

**Comment by chillu** [comment]
A bit quirky, but I doubt we'll get around fixing that anytime soon. You could even argue that it's expected behaviour in the unlikely case that a page actually *needs* to link to itself :D

**Comment by mandrew** [comment]
You're a hard task master @chillu :D

**Comment by chillu** [comment]
⛑
