### ISSUE TITLE
"Cancel draft changes" not working on some fields

### ISSUE THREAD

**Issue by patbolo** [silverstripe/silverstripe-cms#901]
"Cancel draft changes" works on fields defined immediately on SiteTree, ie "Content". However, changes done in fields belonging to a pagetype inheriting from sitetree will not be rolled back.
Reproduction steps:
- Go to http://ss3.demo.silverstripe.org/admin/
- Select the "Page not found" page
- Change the status code, from 404 to something else, 
- Change the "Content" field a bit, and save
- Select "Cancel draft changes"
- Observe that the "Content" field is rolled back, but not the status code

**Comment by kinglozzer** [comment]
The issue described in the original ticket doesn’t happen in 3.5.3 or 4.0.0-alpha7, I’ve tested a couple of other fields and they also work as expected so I’m going to close this
