### ISSUE TITLE
ampersands in asset filenames break the shortcode parser. 

### ISSUE THREAD

**Issue by chillburn** [silverstripe/silverstripe-cms#906]
I have a filename called Cole_&_Son_Albemarle_Press_Release_Jan_2012_launch.pdf

When using the shortcode  [file_link,id=72]  this will break the site. 

![image](https://f.cloud.github.com/assets/750993/1690272/06084c8a-5e41-11e3-8277-5489cd971a48.png)

**Comment by sminnee** [comment]
This has been solved in SS4 by scrubbing ampersands out of the filenames.
