### ISSUE TITLE
URLSegment doesn't auto-update for new page

### ISSUE THREAD

**Issue by febsn** [silverstripe/silverstripe-cms#915]
A customer pointed out that their URLSegment doesn't auto-update when changing the title of a newly created page (CMS version 3.1.2). Some research showed that this is only the case when using a non-english interface language, and some more research showed that the page title (via indexof('new')) is used to check whether it's a new page, which of course doesn't work if a new page isn't called 'new page', as in most languages.

**Comment by tractorcow** [comment]
The breaking code seems to have been updated.

```
// Criteria for defining a "new" page
if (
	urlSegmentInput.val().indexOf(urlSegmentInput.data('defaultUrl')) === 0
	&& liveLinkInput.val() == ''
) {
	self.updateURLSegment(title);
} else {
	$('.update', self.parent()).show();
}
```

Please ping this ticket if the issue persists, but I'll close this in the mean time.
