### ISSUE TITLE
ReportAdmin: quotes in report titles  are encoded &#039;

### ISSUE THREAD

**Issue by Martimiz** [silverstripe/silverstripe-cms#918]
**Pages** in Dutch are **pagina's**, now displayed as 

```
pagina&#039;s
```

ReportAdmin.php #166:

```
$columns->setFieldFormatting(array(
    'title' => function($value, &$item) {
        return sprintf(
            '<a href="%s" class="cms-panel-link">%s</a>',
            Convert::raw2xml($item->Link),
            Convert::raw2xml($value)  
        );
    }
));
```

Is there a valid reason for performing a raw2xml() on report titles or would replacing Convert::raw2xml($value) by just $value even be ok?

**Comment by tractorcow** [comment]
Casting fixed with https://github.com/silverstripe/silverstripe-framework/pull/5653
