### ISSUE TITLE
Update HTMLEditor config upon pageload

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-cms#929]
One way to style pages on a SilverStripe website differently depending on their PageType, is using the class it puts on the body tag. E.g., `.HomePage > div:first-child` could be styled differently from the default on `.Page`. 

Unfortunately, it is currently impossible to use those css classes in the HTMLEditor. 
`HtmlEditorConfig::get('cms')->setOption('body_class', page_class);` can be used to set the body's class in the editor, but only on a full page load: any subsequent ajax loads do not update that body class. Since SilverStripe loads everything with ajax now, it's impossible to have the correct styles inside the HTMLEditor for different PageTypes. This is also not very intuitive: one would expect the config options that are set during php execution to actually take effect. 

There are several ways to fix this. 

The most flexible one would be to not only send a `Content` field upon the ajax loads, but also a new `ssTinyMceConfig`. 

Alternatively, a script tag in the Content field could set any overwritten config options, such as `<script>ssTinyMceConfig.body_class="..."</script>`. This way, no extra field needs to be added to the returned json, should that be a difficulty.

**Comment by tractorcow** [comment]
TinyMCE Config can now be customised per-editor in 4.x. Config is embedded into data attributes on the field itself instead of being globally configured.
