### ISSUE TITLE
Translation in Asset Admin for cs_CZ, sk_SK

### ISSUE THREAD

**Issue by JStika** [silverstripe/silverstripe-cms#934]
I cannot find where is string "Are you sure you want to delete this record?" has to be translated, when user click to delete file.

I find In /cms/javascript/AssetAdmin.js is code:
		$('.AssetAdmin.cms-edit-form .action.gridfield-button-delete').entwine({
			onclick: function(e) {
				var msg;
				if(this.closest('.ss-gridfield-item').data('class') == 'Folder') {
					msg = ss.i18n._t('AssetAdmin.ConfirmDelete');
				} else {
					msg = ss.i18n._t('TABLEFIELD.DELETECONFIRMMESSAGE');
				} 
				if(!confirm(msg)) return false;	
				
				this.getGridField().reload({data: [{name: this.attr('name'), value: this.val()}]});
				e.preventDefault();
				return false;
			}
		});

But translated not loaded:

"TABLEFIELD.DELETECONFIRMMESSAGE": "Are you sure you want to delete this record?"

nor

"AssetAdmin.ConfirmDelete": "Are you sure you want to delete this record?"

Why?

**Comment by chillu** [comment]
We've completely rewriting AssetAdmin in 4.x (see https://github.com/silverstripe/silverstripe-asset-admin). If you think this is still an issue in 4.x (currently the `master` branch), please reopen an issue on the other repo. Sorry for the long radio silence here.
