### ISSUE TITLE
'Pages' Admin ListView Gridfield sort search disappears on click

### ISSUE THREAD

**Issue by LukePercy** [silverstripe/silverstripe-cms#947]
![search functionality](https://f.cloud.github.com/assets/2508506/2191365/a262c27a-9845-11e3-9332-0f42d88e9098.png)

When sorting the 'Pages' sitetree gridfield a search icon appears, but clicking this results in it disappearing. 

You can also no longer sort last updated or page type once you click this.

Reproduction Steps:
1. Visit admin/pages/#cms-content-listview
2. Click on 'Last Updated' to sort this field
3. Observe Magnify icon for Search appears on column heading
4. Click on Magnify icon 

Actual:
Magnify icon disappears and you are no longer able to search

Expected:
Search function appears and works as expected on all columns. 
Sorting functionality works as expected upon selecting Search criteria.

**Comment by chillu** [comment]
No longer the case in 4.x
