### ISSUE TITLE
Don't let user define CMS page that conflicts with controller class URL segment

### ISSUE THREAD

**Issue by Rexeh** [silverstripe/silverstripe-cms#948]
Currently you are able to define a controller with the URL of /book. You can then create a page in the CMS of the same URL segment.

Should be message along the lines of "This is a reserved page name" or similar. Creating page seems to have no negative affects, controller takes precedence when visited.

**Comment by chillu** [comment]
Agreed that it's bad UX - the authors will be left wondering why their page doesn't work.

**Comment by dhensby** [comment]
Fix being worked on here https://github.com/silverstripe/silverstripe-cms/pull/1886

**Comment by maxime-rainville** [comment]
That's been fixed in 4 and we won't be backporting in SS3
