### ISSUE TITLE
Page re-order problem leads to 100% cpu-usage

### ISSUE THREAD

**Issue by gerrut** [silverstripe/silverstripe-cms#949]
Sometimes the page re-ordering goes wrong and this may lock-up the whole cms (3.1.2) and server! I don't have all the information on how it happened, but I reconstructed it from the user to happen after the following steps, starting from a tree like:
- folder 1
  -- page 1
  -- folder 1.1
  --- page 1
  --- page 2

which was changed like this
- folder 1
  -- page 1
  -- new folder
  --- folder 1.1
  ---- page 1
  ---- page 2

And consequently like this:
- folder 1
  -- page 1
  -- new folder
  --- page 1.1 (formerly folder 1.1)
  --- page 1
  --- page 2

so the folder 1.1 has been changed to type page, and its children are now its siblings. Only after this re-order where the pages saved. The consequence of this action is that folder 1 won't open anymore and keeps displaying a spinning wheel. This locks up the server completely (100 % cpu usage in Cloudwatch, cms won't change pages anymore). In order to continue I had to restart the apache server and change the pages with phpmyadmin. Usually there is something wrong with the Sort or the ParentID of the changed pages. And if there are for example two Sort 8's, the cms gets crazy. 

Maybe this would not have happened if the modified child-pages were saved after the first step. The main problem here is not, at least in my opinion, the wrong results in the db. That can be solved. However it is not acceptable for the system to lock-up so completely once it spots an error in the db. It simply keeps trying to get the data, while it should give an error. 

Does anyone else have a similar experience?

**Comment by kinglozzer** [comment]
This sounds very similar to https://github.com/silverstripe/silverstripe-cms/issues/776

**Comment by dhensby** [comment]
Yep - this is probably a duplicate.
