### ISSUE TITLE
Ajax links should still be real links

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-cms#953]
Everything loads with ajax now. That's smooth and everything, but it causes some annoyances here and there. 

One such thing is when I want to open multiple links in multiple tabs: that is currently not possible. For example if I have a list of 7 Files, and I want to open all of them in separate tabs in order to then make the same change to all of their Names. 

If I middle click though, that's interpreted as a click and it just loads in the same window. Even when I right click to inspect what the link looks like - the right click loads the new page. 
1. Middle click and right click should never open a new page in the current window. 
2. It would be very useful to have actual links (i.e. `<a>` tags), and overwrite their default behavior -for left clicks- to load with ajax. After all, all links in overview pages like that send simple GET requests, right? That means it's perfectly possible to generate an `<a>` there as well. 

Apologies if this was already reported, was a bit hard figuring out the right terms for this issue.

**Comment by GuySartorelli** [comment]
Great idea but it's a super old issue that we're not going to do anything with any time soon. Closing. If someone is keen for this and wants to put in the work to implement it, `@` me and we can revisit.
