### ISSUE TITLE
Menu arrow dissapears when publishing a closed container

### ISSUE THREAD

**Issue by oetiker** [silverstripe/silverstripe-cms#960]
When editing a page with child pages attached (as indicated by the black arrow symbol)

![ss3132](https://f.cloud.github.com/assets/429279/2291936/0869ad46-a04c-11e3-8914-94b6f58fbade.png)

and then publishing the changes without opening the subtree

![ss3131](https://f.cloud.github.com/assets/429279/2291937/086a519c-a04c-11e3-9356-fac881f61ebc.png)

the arrow for opening the subtree disappears.

this is with silverstripe-cms/tree/3.1.3-rc2

**Comment by wilr** [comment]
Tested in 3.3 and looks to be resolved.
