### ISSUE TITLE
SS 3.1.3 Tree popup missing localized strings cs_CZ, sk_SK

### ISSUE THREAD

**Issue by JStika** [silverstripe/silverstripe-cms#963]
In tree popup (right mouse button click) localized strings for javascript not loaded for cs_CZ, sk_SK. 
Why? 
I checked translation and they not missed, only (array keys) order is diffrent

In file /assets/_/_combinedfiles/cmsmain.js I see  2 x this:
/*****\* FILE: cms/javascript/lang/en.js *****/ two times.

Why?

![screen](https://f.cloud.github.com/assets/722942/2365531/d2f5d45e-a6cd-11e3-988b-4b3c96593566.jpg)

**Comment by chillu** [comment]
That's indeed a bit weird - the strings are definitely translated in Slovak (sk) in Transifex (https://www.transifex.com/silverstripe/silverstripe-cms/viewstrings/#sk/master-js/112005181), but they don't get pulled down into the `cms/client/lang/src/sk_SK.js` file.

**Comment by maxime-rainville** [comment]
I just had a look on SS4 in French and the translations are showing for me.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
