### ISSUE TITLE
GridField view of SiteTree: Sort by status

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-cms#967]
It would be great if the GridField view of the SiteTree in the CMS had an additional, sortable column "status" which showed the current status of a Page. 

If the sortable function is added and there can be occasions where there's more than just one status attached to a Page, just sort by the first label. I have had this request from one or two clients.

**Comment by GuySartorelli** [comment]
Great idea but it's a super old issue that we're not going to do anything with any time soon. Closing. If someone is keen for this and wants to put in the work to implement it, `@` me and we can revisit.
