### ISSUE TITLE
Bug: Going to the 'Add New' form on split screen preview results in being unable to leave/cancel 'Add New' Form

### ISSUE THREAD

**Issue by LukePercy** [silverstripe/silverstripe-cms#973]
When Selecting to add a new Page from within an existing Page form results in the button actions "Cancel" and other Admin buttons to not work.

Reproduction Steps:
1. Select a 'Page' pagetype
2. Select 'Settings' Tab
3. Select 'Add New' button above site tree
4. Click Cancel
5. Observe form does not cancel
6. Click any other admin i.e. Files, Reports
7. Observe admins do not load in Main.

Additional Notes: the form does return to normal after selecting to 'Create' a page, just all other actions don't work.

**Comment by mediabeastnz** [comment]
Seems to work fine in some browsers e.g. Mac Firefox. But not others e.g. Mac Safari.

I had a quick look and it looks like a standard submit function (doCancel), no javascript errors get thrown...
