### ISSUE TITLE
Inconsistent application of GridFieldToolbarHeader in CMS ModelAdmins

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-cms#981]
There is an inconsistent application of `GridFieldToolbarHeader` components in the default CMS ModelAdmins:
- admin/pages: No
- admin/files: Yes
- admin/reports: No
- admin/security: Yes (But no default title to show in it)

These should probably be made consistent to try and be "professional" (tm)

**Comment by chillu** [comment]
This has been "fixed" in 4.x, since admin/files no longer uses GridField. Somehow the toolbar header has crept into admin/reports though, causing extra space - I've removed it there: https://github.com/silverstripe/silverstripe-reports/pull/71
