### ISSUE TITLE
ModelController URL request argument handler problem

### ISSUE THREAD

**Issue by svandragt** [silverstripe/silverstripe-cms#993]
It seems the problem is that the ModelAsController's handleRequest method does not always check if the request is finished prior to calling popCurrent(). [Source code line](http://api.silverstripe.org/3.1/source-class-ModelAsController.html#87) 

This means that additional arguments can be added to the url which results in the warning: `popCurrent called on ModelAsController controller, but it wasn't at the top of the stack` followed by the correct display of the 404 page.

The warning  only manifests if an allowed_action is visited not on a regular page request.

[Reproduction](https://gist.github.com/svandragt/10363474)

The issue can be worked around on an individual controller basis by specifying additional arguments in the $url_handler static which is not great because every controller is affected by this.

Thanks to @micmania1 and @kinglozzer for help diagnosing this issue.

**Comment by tractorcow** [comment]
Seems ok in 3.x branch.
